### ISSUE TITLE
Cannot use transform from rules

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab-distro#100]
I've seen that Thomas had reported this issue here (https://github.com/openhab/openhab2-addons/issues/636).

But I am also interrested in the answer.

I got a script where I do this 
```
	var String dest  = transform("JSONPATH", "$[0].value", json)
```
And I got the same message
```
2016-01-20 16:25:04.189 [ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'Send Mail': The name 'transform(<XStringLiteralImpl>,<XStringLiteralImpl>,<XFeatureCallImplCustom>)' cannot be resolved to an item or type.
```
This code used to work with alpha version of openhab 2...
I added
```
transformation = jsonpath
```
in addons.cfg and it seems that the bundle is Active on my console...

**Comment by kaikreuzer** [comment]
I would hope that this is fixed by https://github.com/eclipse/smarthome/pull/885, which will be in the next stable snapshot of ESH (planning it for tomorrow).

**Comment by kaikreuzer** [comment]
Could you retest with the latest snapshot build from https://openhab.ci.cloudbees.com/job/openHAB-Distribution/?
Note that you first need to install the JsonPath transformation service (e.g. through the Paper UI)

**Comment by thomasjetzinger** [comment]
Unfortunately I'm getting the same error with the latest snapshot:

```
The name 'transform(<XStringLiteralImpl>,<XStringLiteralImpl>,<XFeatureCallImplCustom>)' cannot be resolved to an item or type.
```

Additionally the following error message is shown at startup:

```
17:50:34.538 [ERROR] [org.eclipse.smarthome.core.transform] - [org.eclipse.smarthome.action.transformation.action(78)] Circular reference detected, getService returning null
```

**Comment by moutemoute38** [comment]
I get the same error with today's stable snapshot, when I use transformation-map.

On startup : 

```
[ERROR] [org.eclipse.smarthome.core.transform] - [org.eclipse.smarthome.action.transformation.action(45)] Circular reference detected, getService returning null`
```
and then when my rule runs : 

```
[ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'VoiceCommand': The name 'transform(<XStringLiteralImpl>,<XStringLiteralImpl>,<XFeatureCallImplCustom>)' cannot be resolved to an item or type.
[WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type MAP
[WARN ] [.core.transform.TransformationHelper] - couldn't transform value  because transformationService of type 'MAP' is unavailable
[WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type MAP
[WARN ] [ui.internal.items.ItemUIRegistryImpl] - couldn't transform value in label because transformationService of type 'MAP' is unavailable
```

**Comment by kaikreuzer** [comment]
My next hope is that this will be fixed by https://github.com/eclipse/smarthome/issues/870 - but this is not yet ready...

**Comment by tracstarr** [comment]
I was receiving the original error posted here this morning. After updating to the latest snapshot from today the error is now simply 

 The name 'jsonpath' cannot be resolved to an item or type.

Is this still related to the same issue or something different?

**Comment by bsautere** [comment]
Hi, any news on this ? I have the issue with openhab2 online snapshot downloaded from https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ on 5.3.2016.

**Comment by thomasjetzinger** [comment]
I'm also waiting for a solution on this. Can't use openhab2 due to this issue.

**Comment by leoluk** [comment]
+1. This breaks a bunch of scripts

**Comment by jrcourtois** [comment]
I don't resolve the issue but i have a workaround.
The problem seems to come from this error
`2016-03-18 16:32:34.228 [ERROR] [org.eclipse.smarthome.core.transform] - [org.eclipse.smarthome.action.transformation.action(51)] Circular reference detected, getService returning null
`

So to avoid this error : I restart the Script Engine
`openhab> list | grep Script`
`115 | Active   |  80 | 0.8.0.201603141848    | Eclipse SmartHome Script`
`116 | Active   |  80 | 0.8.0.201603141848    | Eclipse SmartHome Script Runtime`
`openhab> restart 115`

Not a long term solution, but to avoid becoming crazy with non testable scripts...

**Comment by smar000** [comment]
@jrcourtois Thanks for the work around. Is there anyway to get the script engine to automatically restart on start-up after the transform service fails?

**Comment by jspuij** [comment]
Unfortunately the work around seems to "unset" itself after a couple of hours of running. Restarting the script service again does not work anymore then. It could be because of starting or stopping other bundles, but still not a very stable work around.

**Comment by SingleDadLiving** [comment]
I just pulled the most recent snapshot and I'm still getting this error as well

**Comment by kaikreuzer** [comment]
Hi all,

I think this is now finally solved - please have a try with the latest OH2 distro build (253) and let me know if it works for you!

**Comment by jrcourtois** [comment]
Worked for me, cool, thank you !

**Comment by SingleDadLiving** [comment]
Thank you so much for fixing this. I just updated my install and it's working!!!

**Comment by kaikreuzer** [comment]
Thanks for your quick feedback - I am very happy to hear that this is now indeed solved!

**Comment by thomasjetzinger** [comment]
For met it works as well!

**Comment by cyberkov** [comment]
Works for me as well. Thanks!

**Comment by jspuij** [comment]
Me too ;-)

**Comment by kaikreuzer** [comment]
Since https://github.com/eclipse/smarthome/issues/870 is unfortunately back, this issue is back as well, so I need to re-open it :-(

**Comment by pabloNZ** [comment]
This error has played havoc with my ability to get OH2 set up and running! For the life of me I couldn't figure out what I was doing wrong, and the number of times I rewrote my rules/items from scratch to try and figure it out is scary. It's pretty much a deal breaker for my use of OH which bums me out.

**Comment by kaikreuzer** [comment]
All, after a few days work, I think I have finally solved the startup issues through https://github.com/eclipse/smarthome/pull/1828. Please try the latest distro (build 399) and let me know if you still experience any problems!
