### ISSUE TITLE
openHAB 2.5.0~S1754-1 (Build #1754) does not start up on openhabian

### ISSUE THREAD

**Issue by wrosenauer** [openhab/openhab-distro#1002]
I installed the snapshot today and it does not start up correctly.
It does not even start logging into /var/log/openhab2 so I have no further information.
Some processes are running though.
(https://community.openhab.org/t/2-5-0-s1754-1-does-not-start-up-for-me/85341)

I've updated from 1733 but that version is not available anymore it seems.
So I reverted back to the oldest available (2.5.0~S1738-1) but this one also has issues starting some modules. (Cannot resolve many/all UI packages for some reason.)
Meanwhile by reporting I also look for the best way to recover for the moment to a version which works. Not sure if anyone can give a hint here. Using 2.5.0M4?

**Comment by wborn** [comment]
I just successfully upgraded an openHAB instance in an Debian 10 VM from 2.5.0~S1719-1 to 2.5.0~S1754-1. So it might be some local issue with your installation.

**Comment by wrosenauer** [comment]
Might be. But it might be interesting to find the root cause and since I have no clue how this can be done I'll wait for feedback.
Just as a sidenote, downgrading to 2.5.0M4 made it work again.

**Comment by kaikreuzer** [comment]
2.5.0 release should work fine and we have no way to investigate problems on some old snapshot - so I'll close this issue.
