### ISSUE TITLE
2.5 distro has grown by 10MB since 2.4

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#1009]
Just wanted to mention this - a while ago, I remember that the distro zip was around 65MB and we have now reached 84MB. 
I haven't analyzed what has contributed to this, but as the functionality hasn't much changed (apart from the ephemeris feature with an external lib), my expectation would rather be that we should have a similar size as before.
In the past, the Karaf upgrades were often the culprit as they brought new versions of bundles, which were then packaged twice in the distro.

@openhab/distro-maintainers, if anyone of you has a good idea or would like to investigate, feel free to do so :-) .

**Comment by wborn** [comment]
I had a brief look:

* openhab-2.4.0.zip (74,0 MB)
* openhab-2.5.0-SNAPSHOT.zip (83,1 MB)

So it grew by 9,1MB.

Seems most weight is gained by the change from the MQTT change from paho to hivemq (+1.1M hivemq, +3M netty, +2.3M reactivex). The org.eclipse.paho.client.mqttv3 is only 221,5 kB.

Furthermore there are 2 joda-time versions instead of one (2.2,  2.9.2 (new, +625,6 kB)).

Another big gain is by org.apache.servicemix.bundles.saaj-impl (+2.6M) which is used for supporting JAX-WS on newer Java versions.

**Comment by kaikreuzer** [comment]
Thanks for the analysis!
It is a bit unfortunate that we package the MQTT stuff with the distro although it is only required if the MQTT binding is installed. Maybe we should think about moving the io.transport bundles to the addons repo for openHAB 3...

> Furthermore there are 2 joda-time versions instead of one (2.2, 2.9.2 (new, +625,6 kB)).

Would be interesting to check why this came in and if we can remove it again.

> Another big gain is by org.apache.servicemix.bundles.saaj-impl

SOAP with attachments...? Do we really need this or is this something optional, which we can exclude?

**Comment by wborn** [comment]
> Maybe we should think about moving the io.transport bundles to the addons repo for openHAB 3

That's indeed worth considering and may make life easier for contributors.

> Would be interesting to check why this came in and if we can remove it again.

We specify 2.9.2 for [openhab.tp-base](https://github.com/openhab/openhab-core/blob/5dbd33ab61e0eb7f20ba33c4310a4b69a07c6b90/features/karaf/openhab-tp/src/main/feature/feature.xml#L40) and use 2.2 for [openhab.tp-swagger-jax-rs-provider](https://github.com/openhab/openhab-core/blob/5dbd33ab61e0eb7f20ba33c4310a4b69a07c6b90/features/karaf/openhab-tp/src/main/feature/feature.xml#L299).

> SOAP with attachments...? Do we really need this or is this something optional, which we can exclude?

It's currently only used by [dlinksmarthome](https://github.com/openhab/openhab2-addons/blob/4ee787ede8907c717e3ba2b127370e73512da359/bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml#L8). It may also be useful for [helios](https://github.com/openhab/openhab2-addons/blob/4ee787ede8907c717e3ba2b127370e73512da359/bundles/org.openhab.binding.helios/src/main/feature/feature.xml#L8-L9).

**Comment by pavel-gololobov** [comment]
@kaikreuzer, sorry for the offtopic, but I did not find another method of contacting you. In the 2.5 Release Notes, you forgot to mention the new XMPPClient Binding (https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.xmppclient) binding, which is a replacement for the old 1.x XMPP Action. The old action works not very well. And it could be important to someone. Thank you.

**Comment by wborn** [comment]
That's good to know! Seems that https://github.com/openhab/openhab2-addons/pull/5433 didn't have the "new binding" label when we generated the release notes.

**Comment by kaikreuzer** [comment]
@pavel-gololobov Thanks for noticing, I have now manually added this new binding to the release notes as well!

**Comment by kaikreuzer** [comment]
I guess we can close this.
