### ISSUE TITLE
2.5 logs

### ISSUE THREAD

**Issue by erhapp** [openhab/openhab-distro#1047]
After upgrading from 2.4 tot 2.5 using APT package on Raspbian (Raspberry Pi 3) the logs in /var/logs/openhab2 aren't updated anymore. The last entries in both openhab.log and events.log are items related to version 2.4 going "down".

Did I miss something while upgrading to 2.5 or are does Openhab2 2.5  stopped using the logs in /var/logs/openhab2? (on Raspbian)

kind regards

Erik

**Comment by vot3c** [comment]
first check your log from openhab-cli by log:tail command. If you have logs over there, the problem highly occurs due the no space left on device for any log. you can fix it by clearing the system logs or you can enable zram which is easly can enable by openhabian-config.

**Comment by kaikreuzer** [comment]
I assume that was some local Linux problem - if there was a general problem in the 2.5 release, others would have come across it.

**Comment by openhab-5iver** [comment]
@kaikreuzer, I have seen this a few times in testing and have saved at least one manual install that was exhibiting this. Others have reported it too in the forum, especially after [setting up Jython on Windows](https://community.openhab.org/t/windows-all-oh-logs-stop-when-jython-is-in-the-classpath/79654), but I've seen it on Linux too. I've never been able figure out a cause.
