### ISSUE TITLE
Drop HTTP for OH3

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-distro#1048]
I think this is time were breaking changes can take place. Is it a good idea ?

**Comment by J-N-K** [comment]
What do you mean by „drop http“?

**Comment by clinique** [comment]
Switching the UI to HTTPS only.

**Comment by MHerbst** [comment]
What would be the advantages of https only? I think that most users are using the UI in a private network (or via myopenhab). In this configuration For a "normal" user, however, the usage would be more difficult. In a private network, self-signed certificates would have to be used. However, these certificates lead to warnings in most browsers and not every user can easily avoid this.

I would therefore vote for making https only optional. BTW: if you really want to use https you install a reverse proxy.

**Comment by kaikreuzer** [comment]
@clinique Does closing the issue mean you agree that HTTP should be kept?

I think in general, it is a good idea to force HTTPS. But the main issue are the browser warnings as @MHerbst correctly says. We could nonetheless "strongly recommend" users to switch to HTTPS, e.g. by having a small "welcome wizard" in the new UI, which offers a simply way to install the certificate in the browser and make Jetty then automatically redirect to HTTPS.

**Comment by clinique** [comment]
Yes, I also think enforcing https would be a good practice, that could BTW simplify documentation with only one entry point but for sure, getting and installing a certificate may raise another barrier. So I'm not sure its worth it.
