### ISSUE TITLE
MQTT Item in PaperUI has no decimal points

### ISSUE THREAD

**Issue by moonilightshaker** [openhab/openhab-distro#1049]
After upgrading from 2.4 to 2.5 using APT package, all mqtt items in the PaperUI have no decimal points and no decimal value. The value is rounded to the nearest whole number.

kind regards

**Comment by mpuff** [comment]
i have with v 2.5.1 the problem that i have 5 decimals instead of 1 ore 2 like in v2.5.0 bevore;

https://community.openhab.org/t/problem-with-dezimals-in-value-openhab-2-5-1-mqttv2/90887/4

**Comment by wborn** [comment]
> all mqtt items in the PaperUI have no decimal points and no decimal value

You apply apply a format on the item state showin in UIs:

https://www.openhab.org/docs/configuration/items.html#state-presentation

> mqtt is sending 5 decimals instead of 1 ore 2

You can format the state when publishing by configuring the `formatBeforePublish` channel property: 

https://www.openhab.org/addons/bindings/mqtt.generic/#channel-configuration
