### ISSUE TITLE
Build, Run, Debug

### ISSUE THREAD

**Issue by azim0ff** [openhab/openhab-distro#105]
I have a "feature request" for the installation walkthrough. I was wondering if 3 sections could be added:

-How to build
-How to run
-How to debug

I realize this is, ultimately, basic material... But for someone who is not used to maven and osgi this would be of great help. 

For example, I know that running 'mvn install' will build a jar file that is ready for distribution, but how do I build from within eclipse? And then run from within eclipse, without having to go to the console?

**Comment by dvanherbergen** [comment]
Compilation in eclipse is done automatically. How to start openHAB inside eclipse is described [here] (https://github.com/dvanherbergen/openhab-distro/blob/master/docs/sources/development/ide.md) in step 8. 
To debug, right click the openHAB_Runtime.launch and select ```debug as > openHAB_Runtime``` instead of ```run as > openHAB_Runtime```.

For more information on maven, have a look [here] (https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html).

**Comment by azim0ff** [comment]
Ok, just did a clean install.

> Step8. Your workspace should now fully compile and you can start the runtime by launching the "openHAB_Runtime" launch configuration.

I do not see this launch configuration. Am I looking in the wrong place, or am I supposed to create it?

**Comment by dvanherbergen** [comment]
Check in the folder Infrastructure > Launch.

**Comment by azim0ff** [comment]
Ok, I am able to run and debug. For building, when I try to add a print statement to YahooWeatherBinding Handler initialize(), it does not have any effect, despite a clean/build cycle. Is it supposed to be this way?

**Comment by dvanherbergen** [comment]
In debug mode, hot code replace should work. If your print statement is not working, maybe the method is not being called?
Try changing the text of an existing statement that you see being printed..

**Comment by azim0ff** [comment]
That's exactly what I did, like this:
logger.debug("******** Initializing YahooWeather handler.");

but in debugger I still see:
logger.debug("Initializing YahooWeather handler.");

**Comment by azim0ff** [comment]
Let me try a completely new binding ...

**Comment by azim0ff** [comment]
Ok, got it, to activate hot code replace the **workplace** instance of the binding must be selected in the Run Configuration. (In addition to the one under Target Platform).

One last question - is it possible to trigger a binary build (for distribution) from within eclipse? Or does it have to be done with 'mvn' on the command line?

**Comment by dvanherbergen** [comment]
It depends. If you want to build only a single binding, yes. Then you can just right click on the pom.xml in your project and select ```run as ... > maven install``` for example.
To build the whole openHAB, you need to use the command line. Just go to the root folder of the project and enter ```mvn install```.

**Comment by azim0ff** [comment]
Gotcha. Would you be opposed if I added a paragraph about all of this to the end of the IDE installation readme?

**Comment by dvanherbergen** [comment]
Not at all. Any pull request with documentation improvements is always very welcome...

**Comment by azim0ff** [comment]
Ok, awesome. Will send in the next 24 hours. And thank you for your help!

**Comment by dvanherbergen** [comment]
You're welcome.

**Comment by azim0ff** [comment]
Hey, I have one more related question. When I build using 'mvn install' from the 'openhab-distro' directory, is there any way to specify to use local sources instead of online ones? I'm trying to build a distribution version of what I am running from Eclipse (with my changes to system classes).
