### ISSUE TITLE
Provide binding distribution / marketplace

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-distro#1054]
The current Eclipse IOT marketplace is no longer available, and one of the most commonly asked questions on the OH forum is some variationof -:

* Where do I get X binding from
* How do I install the latest X binding

I think this imposes significant usability issues with OH at the moment and it is something that should be looked at with OH3 to try and improve the user experience. Currently people try and write scripts to work around this, but it's still a 

I know there have been other discussions, but I've not seen anything concrete. I don't really have any suggestions for a concrete implementation, but I would propose at least the following initial requirements -:

* Should allow the user to install the latest version of a binding (eg SNAPSHOT version, even when they are on STABLE). I know that things like mixing SNAPSHOT and STABLE versions may cause issues (ie a binding may not run, or may crash out with some sort of ```ClassNotFound``` exception, but I think we should make users aware of this, but not prevent them from doing it (at the moment, they do it anyway, and most of the time it works find - we just make things difficult right now).
* It should allow installation from "various" sources - ie I would propose to avoid allow binding installs from outside of the OH controlled world so that users can install test bindings, or bindings that are even not directly part of OH. Eg pointing at a git repo (with some sort of standard around how this is published). I know there will be arguments about security, or licensing, or other reasons not to do this, but as above, we should clearly warn the user they are stepping into the wild unknown, but not block them from doing something (similar to Mac or Linux - you can run unsigned apps, or you can run files off the web, but you're warned and made aware of the potential danger).
* Let's try and keep it simple - I think this is one of the biggest usability issues so getting something working is important.

Apologies if this is duplicated - I did a search for other open issues and the main one I could find is  https://github.com/openhab/openhab-core/issues/767 which is more looking at the interface.

This probably should also be considered in the UI design https://github.com/openhab/openhab-webui/issues/155

**Comment by openhab-5iver** [comment]
I was trying to get a similar discussion going in https://github.com/openhab/openhab-core/issues/1175. I'm also about to post an issue that touches on the automation side of an ExtensionService/marketplace. Collaboration and sharing of rule templates will be a very big piece of the NGRE UI rule editor.

**Comment by kaikreuzer** [comment]
I'd suggest to close this issue as it mixes different things. At the one hand the way to install "official" add-ons from the openHAB repos and at the other hand 3rd party stuff from a marketplace.

For the first, we already have openhab/openhab-core#1175.
For the second, the best issue to follow-up on is imho https://github.com/openhab/openhab-addons/issues/6673.

**Comment by Hilbrand** [comment]
It also was recently addressed at https://github.com/openhab/openhab-addons/issues/6673. The idea is indeed to be able to point to a GitHub repository. It is my intention to come up with a proposal on how that should be structured and then work on the needed addon. Any ideas are welcome of course.

**Comment by cdjackson** [comment]
> I'd suggest to close this issue as it mixes different things. At the one hand the way to install "official" add-ons from the openHAB repos and at the other hand 3rd party stuff from a marketplace.

The reason I "mixed this up" is I personally think it should have a unified feel to it and not feel like there are different ways to do different things. Maybe under the hood this is the case, but I was trying to come at this from a user perspective to improve the user experience which is an area that OH really falls short at the moment.

It looks like the suggestion from @Hilbrand might cover this anyway, but we also should make sure that the user, and the UI is properly considered.
