### ISSUE TITLE
Provide generic OPENHAB_JAVA_OPTS env variable

### ISSUE THREAD

**Issue by dvanherbergen** [openhab/openhab-distro#109]
[Currently](https://community.openhab.org/t/solved-how-to-define-a-serial-port-on-raspberry-for-openhab2-for-my-razberry-zwave-binding/6693/5) you have to edit the setenv.sh to add additional java options. 
To make this easier, it would be nice to have an OPENHAB_JAVA_OPTS env variable, which can be set by the user and which is appended to the java options to start openhab.

**Comment by maggu2810** [comment]
See also: https://github.com/openhab/openhab-distro/pull/111#issuecomment-177456732

**Comment by kaikreuzer** [comment]
Solved through documentation update in #111
