### ISSUE TITLE
Logging out of new Rule Engine (Paper UI) does not work

### ISSUE THREAD

**Issue by DimitriLubenski** [openhab/openhab-distro#1090]
Dear all,

Just installed the OpenHab2 2.5.2 (blank new installation) on Synology to compile reproduction steps. 

- Started the Paper UI
- Go to Rules and hit "+"
- Select for simplicity cron and put 0/10 0 0 ? * * *   
- Select Java Script as a language and put following JS snippet into the "execute given script"
<img width="935" alt="Capture" src="https://user-images.githubusercontent.com/35936894/76710084-a391e880-6704-11ea-8567-cf1f2891b021.PNG">

`
function(module, input){

println("Text " + "to " + "log.");

logError("Test", "TEST");

}
`

events.log contains following lines if the rule is executed pressing the button

`
2020-03-15 21:08:57.417 [.event.RuleStatusInfoEvent] - c7ed474a-3faa-481d-b004-15c2510fd63c updated: RUNNING
2020-03-15 21:08:57.803 [.event.RuleStatusInfoEvent] - c7ed474a-3faa-481d-b004-15c2510fd63c updated: IDLE
`

but the log entries with debugging texts do not appear in the log. 

Attaching the cfg file with the log configuration. 

[org.ops4j.pax.logging.cfg.txt](https://github.com/openhab/openhab-distro/files/4335016/org.ops4j.pax.logging.cfg.txt)

**Comment by openhab-5iver** [comment]
This is just a configuration issue and should be addressed in the [forum](https://community.openhab.org/c/setup-configuration-and-use/scripts-rules/13). Hint: you will need to import LogAction ([much easier with the helper libraries](https://openhab-scripters.github.io/openhab-helper-libraries/Guides/Logging.html#logaction)).
