### ISSUE TITLE
Problems with Maven build

### ISSUE THREAD

**Issue by fabgio** [openhab/openhab-distro#1107]
Java version: openjdk 11.0.6 2020-01-14

Maven version: Apache Maven 3.6.3
Repository cloning from: https://github.com/openhab/openhab-distro.git 1 (O.H distro).
Then I performed:

mvn clean install

Then I got this from Maven:

Could not resolve dependencies for project org.openhab.distro:distro:feature:3.0.0-SNAPSHOT: The following artifacts could not be resolved: org.openhab.core.features.karaf:org.openhab.core.features.karaf.openhab-core:xml:features:2.5, org.openhab.core.features.karaf:org.openhab.core.features.karaf.openhab-tp:xml:features:3.0.0-SNAPSHOT: Could not find artifact org.openhab.core.features.karaf:org.openhab.core.features.karaf.openhab-core:xml:features:2.5 in carlspring (http://repo.carlspring.org/content/groups/carlspring)

Here's wath I tried to solve the problem:
1) Cleaned upthe local .m2 repo lib
2)I Checked the project's poms  to pick the correct libraries' version

I tried building with java 8 too  and I got other issues.
What's wrong? Thank you so much

**Comment by wborn** [comment]
Maybe you have a mirror configured in ~/.m2/settings.xml?
If not, please use the [community forums](https://community.openhab.org/c/development/ide/34) for such support questions.
