### ISSUE TITLE
changed from NULL to 0

### ISSUE THREAD

**Issue by mvdboogaard** [openhab/openhab-distro#1113]
After upgrading to 2.5.5 I get the following message every time a check is done on my z-wave device: ZwaveMultisensorLuminance changed from NULL to 0. Also when no change is there.
When downgrading back to 2.5.4 I don't see this behaviour.
The z-wave device is a Aeotec 6in1 multisensor and I'm making use of a z-wave USB stick. 

For me this is disturbing my automation rules

**Comment by openhab-5iver** [comment]
The [community forum](https://community.openhab.org/) would be the best place to report this, where there are community members available to provide Z-Wave support. Specifically, this issue has nothing to do with the code in this repo.

**Comment by mvdboogaard** [comment]
Thanks. I thought this should be the place to be. I will ask this in the community forum.
