### ISSUE TITLE
Error: Could not find or load main class Files when installing openhab2 as a service on Windows

### ISSUE THREAD

**Issue by davidreinhold** [openhab/openhab-distro#112]
I'm trying out openHab 2.0 on my windows home server 2011 and starting it manually works but when running it as a service (followed the steps in https://github.com/openhab/openhab-distro/blob/master/docs/sources/getting-started.md) , the service refuses to start.

This is the contents of wrapper.log after an attempt to start it (sorry, my OS is in Swedish, "Hittar inte eller kan inte ladda huvudklassen" should be translated to "Could not find or load main class").

STATUS | wrapper  | 2016/01/31 14:47:14 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/01/31 14:47:14 | Launching a JVM...
INFO   | jvm 1    | 2016/01/31 14:47:15 | Fel: Hittar inte eller kan inte ladda huvudklassen Files
ERROR  | wrapper  | 2016/01/31 14:47:15 | JVM exited while loading the application.
STATUS | wrapper  | 2016/01/31 14:47:19 | Launching a JVM...
INFO   | jvm 2    | 2016/01/31 14:47:19 | Fel: Hittar inte eller kan inte ladda huvudklassen Files
ERROR  | wrapper  | 2016/01/31 14:47:19 | JVM exited while loading the application.
STATUS | wrapper  | 2016/01/31 14:47:24 | Launching a JVM...
INFO   | jvm 3    | 2016/01/31 14:47:24 | Fel: Hittar inte eller kan inte ladda huvudklassen Files
ERROR  | wrapper  | 2016/01/31 14:47:24 | JVM exited while loading the application.
STATUS | wrapper  | 2016/01/31 14:47:29 | Launching a JVM...
INFO   | jvm 4    | 2016/01/31 14:47:29 | Fel: Hittar inte eller kan inte ladda huvudklassen Files
ERROR  | wrapper  | 2016/01/31 14:47:29 | JVM exited while loading the application.
STATUS | wrapper  | 2016/01/31 14:47:34 | Launching a JVM...
INFO   | jvm 5    | 2016/01/31 14:47:34 | Fel: Hittar inte eller kan inte ladda huvudklassen Files
ERROR  | wrapper  | 2016/01/31 14:47:34 | JVM exited while loading the application.
FATAL  | wrapper  | 2016/01/31 14:47:34 | There were 5 failed launches in a row, each lasting less than 300 seconds.  Giving up.
FATAL  | wrapper  | 2016/01/31 14:47:34 |   There may be a configuration problem: please check the logs.
STATUS | wrapper  | 2016/01/31 14:47:34 | <-- Wrapper Stopped

I'm not sure exactly what build I'm using, downloaded the 2.0 online distro snapshot from openhab.org  on jan 31.

I'm not that good at Java but I guess there's an error or something missing in wrapper.conf. Can anyone help out?

Regards.
David
##

**Comment by dvanherbergen** [comment]
Are you using Java 1.8? Does your installation path have spaces? 
Did you install the service whilst logged on with administrator rights?

**Comment by davidreinhold** [comment]
Hi!

Are you using Java 1.8?  Yes, 1.8.0_71
Does your installation path have spaces? JAVA_HOME does, not the path to openhab (c:\openhab2)
Did you install the service whilst logged on with administrator rights? Yes

Regards,
David

Från:  dvanherbergen <notifications@github.com>
Svara till:  openhab/openhab-distro <reply@reply.github.com>
Datum:  måndag 1 februari 2016 14:35
Till:  openhab/openhab-distro <openhab-distro@noreply.github.com>
Kopia:  David Reinhold <david@reinholds.se>
Ämne:  Re: [openhab-distro] Error: Could not find or load main class Files when installing openhab2 as a service on Windows (#112)


Are you using Java 1.8? Does your installation path have spaces? 
Did you install the service whilst logged on with administrator rights?

**Comment by splatch** [comment]
Most likely wrapper configuration is invalid. Please add `wrapper.debug=TRUE` to your configuration file and post output cause you could get invalid pointer to karaf main.jar.

**Comment by davidreinhold** [comment]
Hi,

I didn’t see the loglevel-flag in the config. Thank you!

The issue was the paths in the config file. The file was originally generated with slashes instead of backslashes so the path:s looked like this:


#********************************************************************
# Wrapper Properties
#********************************************************************
set.default.JAVA_HOME=/C:/Program Files (x86)/Java/jre1.8.0_71
set.default.KARAF_HOME=/C:/openhab2/runtime/karaf/
set.default.KARAF_BASE=/C:/openhab2/userdata/
set.default.KARAF_DATA=/C:/openhab2/userdata/
set.default.KARAF_ETC=/C:/openhab2/runtime/karaf/etc/

To begin with, I only removed the first slash and replaced all slashes with backslashes but now that I saw the paths in the debug output I noticed that some path’s got double backslashes… so I removed the trailing backslashes to the  ”Wrapper Properties”-paths:

#********************************************************************
# Wrapper Properties
#********************************************************************
set.default.JAVA_HOME=C:\Program Files (x86)\Java\jre1.8.0_71
set.default.KARAF_HOME=C:\openhab2\runtime\karaf
set.default.KARAF_BASE=C:\openhab2\userdata
set.default.KARAF_DATA=C:\openhab2\userdata
set.default.KARAF_ETC=C:\openhab2\runtime\karaf\etc

That did the trick. Again, thanks for your help!

Regards,
David


Från:  Łukasz Dywicki <notifications@github.com>
Svara till:  openhab/openhab-distro <reply@reply.github.com>
Datum:  tisdag 2 februari 2016 12:42
Till:  openhab/openhab-distro <openhab-distro@noreply.github.com>
Kopia:  David Reinhold <david@reinholds.se>
Ämne:  Re: [openhab-distro] Error: Could not find or load main class Files when installing openhab2 as a service on Windows (#112)


Most likely wrapper configuration is invalid. Please add wrapper.debug=TRUE to your configuration file and post output cause you could get invalid pointer to karaf main.jar.

**Comment by dvanherbergen** [comment]
@davidreinhold which version or build of openHAB did you encounter this issue with?

**Comment by davidreinhold** [comment]
@dvanherbergen I'm not sure exactly what build I'm using, downloaded the 2.0 online distro snapshot from openhab.org on jan 31.

**Comment by dvanherbergen** [comment]
Could you try with the [latest](https://openhab.ci.cloudbees.com/job/openHAB-Distribution/) build?

**Comment by ThoSt81** [comment]
Hi there,

@dvanherbergen I tried with the build I downloaded on Feb 7th.:
https://github.com/openhab/openhab-distro/issues/132

Sorry for the duplicate ticket, I'm new here so I dont know how to link/merge them.

**Comment by kaikreuzer** [comment]
closing this in favor of #132
