### ISSUE TITLE
OH2 first startup does not load everything

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#113]
When starting the first time openHAB2 (snapshot 114) after defining in file addons.cfg package = standard and setting few bindings to be installed, th ebindings are installed but items/sitemaps/rules files are never loaded. The server is OK and I can even use Paper UI. But of course, I can link channel to no item for example.
Stopping OH2 and restarting it solves the problem.

Here is my file addons:cfg:
```
# The base installation package of this openHAB instance
# Valid options:
#   - minimal  : Installation only with dashboard, but no UIs or other addons
#   - standard : Typical installation with all standards UIs
#   - demo     : A demo setup which includes UIs, a few bindings, config files etc.
package = standard

# A comma-separated list of bindings to install (e.g. "sonos,knx,zwave")
binding = ntp,astro,netatmo,mios,mqtt,weather

# A comma-separated list of UIs to install (e.g. "basic,paper")
ui =

# A comma-separated list of persistence services to install (e.g. "rrd4j,jpa")
persistence =

# A comma-separated list of actions to install (e.g. "mail,pushover")
action = mios

# A comma-separated list of transformation services to install (e.g. "map,jsonpath")
transformation = map

# A comma-separated list of text-to-speech engines to install (e.g. "marytts,freetts")
tts =

# A comma-separated list of miscellaneous services to install (e.g. "myopenhab")
misc =
```
And I have only one additional file in addons directory: org.openhab.binding.freebox-1.9.0-SNAPSHOT.jar

**Comment by xsnrg** [comment]
I have noticed this as well.  It acts as if the repository is timing out on the download of dependencies.  Is there a timeout that perhaps could be adjusted lower?

**Comment by kaikreuzer** [comment]
@xsnrg I don't think this issue is about download failures from the remote repo - it is rather that the local config files are not correctly processed on a very first startup (likely because the OSGi framework restarts major parts after finishing the package installation, but failing to retrigger config file loading).

**Comment by maggu2810** [comment]
> it is rather that the local config files are not correctly processed on a very first startup

It seems so.
After I unpacked the b2 from bintray, the demo sitemap could not be found on first startup.
After a restart of OH2 the demo sitemap works as expected.

**Comment by lolodomo** [comment]
With a recent snapshot, I did not notice that issue.

**Comment by ibantxo** [comment]
I have installed do this: 
1) download "OH2-offline"
2) launch it in debug mode
3) open Paper UI and activate MQTT
The "loading" icon does not stop loading. So I have done a "logout" and restart OH2.

4) In openhab console --> bundle:list -s | grep mqtt. This shows 3 "Active" elements:

-      org.openhab.binding.mqtt
-      org.openhab.io.transport.mqtt
-      org.openhab.action.mqtt

If I go to Paper UI -->Configuration-->Bindings nothing appears.

If I go to conf/services/addons.cfg "binding = " line is empty
If I write this inside:
binding = ntp,astro,netatmo,mios,mqtt,weather

When I start again, in "Paper UI" -> Configuration -> Bindings only appears: "Astro Binding", "Netatmo Binding" and "NTP Binding", but "MQTT" does not appear...

**Comment by Nickolay40** [comment]
mqtt1
