### ISSUE TITLE
Create archive with Demo files

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-distro#1147]
As discussed in [openhab-webui#306](https://github.com/openhab/openhab-webui/pull/306#issuecomment-678621976) it might be better to provide the Demo setup using an archive instead of a package because it is complicated to switch from the "demo" to the "standard" package afterwards. The new UI also no longer allows for selecting the package.

**Comment by kaikreuzer** [comment]
@wborn Would you be willing to coming up with a PR for that yourself?
Or would you know anyone with a decent set of demo files (maybe @ghys as it should go well with the new UI)?

**Comment by wborn** [comment]
The current demo would be nice starting point. Coming up with a PR to create an archive is already somewhere on my todo list, but it isn't at the top. :wink: 

Maybe we want to enhance it by adding some nice UI features that @ghys showed yesterday. :sunglasses: If the demo content should also be easily modifiable using the UI we could also see if we can get the demo config/items/rules into JSON DB some way.

**Comment by kaikreuzer** [comment]
> Coming up with a PR to create an archive is already somewhere on my todo list, but it isn't at the top.

Is it getting closer to the top now? I guess we can/should pretty much reuse what @ghys created for the demo server (which is pretty awesome).

**Comment by wborn** [comment]
Yes it's getting closer. But I'm also just enjoying the OH3 release now. :wink:
