### ISSUE TITLE
2.5.9 release notes: add PR [openwebnet] #8437

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-distro#1151]
PR #8437 has not been included 2.5.9 in rel notes. 
Since it's an important enhancement, it should be probably included for tracking IMHO.
PR #8417 and #8403 are also part of rel 2.5.9, but maybe these are not so important for rel notes.

**Comment by kaikreuzer** [comment]
That PR was lacking the "enhancement" label, it hence wasn't included in the automatic release note generation.
I have now added it manually.

**Comment by mvalla** [comment]
many thanks, will check the label next time.
