### ISSUE TITLE
Upgrade Karaf to 4.3.1

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-distro#1167]
These Karaf versions will be released soon so we should upgrade the Karaf version used in the distro to get the latest bugfixes and enhancements.

**Comment by wborn** [comment]
Let's wait for Karaf 4.2.11 because I found an annoying bug in 4.2.10 with the `log:tail` command (https://github.com/apache/karaf/pull/1198#issuecomment-707387167) which will hopefully be fixed [soon](http://karaf.922171.n3.nabble.com/Apache-Karaf-4-2-11-soon-td4059032.html) in the 4.2.11 release. Other than that it seemed to worked fine. :slightly_smiling_face:

**Comment by kaikreuzer** [comment]
There are still no news on 4.2.11, but 4.3.0 is out instead and I assume it also contains the fix for the issue you've found.
Did you already do any tests with 4.3.0 as well? Should we aim for that, instead of 4.2.x?

**Comment by wborn** [comment]
> There are still no news on 4.2.11 

According to the [download page](https://karaf.apache.org/download.html) "soon" is 2 months later. :disappointed: 

> 4.3.0 is out instead and I assume it also contains the fix for the issue

Yes it has the fix but I currently don't have time to test it and it is not that high prio for me. It doesn't look like we're missing out on 4.3.0 features (http://blog.nanthrax.net/?p=1038) at the moment to risk stability. Unless you want to start using newer Java versions or OSGi R7 features today. :wink:

**Comment by kaikreuzer** [comment]
> According to the download page "soon" is 2 months later. 

Ah, I should have scrolled down that page 😆 .
So that sounds rather a bit late for our release, maybe it's better then to keep it for openHAB 3.1 and then go for 4.3 or newer (even though I don't need R7 right now ;-))

**Comment by kaikreuzer** [comment]
I've removed the issue from the openHAB 3 tracking.

**Comment by wborn** [comment]
This weekend I successfully tested integrating Karaf 4.3.1-SNAPSHOT in OH 3.1 and it also [seems to be released "soon"](http://karaf.922171.n3.nabble.com/HEADS-UP-Apache-Karaf-4-2-11-release-to-vote-today-td4059658.html). :smile:

**Comment by wborn** [comment]
As you can see I already created some draft PRs for upgrading to Karaf 4.3.1 which is currently on [vote](http://karaf.922171.n3.nabble.com/VOTE-Apache-Karaf-runtime-4-3-1-release-td4059759.html).
So if you can already review these changes, then we can merge the PRs when Karaf 4.3.1 is released later this week. :slightly_smiling_face:

**Comment by wborn** [comment]
I've removed the draft status from my PRs since Karaf 4.3.1 has been released.
