### ISSUE TITLE
Upgrade / Update option in UI Openhab 3 - Windows

### ISSUE THREAD

**Issue by Daniel10001** [openhab/openhab-distro#1176]
Upgrade/Update option within UI. 

Will it be possible to create a auto update / Update button within the UI to update openhab?

It is a real pain using Powershell.

Your Environment
 Windows 10. 
openhab-3.0.0-SNAPSHOT

**Comment by kaikreuzer** [comment]
This won't be possible as there are many different ways of installing (and hence upgrading) openHAB: From the zip, through APT or YUM, in openHABian, on Synology or as a Snap,...
For Windows specifically, you might be interested in https://github.com/openhab/openhab-distro/issues/807, though.
