### ISSUE TITLE
Upgrade to 2.5.10 causes systemd warning "The unit file, source configuration file or drop-ins of openh ab2.service changed on disk."

### ISSUE THREAD

**Issue by Rosi2143** [openhab/openhab-distro#1182]
When upgrading to OH 2.5.10 the file `/etc/systemd/system/openhab2.service.d/override.conf`, but does not trigger a `systemctl daemon-reload`.

This results in the warning
```
systemctl status --full --line=50 openhab2.service
Warning: The unit file, source configuration file or drop-ins of openhab2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● openhab2.service - openHAB2 instance, reachable at http://openhab:8080
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/openhab2.service.d
           └─override.conf
   Active: active (running) since Wed 2020-11-04 16:09:26 CET; 3h 20min ago
     Docs: https://www.openhab.org/docs/
```

This warning is printed at the end of a `systemctl restart openhab2.service`.

see also [The unit file, source configuration file or drop-ins of openh ab2.service changed on disk. Run ‘systemctl daemon-reload’ to reload units](https://community.openhab.org/t/the-unit-file-source-configuration-file-or-drop-ins-of-openh-ab2-service-changed-on-disk-run-systemctl-daemon-reload-to-reload-units/85378/17)

**Comment by wborn** [comment]
If this is still an issue in OH4, please create an issue for it in the openHABian [issue tracker](https://github.com/openhab/openhabian/issues).
