### ISSUE TITLE
DateTime format in things OH3 - how to change

### ISSUE THREAD

**Issue by matulekpl** [openhab/openhab-distro#1185]
Hello,
Can someone tell me how to change DateTime format?
Now it shows as "2020-11-18T11:53:56.101236+01:00[Europe/Warsaw]".
How to change it to normal?:slight_smile:

[%1$td.%1$tm.%1$tY, %1$tH:%1$tM] in item label isn’t working…

**Comment by wborn** [comment]
[I think you've already found a solution](https://community.openhab.org/t/openhab-3-0-milestone-2-discussion/107564/179?u=wborn)?
Please use the [community](https://community.openhab.org/) for such support questions.

**Comment by matulekpl** [comment]
> [I think you've already found a solution](https://community.openhab.org/t/openhab-3-0-milestone-2-discussion/107564/179?u=wborn)?
> Please use the [community](https://community.openhab.org/) for such support questions.

No I didnt.
This linked post was due to frontail log viewer.

On community forum they always say that they are not support...
I try to find every anwers to my questions by myself. But for this I cannot find enything.

**Comment by matulekpl** [comment]
Can You please reopen it? 
I cant find any way to change format of any items. I cant change units of mesurement, cant change datetime format...

**Comment by kaikreuzer** [comment]
As @wborn mentioned: Github is for bug reports, not for support.
If you think you have found a bug, i.e. something that worked as expected in 2.5 but now seems broken, please formulate a clear bug report by answering the questions you find e.g. in https://github.com/openhab/openhab-addons/issues/new?labels=bug&template=bug_report.md and make it as easy as possible to reproduce, e.g. by giving example config files.
