### ISSUE TITLE
Erroneous newline for 3.0.0M1-1 /var/lib/apt/lists/openhab.jfrog.io_openhab_openhab-linuxpkg_dists_testing_main_binary-i386_Packages

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-distro#1203]
![image](https://user-images.githubusercontent.com/28068256/101291479-6bd64e00-3809-11eb-91d6-dd2f4fe0ada0.png)

Coming from OH2.5.8 to OH2.5.10.
sudo apt-get update/upgrade

After a restart on 2.5.10:

```
sudo apt list -a openhab
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/openhab.jfrog.io_openhab_openhab-linuxpkg_dists_testing_main_binary-i386_Packages
E: The package lists or status file could not be parsed or opened.
```

Deleting the line fixes the problem.

**Comment by hmerk** [comment]
M1 is a couple of weeks old, we are on M5 since today, could you please recheck with M5.

**Comment by kaikreuzer** [comment]
Shouldn't this rather go to https://github.com/openhab/openhab-linuxpkg?

**Comment by olemr** [comment]
@kaikreuzer OK, I wasn't quite certain where to post. Can you move it?
@hmerk it is not a 3.0.0 issue per se, I find that apt-get update et al stops working after coming from 2.5.8 to 2.5.10.

**Comment by kaikreuzer** [comment]
@olemr Unfortunately I cannot move it - somehow some repos disappeared for me from the list of repos I can move issues to... 🙄

**Comment by hmerk** [comment]
@olemr there was a known issue with Artfactory, which should have been solved now.
One issue remains, you need to stop openHAB before doing apt upgrade.

**Comment by olemr** [comment]
OK, thanks. It just that I have this happen since I have tried downgrading from 2.5.10 to 2.5.8 several times because of https://github.com/openhab/openhab-addons/issues/9175.
A bit OT, but downgrading both OH2 & deconz to known working versions did not help. Feels like something is 'stuck' between versions when upgrading and downgrading.
And then I hit https://github.com/openhab/openhab-addons/issues/9264 so 2.5.10 feels a bit broken for me just now, so I'm gonna try out 3.0.0M5 when the dust settles :-)
Thanks.

**Comment by wborn** [comment]
Is this still an issue and is there something to be fixed here @BClark09?

**Comment by BClark09** [comment]
I don't think so. I think this was a temporary error on Artifactory at the time which has been resolved.
