### ISSUE TITLE
log:set doesn't work when manually edited log4j2.xml exists

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-distro#1217]
I manually edited the log4j2.xml file to peel off logs for a specific binding (lutron) to do testing so that the main openhab.log file wasn't flooded out.  I made the following additions:

                
                <RollingFile fileName="${sys:openhab.logdir}/lutron.log" filePattern="${sys:openhab.logdir}/lutron.log.%i" name="LUTRON">
                        <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%-36.36c] - %m%n"/>
                        <Policies>
                                <SizeBasedTriggeringPolicy size="16 MB"/>
                        </Policies>
                </RollingFile>

                <Logger additivity="false" level="TRACE" name="org.openhab.binding.lutron">
                        <AppenderRef ref="LUTRON"/>
                </Logger>

After adding those lines, I can no longer use log:set in the console:

openhab> log:set DEBUG org.openhab.binding.samsungtv
Error executing command: Unable to set level for logger

I can make changes to existing loggers though:
openhab> log:set INFO org.openhab.binding.lutron
openhab> log:set TRACE org.openhab.binding.lutron
openhab> log:set INFO org.jupnp
openhab> log:set default org.jupnp

This seems to not be an issue with the stock/default xml file in place.

**Comment by kaikreuzer** [comment]
Have you checked whether you might have changed the file access rights when manually editing it?

**Comment by morph166955** [comment]
Changes to things that are defined in the file are made (e.g. jupnp and lutron) so I'd be hesitant to say it's a permission issue if it can modify those.

**Comment by digitaldan** [comment]
I can confirm this.  I modified my log4j2.xml  today to send zwave logs to a different appender and see the same thing.  One thing that is interesting is that i only get this error setting the log level for a binding that previously did NOT have an explicit log level set.  For those that i had already set a log level for, i can still change from say DEBUG to TRACE, but i get this error if i try setting the log level for a binding without an entry already in the   log4j2.xml file.

**Comment by digitaldan** [comment]
Also,  user, group and permissions are all fine for the file.

**Comment by matulekpl** [comment]
I had same problem, but when I updated this file throu ftp owner of the file changed to openhabian, and shoud be openhab. I changed it and everything is ok.

**Comment by Dan1001** [comment]
Hi - just wondered if anyone had made any progress on this. I've changed the ownership of log4j2.xml to openhab and still can't change log levels at the console...

**Comment by wborn** [comment]
Is this still an issue? It seems to work fine for me on OH 3.4.0-SNAPSHOT.

**Comment by mhilbush** [comment]
I recall seeing this problem in the past. But I just tried it and it's no longer a problem for me. I'm on 
```
3.4.0-SNAPSHOT - Build #2991
```
