### ISSUE TITLE
Is mid the new file extension for Karaf files ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#1218]
![image](https://user-images.githubusercontent.com/10186704/102710657-23606b00-42b4-11eb-915a-eb2133476cde.png)

I usually download from this page for new snapshosts, the zip and the kar files.

Since few days, even if the displayed text is openhab-addons-3.0.0-SNAPSHOT.kar, the result of its downloading leads to a file named openhab-addons-3.0.0-SNAPSHOT.mid.

Is mid the enw extension for Karaf files ?
The last times, I just renamed the file extension and it was working.

**Comment by lolodomo** [comment]
Addtional note: kar file size moved form 168 KB to 207 KB between snapshot 2085 and 2093.

**Comment by kaikreuzer** [comment]
> even if the displayed text is openhab-addons-3.0.0-SNAPSHOT.kar, the result of its downloading leads to a file named openhab-addons-3.0.0-SNAPSHOT.mid.

It is not just the text, but if you have a closer look, the link itself is also to .kar: https://ci.openhab.org/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-addons/target/openhab-addons-3.0.0-SNAPSHOT.kar

And it also downloads just fine:
```
➜  ~ wget https://ci.openhab.org/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-addons/target/openhab-addons-3.0.0-SNAPSHOT.kar
--2020-12-20 12:37:00--  https://ci.openhab.org/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-addons/target/openhab-addons-3.0.0-SNAPSHOT.kar
Resolving ci.openhab.org (ci.openhab.org)... 51.15.109.212
Connecting to ci.openhab.org (ci.openhab.org)|51.15.109.212|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 212860169 (203M) [audio/midi]
Saving to: ‘openhab-addons-3.0.0-SNAPSHOT.kar’

openhab-addons-3.0.0-SNAPSHOT.kar                 100%[============================================================================================================>] 203,00M  15,9MB/s    in 13s     

2020-12-20 12:37:14 (15,1 MB/s) - ‘openhab-addons-3.0.0-SNAPSHOT.kar’ saved [212860169/212860169]
```

> kar file size moved form 168 KB to 207 KB

I guess you mean MB, not KB :-)
That's expected see https://github.com/openhab/openhab-addons/pull/9404#issue-541488150

**Comment by lolodomo** [comment]
Maybe a problem with Firefox browser !?
