### ISSUE TITLE
thing files not evaluated in OH3

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-distro#1221]
Hello all,
I still have the problem that some thing files not evaluated and things not loaded correctly. For example yio thing is not loaded at the beginning and there is no error message in the log.
And if i add this manually over the gui everything is there also loading at next restart, therefore it's not a binding issue.

Also I see no debug output if I add the logger but the binding is loaded

252 │ Active │  80 │ 3.0.0.202012201547      │ org.openhab.binding.yioremote

**Comment by kaikreuzer** [comment]
If the thing type used in a thing file is not available in the system, you won't see the thing in the UI - so this is normal/expected behaviour.
I thus suspect that there is an issue with your thing definition. If you really believe that there is a bug, please provide a reproducible example of a things file and file the issue for yioremote in openhab-addons. Thanks!

**Comment by miloit** [comment]
Hello @kaikreuzer in the developer environment it is visible in the ui and also debug messaages appear only in the OH3 RC2 it is not there.

attached the thing file

`Thing yioremote:yioRemoteDock:livingroom "YIO Remote Dock Livingroom" [host="192.168.178.44",	accesstoken="0"  ]`

**Comment by kaikreuzer** [comment]
I have tested your file on 3.0.0 and the thing turns up in the UI and I see in the log that the handler is also initialized:
```
11:22:10.851 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'yioremote:yioRemoteDock:livingroom' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): Communication lost no ping from YIO DOCK
```

**Comment by miloit** [comment]
@kaikreuzer I tracked it also down....and I had a bad thing file in my configuration and every file after the bad file never loaded.
