### ISSUE TITLE
Set Chromecast binding to Error level in log4j2.xml

### ISSUE THREAD

**Issue by scatterthought** [openhab/openhab-distro#1241]
@wborn I'd like to suggest that the following code be added to log4j2.xml to set the Chromecast binding to Error level. 

```
<!-- Filters known issues of Chromecast -->
<!-- https://community.openhab.org/t/oh3-chromecast-broken-pipe/112581 -->
<Logger level="ERROR" name="su.litvak.chromecast.api.v2.Channel"/>
```

This is due to the known issue of Chromecasts throwing regular errors, per this conversation with @cweitkamp:

https://community.openhab.org/t/oh3-chromecast-broken-pipe/112581

Thanks!

**Comment by wborn** [comment]
Yes they are annoying and I also reconfigure the logging to suppress them! I've created a PR for it.

**Comment by scatterthought** [comment]
Thanks, guys!
