### ISSUE TITLE
demo.rules still uses "system started"-Trigger

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-distro#1246]
The demo.rules file still uses the "system started"-Trigger even though on openHAB 3 we now have the start level functionality and trigger (and system started is mapped internally). As it's foreseeable that this will become deprecated it shouldn't be used in the demo file so when people are migrating they can consider changing that aswell (and new OH 3.0 users learn how to do it properly from day 1).

**Comment by kaikreuzer** [comment]
"system started" makes perfect sense for DSLs and there are no plans to deprecate/remove it.
Once something is declared deprecated, it makes sense to remove it from examples.
