### ISSUE TITLE
Repo for extensions persistence services not complete

### ISSUE THREAD

**Issue by msfunty** [openhab/openhab-distro#125]
I don't know if this issue belongs to the distro or add-on package.

When configuring extensions in Paper UI the list for persistence services is not complete referring to documentation https://github.com/openhab/openhab-distro/blob/master/docs/sources/addons.md#compatible-1x-add-ons:

- InfluxDB (v. 1.0) is working fine but not listed in extension repo
- MongoDB is missing
- Logging should not be listing anymore (or is documentation wrong)

**Comment by maggu2810** [comment]
This files needs to be changed:
https://github.com/openhab/openhab/blob/master/features/openhab-addons/src/main/feature/feature.xml#L461

**Comment by msfunty** [comment]
Updated with https://github.com/openhab/openhab/pull/4024

**Comment by kaikreuzer** [comment]
As it is tracked on https://github.com/openhab/openhab/pull/4024, I close this issue here.
