### ISSUE TITLE
Docker upgrade from 3.0.0 to 3.0.1 (latest)

### ISSUE THREAD

**Issue by Samo27** [openhab/openhab-distro#1254]
Hi,
after docker upgrade from 3.0.0 to latest (3.0.1) the bindings are all gone.

Error:
_2021-01-27 11:15:11.959 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-modbus, openhab-binding-icalendar, openhab-persistence-mapdb, openhab-binding-exec, openhab-binding-mail, openhab-persistence-jdbc-mariadb, openhab-binding-network, openhab-ui-habpanel, openhab-transformation-jsonpath, openhab-binding-miio, openhab-binding-zoneminder, openhab-binding-mqtt, openhab-ui-basic, openhab-binding-openweathermap, openhab-binding-astro': Error: Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.jdbc/3.0.1_

I downgraded to 3.0.0 and everything works fine.

Best regards,
Samo

**Comment by kaikreuzer** [comment]
3.0.1 release isn't yet fully in place - please wait until tonight, everything should work by then.
