### ISSUE TITLE
Download link to OH 3.0.1 is broken

### ISSUE THREAD

**Issue by egoist6** [openhab/openhab-distro#1255]
"The binaries are available on Bintray and via "Stable" on our APT repository."
Download links are broken
[https://bintray.com/openhab/mvn/openhab-distro/3.0.1](url)
[https://bintray.com/openhab/apt-repo2/openhab2/3.0.1](url)

**Comment by kaikreuzer** [comment]
Release has not yet been completed & announced. I removed the release notes again to avoid such confusion.
