### ISSUE TITLE
Move away from Bintray

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#1256]
Bintray is about to be closed: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We will therefore need to remove any links to Bintray and find a suitable substitution.

The simplest option atm seems to be the move to Artifactory (openhab.jfrog.io) - the risk here is though that it is operated by the same company as Bintray, so we might be warned that this could turn out to be a fragile option as well. Since we have all our snapshot and milestone artifacts there already. I'd nonetheless suggest to go this way. It might be a worthwhile effort to check whether we can set up a [CNAME DNS entry](https://jfrog.com/knowledge-base/how-to-configure-custom-cname-for-artifactory-cloud/), so that we would at least be under control of the DNS name and could point it to somewhere else in case the free JFrog Artifactory is ended some day.

A better option for releases would be to directly publish them to Maven Central - I am not sure how easy and stable we could get that into our release build jobs.

This issue is meant as an aggregate to track the efforts that are needed.

- [X] Change "update" script in distro  - #1271
- [x] Change website download location
- [x] Remove mentions of Bintray from documentation/website
- [x] Change "distributionManagement" section in all pom-xmls
- [x] Adapt build plans
- [x] Adapt Docker build/containers (https://github.com/openhab/openhab-docker/pull/356)
- [x]  inform users to change download locations e.g. in their linux distributions (apt/rpm)
- [x] Change openhab-osgiify to not require artifacts from Bintray
- [x] Change artifactory to not include Bintray locations anymore

**Comment by BClark09** [comment]
Also commenting here to track and to mention that Bintray is our stable host for the Linux packages.

Fortunately, our stable packages are available on Artifactory so I suspect a notification to transfer and documentation change is all that's needed here.

We have openHAB 1.x packages available from Bintray. I know that's going back a bit, but should we transfer these?

**Comment by kaikreuzer** [comment]
For the zipped distro and KARs, I am just pushing the latest+major releases (2.5.12, 2.5.0, 2.4.0, ... 2.0.0, 1.8.3) to Maven Central, see https://repo1.maven.org/maven2/org/openhab/distro/openhab/

If it is possible to move the linux packages as well (I guess our Artifactory is the only real target option, right?), it might be nice not to loose them. Is there some mechanism you could use to transfer them?

**Comment by Orifahrer** [comment]
I am trying to set up openhab 2.5.12 in my new docker env (using OH2 on Raspi until now). As my docker setup still needs some tweaking, I reinstalled the container several times to improve my settings. This seemed to be working until yesterday, but today I am getting a whole bunch of errors when I try to do the recommended setup to install PaperUI.

openhab.log says:
[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-homebuilder, openhab-ui-basic, openhab-ui-habpanel, openhab-ui-paper': Error:
	Error downloading mvn:commons-collections/commons-collections/3.2.2

I find these errors in the container stdout log:
Error downloading mvn:commons-collections/commons-collections/3.2.2
...
Caused by: java.io.IOException: Error resolving artifact commons-collections:commons-collections:jar:3.2.2: [Could not find artifact commons-collections:commons-collections:jar:3.2.2 in openhab (https://openhab.jfrog.io/openhab/libs-release/)]

Could it be related to this issue (as I cannot find anything related to common-collections under the given URL)?

**Comment by kaikreuzer** [comment]
@Orifahrer That seems due to cleanups on Artifactory - I hope that this will be fixed again when Artifactory hit cache expires after a couple of hours. If the problem persists tomorrow, please open a dedicated issue about it here in this repo.

**Comment by BClark09** [comment]
> I guess our Artifactory is the only real target option, right? 

I think so, although would we run into any storage constraints?

> Is there some mechanism you could use to transfer them?

I'll have a look, might be a case of designing a new script for it so that we can get those 1.8.3 packages on and signed. There's a .deb package for each add-on so might take a bit of time.

**Comment by mvalla** [comment]
- is moving OH to [GitHub packages](https://docs.github.com/en/packages/learn-github-packages/about-github-packages)  maybe another option?
- the OH3 openwebnet binding links a lib that is currently published to bintray/JCenter. I would like to move the lib to either maven central or to GitHub packages. What would you suggest? Can GitHub packages be added in the OH build process as a source for dependency libs? How?

Sorry maybe question is stupid but I am not full knowledgeable about OH build process

**Comment by kaikreuzer** [comment]
> is moving OH to GitHub packages maybe another option?

The last time I checked, it still was required to authenticate even for public packages - so this is imho currently no option.

>  I would like to move the lib to either maven central or to GitHub packages. What would you suggest? 

I'd definitely suggest to push it to Maven Central. As long as Bintray/JCenter is available, it is actually [quite easy to get it pushed to MC](https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/).

**Comment by pfink** [comment]
What about the apt packages?

**Comment by pfink** [comment]
Results from JFrog call: They are dedicated to support FOSS projects (they referred this website: https://jfrog.com/open-source/#programs). They have a replacement solution for the software distribution use case (e.g. `apt`, download from website, ...), but they can't tell whether this could be offered to us free of charge. They requested to write an e-mail with all details regarding our project.

**Comment by pfink** [comment]
Update from packagecloud: They would offer us all their services for free if we confirm that we're not backed by any company.

**Comment by kaikreuzer** [comment]
> It seems that we assume Artifactory already provides everything we need. I'm wondering, what was the reason to use Bintray in the first place then?

Simply: Bintray was there in the first place and we always used it for our downloads. It especially provides a CDN, which makes it more efficient than Artifactory.

For Artifactory, we already have a free OSS plan, so assuming that will stay, we could stick to it. I'll follow up on the CNAME with them, let's see.

**Comment by kaikreuzer** [comment]
@wborn I have added our latest releases 3.0.1 and 2.5.12 to Artifactory, so that they are now available under the new location https://www.openhab.org/download/releases (like e.g. https://www.openhab.org/download/releases/org/openhab/distro/openhab/3.0.1/openhab-3.0.1.zip).
I do not plan to move any older releases, though.

This should make it possible to start working on adapting the Docker build right away.

**Comment by kaikreuzer** [comment]
@BClark09 May I ask you to look into what is necessary to do for the linux-packages?

> I'll have a look, might be a case of designing a new script for it so that we can get those 1.8.3 packages on and signed. There's a .deb package for each add-on so might take a bit of time.

We should be careful with the disk space on Artifactory. My suggestion would be to only keep the latest version of every (old) release, i.e. openHAB Distro 1.8.3, 2.5.12, 3.0.1, openHAB Addons 1.14.0, 2.5.12, 3.0.1.

More important than moving the old ones is to make sure that any update scripts etc. are changed on time. After April, we do not have any write access to Bintray anymore, so whatever we need to deploy there in order to push out required changes to the users, must be done within the next weeks.

**Comment by kaikreuzer** [comment]
> I'll follow up on the CNAME with them, let's see.

This feels too complicated and I think https://github.com/openhab/website/pull/278 is a good solution for our problem. With this, we can make sure that our download location for updates can stay the same, even if we have to move binaries in the future. For the build itself, we had already introduced the openhab-super-pom, which allows us to "retrofit" any changes in repositories on the existing builds.

**Comment by wborn** [comment]
> I have added our latest releases 3.0.1

Thanks but it looks like the KAR file didn't get properly named. :thinking: 

https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/openhab-addons/3.0.1/

> We should be careful with the disk space on Artifactory.

OK that explains why it might not be feasible to upload all releases there right now.

There are also some scripts in [openhab-syno-spk](https://github.com/openhab/openhab-syno-spk/blob/a8554865167a5d28358fdc91a1de182301e30c47/scripts/installer.sh#L16) (@cniweb) and [openhab-snap](https://github.com/openhab/openhab-snap/blob/8c2e0caf5912652e20b800b4ee285e4f60d64183/snap/snapcraft.yaml#L223) (@kubiko) that need to be updated before they can download artifacts using these new URLs

**Comment by kaikreuzer** [comment]
> Thanks but it looks like the KAR file didn't get properly named.

Oops. Fixed!

**Comment by wborn** [comment]
> For the build itself, we had already introduced the openhab-super-pom, which allows us to "retrofit" any changes in repositories on the existing builds.

Looks like with these changes the redirect isn't used for the [online.repo](https://github.com/openhab/openhab-distro/blob/1feb2667b294907a8f958446a4f1b23a1fc9ae82/pom.xml#L203-L228) used for downloading add-ons? So if `openhab.jfrog.io` is moved some place else, it currently can only be used after upgrading openHAB to a new version with an updated online.repo URL.

If those downloads get redirect too, I think it would further increase the download counts you gave in https://github.com/openhab/website/pull/277#issuecomment-808011037: 

> We have around 500-1000 (manual, not apt) downloads a day - that's less than one request per minute, so that shouldn't be an issue really.

Do these redirects also keep working while the website is updated to a new version?

**Comment by kaikreuzer** [comment]
> Looks like with these changes the redirect isn't used for the online.repo used for downloading add-ons?

Correct, I suggest to keep it the same and not use the redirect. It will point to the location of the addons for the version.
It won't matter if the location for future releases changes.
And in case we have to (re)move addons for older releases, people can still either use the KAR or easily change the online repo location in `userdata/etc/versions.properties`.

**Comment by kaikreuzer** [comment]
> Do these redirects also keep working while the website is updated to a new version?

You mean if it can be temporarily down? No, I think Netlify does a live update where we shouldn't really see any downtimes.

**Comment by BClark09** [comment]
> We should be careful with the disk space on Artifactory. My suggestion would be to only keep the latest version of every (old) release, i.e. openHAB Distro 1.8.3, 2.5.12, 3.0.1, openHAB Addons 1.14.0, 2.5.12, 3.0.1.

That's fine, I've cleared some space on Artifactory for this as I mentioned to you earlier, but what URL should we provide the build scripts to build the new installer packages?

https://repo1.maven.org/maven2/org/openhab/distro/

or 

https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/

I would like to keep the ability to build installers of older packages should anyone need them.

**Comment by kaikreuzer** [comment]
> what URL should we provide the build scripts to build the new installer packages?

Please use https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/.

> I'm not quite clear on the deadline to upload new artifacts to Bintray

<img width="952" alt="Screenshot 2021-03-30 at 19 33 35" src="https://user-images.githubusercontent.com/3244965/113031323-dc292680-918e-11eb-9324-c65450a0b73a.png">

> but I would like to include a sources file in the 3.0.2 package that automatically moves them to artifactory.

That would be great, yes.
I'd suggest we aim for a 3.0.2 release on April 18. This will still leave us another weekend, in case something does not work out and we have to do further fixes on Bintray through a 3.0.3 release.

**Comment by BClark09** [comment]
Sounds good to me! 🙂

**Comment by bwosborne2** [comment]
I notice all 2.5.x snapshot builds are broken in Jenkins die to this more. This is especially an issue for the zwave binding. Are there any plans to resume 2.5.1x SNAPSHOTs?

**Comment by kaikreuzer** [comment]
@bwosborne2 Not really, I simply do not have the capacity to do release management for 3 branches in parallel and 2.5.x was anyhow considered to only be continued for critical (security) bug fixes - which we did with 2.5.12. The Bintray sunset is indeed an additional burden that makes any further release unlikely.

**Comment by bwosborne2** [comment]
@kaikreuzer That is the reason mature projects do not depend on a single individual, especially for critical tasks. There is more than one individual for redundancy and scalability. I would guess everybody (developers & users) would not want OH releases to stop because you became unavailable or unable to handle release management. I expected such a system was already in place for OH.

There were already some 2.5.13 snapshot releases. Where were the users & developers given advance notice  there would no longer be any new 2.5.1x releases?

One reason I subscribed to this issue was to follow the progression of 2.5.x movement away from bintray.It appears I personally made a mistake moving my Z-Wave home system from Home Assistant to openHAB. I still see many issues in 3.0.x that will hopefully be corrected in 3.1.x, fulfilling  my prediction it would take 2 years for a stable (meaning feature-complete & bug-free) OH3 release.

**Comment by yuergen** [comment]
I am not exactly sure if my comment will be helpful, I hope it will be. OpenSuse does offer the build service which can build packages for the major distributions (i guess .deb ist morst important here). It's also powered by an established company, which does offer the service since 15 years according to archive.org for the URIs. I do not have enough understanding about the openhab build process to know if OBS can build openhab - maybe you can give it a go. [https://en.opensuse.org/Portal:Build_Service] and [https://build.opensuse.org/]

**Comment by delid4ve** [comment]
Some of us simply do not have the option to move to 3.x either. No docker support for arm and 3.x has not yet been packaged for QNAP/Synology afaik.

I also feel openhab needs a status page for all the different servers.  There are countless forum posts today (myself included) regarding bintray being down.  I only cleared my cache to test a newly compiled jar and now I’m without a home. End users and others (myself included again) simply don’t know about all the different servers used

**Comment by wborn** [comment]
Hi @kaikreuzer! We probably still need to make some changes for [openhab-osgiify](https://github.com/openhab/openhab-osgiify). I cannot build it with an empty repo.

The build also seems to have some issues downloading content, see:

https://ci.openhab.org/view/All/job/openhab-osgiify/22/

**Comment by kaikreuzer** [comment]
Build issues were seemingly just temporarily - now it is green.
But yes, as it downloads stuff from Bintray, we will have to take care of this since it will otherwise break next month.

**Comment by wborn** [comment]
I only build the new project in that build as workaround for the brown-out today, see:

https://status.bintray.com/

**Comment by kaikreuzer** [comment]
Got it.
I've transferred the required files to Artifactory and created https://github.com/openhab/openhab-osgiify/pull/20 and https://github.com/openhab/openhab-osgiify/pull/21, which together should solve the build issue.

**Comment by kaikreuzer** [comment]
I guess this can be closed now.
