### ISSUE TITLE
Delay Configuration Loading after Cache Clearing

### ISSUE THREAD

**Issue by bwosborne2** [openhab/openhab-distro#1272]
openHAB should delay loading its Thing and Item configuration until after its cach has been rebuilt. 

Currently many people need to restart openHAB after upgrading due to the cache not being available immediately after the upgrade.

More comments here.
https://community.openhab.org/t/need-to-restart-oh-twice-after-upgrading-daily-snapshot-release/77847

**Comment by kaikreuzer** [comment]
The linked thread was created for openHAB 2.5 and there isn't any helpful information wrt openHAB 3 of what's going wrong.

With https://github.com/openhab/openhab-core/pull/1914, we have put a lot of effort on optimizing startup behavior and order. If there are certain parts still open, I'd wish for a more detailed bug report to see what's happening and what might be possible to improve.
