### ISSUE TITLE
OH3 Apache Reverse-proxy Authentication Fails Unauthorized access

### ISSUE THREAD

**Issue by Hect0rG** [openhab/openhab-distro#1277]
I am having issues just recently when connecting remotely using the proxy setup. It gives me the same issue from the android app, iPhone app, and browser.

The issue began around the time of my update to openHAB 3.1.0.M3 from M2 but I can’t pinpoint the exact date or if it was due to that.

I recently posted this same info on the openHAB community forum [here](https://community.openhab.org/t/oh3-apache-reverse-proxy-authentication-fails-unauthorized-access/120578) and others are having the same issues. Some without having the reverse proxy setup so it seems something on M3 did break functionality.

Here is some info that may be helpful. ( local IP’s and hostnames have been masked )

My apache config that has been stable since December of 2020 when I got my last issue resolved is below.

```
<VirtualHost *:444>
        ServerName xyz.example.com
        SSLEngine on
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
        ProxyPreserveHost on
        ProxyPass      / http://10.0.0.1:8080/
        ProxyPassReverse / http://10.0.0.1:8080/
        RequestHeader set X-Forwarded-Proto "https" env=HTTPS
        <Location />
                AuthType Basic
                AuthName "xyz.example.com 444 "
                AuthUserFile /etc/apache2/.passwd
                Require valid-user
                Allow from 10.0.0.0/255.255.255.0
        </Location>
</VirtualHost>
```
Here is the [link to thread ](https://community.openhab.org/t/openhab-3-apache-reverse-proxy-setup-issue/110148) that helped me figure out what was wrong originally after migrating to OH3 when I had my first issue.

Below is my apache log when I try to use the openhab app on the android phone remotely using the apache proxy setup above. Notice that the first line gets a 200 response but the second gets a 401 Unauthorized access. This tells me that the username/password combo is correct because the first line goes through but somehow it is being prompted for authentication again and failing.

```
10.0.###.### - openhabuser [10/Apr/2021:08:35:55 -0400] "GET /rest/ HTTP/1.1" 200 6133 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
10.0.###.### - openhabuser [10/Apr/2021:08:35:55 -0400] "GET /rest/sitemaps HTTP/1.1" 401 364 "-" "Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19"
```
I do have various virtualhosts set up on this server for other functions but to make sure that it is being captured by the correct virtualhost, I added the following two lines to my original virtualhost declaration up top and am now just looking at those two logs specific to this virtualhost. This assures me that it is not an issue with the virtualhost setup.

```
ErrorLog /var/log/apache2/oh_444_error.log
CustomLog /var/log/apache2/oh_444_access.log combined
```
I can access with no issue locally when I am on my home network (this bypasses the proxy and password setup).

When accessing from a firefox browser on an android phone remotely, I am able to get in. My basiui sitemaps however has a note on the bottom that says “SSE subscription failed. running in fallback mode” and I am getting these errors continuously.

```
166.175.167.22 - openhabuser [10/Apr/2021:10:11:10 -0400] "GET /rest/sitemaps/xyz/xyz?_=87906b6db52eb8 HTTP/1.1" 401 364 "https://xyz.example.com:444/basicui/app" "Mozilla/5.0 (Android 11; Mobile; rv:87.0) Gecko/87.0 Firefox/87.0"
```

**Comment by Hect0rG** [comment]
Yup I was the one that opened that thread :) and I actually included it in my post above. 

After I posted, others mentioned they were having same issues and recommended I post an issue here.

**Comment by dooblem** [comment]
I got the same problem.

With OH3 you need to add some config on the headers. Relevant apache config here: 
https://community.openhab.org/t/oh3-with-nginx-reverse-proxy-and-authentication/106528/34

Official doc on the matter (nginx):
https://www.openhab.org/docs/installation/security.html#add-authorization-and-cookie-directives-in-nginx-configuration

**Comment by JustinGeorgi** [comment]
> With OH3 you need to add some config on the headers. Relevant apache config here:
> https://community.openhab.org/t/oh3-with-nginx-reverse-proxy-and-authentication/106528/34

Thank you, but this issue is not about upgrading from OH2 to OH3.  The users experiencing this issue had reverse proxies that took the new OH3 header requirements into account and were working with earlier versions of OH3 but stopped working only on the newest milestone version of OH3.

If you do have a working apache reverse proxy config specifically for the 3.1.0.M3 release then it would be very helpful to share that information, otherwise, to my knowledge, this bug is still open.

**Comment by Hect0rG** [comment]
I checked and I actually already have those headers set up. Still not working.

**Comment by kaikreuzer** [comment]
@wborn or @ghys: Do you happen to have any idea what change might have changed anything in the behavior between M2 and M3?

**Comment by ghys** [comment]
Could be a misconfiguration in Settings > API Security

Allow Basic authentication needs to be OFF
Implicit User Role (under "Show advanced") needs to be ON

**Comment by wborn** [comment]
For me it still seems to work if I use a NGINX container as reverse proxy with openHAB 3.1.0.M5.

**Comment by JustinGeorgi** [comment]
> Could be a misconfiguration in Settings > API Security

It's not the security settings.  Mine are currently set to Basic OFF and User Role ON and it doesn't work.  Also, those settings didn't change on my system when upgrading from M2 to M3.  If it helps, testing at the time the error occurred showed no difference in response between Basic OFF and ON options.



> For me it still seems to work if I use a NGINX container as reverse proxy with openHAB 3.1.0.M5.

Yep, it only appears to be the small minority of us apache dinosaurs so it's possible that whatever changed could be solved with some additional apache config, but I (with little to no expertise) haven't been able to find any such thing.

**Comment by wborn** [comment]
I also noticed your config doesn't have something equivalent to [Add authorization and cookie directives in NGINX Configuration](https://www.openhab.org/docs/installation/security.html#add-authorization-and-cookie-directives-in-nginx-configuration). So if your passwords mismatch there will be issues. 🤔

**Comment by JustinGeorgi** [comment]
The OP does not show these lines, but my config has always had them (at least, I believe these are the apache equivalents):

```
<VirtualHost *:443>
        ServerName ****************
        SSLEngine on
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/**************/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/***********/privkey.pem
        Header set Set-Cookie "X-OPENHAB-AUTH-HEADER=1"
        ProxyPreserveHost on
        ProxyPass      / http://localhost:9080/
        ProxyPassReverse http://localhost:9080/ /
        RequestHeader set X-Forwarded-Proto "https" env=HTTPS
  	Header add Authorization ""
  	RequestHeader set Authorization ""
        <Location />
                AuthType Basic
                AuthName "********"
                AuthUserFile ***************
                Require valid-user
        </Location>
</VirtualHost>
```

**Comment by ghys** [comment]
```
  	Header add Authorization ""
  	RequestHeader set Authorization ""
```
The first `Header` directive is perhaps causing your issues. Here you send an empty Authorization header in the *response* which might cause issues. - try removing it.

**Comment by JustinGeorgi** [comment]
> The first `Header` directive is perhaps causing your issues. Here you send an empty Authorization header in the _response_ which might cause issues. - try removing it.

No luck.  Still the same result without the `Header add Authorization ""` line, and again that exact config is not an issue with M2.

Could something in [this PR](https://github.com/openhab/openhab-webui/pull/948) have caused the issue?

**Comment by JustinGeorgi** [comment]
Additional data point: As a test, I configured my owntracks app to use the reverse proxy instead of ohCloud.  That works 100%.

It seems it is just the UI that is choking on the reverse proxy.

**Comment by Hect0rG** [comment]
I can also confirm I have tried setting the passwords the same on reverse proxy in apache and in openhab but that does not work. Finally as @JustinGeorgi noted, I also happen to have OwnTracks running and that works flawlessly.

**Comment by hal2000gh** [comment]
Just an additional note (not sure it's of any help, but maybe it is):
 
I have just upgraded from 3.0.2-1 to 3.1.0-1 (stable) and observe the same issue with Apache reverse-proxy and similar config as shown above. I also noted that calling `<server>/rest/sitemaps` I get the following response **after entering username and password** for the Apache authentication: 

`{"error":{"message":"Authentication required","http-code":401}}`

**Comment by roben** [comment]
I am experiencing the same issue having a nearly identical vhost config as the OP. 
After downgrading to the latest OH 3.0.x everything worked again just fine.

**Comment by roben** [comment]
> Could something in [this PR](https://github.com/openhab/openhab-webui/pull/948) have caused the issue?

The issue also affects the Basic UI which seems to not be changed by the PR. I don't think that it is the cause.

**Comment by roben** [comment]
The problem was resolved in the forum thread (https://community.openhab.org/t/oh3-apache-reverse-proxy-authentication-fails-unauthorized-access/120578/13). It was either `RequestHeader unset Authorization` vs `RequestHeader set Authorization ""` or `X-OPENHAB-AUTH-HEADER=true` vs `X-OPENHAB-AUTH-HEADER=1` which worked fine up until M2.

**Comment by Hect0rG** [comment]
As @roben mentioned just above, the issue was resolved with a change to apache config. 

I confirmed that what fixed it was changing from

` RequestHeader set Authorization "" `

to

` RequestHeader unset Authorization `

The following made no difference... X-OPENHAB-AUTH-HEADER=true vs X-OPENHAB-AUTH-HEADER=1

Closing bug report as a result. Thanks to all who helped look into the issue!
