### ISSUE TITLE
Starting OPENHAB 2 requires Registry Entries under Windows 10

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab-distro#128]
Everytime I am starting OH 2 (v2.0.0, build 201601310204), I am receiving two modal dialogs to confirm an modification to the windows registry.
This behaviour is permanent and not only during first run.

**Comment by dvanherbergen** [comment]
It's trying to read registry entries to determine your java location. Did you set JAVA_HOME?

**Comment by Marty56** [comment]
no, I did not. This resolved my problem. Thanks.
