### ISSUE TITLE
Jetty 403 Forbidden after migration from 3.1.0M3 -> 3.1.0M4

### ISSUE THREAD

**Issue by sebiJo** [openhab/openhab-distro#1284]
I am running openhabian on a Raspberry Pi. After upgrading from 3.1.0M3 to 3.1.0M4, I am not getting openHAB to run anymore: 

UI not accessible: Jetty shows `403 Forbidden`

openhab-cli console    shows: 
```
Logging in as ***
Failed to get the session.
```

OpenHab.log shows:
```
2021-05-02 22:24:35.111 [WARN ] [raf.features.internal.osgi.Activator] - Error starting activator
java.lang.IllegalStateException: BundleContext is no longer valid org.apache.karaf.features.core_4.3.1 [18]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:1027) ~[org.eclipse.osgi-3.16.200.jar:?]
```

Auto-Fix of the file permissions did not help.
Any idea what I can do?

**Comment by sebiJo** [comment]
The following has solved the issue for me:

sudo systemctl stop openhab
sudo openhab-cli clean-cache
sudo systemctl start openhab

I thought that I also tried that yesterday but maybe not as root. I cannot exclude that something else of my various attempts also has had an effect on solving the issue.

**Comment by blockbasti** [comment]
Had the same issue. @sebiJo's workaround got it working again

**Comment by kaikreuzer** [comment]
Cleaning the cache should actually automatically happen when updating, so I am not sure why this was necessary here. But besides this, I don't think we can provide any other fix here, so I'd suggest to close this issue.
