### ISSUE TITLE
Sort order in update.lst

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-distro#1296]
The sort order of versions in https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/update.lst doesn't seem intuitive (e.g. `3.1.0` is in the middle). Also, `2.5.0` exists twice. Is that intentional?

**Comment by kaikreuzer** [comment]
It is all nicely sorted.
What you have probably missed is that the file contains three different sections:
`[[MSG]]`, `[[PRE]]` and `[[POST]]`
Any release version can have entries in all of these sections, but most only have one in the MSG section. The others are for automatic migration steps on files (either before performing the update (pre) or after it (post).

**Comment by fwolter** [comment]
Oops, yes I missed that. Thanks for enlighten me!
