### ISSUE TITLE
Null Pointer Exception in OH 3.0.2

### ISSUE THREAD

**Issue by flpaoli** [openhab/openhab-distro#1297]
Platform information:
        Hardware: Pi4
        OS: OpenHabian 3.0.2
        openHAB version: 3.0.2

At 4:04 AM, when nothing special was happening, my OH started giving NullPointerExceptions in event executor, which didn't stop until I restarted the service some 16 hours later.  During this period no Item could be updated, it was almost as if the system had gone into read only mode.

```
Jun 18 04:04:27 openHABianDevice karaf[667]: Exception in thread "OH-eventexecutor-1" Exception in thread "OH-eventexecutor-2" java.lang.NullPointerException
Jun 18 04:04:27 openHABianDevice karaf[667]: #011at java.base/java.util.concurrent.LinkedBlockingQueue.dequeue(LinkedBlockingQueue.java:217)
Jun 18 04:04:27 openHABianDevice karaf[667]: #011at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
Jun 18 04:04:27 openHABianDevice karaf[667]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
Jun 18 04:04:27 openHABianDevice karaf[667]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
Jun 18 04:04:27 openHABianDevice karaf[667]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jun 18 04:04:27 openHABianDevice karaf[667]: #011at java.base/java.lang.Thread.run(Thread.java:834)
```

Five minutes later this was in my kernel.log, apprently indicating the NPE above lead to an exploding number of tasks:
`Jun 18 04:09:35 openHABianDevice kernel: [322042.913439] cgroup: fork rejected by pids controller in /system.slice/openhab.service
`

Apart from this I have no other details, no stacktrace, and am not able to reproduce since I don't know the cause.

**Comment by flpaoli** [comment]
Extra info, these are the only bindings I use:
- MQTT
- OpenWeatherMap
- SystemInfo
- WLED
- Z-Wave

**Comment by kaikreuzer** [comment]
The log does not show a proper exception, which would point to a certain line in the code where the NPE happens...
Was there anything else in your log that might be helpful for the analysis?
The effect sounds indeed worrying.

**Comment by flpaoli** [comment]
> The log does not show a proper exception, which would point to a certain line in the code where the NPE happens...
> Was there anything else in your log that might be helpful for the analysis?
> The effect sounds indeed worrying.

No, unfortunately I don't see a stacktrace of the Exception anywhere else, in any other log, nor anything else abnormal.

The only thing I can see in the logs is that:
- a motion detection rule I have in NodeRed stops detecting motion.  It is in my room and during the night detects motion as me and wife turn around the bed.  It is silent after 4:01am.
- At 6:50 another rule I have, this one a JS one in OpenHAB, tried to update a String Item (vTimeOfDay pattern) and fails.  Every minute after that it fails.  I run this rule once a minute.

**Comment by DaveJarvis** [comment]
@flpaoli -- What version of Java, what Java vendor, what Java runtime (JDK/JRE), and what CPU architecture (arm64, amd64, armhf, etc.)?

**Comment by flpaoli** [comment]
> @flpaoli -- What version of Java, what Java vendor, what Java runtime (JDK/JRE), and what CPU architecture (arm64, amd64, armhf, etc.)?

$ java --version
openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK Client VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)`

and

Release = Raspbian GNU/Linux 10 (buster)
Kernel = Linux 5.10.103-v7l+
Platform = Raspberry Pi 4 Model B Rev 1.4

**Comment by wborn** [comment]
It could be a JVM bug so if you still have this issue try upgrading to a more recent Java 11 or 17 version.
This issue is similar to https://github.com/adoptium/adoptium-support/issues/544.

**Comment by wborn** [comment]
According to https://github.com/hypfvieh/dbus-java/issues/172#issuecomment-1182303060 this bug likely is Zulu JVM specific. So try using the OpenJDK 11 package that comes with your distro or [Eclipse Temurin](https://adoptium.net/temurin/releases?version=11).

**Comment by DaveJarvis** [comment]
@wborn We may have witness this bug again with JDK 17, FWIW.
