### ISSUE TITLE
package=minimal/standard in addons.cfg is not in documentation anymore

### ISSUE THREAD

**Issue by batje** [openhab/openhab-distro#1305]
The link to https://www.openhab.org/docs/configuration/packages.html is dead and when searching the documentation the packages= option is not mentioned in the documentation anymore. Is this still supported?

https://github.com/openhab/openhab-distro/blob/9461f1d17682938dc7083c081c84516ca37e03af/distributions/openhab/src/main/resources/conf/services/addons.cfg#L10

**Comment by wborn** [comment]
Besides the 'standard' package, you can still use the 'minimal' package if you don't want openHAB to automatically install the [standard add-ons](https://github.com/openhab/openhab-distro/blob/9461f1d17682938dc7083c081c84516ca37e03af/features/distro/src/main/feature/feature.xml#L10-L17) if you don't use them:

* Basic UI
* HABPanel
* RRD4J

I use it for testing where I usually don't want any of these add-ons to be installed. 

But it is better to remove this dead link and get rid of the whole package concept one day and have the initial setup wizard select these add-ons as sensible defaults for new users. It would then also allow more experienced users to deselect them.
