### ISSUE TITLE
upgrading from 3.1.0 M4 to openhab 3.1.0 stable release breaks homematic binding

### ISSUE THREAD

**Issue by clh27** [openhab/openhab-distro#1308]
I'm using openhabian on Raspberry Pi 3B+
homematic binding worked perfectly under 3.1.0 M4 with homegear 0.8
 upgrading to openhab 3.1.0 release breaks hommatic binding,
3.1.0 release binding homematic does not connect to homegear 0.8.

homegear cannot connect to port 9126 on OH 3

**Comment by kaikreuzer** [comment]
Please check https://github.com/openhab/openhab-addons/issues for related bug reports and if none is found, create an issue there with all required details like log files etc. Thanks!
