### ISSUE TITLE
OPENHAB 2 put all user specific data under one folder

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab-distro#131]
To ease the user backup and also installation of a new OH build, it would be great if all user generated content would be under one folder. Since most of the user generated content is already under "config" it makes sense to us this folder also for

1. the credentials of the myopenhab binding, namely uidd and secret. Preferrable this should be in a consistent format like the other services, namely a myopenhab.cfg.
2. the logs folder, especially the logs that are created by the logging persistence service
3. the data bases created by other persistence services e.g. rdd4j.
4. the sound directory with user generated sounds

**Comment by kaikreuzer** [comment]
It is split into two folders: conf and userdata, see https://github.com/openhab/openhab-distro/blob/master/docs/sources/getting-started.md#installation.
Please also have a look at this discussion: https://community.openhab.org/t/recommended-way-to-backup-restore-oh2-configurations-and-things/7193

**Comment by Marty56** [comment]
Thanks for the links!!
Interesting discussions. There is still a lot of work to do.
