### ISSUE TITLE
Migration guide from v 2.x.x to 3.x.x Breaking changes link is broken

### ISSUE THREAD

**Issue by dgrechka** [openhab/openhab-distro#1339]
Official docs https://www.openhab.org/docs/configuration/migration/ guides the user to the wiki page "Breaking Changes in openHAB 3" (https://github.com/openhab/openhab-distro/wiki/Breaking-Changes-in-openHAB-3), which in turn
guides the user to another document (https://github.com/openhab/openhab-distro/releases/tag/3.0.0#breaking-changes-that-require-manual-interaction-after-the-upgrade).

It has a quick link "Breaking Changes" which refers the document that does not exist: https://github.com/openhab/openhab-distro/blob/3.0.0/breaking-changes-that-require-manual-interaction-after-the-upgrade.

As a result there is no way to see the breaking changes when migrating from v2.x.x to v3.x.x

**Comment by wborn** [comment]
There's an [older revision of that wiki](https://github.com/openhab/openhab-distro/wiki/Breaking-Changes-in-openHAB-3/139901f0ef7ee8b5b7dd480204ddf5069f030f50) that still shows them.
Maybe @kaikreuzer forgot to add these changes back after regenerating the release notes?

**Comment by wborn** [comment]
Better late than never, this is fixed now. :slightly_smiling_face:
