### ISSUE TITLE
log4j2 security leak

### ISSUE THREAD

**Issue by JoergLaub** [openhab/openhab-distro#1346]
Is it possible to change the vulnerable /usr/share/openhab/runtime/system/org/ops4j/pax/logging/pax-logging-log4j2/2.0.9/pax-logging-log4j2-2.0.9.jar against a secure version?

**Comment by kaikreuzer** [comment]
Please see https://community.openhab.org/t/openhab-and-the-log4j-security-vulnerability/129901.
