### ISSUE TITLE
Update Docker 3.1.0 to 3.1.1 Startup Warning

### ISSUE THREAD

**Issue by klementuel** [openhab/openhab-distro#1348]
Hello,
I just wanted to set the Docker container from 3.1.0 to 3.1.1.
Unfortunately here comes a warning during the startup process 
```
openhab    | Launching the openHAB runtime...
openhab    | OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
```

Unfortunately the warning also doesn't load the WebUI, so I went back to 3.1.0 and did the bug fix with the variable `EXTRA_JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true"` and check it with
```
openhab> system:property log4j2.formatMsgNoLookups                                                                                                   
true
```
Does anyone else have this problem or know what it is?

**Comment by wborn** [comment]
This is an issue caused by outdated libraries on your Docker host, see this [community thread](https://community.openhab.org/t/docker-openhab-3-2-0-snapshot-stuck-at-unhealthy-with-openjdk-client-vm-warning-no-monotonic-clock-was-available/128865?u=wborn).

**Comment by klementuel** [comment]
ok thanks i fix it on RP4

```
#Add dep Key
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
#Add dep 
sudo echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
#Update and Install
sudo apt update
sudo apt install libseccomp2 -t buster-backports
```

Thats works for me

**Comment by wborn** [comment]
Great! That should also prevent similar issues with other applications in containers when those also use a recent distro version like Debian 11.
