### ISSUE TITLE
NodeRed-OpenHab connection and ThingStorageEntity 3.3.0~M7-1

### ISSUE THREAD

**Issue by blue-danube-vienna** [openhab/openhab-distro#1403]
Since 3.3.0~M7-1 the NodeRed-OpenHab connection via [node-red-contrib-openhab3] and [node-red-contrib-openhab2] doesn't work anymore.

Downgrade to 3.2.0 solves that. 
BUT: the Enhancement "ThingStorageEntity" instead of ThingImpl/BridgeImpl generate many log entries:

2022-06-26 22:02:00.870 [ERROR] [re.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.openhab.core.storage.json.internal.StorageEntry@17b5824'. Root cause is: org.openhab.core.thing.internal.ThingStorageEntity cannot be found by org.openhab.core.thing_3.2.0

best regards

**Comment by J-N-K** [comment]
I can’t comment on nodered, but downgrading to 3.2 is not supported and the message you see is because of that. The thing storage changed and 3.2 can‘t read a 3.3 thing database.

**Comment by blue-danube-vienna** [comment]
"_..but downgrading to 3.2 is not supported.._"  - it's a pity when you can't take a step back when a version doesn't work

my solution was an openhab-cli restore from the last backup and install 3.2 again.
