### ISSUE TITLE
Unable to find openHAB in TargetOlatFormin 

### ISSUE THREAD

**Issue by sachinacharya** [openhab/openhab-distro#141]
windows->prferences->Plugin_development->TargetOlatForm
I am getting 100errors.P
![screenshot from 2016-02-24 17 23 13](https://cloud.githubusercontent.com/assets/16730096/13284603/6c0b9ca4-db1b-11e5-9aa3-f4704ce385a1.png)
![screenshot from 2016-02-24 17 23 28](https://cloud.githubusercontent.com/assets/16730096/13284617/7d67bfbe-db1b-11e5-8cdf-27fad8da8182.png)
Please help me

**Comment by kaikreuzer** [comment]
this does not look as if the official IDE setup had been used - please try to follow this description step by step: https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/ide.md
