### ISSUE TITLE
create docker container for the openHAB distro

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#144]
There are several docker containers for openHAB 1 and openHAB 2 (pre-Karaf) like:
https://github.com/tdeckers/docker-openhab (@tdeckers)
https://github.com/WetwareLabs/docker-openhab2 (@WetwareLabs)
https://hub.docker.com/r/armv7/armhf-openhab2/ (@umiddelb)
https://hub.docker.com/r/christianwaite/openhab2/ (@christianwaite)
etc.

I think it would make a lot of sense to join forces and to maintain an official docker container in a repository at openHAB. I am myself by no means a Docker expert and also don't feel finding the time to deal with it myself. It would therefore be gorgeous, if somebody from the community would be willing to take the lead here (or at least coordinating the creation together with the others). Please speak up, if you are volunteering!

**Comment by christianwaite** [comment]
The wetwarelabs docker looks excellent! I'd say it would benefit from exposing the config, addon and userdata folders to the user. It doesn't look like it does at the minute.

I'm going to test it out and see how it is and get back to you. Is it pre karaf? Looks like its latest snapshot or alpha2 so shouldn't be.

**Comment by kaikreuzer** [comment]
Yes, it is pre-karaf, so it will need some adaption.
@WetwareLabs Are you ok with taking your work as a initial base? Would you share it under the EPL? If you have the time, maybe you could create an initial PR against https://github.com/openhab/openhab-docker, which I have just created for this purpose?

@cyberkov suggested to automate the build and publishing to Dockerhub on Cloudbees through https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Build+and+Publish+plugin. I think this would be brilliant!

**Comment by cniweb** [comment]
We have now an official Docker Image:
https://hub.docker.com/r/openhab/openhab

The official GitHub project:
https://github.com/openhab/openhab-docker

**Comment by christianwaite** [comment]
Wicked, well done everyone!
So I tried installing this through UnRaid and can't get it running. Any ideas?

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="OpenHab" --net="host" --privileged="true" -e TZ="Europe/London" -e HOST_OS="unRAID" -v "/etc/timezone":"/etc/timezone":ro -v "/mnt/cache/appdata/openhab/userdata":"/opt/openhab/userdata":rw -v "/mnt/cache/appdata/openhab/conf":"/opt/openhab/conf":rw openhab/openhab:amd64-online
Unable to find image 'openhab/openhab:amd64-online' locally
amd64-online: Pulling from openhab/openhab
37217193cce9: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a2c9860c1f7a: Pulling fs layer
afae402ea086: Pulling fs layer
f7c64e3a1f88: Pulling fs layer
80bd73fb43ca: Pulling fs layer
d4080f02082e: Pulling fs layer
93cd6b5c38ca: Pulling fs layer
dabf8bf97a2c: Pulling fs layer
c18497e7c214: Pulling fs layer
0b89d3963be2: Pulling fs layer
d4080f02082e: Waiting
93cd6b5c38ca: Waiting
dabf8bf97a2c: Waiting
c18497e7c214: Waiting
0b89d3963be2: Waiting
afae402ea086: Waiting
f7c64e3a1f88: Waiting
80bd73fb43ca: Waiting
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a2c9860c1f7a: Download complete
afae402ea086: Verifying Checksum
afae402ea086: Download complete
80bd73fb43ca: Verifying Checksum
80bd73fb43ca: Download complete
37217193cce9: Verifying Checksum
37217193cce9: Download complete
93cd6b5c38ca: Verifying Checksum
93cd6b5c38ca: Download complete
dabf8bf97a2c: Verifying Checksum
dabf8bf97a2c: Download complete
c18497e7c214: Verifying Checksum
c18497e7c214: Download complete
37217193cce9: Pull complete
37217193cce9: Pull complete
a3ed95caeb02: Pull complete
a3ed95caeb02: Pull complete
a2c9860c1f7a: Pull complete
a2c9860c1f7a: Pull complete
afae402ea086: Pull complete
afae402ea086: Pull complete
d4080f02082e: Verifying Checksum
d4080f02082e: Download complete
0b89d3963be2: Verifying Checksum
0b89d3963be2: Download complete
f7c64e3a1f88: Verifying Checksum
f7c64e3a1f88: Download complete
f7c64e3a1f88: Pull complete
f7c64e3a1f88: Pull complete
80bd73fb43ca: Pull complete
80bd73fb43ca: Pull complete
d4080f02082e: Pull complete
d4080f02082e: Pull complete
93cd6b5c38ca: Pull complete
93cd6b5c38ca: Pull complete
dabf8bf97a2c: Pull complete
dabf8bf97a2c: Pull complete
c18497e7c214: Pull complete
c18497e7c214: Pull complete
0b89d3963be2: Pull complete
0b89d3963be2: Pull complete
Digest: sha256:1a6657dd5f76c7a978948cbfb8a8ee795f78a7c539cc5fe829cc02ea447be32d
Status: Downloaded newer image for openhab/openhab:amd64-online
a84fb92304a5ba27f19c3e10ae5ab42a40ca101aecf6f547f662981842380427
docker: Error response from daemon: Cannot start container a84fb92304a5ba27f19c3e10ae5ab42a40ca101aecf6f547f662981842380427: [9] System error: not a directory.
```

**Comment by cyberkov** [comment]
Hello @christianwaite !

I am not 100% sure that this will solve the problem, but the first thing i noticed is that you are using ``/opt/openhab/`` as the basedir. It should be ``/openhab``.

Cheers
Hannes
