### ISSUE TITLE
OH 3.4 RC1: Some .kar files are not installed yet. Delaying add-on installation by 15s.

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#1440]
When I start OH 3.4 RC1, I have this message repeated even after 10 minutes running: Some .kar files are not installed yet. Delaying add-on installation by 15s.
If I restart the OH server, this message occurs few times but then after 4 minutes, things start to be started.
This looks like the come back of an old bug (OH not working at the first start) that was fixed in the past.

**Comment by lolodomo** [comment]
I forgot to mention it is when using a local kar file.

**Comment by lolodomo** [comment]
I believe I got the same problem with a very recent snapshot but stupidity did ignore it rather than opening an issue!

**Comment by J-N-K** [comment]
I don‘t know of any recent change that could cause this. Is there a simple way to reproduce it? Is it happening on a fresh install, too?

**Comment by lolodomo** [comment]
Yes, I always start from a fresh install (unzipping the zip file, putting the kar file in addons and restoring my specific config files) .

**Comment by lolodomo** [comment]
Should I have wait more than 10 minutes? In the past, I have to wait only few minutes.

**Comment by lolodomo** [comment]
I tried again the installation and that time I did not encounter this problem. So the issue is not systematic.

**Comment by mstormi** [comment]
Well I have been seeing this in a long time and I don't believe it's because of some recent change.
It doesn't happen always. I believe it once was persistent until I restarted OH but I've also seen occurrences where it went away
It's obviously much more likely to happen on a slow box like a RPi but most (all?) core developers use fast machines and don't get to see it. I don't know how to systematically approach debugging that, though.

**Comment by apella12** [comment]
I occasionally see this message on my pi3 after an upgrade. What I have wondered is whether it is best, as the number bundles approach 400, to continue to use an all-inclusive .kar. My pi3 uses 4 bundles (9 on my pi4) and most of the time of an upgrade is getting the kar downloaded and working (Pi3 also on wifi). Would it be possible to only download the bundles in use from the installed list?  Better yet, like the apt update command, if the bundle has not changed just use the one already installed. If I need a new application (binding) I get it from the store (UI Binding page) and it would be added to my installed list. My two cents (and I have no idea what this entails). However, I do see this problem likely to grow as the bundles increase in both size and number.

**Comment by lolodomo** [comment]
Did not see that recently.
