### ISSUE TITLE
Deny connections over ssh from interfaces different than local

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-distro#145]
To avoid security flaws the best will be to not listen for ssh connections coming from external interfaces.

**Comment by dvanherbergen** [comment]
If you limit it to localhost, what is the point of keeping ssh?

**Comment by splatch** [comment]
@dvanherbergen You can ssh into console when you run openhab as a service.

**Comment by kaikreuzer** [comment]
But you can also use bin/client to do the very same, can't you?

**Comment by splatch** [comment]
@kaikreuzer bin/client uses ssh connection to do that. It's just java way of making `ssh -p 8101 karaf@localhost`.

**Comment by dvanherbergen** [comment]
So the default access would then be ssh into machine, then ssh into karaf using the bin/client...

**Comment by splatch** [comment]
Correct.

**Comment by dvanherbergen** [comment]
OK, works for me...

**Comment by kaikreuzer** [comment]
Can we somehow manage to have the default user being openhab/openhab instead of karaf/karaf...?

**Comment by splatch** [comment]
Sure, we can ship our own `user.properties` which replaces karaf user with openhab.

**Comment by kaikreuzer** [comment]
May I ask you to do so and maybe also add a small paragraph about local access to https://github.com/openhab/openhab-distro/blob/master/docs/sources/getting-started.md#registering-openhab-as-a-system-service-in-the-os?

**Comment by splatch** [comment]
Sure, I will extend this PR to include more datails. Just to be clear I would like to get statement if limiting ssh connections to 127.0.0.1 and documenting how to extend it is fine.

**Comment by kaikreuzer** [comment]
> I would like to get statement if limiting ssh connections to 127.0.0.1 and documenting how to extend it is fine.

Yes, and mentioning the local access (and its credentials) option as well, if being started as a service.
What I wonder: How shall we tell people to change their password? The "runtime/karaf" folder is not supposed to be edited by users as it is overwritten by updates. How else could people change the password easily?

**Comment by splatch** [comment]
We could use other file and other jaas realm than default (`karaf`), however this would require extra configuration/bundle to be installed. Easiest way to enable fresh JAAS realm is just blueprint XML with dedicated namespace, however this is disabled by default in your distro.

For me it would be worth to consider moving `${karaf.home}/etc` higher so it won't be overriden by updates. I know it contains bunch of files which are not interesting for all users, but these may contain user changes which should be kept. It is possible to move some files higher and let felix fileinstall push updates to config admin, but then it requires extra care to avoid duplicated entries.

**Comment by kaikreuzer** [comment]
> For me it would be worth to consider moving ${karaf.home}/etc higher so it won't be overriden by updates.

Yes, in some way we could think about merging it with `conf/services`, which is parsed through an ESH-prorietary mechanism (doing similar things as fileinstall).
If Karaf is configured to write config admin changes back to the files, where does it actually do this? Back to `${karaf.home}/etc`?

**Comment by kaikreuzer** [comment]
I have merged https://github.com/openhab/openhab-distro/pull/146 now, so that we do not have this security hole anymore.
@splatch, It would be great if you could come up with further PRs about changing the user, possibly the config location and a few words for the documentation. Thanks!

**Comment by splatch** [comment]
I've been working on wider solution to secure backend services via jaas as promised in one topic on forum.

Code which allows to introduce that layer is here: https://github.com/Code-House/openhab-cxf. Jaas is next thing I plan to add.

**Comment by kaikreuzer** [comment]
Thanks for the update.
I am not quite sure if we should really completely change all the JAXRS integration layer here, this might have some huge impact.
So far, the discussion was to introduce JAAS on Jetty / OSGi HTTPService level, so that it also covers the other servlets besides Jersey.
Also note that the general role based authentication should rather be solved at ESH in https://github.com/eclipse/smarthome/issues/579.

**Comment by kaikreuzer** [comment]
I think for this issue here, we should merely do https://github.com/openhab/openhab-distro/issues/145#issuecomment-188827135 for it to be closed.

**Comment by splatch** [comment]
I've added in linked repo [36a8c78](https://github.com/Code-House/openhab-cxf/commit/36a8c78f1617543dcb8f11b022d8ec26458db9ba) which introduces support for basic authentication via jaxrs container request filter. It does work with default JAAS realm deployed on Karaf (karaf/karaf). I think the same way - jaxrs container request filter - could be used with jersey to plug in authentication.

Other half of task which is still lef to do requires input from you. I did look how Karaf 4 configures JAAS realms and sadly there is no possibility to override location of `users.properties` file. It is hardcoded. Configuration shipped via Declarative Services will also not work cause structure of objects which needs to be exposed requires more advanced construction (realm contains 0..N login modules which are having text configuration). For that reason I will need to submit Java code which will bring up new JAAS realm for openhab. Where should I put it? After submiting necessary code I can finish this task.

**Comment by splatch** [comment]
@kaikreuzer any thoughts around above topic?

**Comment by kaikreuzer** [comment]
Sorry for the late reply, I was travelling last week.

> I think the same way - jaxrs container request filter - could be used with jersey to plug in authentication.

So this could probably be done using https://github.com/hstaudacher/osgi-jax-rs-connector/wiki/security, right?
The problem I see is that security on Jersey is not enough, because it leaves the other servlets unsecured (the uis, icon servlet, chart servlet, etc.). That's why I mentioned that we will need some solution on HttpService level - or at least provide some secured HttpContext. Probably this can internally access the same JAAS classes as the Jersey filter then.

> For that reason I will need to submit Java code which will bring up new JAAS realm for openhab. Where should I put it?

It depends on what kind of dependencies this code will have. Is the JAAS realm specific to Karaf? If so, the best place is probably [here](https://github.com/kaikreuzer/openhab-core/tree/master/bundles/org.openhab.core.karaf). If there is no dependency to Karaf, but it might be generally useful for doing JAAS integration, then it should best go directly into ESH.

**Comment by splatch** [comment]
It is possible to [control security](https://osgi.org/javadoc/r4v42/org/osgi/service/http/HttpContext.html#handleSecurity(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)) via HttpContext, however the same context instance should be used for registering resource servlets and jaxrs servlet.
What I am afraid is heavy usage of basic/digest authentication which is default in such cases, but far away from being secure. If we will decide to to things in this way should notify users that it should be  always combined with encrypted channel.
For a regular usage in web layer I would recommend single login page with http session to keep authentication on server side and avoid resending credentials with every request.

Approach which is based just on Jersey API is limiting cause we won't be able to easily use these in openhab core if we will enable security there, ie. to limit visibility of things based on authenticated user or device. I would opt for ESH to have such API as part of core services.

**Comment by kaikreuzer** [comment]
> For a regular usage in web layer I would recommend single login page with http session

Yes, this probably makes sense.
Besides looking at web sessions, we should also have OAuth2 in mind - see [this discussion](https://community.openhab.org/t/oauth-binding/3798). Sending an access token instead of a session id with the requests should be fine as well.

> I would opt for ESH to have such API as part of core services.

Agreed, then I would suggest to continue the discussion at https://github.com/eclipse/smarthome/issues/579.

**Comment by kaikreuzer** [comment]
@splatch I don't remember the details here anymore: Was the original issue ever fixed here, so that we can close this issue?

**Comment by splatch** [comment]
Orginal issue was to not leave open socket with default user/password. I still need to add doc section about that. So please leave it open for couple mode days and I will submit PR to docs after which this issue could be closed.

**Comment by kaikreuzer** [comment]
Right, no open socket for remote access, only local one. And credentials were supposed to change from karaf/karaf to openhab/openhab.
Happy to wait for your PR, thanks for the help!
