### ISSUE TITLE
Lots of switches switching on the same time...

### ISSUE THREAD

**Issue by Horschie** [openhab/openhab-distro#1466]
Hello,

I just got two times a non-reproducable error last night. The same thing
happened about 8 weeks ago. 

Nearly every switch on the main page was toggled on and a few in sub-categories

The instance is used with a 4G-chip on a raspberry and I'm the
only one having the passwords. 

Regularly these switches should only be toggled by rule. I should better use contacts instead, 
but for resetting it is much easier, so I don't extra rules. 

By the way, is there an option for logging all logins to openhab with IP and everything else? 

Kind regards 
Christoph

**Comment by Gifford47** [comment]
Hi!
If possible, try to disable the openhabcloud addon and disable the rule for a while and look if the problem persists.
Alternatively, you can configure a vpn and use it to access your server.

**Comment by wborn** [comment]
Please use the [community](https://community.openhab.org/) to troubleshoot issues. If it is clear there is a bug an issue should be created with details about your setup, logging and a reproduction scenario.
