### ISSUE TITLE
Failed to download artifacts (jackson-databind)

### ISSUE THREAD

**Issue by nebulade** [openhab/openhab-distro#1468]
Hi, I was trying to install a new binding today and found that it failed to download a specific jar file from the artifacts repo. After clearing the tmp and cache folder, as well as removing that binding from the addons.cfg and restarting the app, it still fails.

The error in question is:
```
Caused by: java.io.IOException: Error resolving artifact com.fasterxml.jackson.core:jackson-databind:jar:2.12.6.1: [Could not find artifact com.fasterxml.jackson.core:jackson-databind:jar:2.12.6.1 in openhab (https://openhab.jfrog.io/openhab/libs-release/)]
```
looking at the actual repo on jfrog, it seems the jar file in question is version 2.12.2 (so older) https://openhab.jfrog.io/ui/native/libs-release/com/fasterxml/jackson/core/jackson-databind/

This is OpenHAB version 3.4.1 running on Cloudron.

I wonder if I miss some other repo information cache which needs to be updated first so it attempts to download the correct version?

**Comment by wborn** [comment]
It should not download anything but use the pre-installed Jackson 2.12.7 dependencies.
Perhaps some Marketplace add-on messed up your openHAB, see also https://github.com/openhab/openhab-addons/issues/14257.
