### ISSUE TITLE
Warning: Server-mode is not aviable

### ISSUE THREAD

**Issue by maze42** [openhab/openhab-distro#149]
I get below error at startup. Anything I need to worry about or...?
Running on Win 7 and java 1.8.0_71. openHab version 2.0.0.snappshot from last week

![capture](https://cloud.githubusercontent.com/assets/3599961/13360385/558c9e48-dcb9-11e5-85c6-9359dbfe9076.JPG)

**Comment by kaikreuzer** [comment]
This looks as if you are using a JRE and not a JDK - but openHAB currently requires a JDK for execution, see https://github.com/openhab/openhab-distro/issues/56.
