### ISSUE TITLE
Clarify doc in addons.cfg as to when it gets loaded, and that it replaces any UI-based addons

### ISSUE THREAD

**Issue by markfickett** [openhab/openhab-distro#1503]
At the top of `addons.cfg` it says “This is only regarded at the VERY FIRST START of openHAB." (Sorry if that file doesn't live in this repo, I [couldn't find](https://github.com/search?q=org%3Aopenhab+addons.cfg&type=code) where it comes from.)

From that description, I would expect that the first launch of openHAB would read `addons.cfg`, and then any subsequent service restart, even after host restart or cache clear, would not even read the file.

However, my experience is that I installed some addons via UI, and then they got uninstalled again. (I had restarted the openHAB service and also cleared the cache while debugging things). And [on the forums](https://community.openhab.org/t/oh3-transformation-service-config-for-js-and-map-in-a-thing-channel-what-worked-qs-about-what-didnt/145507/3) someone advised me that that's expected / not to mix `addons.cfg` and UI installs.

So, it would be great to clarify the file comment. It's a great place to explain the behavior, I definitely saw the warning and tried to hede it.

**Comment by wborn** [comment]
Yes it would be a good idea to clarify this behavior in `addons.cfg` as well as the openHAB docs because it is a common pitfall.
I've transferred this issue to the distro repo that contains this file.

It would be even better if the UI would disallow add-on installation or show a warning when configuring add-ons using files. But that will involve some more work.

**Comment by jimtng** [comment]
> It would be even better if the UI would disallow add-on installation or show a warning when configuring add-ons using files.

I primarily use addons.cfg but I like installing additional addons using UI for doing quick tests too.

**Comment by lolodomo** [comment]
> I primarily use addons.cfg but I like installing additional addons using UI for doing quick tests too.

Same here. So a warning would be sufficient.
