### ISSUE TITLE
JFrog does not handle pull request builds anymore

### ISSUE THREAD

**Issue by Skinah** [openhab/openhab-distro#1527]
When you create a new pull request in openhab/addons, the PR gives you the following text:
```
Your pull request will automatically be built and available under the following folder:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/
```

Issue is the build in that folder on jfrog is NOT containing your changes in the pull request and is an older SNAPSHOT build. This was working in V3.x but stopped working when the build system changed over to V4.x

I expect the PR changes to be included in that folder the way it used to be.

It was handy to give people in the forum this URL and ask them to test it instead of giving a JAR shared via a private website or filesharing website.

**Comment by kaikreuzer** [comment]
Do you have an example?
I've e.g. just checked todays PR https://ci.openhab.org/job/PR-openHAB-Addons/15418/. The build info can be found at https://openhab.jfrog.io/ui/builds/PR-openHAB-Addons/15418/1682879320877/published and the artifacts appear at https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.tapocontrol/4.0.0-SNAPSHOT/. This looks all ok to me.

**Comment by wborn** [comment]
> I expect the PR changes to be included in that folder the way it used to be.

Nothing changed, it only works well for new add-ons as Kai commented when this was first [introduced](https://community.openhab.org/t/distributing-bindings-through-the-iot-marketplace/24491):

> Note: The shared Maven repo for PRs obviously has the risk that if somebody else includes changes to a certain binding in his PR that the binary jar is changed accordingly - so it can be tricky to tell, what its origin is. I therefore only recommend using these urls for new bindings that are not yet part of the repo - refactorings of existing bindings are probably better offered elsewhere.

Every time a PR triggers a full build or when there are multiple PRs for the same add-on, the last triggered build overwrites the artifacts.

**Comment by Skinah** [comment]
Thanks I guess it was caused by multiple PR so will close this Issue.
