### ISSUE TITLE
Release build broken due to SAT using Java 17

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#1540]
Our release build is broken since May 17: https://ci.openhab.org/view/Sandbox/job/sandbox-openhab4-release/

It runs the unleash steps with Java 11 and complains that the SAT classes were compiled with Java 17 (which is true since we released SAT 0.14.0).
I'm not sure why SAT classes are loaded here at all, since we use `-skipChecks=true` here.

**Comment by kaikreuzer** [comment]
What I have figured out so far is the fact that the issue comes by loading the SAT extension (not the plugin) in the build.

**Comment by kaikreuzer** [comment]
@pfink & @wborn: Would you have any good idea how we could resolve this issue?

**Comment by wborn** [comment]
Apparently you can't move extensions into a profile (see [Maven Model](https://maven.apache.org/ref/3.9.2/maven-model/maven.html)) or disable them in some other way. So perhaps the easiest way to workaround it is to compile SAT using Java 11 again until https://github.com/openhab/openhab-distro/issues/1475 is resolved.

**Comment by kaikreuzer** [comment]
Hm, I thought that SAT already uses Java 17 features as it has been updated - but it indeed still compiles nicely with Java 11. I have created https://github.com/openhab/static-code-analysis/pull/451 to do this change.
We will have to release a new version 0.15.0 as we are not able to replace the version on Maven Central.
