### ISSUE TITLE
Missing ElectricConductivity in Number:Type

### ISSUE THREAD

**Issue by WhiteSockedDancer** [openhab/openhab-distro#1545]
Version: 4.0.0 M4

My plant sensors give me µS/cm
![image](https://github.com/openhab/openhab-distro/assets/52671054/53053e26-4a68-4f9c-9ada-6d141d1caad4)

Missing in Gui-popup Number:ElectricConducitivity (S/m) for Soil Conductivity:
![image](https://github.com/openhab/openhab-distro/assets/52671054/35701465-f30f-4ed5-846a-4425dad78624)

Should be possible since it is in our list for UoM:
https://next.openhab.org/docs/concepts/units-of-measurement.html#quantitytype
![image](https://github.com/openhab/openhab-distro/assets/52671054/cb061a13-e8d6-40d2-94d4-2331074f8b22)

**Comment by J-N-K** [comment]
This is an UI bug. Core added support for getting all available dimensions in https://github.com/openhab/openhab-core/pull/3611, but it seems that MainUI currently is not using that.

**Comment by florian-h05** [comment]
Closing as we have https://github.com/openhab/openhab-webui/issues/1926.
