### ISSUE TITLE
karaf console bundle:list error

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-distro#1549]
I upgraded my OH3 install to OH4, recent snapshot. I am getting the following error when executing the `bundle:list` command in the console:

```
START LEVEL 100 , List Threshold: 50
Error executing command: java.lang.NoSuchMethodError: 'java.lang.Object org.osgi.framework.ServiceReference.adapt(java.lang.Class)'
```
 No bundles are shown.

This same issue was reported in the [forum ](https://community.openhab.org/t/openhab-4-0-milestone-discussion/145133/449?u=mherwege) by @jlaur  a few months ago.

I am running on an RPi4, using openHabian. All addons are installed through the UI. Here is the list:

```
   automation = jythonscripting,jsscripting,jsscriptingnashorn
   binding = mpd,elroconnects,mail,nikohomecontrol,systeminfo,upnpcontrol,ntp,network,openweathermap,neeo,astro,bluetooth,mqtt,unifi,exec,synopanalyzer
   misc = neeo,openhabcloud
   persistence = rrd4j,mapdb,influxdb
   transformation = jsonpath,regex,map,scale
   ui = basic,habot
```

Any hints on how to diagnose this any further?

**Comment by mherwege** [comment]
Upgraded to snapshot build 3513, still the same problem.

**Comment by J-N-K** [comment]
Please check what is in `runtime/system/org/eclipse/platform/org.eclipse.osgi`

**Comment by mherwege** [comment]
I have 2 subfolders there: 3.12.100 and 3.18.0. Both contain an org.eclipse.osgi jar file for the corresponding version.

**Comment by mherwege** [comment]
@J-N-K any further suggestions? I upgraded to the 4.0 release build and still have the same issue.

**Comment by mherwege** [comment]
I removed the runtime folder and re-installed. The issue is gone. I still don't know what caused it.
