### ISSUE TITLE
GPG key will expire soon

### ISSUE THREAD

**Issue by phosei** [openhab/openhab-distro#1553]
I'm sorry, I'm not sure if this is the correct project for this issue.

The GPG key mentioned [on the download page](https://www.openhab.org/download/) will expire in about a month. It would be great if you could provide a new/extended key before the old one expires (which would break at least `apt update`).

```
$ curl -s https://openhab.jfrog.io/artifactory/api/gpg/key/public | gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2015-07-25 [SC] [expires: 2023-07-24]
      EDB7D0304E2FCAF629DF1163075721F6A224060A
uid           openHAB Bintray Repositories <owner@openhab.org>
sub   rsa4096 2015-07-25 [E] [expires: 2023-07-25]
```

Thank you!

**Comment by florian-h05** [comment]
Ping @BClark09

**Comment by BClark09** [comment]
Thanks @florian-h05, I think it is @kaikreuzer that owns the private key, so he will have to change the expiry date and upload to the server.

@kaikreuzer that is rather an unfortunate date 😅 - if we can update the key and get a few release notes telling people what to do well in advance then that would make things smoother.

**Comment by kaikreuzer** [comment]
@BClark09 That's indeed unfortunate timing. What is even worse is that I have absolutely no clue, where I might have the private key of this...
Does it actually make any difference whether we issue a new key or if we update the expiry date of the existing one?

**Comment by phosei** [comment]
@kaikreuzer 

> Does it actually make any difference whether we issue a new key or if we update the expiry date of the existing one?

I’m not an expert on Debian package management, but the last time I reported something like this, people were leaning towards creating a new key:

https://github.com/jenkins-infra/helpdesk/issues/3457#issuecomment-1485216575

**Comment by kaikreuzer** [comment]
I was able to extend the public key and have uploaded it to https://openhab.jfrog.io/artifactory/api/gpg/key/public:

```
➜  ~ curl -s https://openhab.jfrog.io/artifactory/api/gpg/key/public | gpg
pub   rsa4096 2015-07-25 [SC] [expires: 2030-09-09]
      EDB7D0304E2FCAF629DF1163075721F6A224060A
uid           openHAB Bintray Repositories <owner@openhab.org>
sub   rsa4096 2015-07-25 [E] [expires: 2030-09-09]
````

**Comment by phosei** [comment]
Great, thank you!

**Comment by BClark09** [comment]
@openhab/openhabian-maintainers, I'm trying to work out the best way of asking openHABian users to update the public key. I thought it may be use Menu option 40, but this keeps trying to install openHAB 2.5.12? Admittedly, I've just cloned the repository and used the menu item but is this behaviour expected? What way would you recommend your users update the repo?

**Comment by mstormi** [comment]
openhabian users aren't supposed to update repo settings.
I'd do it for them (rather than ask) on start of the openhabian-config tool, similar to how it updates itself every time.

**Comment by BClark09** [comment]
> openhabian users aren't supposed to update repo settings. I'd do it for them (rather than ask) on start of the openhabian-config tool, similar to how it updates itself every time. There's a routine `openhabian_update_check()` in `functions/openhabian.bash` being called from the main script you can put this into.

Thanks @mstormi, I am a little unsure how I can add it without constantly redownloading the public key - perhaps there is no harm in this but I wanted to think about it more. Would there be any issue in adding 
```
wget -qO- https://openhab.jfrog.io/artifactory/api/gpg/key/public | gpg --dearmor | sudo tee /usr/share/keyrings/openhab.gpg >/dev/null
```
to openhabian_update_check()?

I've made a post explaining how anyone can update to the new key.

Perhaps a conversation for another repository, but related to this problem -  I would still be interested in managing the source.list and key from the apt package itself.

**Comment by mstormi** [comment]
> Would there be any issue in adding


I'd prefer if you check for the need to add/replace the key first.
There a add_keys() function in helpers.bash, please use that.

Remember most people are not Linux affine and expect openHABian to handle it for them.

Repo and key management yes we might think about some global maintenance routine to keep all repos+keys up to date or some such, but that's a different story. For now, repos are updated when you call _setup() for some 3rd party SW.
Hard to stay up to date already.
