### ISSUE TITLE
XCharts not rendering time-axis when period=D

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-distro#1556]
Since openHAB 4 M4 XCharts for Basic UI are missing time-axis for period=D. With other intervals like 12h the time-axis is shown correctly.

`Chart item=espaltherma_ext_ambient_temp label="External Ambient" period=D refresh="60000"`
![image](https://github.com/openhab/openhab-distro/assets/34278179/48df9a70-f256-4416-a90b-d6f4f02b46da)

`Chart item=espaltherma_ext_ambient_temp label="External Ambient" period=12h refresh="60000"`
![image](https://github.com/openhab/openhab-distro/assets/34278179/04373d06-1ccf-4c9e-b2d5-63f5586afb53)

**Comment by lolodomo** [comment]
Closed by openhab/openhab-core#3720
