### ISSUE TITLE
mention Java 17 requirement

### ISSUE THREAD

**Issue by Jagohu** [openhab/openhab-distro#1560]
I think it would be helpful to mention that Openhab 4 requires Java 17. It was not apparent and not mentioned in the release notes, it takes some searching to figure it out.

**Comment by wborn** [comment]
Yes that is important. :+1: 

I added it to the :sparkles: "New and Noteworthy" :sparkles: section which still has the reader's attention. :wink: 

Perhaps some additional text should also be added to the openHABian section about upgrading the OS for Java 17 @mstormi?

**Comment by mstormi** [comment]
The 'official' way through openHABian menu will upgrade Java for you, then there's already a "preparation" section and an upgrade-if-on-openHABian section.

But it's a bit difficult because there's a gazillion ways to update Java and the OS and they all come with their own issues.

Wouter could you please prominently update the relnotes that the OS has to be upgraded to Debian 11 (bullseye) BEFORE installing Java and OH4 ? Please also name the official link to the Release Notes we should refer users to in docs, openHABian, forum etc.

**Comment by Jagohu** [comment]
Surely, but for people who don't run openHABian (I personally don't) and only upgrade through ie. apt will need to know. It doesn't hurt to include one more line and it's a major change in my opinion, which needs to be known.

**Comment by wborn** [comment]
I now also added a section about [installing Java 17](https://github.com/openhab/openhab-distro/releases/tag/4.0.0#java-17) and added a couple of lines about openHABian requiring Debian 11.
Let me know if you see more room for improvement!

**Comment by mstormi** [comment]
Mention Debian 10=buster and 11=bullseye people need names to remember better.
If you have a link that describes the dist-upgrade process add it, too (I don't have any good one ATM).

FWIW, if you select menu 03 in latest openHABian and still are on buster or earlier, it'll refuse to perform the upgrade.

**Comment by wborn** [comment]
> Mention Debian 10=buster and 11=bullseye people need names to remember better.

Done!

> If you have a link that describes the dist-upgrade process add it, too (I don't have any good one ATM).

Looks like in place Raspberry Pi OS upgrades are still not supported?

https://www.raspberrypi.com/documentation/computers/os.html#upgrading-from-previous-operating-system-versions
https://forums.raspberrypi.com/viewtopic.php?t=323279


There are some links but one without ads and popups would be nicer:

https://www.tomshardware.com/how-to/upgrade-raspberry-pi-os-to-bullseye-from-buster
https://linuxhint.com/upgrade-raspberry-pi-os-buster-to-bullseye/

> it'll refuse to perform the upgrade

That will prevent some unhappy accidents for sure. :+1:

**Comment by mstormi** [comment]
> Looks like in place Raspberry Pi OS upgrades are still not supported?

Well that's a statement that applies for any other Debian variant, too, all the time, doesn't it ?
It's why I don't attempt that from within openHABian.

Given the RPi platform popularity I think that's a good link to refer to.

**Comment by wborn** [comment]
Isn't there an openHABian announcement/FAQ/community topic where we can link to about Debian 10 being EOL and upgrading or migrating it?

**Comment by mstormi** [comment]
none that I know of

**Comment by wborn** [comment]
Do you have a link?

**Comment by mstormi** [comment]
https://community.openhab.org/t/openhabian-1-8-release/147470/2

**Comment by wborn** [comment]
Perhaps you can also add some info for openHABian users on how to do the upgrade from Debian 10 to Debian 11?
There is no point in linking to this post from the release notes because it does not provide any additional info. :wink:

**Comment by mstormi** [comment]
I've added your Raspi OS link

**Comment by wborn** [comment]
I've added a link to the announcement. That way you can easily provide more info if needed and users will find a way to discuss any problems that way.

I also have a small review comment on your post :slightly_smiling_face: 

```diff
- Debian 11 “buster”
+ Debian 10 “buster”
```

**Comment by mstormi** [comment]
I noticed that on the download page, Zulu is recommended for Java 17 apt .
I'd think that does not apply at least on Raspi OS it does not, can you remove that ? Cannot comment on other OSs
cc @Confectrician
