### ISSUE TITLE
Uninstalling or installing any binding causes all extensions to be updated

### ISSUE THREAD

**Issue by feens** [openhab/openhab-distro#157]
I've noticed that any time I go to re-install a binding in order to update it (via PaperUI), it will automatically update all bindings.  Generally speaking this may be a good thing, but can lead to unwanted issues if one of the other bindings isn't production ready at that point.

**Comment by kaikreuzer** [comment]
Can you prove this through some logging? I would not know how this can happen - an action from the Paper UI should only have an effect on this one binding.

**Comment by feens** [comment]
I'll give this a test again the next time I update my zwave binding again.  I managed to get everything setup and stable, and don't have time to put out fires if something goes wrong when upgrading right now so I've been holding off.

**Comment by feens** [comment]
Finally had some time to update my setup and give this a go again.  Looks to be working fine now.

**Comment by kaikreuzer** [comment]
Great, thanks for the feedback!
