### ISSUE TITLE
Exclude log format settings file from update

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-distro#1573]
I propose to remove `org.apache.karaf.log.cfg` from `userdata_sysfiles.lst`. There is nothing we need to update on a regular basis and it always overwrites custom log format setting on upgrade. @openhab/distro-maintainers WDYT?

**Comment by wborn** [comment]
The only issue I see with that is that users that upgrade from OH2 will not be using log4j2.xml 

To prevent such issues we could also add some notes on what upgrade paths are supported. Ie. to upgrade from OH n to OH n+2 you first need to upgrade to OH n+1.

That can also become complicated after a while. So some software even have upgrade path tools to compute what versions to you need to upgrade through to get to a specific version like GitLab:

https://gitlab-com.gitlab.io/support/toolbox/upgrade-path/

**Comment by wborn** [comment]
I see I mistook this file for org.ops4j.pax.logging.cfg but there was probably also something that needed to be changed in this file between certain OH versions.

**Comment by J-N-K** [comment]
The file was changed once in the last five years (to add colored log-messages). I guess we can do the same thing like #1561 if we really need to change it in the future.

**Comment by wborn** [comment]
Yes that might work as well. We could also add a DEFAULT command for it in the release where it the coloring change was made. That way it still gets updated for users upgrading from those older releases.
