### ISSUE TITLE
postUpdate not working on the demo rules

### ISSUE THREAD

**Issue by danielo515** [openhab/openhab-distro#158]
Hello,
postUpdate function is not working as seems to be expected on demo rules: 
https://github.com/openhab/openhab-distro/blob/master/features/openhab-demo-resources/src/main/resources/rules/demo.rules

When it tries to execute any rule that contains a post update in the form of `postUpdate(item,update)` it fails with an error
`Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,org.openhab.core.types.State) on instance: null
`

Changing that to `item.postUpdate(update)` works perfectly.
Could you please update the examples so noobs like me does not gets confused about it?

This is my java version
```
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) Client VM (build 25.73-b02, mixed mode)
```

Thanks in advance.

**Comment by watou** [comment]
There is a hypothesis in the forums that this issue occurs on Java 1.8 and not on Java 1.7.

**Comment by kaikreuzer** [comment]
OH2 requires Java8 - I have just tested the latest distro (which had some fixes wrt scripts/rules) and the demo rules work perfect as they are; so I would claim the issue is fixed.

If you still see it happening, please feel free to re-open the issue!
