### ISSUE TITLE
Unclear sentence in 4.0.0 release notes

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-distro#1582]
https://github.com/openhab/openhab-distro/releases/tag/4.0.0 contains under “Changes in Units of Measurement (UoM)”

> An item with dimension (`Number:Power`) has a unit (e.g. `kW` that is used within openHAB that is independent from the unit that is used for displaying.

There is no closing bracket.  Due the use of “that“ three times it is unclear to what it refers.  Please reword this sentence to make it easier to understand, e.g. by splitting it in two sentences.

Is the above sentence only in Github release notes, or also in some repository?  I could not find it in the repositories.

**Comment by kaikreuzer** [comment]
Thanks, I have updated the sentence and added the missing bracket.
No, the release notes are not available in any git repo.

**Comment by dilyanpalauzov** [comment]
Now it contains

> This unit is independent from the unit Which is used for displaying.

The Which shall not be capital.

**Comment by kaikreuzer** [comment]
Fixed.
