### ISSUE TITLE
Circular reference when exporting deployable fragments

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#160]
A cycle was detected when generating the classpath org.openhab.binding.knx_2.0.0.201603201226, org.eclipse.smarthome.config.core_0.8.0.201603201226, org.eclipse.smarthome.core_0.8.0.201603201226, org.eclipse.smarthome.test_0.8.0.201603141848, org.eclipse.smarthome.config.xml_0.8.0.201603201226, org.eclipse.smarthome.config.core_0.8.0.201603201226.

Happens with any binding. Also happens with a clean install of the IDE using the latest TP etc.

**Comment by maggu2810** [comment]
This remember me about a already reported bug entry long time ago.
Could why try to close the test bundle(s)?

**Comment by maggu2810** [comment]
I see you already reported it here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479269

**Comment by kgoderis** [comment]
I was not sure it was the same thing

**Comment by maggu2810** [comment]
Hm, if you try to close the project "org.eclipse.smarthome.test" and the error is gone, I assume it is the same.

**Comment by kgoderis** [comment]
Well, that was not sufficient. I had to file search for that project, and close all other test projects referring to that project

**Comment by maggu2810** [comment]
Perhaps we should add a dynamic working set for the tests, too.
This way it would be easy to close and open all test projects.
As long as projects could be part of multiple working sets, I do not see
any disadvantage.
WDYT?

2016-03-20 16:20 GMT+01:00 Karel Goderis <notifications@github.com>:

**Comment by kgoderis** [comment]
Maybe that is the best way forward indeed

**Comment by maggu2810** [comment]
Yes, it seems so. But it is up to @kaikreuzer if he would like to support it in the openHAB Eclipse IDE.
For the ESH one I will have a look at.

**Comment by kaikreuzer** [comment]
Never tried the dynamic working sets. I guess in the OH IDE, the problem also only exists, if people have the ESH repo checked out as well (which should hopefully be a minority).
But I'll have a look at what @maggu2810 does for the ESH IDE and then we can decide :-)

**Comment by maggu2810** [comment]
> Never tried the dynamic working sets.

You are using dynamic working sets in your setup file. :wink: 
Have a look at the preferences: Oomph, Dynamic Working Sets
There you will find the ones you defined in the setup file.
As we are using wildcards, etc. we should also be possible to state we want all projects that ends with test.

**Comment by kaikreuzer** [comment]
Ok, so Oomphs is using dynamic working sets and I am using Oomph ;-)

**Comment by kgoderis** [comment]
Anyway, since the test projects get imported every time you start up the IDE I am very much in favour of a one-button-click solution here ;-)

**Comment by maggu2810** [comment]
@kgoderis You can test the modified ESH setup if you like or wait if it gets merged (and the setup issue of ESH is solved)
