### ISSUE TITLE
4.0.3->4.0.4: No ProfileFactory found which supports profile 'transform:JS'

### ISSUE THREAD

**Issue by helipus** [openhab/openhab-distro#1603]
Hi there,
I just did an update from openhab 4.0.3 to 4.0.4 and have a new warning in the log which wasn't there before.
I run openhab in a Docker container on my Synology NAS DS716+.

The errors look like this: (1 example)
`[WARN ] [.thing.internal.CommunicationManager] - No ProfileFactory found which supports profile 'transform:JS' for link 'MS_Badezimmer_IstTemperatur -> deconz:temperaturesensor:bridge:a4c138f601177cc0010402:temperature'`

The corresponding item configuration is this:
`Number:Temperature      MS_Badezimmer_IstTemperatur              "Ist-Temperatur MS Badezimmer [%.1f °C]"                             <temperature>  (TemperaturenIstMin,TemperaturenIstMax,TemperaturIst_Badezimmer,MS_Badezimmer)             ["Point"]   {channel="deconz:temperaturesensor:bridge:a4c138f601177cc0010402:temperature"[profile="transform:JS", toItemScript="2fixed.js?digits=1"]}`

Why I'm doing this? I have rules that are called when the item changes and the sensor is much to detailed. So I round the value to one decimal place so the rule is not called so often. 

The 2fixed.js script is here: `conf\transform\2fixed.js` and looks like:
```
(function (data) {
    if (Number.isInteger(digits)) {
        return parseFloat(data).toFixed(digits)
    }
    else {
        return parseFloat(data).toFixed(1)
    }
})(input)
```

Background:
I realized the script with help from the community in this post:
https://community.openhab.org/t/javascript-transformation-services-missing-in-openhab-4/146213

Something changed since the update from 4.0.3 to 4.0.4 so I get this warning now for all my items using this transformation service.

**Comment by J-N-K** [comment]
please show `bundle:list -s | grep -I automation`. Are there any other log entries?

**Comment by helipus** [comment]
Hi @J-N-K,
thank you for your time. I did restart now openhab a few times to reproduce the errors from this morning after the update. 
But it is gone. The warning is not shown anymore. It looks like everything is working now.
I really can't understand what did change here. 
Should I close this issue?

**Comment by lolodomo** [comment]
@helipus or @kaikreuzer : yes, please close the issue.
