### ISSUE TITLE
 openHAB 4.0.4: Changing loglevel via Binding Settings empties org.ops4j.pax.logging.cfg

### ISSUE THREAD

**Issue by wzbfyb** [openhab/openhab-distro#1618]
Hi,

I noticed that whenever I change a log-level via binding settings (GUI), org.ops4j.pax.logging.cfg suddenly is empty and logging stops. Populating the file again will resume logging. This does not happen if I set loglevel via console.

## Expected Behavior
If I change the loglevel for a binding via GUI, I expect logging to still work :)

## Current Behavior
Changing Loglevel via GUI, results in an empty org.ops4j.pax.logging.cfg which in turn causes logging to stop.
![grafik](https://github.com/openhab/openhab-distro/assets/57131473/4124c454-6070-40e6-9ffc-0012e70841dc)

## Possible Solution
only change settings via console, or fix UI

## Steps to Reproduce (for Bugs)
1. Go To Settings, Bindigs
2. go to settings of a Binding (tried with zigbee and tradfri)
3. change loglevel there, Save

## Your Environment

* Version used:  openHAB 4.0.4 
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Docker
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian on Intel

**Comment by wborn** [comment]
> Changing Loglevel via GUI, results in an empty org.ops4j.pax.logging.cfg which in turn causes logging to stop.
>
> 1. Go To Settings, Bindigs
> 2. go to settings of a Binding (tried with zigbee and tradfri)
> 3. change loglevel there, Save

I cannot reproduce the issue using these steps.

**Comment by mherwege** [comment]
I was not able to reproduce either.
