### ISSUE TITLE
mdns service for OH2

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-distro#162]
Could anyone test if OH2 registers a mDNS SD Service? I'm using a fresh openhab2 offline distro with the demo package and use ``avahi-browse -a`` to detect services.

There was [bug 58](https://github.com/openhab/openhab.android/issues/58) of openhab.android which was fixed by https://github.com/kaikreuzer/smarthome/commit/02d49eebbbe68a0c5338d7b185637c65414f5c4d and prevented discovery to work. Is there something similar preventing discovery right now?

If mDNS SD has to be enabled or a package needs to be installed, documentation should be added.
I'm also wondering if this is a ESH or OH issue.

**Comment by kaikreuzer** [comment]
> If mDNS SD has to be enabled or a package needs to be installed, documentation should be added.

No, it should be there out of the box. But you are right, this seems to be broken right now - something to investigate!

**Comment by davidgraeff** [comment]
Also works for me, although no IPv6 but this is intended I guess.

**Comment by kaikreuzer** [comment]
Actually, there is an open issue where it is claimed that mDNS ONLY does IPv6, if such a network is available, see https://github.com/eclipse/smarthome/issues/577.
