### ISSUE TITLE
openHAB 2: first install MAP service before bindings ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#163]
At the first startup of an openHAB 2 distribution, the transformation services should probably be installed before the binding, because few bindings require transformations services.
For example, the MiOS binding require the MAP transformation service.
This is either a problem of install order or maybe a dependency not correctly declared for the MiOS binding.

**Comment by maggu2810** [comment]
If the MiOS binding requires the MAP transformation then the feature should depend on the respective feature.
I am never used that binding. But is this really a hard dependency or an optional one? If the binding cannot work without the MAP transformation then feel free to create a PR for the feature file.

**Comment by lolodomo** [comment]
@mrguessed: can you give your opinion ?

**Comment by watou** [comment]
I think you could add
```
<feature>openhab-transformation-map</feature>
```

below [this line](https://github.com/openhab/openhab/blob/master/features/openhab-addons/src/main/feature/feature.xml#L278)?

**Comment by lolodomo** [comment]
Yes, probably.
I propose waiting for @mrguessed feedback.

**Comment by mrguessed** [comment]
Sorry lads, been tied up for a few weeks.  I attempted to add the `REGEX` and `MAP` depends, but it fails feature verification on openhab (v1).

```
[WARNING] Feature resolution failed for [openhab-binding-mios/1.9.0.SNAPSHOT]
Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-transformation-map; type=karaf.feature; version=0
Repositories: {
	mvn:de.maggu2810.shk/shk-feature-base/1.2/xml/features
	mvn:org.apache.karaf.features/framework/4.0.3/xml/features
	mvn:org.apache.karaf.features/standard/4.0.3/xml/features
	mvn:org.eclipse.smarthome/karaf/0.8.0.b2/xml/features
	mvn:org.openhab.addons/openhab-addons/1.9.0-SNAPSHOT/xml/features
	mvn:org.openhab.core/openhab-core/2.0.0.a4/xml/features
	mvn:org.ops4j.pax.web/pax-web-features/4.2.3/xml/features
}
```

In the feature-verification setup, it looks like the `openhab` Bindings can depend upon `openhab-core-addons`, but not on `openhab-esh-addons`... and that's where `openhab-transformation-regex` and `openhab-transformation-map` are currently defined.

Not clear why they're defined there.  I suspect they need to be moved from `openhab-esh-addons` to `openhab-core` if we want to allow OH 1.x Bindings with dependancies on them, or add `openhab-esh-addons` as a feature-verification (which seems wrong)

Unf, my `eclipse/smarthome` repo won't build atm (under Maven 3.0.5) since it's got some other dependency (see below) that needs Maven 3.1.1.  I can't do builds to verify that changes here don't rock the boat elsewhere, so I'll hold my changes for a bit.... which include the PaperUI MiOS settings support .

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (Install node and npm) on project org.eclipse.smarthome.ui.paper: The plugin com.github.eirslett:frontend-maven-plugin:0.0.27 requires Maven version 3.1.0 -> [Help 1]
```

**Comment by kaikreuzer** [comment]
@maggu2810 Does anything speak against making the esh features available to the openhab1 verification, so that this dependency can be declared?

**Comment by maggu2810** [comment]
@kaikreuzer You are wrapping some esh features by using openhab feature names.
I think this mapping should be moved from distro to core. The distribution should collect stuff.
The openhab core features should be used by the addons. The addons should not use anything of the distro.

I think you should move
mvn:org.openhab.distro/openhab-esh-addons/${ohd.version}
to
mvn:org.openhab.core/openhab-esh-addons/${ohc.version}

So, the core (mvn:org.openhab.core/openhab-core/${ohc.version}) could use:
mvn:org.eclipse.smarthome/karaf/${esh.version}
mvn:org.eclipse.smarthome/karaf-tp/${esh.version}

The addons of openHAB 2 (mvn:org.openhab.addons/openhab2-addons/${oh2.version}) and the old / this ones (mvn:org.openhab.addons/openhab-addons/${oh1.version}) could use:
mvn:org.eclipse.smarthome/karaf/${esh.version}
mvn:org.eclipse.smarthome/karaf-tp/${esh.version}
mvn:org.openhab.core/openhab-core/${ohc.version}
mvn:org.openhab.core/openhab-esh-addons/${ohc.version}

And the last, the distribution (mvn:org.openhab.distro/openhab-esh-addons/${ohd.version}) could aggregate all that ones (esh, core, and the distro.demo, ...).


This could result in a well defined build and release order.
1. esh
2. core: needs esh
3. addons oh1 + oh2 (order independent): needs esh + core
4. distro: needs esh + core + addons-oh1 + addons-oh2


WDYT?

**Comment by maggu2810** [comment]
Short answer, I think this could be done, but I assume you would like to use the wrapper features. This should be moved, so the addons does not depend on the distro.

**Comment by kaikreuzer** [comment]
> This could result in a well defined build and release order

Sounds very much right, that's how it should be.

**Comment by kaikreuzer** [comment]
@mrguessed I have created 
https://github.com/kaikreuzer/openhab-core/pull/38 and https://github.com/openhab/openhab/pull/4308 which should now make it possible to define the dependency on openhab-transformation-map in your feature.

**Comment by mrguessed** [comment]
Thanks @kaikreuzer, I manually moded openhab/openhab#4308 to include the repo during the verification phase (comments in that ticket), as it didn't work without this entry.

It went through ok, but not sure if that's what you'd intended...

**Comment by kaikreuzer** [comment]
Thanks for fixing it, you are right, I missed adding the feature to the list the verification runs against.

So let's check the next distro build and please close this issue if it is (hopefully) resolved!

**Comment by mrguessed** [comment]
Thanks for merging @kaikreuzer !

@lolodomo: Once the build is in place, can you double-check for the specific scenario you were previously seeing?

**Comment by lolodomo** [comment]
Thank you. Of course I will test and let you know.

**Comment by lolodomo** [comment]
I close this issue as it seems to be ok with offline distro 271.
@mrguessed @kaikreuzer : I would have appreciated if dependencies installed would have been notified with a message in the logs, like for any usual addon installed at the first startup. That would have helped to confirm that REGEX and MAP are really installed before MiOS binding.

**Comment by kaikreuzer** [comment]
> I would have appreciated if dependencies installed would have been notified with a message in the logs

Would be nice, yes, but this is done under the hood by Karaf, so the only option would be to have general Karaf logging about features being shown, but then you will probably also have a lot duplicate and misleading logging in there...
