### ISSUE TITLE
OH2 Beta 2 - Paper UI - Inbox Issue

### ISSUE THREAD

**Issue by p5ych017** [openhab/openhab-distro#164]
Started the latest snapshot from today with the following issue.
No additional addons loaded.

![bug](https://cloud.githubusercontent.com/assets/15014519/14060585/ad7a4b70-f369-11e5-8ba4-181c6e898bd3.JPG)

Any ideas?

**Comment by kaikreuzer** [comment]
I just tried the current snapshot and all looks good. Have your tried cleaning your browser cache?
