### ISSUE TITLE
Incorrect Countries and Regions

### ISSUE THREAD

**Issue by martinkeat** [openhab/openhab-distro#1657]
Could you kindly correct the countries and regions of the UK in the UI please. .

At the moment you have the "United Kingdom of Great Britain" listed as a country, and Scotland, England, Wales and Northern Ireland listed as regions.

The UK is not a country, it is a political and economic union of constituent countries.

You should have 4 countries listed as England, Scotland, Wales and Northern Ireland and the regions listed within them (which we refer to as burghs or regions.

The proper list of the countries and regions are below.

Cheers

# Scotland
scotland_regions = [
    "Aberdeen City",
    "Aberdeenshire",
    "Angus",
    "Argyll and Bute",
    "Clackmannanshire",
    "Dumfries and Galloway",
    "Dundee City",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Renfrewshire",
    "Edinburgh (City of)",
    "Falkirk",
    "Fife",
    "Glasgow City",
    "Highland",
    "Inverclyde",
    "Midlothian",
    "Moray",
    "Na h-Eileanan Siar",
    "North Ayrshire",
    "North Lanarkshire",
    "Orkney Islands",
    "Perth and Kinross",
    "Renfrewshire",
    "Scottish Borders",
    "Shetland Islands",
    "South Ayrshire",
    "South Lanarkshire",
    "Stirling",
    "West Dunbartonshire",
    "West Lothian"
]

# England
england_regions = [
    "East Midlands",
    "East of England",
    "London",
    "North East",
    "North West",
    "South East",
    "South West",
    "West Midlands",
    "Yorkshire and the Humber"
]

# Wales
wales_regions = [
    "Anglesey",
    "Blaenau Gwent",
    "Bridgend",
    "Caerphilly",
    "Cardiff",
    "Carmarthenshire",
    "Ceredigion",
    "Conwy",
    "Denbighshire",
    "Flintshire",
    "Gwynedd",
    "Merthyr Tydfil",
    "Monmouthshire",
    "Neath Port Talbot",
    "Newport",
    "Pembrokeshire",
    "Powys",
    "Rhondda Cynon Taff",
    "Swansea",
    "Torfaen",
    "Vale of Glamorgan",
    "Wrexham"
]

# Northern Ireland
northern_ireland_regions = [
    "Antrim and Newtownabbey",
    "Ards and North Down",
    "Armagh City, Banbridge and Craigavon",
    "Belfast",
    "Causeway Coast and Glens",
    "Derry and Strabane",
    "Fermanagh and Omagh",
    "Lisburn and Castlereagh",
    "Mid and East Antrim",
    "Mid Ulster",
    "Newry, Mourne and Down"
]

**Comment by kaikreuzer** [comment]
> The UK is not a country

Well, I do not want to start any political discussions, but as long as [the Commonwealth](https://thecommonwealth.org/our-member-countries/united-kingdom) and [Wikipedia](https://en.wikipedia.org/wiki/United_Kingdom) state that UK is a country, I do not see much need to see it differently.

Anyhow, openHAB does not define those things. We are using the standard mechanisms of Java, which uses the definitions of ISO- 3166 underneath afaik - so this is where you would have to address your concerns.
