### ISSUE TITLE
Part of log4j syntax not recognised by Karaf

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#167]
When changing in org.apache.kara.log.cfg the line 'pattern' to 

pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%36.36c:%-5L] - %M:%m%n

this yields

2016-04-08 14:43:38.929 [DEBUG] [e.osgi.LoggingCommandSessionListener:?    ] - ?:Executing command: 'log:tail'

whereas http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html indicates that %M and %L are valid pattern elements.

These elements are very handy to debug stuff
##

**Comment by kaikreuzer** [comment]
Isn't this rather something that should be reported to the Apache Karaf project?

**Comment by kgoderis** [comment]
Most probably, but I am not a Karaf expert, not knowing to what extend Karaf in OH2 is customised or limited or ....

**Comment by splatch** [comment]
I took quick look on this issue and strictly speaking it is not originating from karaf sources but from pax-logging. This library is used for gathering and bridging logging in karaf. It has certain benefits (such multiple logging libraries are forwarded to log4j) and consequences. One of these is fact that location information is not computed by log4j itself but it is calculated when log event occurs.
I didn't do deep dive to find a cause but as a workaround you can use other pattern element - **%l** (small L) which will produce output such this:
```org.apache.karaf.features.internal.service.FeaturesServiceImpl.print(FeaturesServiceImpl.java:1213)```

**Comment by kaikreuzer** [comment]
As we are by now on log4j2, I assume that issue is obsolete.
