### ISSUE TITLE
Warning  displayed when starting runtime on an ARM computer

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#17]
Since G1 is not supported on JDK for ARM, calling start.sh displays
```
Java HotSpot(TM) Client VM warning: G1 GC is disabled in this release.
```
I wonder if we can tweak the start scripts to only add the jvm arg for G1 on non-ARM systems?

**Comment by maggu2810** [comment]
You could use e.g. <code>uname -m</code> and set the options depend on that value.
