### ISSUE TITLE
distro contains some features in older version as well

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#179]
Listing the features of the distro, I see
```
kat-jmdns                                 | 3.4.2            |          | Uninstalled | openhab-aggregate-xml   | An implemenation of multi-cast DNS in Java.
kat-jmdns                                 | 3.5.0            |          | Uninstalled | openhab-aggregate-xml   | An implemenation of multi-cast DNS in Java.
kat-jupnp                                 | 2.1.0            |          | Uninstalled | openhab-aggregate-xml   |  UPnP/DLNA library for Java
kat-jupnp                                 | 2.2.0            |          | Uninstalled | openhab-aggregate-xml   |  UPnP/DLNA library for Java
kat-paho-client-mqttv3                    | 1.0.2            |          | Uninstalled | openhab-aggregate-xml   | MQTT v3 Client
kat-xtext                                 | 2.6.2            |          | Uninstalled | openhab-aggregate-xml   | Xtext - Language Engineering Made Easy
kat-xtext                                 | 2.9.1            |          | Uninstalled | openhab-aggregate-xml   | Xtext - Language Engineering Made Easy
kat-xtext                                 | 2.9.2            |          | Started     | openhab-aggregate-xml   | Xtext - Language Engineering Made Easy
```
We should imho not package the older versions jmdns 3.4.2, jupnp 2.1.0 and xtext 2.6.2+2.9.1 anymore.

**Comment by maggu2810** [comment]
Hi Kai, sorry about that. I was not awared that this does matter. The
feature are contained in a used repo, but they are not installed. They are
just listed (and perhaps packed in the offline distribution).
I created Karaf features for stuff that does not offer them itself and I
(and others) need for different projects (see
https://github.com/maggu2810/kat/tree/master/features)
I think I cannot remove older versions from the repository just because
openHAB doesn't need them. It will break other projects.
Create different feature repos for different versions of a project does not
work because then I have to create a different repo for every apache
commons component.
For jUPnP and JmDNS the best case would be to move the Karaf features to
the upstream project. IMHO this would be also the correct place.
For Xtext I don't think it is an option, the only thing you can do will be
copy and paste the feature definitions.
What do you think, do you see some other options?

**Comment by maggu2810** [comment]
But perhaps we could wait until tomorrow. I will think about using
different repos or drop old versions.
For jUPnP and JmDNS it would be great if we could move them upstream as you
also prefer to do it for ESH features to the ESH repo. Wouldn't it?

**Comment by kaikreuzer** [comment]
Sure, this is nothing urgent, so leave your time. I just noticed that the offline distro has increased by 10MB, so we should clearly not include stuff that we do not need.

> For jUPnP and JmDNS it would be great if we could move them upstream as you
also prefer to do it for ESH features to the ESH repo. Wouldn't it?

Yes, I am all for it!

> For Xtext I don't think it is an option

Why not? Because the artifacts are not directly available and you aggregate them yourself? If it is not possible to define Xtext features in ESH, then yes, we should create a copy of your work in OH2.

**Comment by maggu2810** [comment]
With upstream I mean the jUPnP feature in the jUPnP project and the JmDNS in the JmDNS project.
So with the comment "For Xtext I don't think it is an option" I would like to say that I don't think that the Xtext project will provide a Karaf feature.

**Comment by kaikreuzer** [comment]
What speaks against moving it to ESH, since we also refer to these bundles in the target platform definition (and thus for the Maven build) and they are the versions that ESH is officially tested against?

**Comment by maggu2810** [comment]
What about the different products?

This is related to all external bundles:
If a feature that do you want to move to ESH is using some external bundle (an apache-commons ones or some others) it has to refer a special version of that artifact (but it is also compatible to all the other major versions).
If a product is using a different minor version number in other features it is using, it is up to the product to decide which one it wants to use.

For example the Xtext feature. You should use the correct asm package version that fits to the Karaf runtime (https://github.com/maggu2810/kat/blob/16ee10c6edd967658ca20630bdc348a2453f2144/features/xtext/src/main/feature/feature.xml#L100).
If openHAB is still using K404 and my products are using K410, which compatible feature should be placed in the ESH repo?

**Comment by kaikreuzer** [comment]
> which compatible feature should be placed in the ESH repo?

The very same as we have in the target platform. This is imho more or less the reference set that ESH is tested against (as its being used in the test execution etc.).

If a product wants to use something else, it is free to define its own feature.
But if I get you right, you are telling me that OH2 is not able to use this "reference set", since certain Karaf versions require some other versions (like asm), so this all wouldn't really help me here at all. Which is in itself not really nice, because I would actually like to have OH2 using exactly the same stuff as in the ESH target platform to make sure that there are no unexpected side effects...

**Comment by maggu2810** [comment]
The Karaf runtime (let's talk about normal not minimal) brings a set of bundles it uses (e.g. the version of the OSGi framework, the version of slf4j, and a all the other versions of external bundles).
Now I can define all my own version of that bundles and keep them installed in different versions with could lead to wired runtime behaviour (and more space requirements), or I can use the versions that comes with the runtime environment.
IIRC if you have the same bundles with the different versions installed at one time, it could result that a few bundles are using version x and other ones are using version y. If they share classes this will result in runtime exceptions.
What I have done all the time is to use the bundle versions that are already present.

**Comment by maggu2810** [comment]
So the intention has been that "Karaf Auxilary Tools" support a special Karaf version.
Example:
* the feature name="xtext" version="2.9.2" of "de.maggu2810.kat.features/xtext/1.4.1" fits best to K404 
* the feature name="xtext" version="2.9.2" of "de.maggu2810.kat.features/xtext/x.y.z" fits best to K405 

So external stuff could use the "Karaf Auxilary Tools" to get features that fits to their Karaf version and does not need to do all the work again.

**Comment by maggu2810** [comment]
I will talk with the Karaf guys some time, to see if the feature resolver includes already some logic to solve such stuff.

**Comment by maggu2810** [comment]
I didn't talk ot the Karaf guys yet, but it seems that much stuff could be solved using requirement tags and dependency flags.

**Comment by maggu2810** [comment]
I think I moved some steps forward. But to proceed further testing I need to solve eclipse/smarthome#1394

**Comment by maggu2810** [comment]
Should be solved with the latest PRs.
See eclipse/smarthome#1396 and all the once that are listed there as linked ones.

**Comment by kaikreuzer** [comment]
All perfect now - thanks a lot for all the work!
