### ISSUE TITLE
Offline distro: very slow to start on RPI 2

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#185]
Starting openHAB 2 has became very slow in the recent snapshots, at least using a RPI 2.

I just tried running snapshot 256 (offline distro).

Please find an extract of my logs for a normal startup (not the initial startup).
```
2016-04-23 12:05:13.935 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'astro_sun_38f3d1cf' has been added.
...
2016-04-23 12:05:14.712 [INFO ] [rthome.event.ItemThingLinkAddedEvent] - Link 'rfxcom_temperaturehumidity_fdf71847_62977-rfxcom:temperaturehumidity:fdf71847:62977' has been added.
2016-04-23 12:05:14.716 [INFO ] [rthome.event.ItemThingLinkAddedEvent] - Link 'rfxcom_temperaturehumidity_fdf71847_8196-rfxcom:temperaturehumidity:fdf71847:8196' has been added.
2016-04-23 12:05:53.667 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-04-23 12:05:56.221 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-04-23 12:05:56.477 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'ntp:ntp:local' changed from UNINITIALIZED to INITIALIZING
...
2016-04-23 12:06:06.206 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-04-23 12:06:06.250 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-04-23 12:06:06.599 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'maisonOH2.sitemap'
2016-04-23 12:06:07.877 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
2016-04-23 12:06:08.257 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'maison.items'
...
```
As you can notice, it looks like my conf (mapdb) is read quickly (first second) and then nothing happens during 40 seconds until I got the first log indicating that Paper UI is started. After that, it took around 20 seconds to have everything started and all items set. As a conclusion, the starting process on a RPI 2 took around 1 minute to complete. I previously did not mesure the starting time on RPI 2 because it was fast. I am almost certain it has been seriously increased in recent snapshots.
Why is there these 40 seconds while apparently nothing happens ?

I can tell you that it took 5 minutes at the first startup to install all packages. It was never so slow in the past.

I even noticed that the first access to the WEB page is now very slow (several seconds while the browser is waiting for data). Then WEB access looks normal after that.

**Comment by kaikreuzer** [comment]
I am just trying it on a Pine64 and it also feels a bit sluggish.

@maggu2810 Might we have lost some of the custom improvements that @dvanherbergen did with the Karaf update?

**Comment by lolodomo** [comment]
As I mentioned on the forum, the snapshot downloaded the 26th of March was ok. Unfortunately, I have overwritted the downloaded ZIP file, so I cannot tell you exactly how much time it took at startup with this version.

**Comment by maggu2810** [comment]
> Might we have lost some of the custom improvements that @dvanherbergen did with the Karaf update?

Perhaps, is there a checklist which improvements has been done?
So I can have a look at if something has been get lost?

I have not changed any configuration file of the distro, so that modifications should be still available.
There has been a patched artifact that has been bumped to another patched artifact (jetty pax web stuff). Both versions has been patched by @dvanherbergen so, I think the changes are the same.

We should compare the offline distro for 0b05b620c1ea672e6a0bbfd9a1a974e6bfd45bab with the one for 110076c59be3bf12ba08cfd9d85c5c1b85878b41.
If the perfomance differ, then it should be related to the Karaf version bump or the ESH Karaf TP.

**Comment by maggu2810** [comment]
There is also the Xtext update, that could be related to some performance impacts.

**Comment by lolodomo** [comment]
I tried offline distro 271 and I can confirm that it is now ok again. Thank you.
On a normal startup, I have now everything started around 26 seconds after launching. Paper UI is started after 6 seconds.

Regarding the initial startup (with all bundles installation), that is even better. My last bundle is installed after 3 min 47. But I don't know if it is a reasonable time. My feeling is that it was faster in the past but I am not really sure. During this initial startup, the banner appears very late. I have 2 jars files put in my addons directory and what I can see in the logs is that OH tries to start them many many times with no success (because some packages are not yet installed). They are finally started with success at the end. I am just asking myself if this is not what making the first startup taking so much time and whether it is normal or not to have so frequent tries to start them ?

**Comment by kaikreuzer** [comment]
I can also confirm that there are no performance issues anymore, so I close this issue.


> whether it is normal or not to have so frequent tries to start them ?

@maggu2810 Would it make sense to change https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/etc/org.apache.felix.fileinstall-deploy.cfg#L4 to a higher value, so that bundles from the addons folder are started last?

**Comment by maggu2810** [comment]
I don't know if this will make a difference. Perhaps it is more related to the "time" the bundles in the addons folder are recognized and the OSGi framework tries to wire them. If all is installed I don't think the start-level will make any difference.
