### ISSUE TITLE
Error "Script interpreter couldn't be obtain"

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab-distro#191]
I upgraded to the Off-Line distro build from 23.Apr.2016 (#256 I think / where could I get the build# after instaling?), using that I'm observing errors when a rule is supposed to be running.
Log:[code]15:55:50.795 [ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'CheckAnwesenheit': Script interpreter couldn't be obtain
[/code]
However, the error is NOT coming consistently, in other words, the rule is being performed in some cases.

**Comment by kaikreuzer** [comment]
Is this without touching anything that it once works and then fails? Or is it only changing its behavior e.g. after a restart?

**Comment by JueBag** [comment]
My rule is normally acting of a Switch-Item changed to ON which is set by a Ping-script checking if a phone is on the WLAN. I saw the errors on this one, however I have seen it running.
For checking I changed to rule in order to react on a Switch that is actuate manually. It does work with that. However that was a change to the rule, so I did "touch" the system.
I'll do another check after a restart, maybe it is not running after a restart.

**Comment by JueBag** [comment]
I did a complete system reboot. After that the Switch changed to ON and the error was reported as above.
NextI put a blank line into the rule and saved it again. 
Log [code]18:15:49.707 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'CheckAnkunft.rules'
18:15:49.896 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'CheckAnkunft.rules'
[/code] (Why is that stated 2 times)
After the detecting the switch, the error was reported again, however the rule was performed. ???

**Comment by maggu2810** [comment]
Add reference: https://github.com/eclipse/smarthome/issues/1393#issuecomment-211988941

**Comment by rplakas** [comment]
I am also seeing this with Builds #256, #261 and #262

`[ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'Zone 1 updated': Script interpreter couldn't be obtain`

Rule fires when a DSC Zone is Tripped

`"rule "Zone 1 updated"
when
    Item ZONE1_TRIPPED changed from OFF to ON
then
    sendNotification("email@gmail.com", "1st Floor Door Zone Opened")
    say("First Floor Door Zone Opened")
end`

I have a similar rule when the MYQ Garage is open or closed and get the error there too:

`[ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'Big Garage Closed': Script interpreter couldn't be obtain`

`rule "Big Garage Closed"
when
    Item GarageDoorString changed from Open to Closed
then
    sendNotification("email@gmail.com", "Big Garage Closed")
    say("The Big Garage Door has closed")
end`

**Comment by jongj** [comment]
I also have this error. For me it started round the time the xtext 2.9.2 changes where made. 
What I am seeing is that after startup a rule does not get executed and shows:
```
 Error during the execution of rule 'gordijnen open': Script interpreter couldn't be obtain
```
When I touch the file with this rule, so it get reloaded, it will get executed but still shows the above error message.

**Comment by kgoderis** [comment]
+1 I am also seeing it in large quantities, especially at startup of the runtime

**Comment by kgoderis** [comment]
Any progress on this, as it is a real showstopper for the Karaf distro if Rules do not execute?

**Comment by joepadmiraal** [comment]
I'm also seeing this in the build of 2016-05-13.
Changing the rules file while oopenhab is running fixes it, until openhab is restarted again.

**Comment by kaikreuzer** [comment]
This discussion is continued here: https://github.com/eclipse/smarthome/issues/1393
