### ISSUE TITLE
Pax web thread pool size 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-distro#192]
Over the last few months I have noticed when I had the paperui, habmin and a mobile client all actively hitting OH2 that web request would get "stuck" until one of the clients was closed.  This also manifested when a mobile client would quickly cycle through menus that make many rest requests.  This would make the system seem very unresponsive to the end user.   I was able to fix this by increasing the thread pool size as show here 

https://github.com/digitaldan/openhab-distro/blob/pax-web-thread-increase/distributions/distribution-resources/src/main/resources/etc/org.ops4j.pax.web.cfg#L9

Normally I would not immediately go increasing threads to solve a concurrency issue, but in this case the problem is happening so often with so many different clients (web, android , ios) that I think this is necessary.

**Comment by kaikreuzer** [comment]
That's interesting. I am a bit afraid that this fix rather hides the problem instead of solving it - 20 concurrent requests should usually be totally fine and if this size is exceeded, it sounds as if some requests are blocked and not returning as expected. Did you try to check if you can find anything in this direction?

**Comment by digitaldan** [comment]
Yes, I don't feel great about this "fix" either, especially since jetty usages NIO and I would hope be able to handle many concurrent requests without needing a huge amount of threads.  I have not looked at the REST code yet,  still recovering from the OH1 atmosphere experience ;-)  Not sure what would be holding on to a thread  like this.

**Comment by kaikreuzer** [comment]
> still recovering from the OH1 atmosphere experience

Haha, I think the situation should be MUCH better now :-)

Ok, I am fine to merge this change, but we should keep it in the back of our heads that there might be something wrong.

**Comment by digitaldan** [comment]
Hmm, this might be something https://github.com/eclipse/smarthome/blob/6426cd1bc6d10789893dca123834e9844478e28f/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java#L156

**Comment by kaikreuzer** [comment]
Yeah, the "atmosphere compatibility pack" - so you indeed cannot escape it ;-)
Hm, yes, it is possible that this causes some blocked threads (until the timeout of 30s).
But you should note that neither the Paper UI nor the Basic UI uses this feature - it is only the Classic UI and the native apps. But if this is with what you are testing, it could be the culprit.
