### ISSUE TITLE
Karaf bundle:update : how to use SNAPSHOT builds

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#195]
Is it possible to update bundles in a running Karaf instance using the latest cloudbees snapshot builds?

**Comment by kaikreuzer** [comment]
You can update addons by simply deinstalling and reinstalling them (being in online mode).
For the rest, see https://community.openhab.org/t/whats-your-way-to-update-oh2-with-another-nightly-build/7880.

P.S.: Could we please move such general questions to the forum (https://community.openhab.org/)?

**Comment by kgoderis** [comment]
> P.S.: Could we please move such general questions to the forum (https://community.openhab.org/)?

Yes sure - my fault
