### ISSUE TITLE
Karaf feature:repo-refresh does not remove obsolete features?

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#196]
Just tried the above, and defunct features like openhab-binding-yahooweather (I presume defunctional, as there is now esh-binding-yahooweather) are still present. Is that normal?

**Comment by kaikreuzer** [comment]
openhab-binding-yahooweather is the correct feature, it is actually wrapping esh-binding-yahooweather.
openHAB users should simply ignore everything that is not prefixed with openhab-.
