### ISSUE TITLE
Karaf-based distro : where to copy custom icons?

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#197]
Is there a pre-determined location where one can copy custom icons for the GUI's, e.g. that are not bundled in jar? there is ./runtime/sounds for sounds, but nothing equivalent for icons?

**Comment by kaikreuzer** [comment]
Look right here: https://github.com/openhab/openhab-distro/blob/master/docs/sources/migration.md#general


> - It is possible to provide your own custom icons in the conf/icons/classic folder - no need to overwrite the icons that come with the runtime.
> - For custom dynamic icons depending on an item state, you need in openHAB 2 to define in the conf/icons/classic folder a default icon (without the state part) in addition to the icons for the different states. This default icon was not required in openHAB 1. For example, for a Wifi level that can take a value from 1 to 4, in addition to the files wifi-1.png, wifi-2.png, wifi-3.png and wifi-4.png, you need to provide a file named wifi.png.
> - Note that Basic UI requires icons with SVG format by default; a Basic UI setting is available to choose beween SVG and PNG formats.
