### ISSUE TITLE
OH2 distro and netatmo binding 1.x

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#198]
OH2 distro is now packaged with netatmo binding 2.0.
Apparently it is still possible to install netatmo 1.x binding using "netatmo1" in addons.cfg file.
In this case, netatmo 1.x is installed but you get this error at each OH startup.
```
2016-04-30 14:04:01.246 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-netatmo1': No matching features for openhab-binding-netatmo1/0.0.0
```

**Comment by kaikreuzer** [comment]
You need to add the two lines:
```
remote = true
legacy = true
```
to your addons.cfg, then this error disappears!

**Comment by lolodomo** [comment]
Well, ok, with these additional settings, the error disappeared at startup.

Maybe the error is that these settings are not included in the addons.cfg file included in the distro ?
Or at least the documentation should be updated to explain that these settings have to set manually by the user.

**Comment by kaikreuzer** [comment]
> Or at least the documentation should be updated to explain that these settings have to set manually by the user.

Agree, but I actually still wait for https://community.openhab.org/t/oh-2-documentation/6927 before investing a bit more time in documentation...
