### ISSUE TITLE
No feature for mqttitude binding?

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#201]
I just noticed that no feature is defined for this (1.8.0) binding. Is that the purpose (because it is 1.8.0)?

**Comment by kaikreuzer** [comment]
You might be the first to test it. If it works, please create a PR for such a feature as described in https://github.com/openhab/openhab-distro/blob/master/docs/sources/features/compatibilitylayer.md#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution.
