### ISSUE TITLE
Some Issues with OpenHab Offiline Distro That  Need Some Advices

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-distro#203]
I am quite new to karaf. Do you have the similar  problem? if so, do you mind to share with me your solution?

1. Both my Eclipse IDE (OpenHab only without ESH code) and Distro have totally different behavior. Things work find on Eclipse IDE does not guarantee they will work on distro. Usually, steps I took are as following but their behavior are somehow like totally different:
     a. Increate sequence # on openhab.target --> Perform Setup Tasks. Once completed, clean the newly self-developed addon then run debug locally. Everything works perfectly.
     b. Export the addon to jar file and then move to RPi which runs on latest distro snapshot from https://openhab.ci.cloudbees.com/job/openHAB-Distribution/, and load it up in karaf (copy to addons folder)
     c.  Things that are not working e.g: void ChannelLinked() in the custom addon is not called upon on distro BUT it is working on IDE

2. Due to the fact that both IDE and Distro have different behavior, i tend to move a lot of the jar file after some tuning from IDE machine to distro RPi. What is the proper way of "refreshing" the currently running addon in distro RPi with the new addon? I have been using the following steps, but somehow there is a "cache" effect on karaf. It means no matter how many time i uninstall/install the addon bundle with latest version, though "bundle:list" shows the latest version #, the system is still using the old version. Do you know why? The only way to solve this is to restart karaf with system:shutdown. Here are the steps i always use:
   a. bundle:uninstall <index>
   b. remove the old addon bundle on addon folder and replace with a latest one
   c.  bundle:refresh <new index>

Thanks

**Comment by kaikreuzer** [comment]
I'd hope this has been discussed by now in the community, which is the right place for general discussions & questions: https://community.openhab.org/
