### ISSUE TITLE
 [vent.ItemChannelLinkAddedEvent:43   ] event is not called on distro but working on Eclipse IDE

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-distro#207]
Hi,

I am wondering how to troubleshoot problem like this. My custom binding relies on @Overide public void channelLinked(ChannelUID) to initialize certain instances. ItemChannelLinkAddedEvent (see IDE log below) is logged and hence the channelLinked() is captured in IDE log and hence channelLinked() is called. But, it fails to fire on openhab2 distro latest snapshots. On distro's karaf console, i run smarthome:links which showed the items are linked to required channels but that event is not fired in my custom bundle. I already setup a new IDE environment by running Eclipse Openhab installation (to make sure i get the latest smarthome packages), so as the distro snapshot (create a new directory). Wondering whether this is a bug or some sort on distro snapshot. Thanks

Eclipse IDE Log:
2016-05-11 12:23:24.677 [INFO ] [vent.ItemChannelLinkAddedEvent:43   ] - Link 'test1-talentswitchmqtt:topic:mygateway1:myswitch1:status' has been added.
2016-05-11 12:23:24.681 [INFO ] [vent.ItemChannelLinkAddedEvent:43   ] - Link 'test3-talentswitchmqtt:topic:mygateway1:mydevice1:status' has been added.
2016-05-11 12:23:24.683 [INFO ] [vent.ItemChannelLinkAddedEvent:43   ] - Link 'test_1_error-talentswitchmqtt:topic:mygateway1:mydevice1:last_error' has been added.
2016-05-11 12:23:24.683 [INFO ] [vent.ItemChannelLinkAddedEvent:43   ] - Link 'test11-talentswitchmqtt:topic:mygateway1:myswitch1:status' has been added.
2016-05-11 12:23:24.684 [DEBUG] [.e.s.m.i.i.GenericItemProvider:130  ] - Read items from model 'default.items'
2016-05-11 12:23:24.705 [DEBUG] [o.o.b.t.handler.TopicHandler  :143  ] - Channel talentswitchmqtt:topic:mygateway1:myswitch1:status is linked

Distro Log:

12:17:25.915 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'talentswitchmqtt:broker:mygateway1' changed from OFFLINE to ONLINE
12:17:25.964 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'talentswitchmqtt:topic:mygateway1:myswitch1' changed from INITIALIZING to ONLINE
12:17:25.996 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Bridgehandler has been initialized for Thing talentswitchmqtt:topic:mygateway1:myswitch1
12:17:26.032 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:myswitch1:last_update has not been linked yet
12:17:26.045 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'talentswitchmqtt:topic:mygateway1:mydevice1' changed from INITIALIZING to ONLINE
12:17:26.054 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Bridgehandler has been initialized for Thing talentswitchmqtt:topic:mygateway1:mydevice1
12:17:26.056 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:mydevice1:last_update has not been linked yet
12:17:26.058 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:mydevice1:signal_strength has not been linked yet
12:17:26.073 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:myswitch1:signal_strength has not been linked yet
12:17:26.102 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:myswitch1:signal_quality has not been linked yet
12:17:26.060 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:mydevice1:signal_quality has not been linked yet
12:17:26.105 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:mydevice1:last_error has not been linked yet
12:17:26.138 [INFO ] [alentswitchmqtt.handler.TopicHandler] - Channel talentswitchmqtt:topic:mygateway1:myswitch1:last_error has not been linked yet

**Comment by lsafelix75** [comment]
By the way, i did run remote debug and it is true that channelLinked(ChannelUID) is never called.

**Comment by kaikreuzer** [comment]
I assume your problem is that you simply do not have any items+links in your distro. At least I do not see any of that in the logs.
Regarding "auto-creation" of items and links, there is still some work in progress, see also https://github.com/eclipse/smarthome/issues/1039.
