### ISSUE TITLE
How Install openhab2 on ARM Qnap

### ISSUE THREAD

**Issue by Mikypan81** [openhab/openhab-distro#208]
Hello everyone! I am trying to install on my arm Qnap the version 2.0 of openhab.
All versions 1.x functioned without problems, but with this new version I just can not start to install. 
The configuration folders are all empty, as I understand I do not have to copy files inside, but I have to run "start.sh" and it should auto-fill ??? I've installed on Qnap the qpkg of Openhab 2.0.0.a1 (taken on qnap forum) and JRE_ARM 8.65.0. I have to install anything else? Or you tell me where to copy all configuration files manually ??? Thx

**Comment by kaikreuzer** [comment]
Hi! Please ask such questions in our forum at https://community.openhab.org/ and only enter an issue here, if there is a bug identified somewhere in the distro itself. Thanks!
