### ISSUE TITLE
Latest Distro-Snapshots don't use latest addons

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-distro#210]
As the title says, Offline Snapshot 302 is using Addons Snapshot 587, not latest, which was 6xx.

Is this by intention or a bug ???

**Comment by kaikreuzer** [comment]
Clearly sounds like a bug to me...

**Comment by kaikreuzer** [comment]
Hm, can you tell me where you see a problem?

I just downloaded build 302 (offline), extracted it and checked runtime/karaf/system/org/openhab/binding/org.openhab.binding.astro...jar and in it I found
```
Bundle-Name: Astro Binding
Bundle-Version: 2.0.0.201605170102
```
So this looks pretty recent to me?

**Comment by hmerk** [comment]
I wanted to try the new systeminfo binding but the distro still uses openhab 1.9-snapshot version

**Comment by kaikreuzer** [comment]
Well, I indeed don't see it listed here yet, so this is no wonder: https://github.com/openhab/openhab2-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml

**Comment by kaikreuzer** [comment]
As a first step, I have declared the 1.x version to be legacy: https://github.com/openhab/openhab/pull/4379/files

**Comment by kaikreuzer** [comment]
Second step is to add the 2.0 version: https://github.com/openhab/openhab2-addons/pull/941

Once it all is built, it should be part of the distro. I assume that your issue is therefore obsolete?

**Comment by hmerk** [comment]
Thanks Kai,
I willtest the next snapshot tomorrow then and close this issue for now.
