### ISSUE TITLE
OH2 beta 3 very slow to start on RPI 2

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#217]
We already got this annoying problem in a recent past with snapshots. Unfortunately, it is back again and even worst than ever.
On a RPI 2, when starting OH2 beta 3:
* the banner appears only after around 15 seconds.
* The first entry in log (Started Paper UI at /ui) appears only after around 1 minute and 24 seconds.
* Everything is loaded only after around 2 minutes and 30 seconds.

As a comparison, the same setup on the same RPI 2 running OH 1.8.3 takes less than one minute to start and load everything.

So OH2 beta 3 is 2,5 times slower than OH 1.8.3 to start up.

**Comment by ThomDietrich** [comment]
I can second that observation.
I am however not sure if this is a bug. With a new core and probably new components and processes, it's only logical to see a change startup time, after which openHAB is quick as ever to react on events. My RPi is restarted every other month, so I don't care about 2-3 minutes startup time...

**Comment by lolodomo** [comment]
Things are apparently largely better with tecent snapshots.
I will measure and then close this issue. If startup time is normal.

**Comment by lolodomo** [comment]
I am now using snapshot 480.
Starting time looks correct.
I think this issue was fixed a long time ago. I close the issue.
