### ISSUE TITLE
Missing Bindings

### ISSUE THREAD

**Issue by staehler** [openhab/openhab-distro#219]
Hi, 
what happens with bindings, which are not referenced at https://github.com/openhab/openhab-distro/blob/master/docs/sources/addons.md
Actually I need plex and fritzbox-tr064 bindings, which are not included in the oh2 disto and not mentioned in the above listing, as well.
I think, I can't just copy my 1.8.3-bindings and hope, they are running, correct?

Greetings,
Michael

**Comment by watou** [comment]
You would have a better chance of success if you grabbed the 1.x addons from here:

https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/

If you have success with these 1.x addons under OH2, please update the documentation to add them to the list, and submit PRs like this one:

https://github.com/openhab/openhab/pull/4384

**Comment by staehler** [comment]
@watou Thanks for your quick reply. I will try it in the evening. So hopefully I can add two further addons to the list.

**Comment by kaikreuzer** [comment]
> what happens with bindings, which are not referenced at https://github.com/openhab/openhab-distro/blob/master/docs/sources/addons.md

Note that this documentation has now moved to http://docs.openhab.org/addons/1xaddons.html and is automatically generated from the feature.xml of the openhab repository.

Please also see http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-use-openhab-1x-add-ons-that-are-not-part-of-the-distribution
