### ISSUE TITLE
documentation gone missing

### ISSUE THREAD

**Issue by aschor** [openhab/openhab-distro#221]
Hello, there might be an issue with github's antispam robots (or did the pages get removed ?) : there are documantation pages missing, and the principal ones  : not exhaustive but for examples :

https://github.com/openhab/openhab-distro/blob/master/docs/sources/getting-started.md
https://github.com/openhab/openhab-distro/raw/master/docs/sources/images/dashboard.png
https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/bindings.md

(...etc ?)

**Comment by maggu2810** [comment]
The documentation moved: https://github.com/openhab/openhab-docs/

**Comment by kaikreuzer** [comment]
Please help updating any of the old links (whereever you have found them)!
As the new location is mentioned [right on the top of the repo root](https://github.com/openhab/openhab-distro/blob/master/README.md), I close this issue.

**Comment by aschor** [comment]
hi, found it there : https://github.com/openhab/openhab-distro

**Comment by kaikreuzer** [comment]
Indeed, there were lots of them that I had missed.

Thanks for pointing it out - they should now be fixed!
