### ISSUE TITLE
[Question] Passing multiple arguments to Javascript transformation ?

### ISSUE THREAD

**Issue by mohsh86** [openhab/openhab-distro#222]
I know the example shows 

```
transform("JS", "getValue.js", "foo bar baz")

// Wrap everything in a function
(function(i) {
    var
        array = i.split(" ");
    return array[array.length - 1].length;
})(input)
// input variable contains data passed by openhab
```

I was wondering if it is possible to pass multiple arguments to Javascript ? the reason i need this because when energy meter accumulated value turnover back to 0, a previous monthly reading should be passed to the script in order to get the accurate reading,  for example if the MAX reading is 9999kWh and most recent reading passed that, the correct value should be (9999-previous_reading+current_reading).

Are rules the only way to do this ? in the docs it says its based on xtext but then xtend is mentioned, what the best way to check rules syntax in OH2 environment  ? ESH designer rules and actions doesn't work AFAIK

**Comment by kaikreuzer** [comment]
Please ask those questions in our forum https://community.openhab.org/, which is the much better place for it!

**Comment by mohsh86** [comment]
thanks for letting me know the right place :)
