### ISSUE TITLE
Log settings persistence - org.ops4j.pax.logging.cfg is getting overwriten

### ISSUE THREAD

**Issue by joergkling** [openhab/openhab-distro#225]
The config file for logging is currently stored in `openhab2/runtime/karaf/etc` and a system update (i.e. via apt) is replacing this file with the default version. Consequently any changes done by the user in regards logging (either in the Karaf console or in the file itself) are getting reverted.

Can the update mechanism be changed so that this file is not getting overwritten?
##

**Comment by theoweiss** [comment]
This could be done, but the cleaner approach would be moving the configuration location to /etc/openhab2/whatever. @kaikreuzer @maggu2810 is there any chance to achieve this?

**Comment by kaikreuzer** [comment]
@theoweiss I fully agree, the runtime folder is supposed to be overwritten by updates.
Unfortunately, I don't have any good suggestion right now on how we can easily move this config file.
I think this might apply to other things in karaf/etc as well, so maybe we would have to move this whole folder to conf and reconfigure Karaf to use it from there.

**Comment by kaikreuzer** [comment]
FTR: WIth #318, the file is moved to userdata/etc and thus should not be overwritten by upgrades anymore.
