### ISSUE TITLE
OH2: server certificate key length is only 256

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#228]
The certificate packaged with openHAB2 includes a public key with a size of 256.
As a comparison, openHAB 1.8 includes a public key with a size of 2048.

**Comment by kaikreuzer** [comment]
OH2 does not include any certificate. Instead, a certificate is generated by the bundle https://github.com/kaikreuzer/openhab-core/tree/master/bundles/org.openhab.io.jetty.certificate.
So if there is need to change anything, please report (or better fix) it there, thanks!
