### ISSUE TITLE
Java Version of Oracle Java  SE Development Kit 8u91 not reckognized

### ISSUE THREAD

**Issue by Folcr** [openhab/openhab-distro#229]
Hi,
my setup:
Ubuntu 14.04, manually installed Oracle Java from 
http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-i586.tar.gz
under /opt/Oracla_Java/
added in  /etc/default/openhab2
`OPENHAB_JAVA="/opt/Oracle_Java/bin/java"`
Also rechecked that the start script in /etc/init.d/openhab2 is sourcing this file. It does.
Nevertheless I get as result of
```
$ sudo /etc/init.d/openhab2 status
Java 1.8 or higher is required. Aborting launch.
```

and 
```
$ /opt/Oracle_Java/bin/java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode)
```

Why is that?

**Comment by watou** [comment]
What is the output of the command `java -version`?  Perhaps the old one is earlier in the path?

**Comment by kaikreuzer** [comment]
I'd suspect that $JAVA_HOME is set to an older Java version, is that possible?

Btw, please better discuss problems in our forum at http://community.openhab.org/

**Comment by Folcr** [comment]
Hi,
my standard Java package is OpenJDK 1.7 which is default in Ubuntu 14.04
```
$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Client VM (build 24.95-b01, mixed mode, sharing)

```As I want using openhab2 (testing) I had to install the latest Oracle JDK (>1.8). I have not put the Oracle Java as default because other packages are also running that use Java (OpenJDK 1.7).
So If openhab2 has the possibility to configure a non system-default Java distribution, which is good, why does it not consistently work? It should use the configured Java package from /etc/default/openhab2, not? Do I have to configure it elsewhere? In /etc/init.d/openhab2 the JAVA environment variable is correctly set according to /etc/default. So the problem must be elsewhere...
Thanks. I want to avoid seting Oracle Java as the default in /etc/alternatives.

**Comment by kaikreuzer** [comment]
As mentioned above, I would say all you need to do is to set $JAVA_HOME to your JDK 1.8 before starting openHAB. Check https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/bin/setenv on how the Java version check is implemented - it definitely considers the $JAVA_HOME setting.
