### ISSUE TITLE
IDE and target platform are incompatible, when running jUnit Plug-in Test 

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-distro#230]
I have installed the openHAB IDE using the Oomph installer on several computers. All face the same problem.
When I try to run a jUnit Plug-in Test configuration (e.g. SysteminfoOSGiTest), I receive a following error message:

```
!ENTRY org.eclipse.pde.junit.runtime 4 0 2016-06-13 11:25:24.684
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.pde.junit.runtime [35]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.11.0,4.0.0)"
    at org.eclipse.osgi.container.Module.start(Module.java:434)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

I think the root cause is that Eclipse Mars.2 Release (4.5.2), Build id: 20160218-0600 is using org.eclipse.pde.junit.runtime.3.4.500.v20150423-1241 that requires bundle org.eclipse.core.runtime with version="[3.11.0,4.0.0)". In the target platform we have only version 3.10,

The runtime bundle depends on additional bundle:
- org.eclipse.equinox.common

The temporary solution that I have found is to include manually two bundles to the target platform:
- org.eclipse.equinox.common_3.7.0.v20150402-1709.jar
- org.eclipse.core.runtime_3.11.1.v20150903-1804.jar

It would be good, if these bundles are part of the target platform.
More information can be found here - https://www.eclipse.org/forums/index.php/t/1067942/  and http://stackoverflow.com/questions/37157052/junit-plug-in-test-ignores-target-platform-in-eclipse-neon

**Comment by petarnv** [comment]
I have the same problem when I try to implement tests for bindings in openhab.

**Comment by kaikreuzer** [comment]
ok ok, I am preparing a new deps repo now ;-)

**Comment by kaikreuzer** [comment]
This isn't yet solved, see https://github.com/openhab/openhab-deps-repo/pull/3#issuecomment-252604280.

**Comment by davidgraeff** [comment]
What is the current status of this issue? I ran into this moments ago. What is the current recommended way to develop binding tests?

**Comment by svilenvul** [comment]
@davidgraeff 

I think it is still not solved.
I am using the workaround described in the first post.

**Comment by davidgraeff** [comment]
Because it is not obvious for p2/maven beginners how to archive the workaround in post 1, I'll add this small howto.

For eclipse oxygen it was necessary for me to add the attached jars to the target platform:
* org.eclipse.jdt.core-3.13.0.v20170516-1929.jar
* org.eclipse.equinox.common-3.7.0.v20150402-1709.jar

This is done by navigating to `Window->Preferences: Plugin-in Development->Target Platform`:
1. Select the OH target and click edit
2. Add the directory containing the two extracted jar files.
3. Close eclipse

Now change the `$WS/eclipse/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info` file and replace the old *org.eclipse.jdt.core* line with the new version.

[org.eclipse_equinox_jdt_core.zip](https://github.com/openhab/openhab-distro/files/1161124/org.eclipse_equinox_jdt_core.zip)

**Comment by svilenvul** [comment]
This is really a painful problem, and the workaround is not easy to apply.

@kaikreuzer 

What do you think about `third-party` folder for easy adding plugins to the Target Platform - as in https://github.com/eclipse/smarthome/commit/b24bbb03c1b765aa7797e47f23fb1577116e320f

**Comment by kaikreuzer** [comment]
I have digged deep and tried to find out the differences to the ESH IDE (where unit tests work smoothly).

My finding was in the end that there is no need to upgrade org.eclipse.core.runtime, but that we needed to add org.eclipse.pde.junit.runtime to the target platform (which wasn't there yet).

I am just deploying a new openhab-deps-repo p2 site and will then update the openhab2.target file accordingly, which should hopefully solve this issue!

**Comment by kaikreuzer** [comment]
New target platform is up with https://github.com/openhab/openhab-distro/pull/495!

So please test and I am confident that you will see it working now!

**Comment by davidgraeff** [comment]
@kaikreuzer The original error is gone, but now Eclipse says it can't find "'org.eclipse.jdt.junit4.runtime" when I try to execute test suits. I reloaded the target platform. Do I need to do anything else?

**Comment by kaikreuzer** [comment]
> when I try to execute test suits

What exactly are you executing? I have tested with the "SysteminfoOSGiTest" launch config which is in the repo and it executes nicely.

**Comment by kaikreuzer** [comment]
Small correction: I used the launch config which I have just pushed with https://github.com/openhab/openhab2-addons/pull/2498.

**Comment by davidgraeff** [comment]
@kaikreuzer : It works with the ESH target. My workflow is: Right click in the package explorer on the unit test file and select "Run as" and "JUnit Plugin Test". The last tests I tried were the ones of the Network binding PR. I'll test with some OH core tests later if time permits.

**Comment by kaikreuzer** [comment]
The "Run as" never works - you need to hand-build your launch config, best by copying one of the existing ones.

**Comment by svilenvul** [comment]
Great, everything works good, thanks !
