### ISSUE TITLE
Installation openHAB2 on a Raspberry Pi

### ISSUE THREAD

**Issue by Ion3** [openhab/openhab-distro#231]
Hi,

I think the description [here](http://docs.openhab.org/installation/rasppi.html) is not corresponding with the [Installation on Linux through APT](http://docs.openhab.org/installation/apt.html).

It is written:

> Curiously, everything was installed as owned by “root”. We need to fix that with the following commands.
> 
> `sudo chown -hR openhab:openhab /etc/openhab` 
> `sudo chown -hR openhab:openhab /usr/share/openhab`

Are the folders correct? Shouldn't it be something like:

`sudo chown -hR openhab:openhab /etc/init.d/openhab2`
`sudo chown -hR openhab:openhab /usr/share/openhab2`

And to add a line break would improve the readability tremendously. :)

Thank you,
Timo

**Comment by kaikreuzer** [comment]
I have fixed the line breaks with https://github.com/openhab/openhab-docs/commit/acdf1717b9ff3fb8c5942975e77e18c16daba29d.

@cniweb Can you comment regarding the folders?

**Comment by cniweb** [comment]
Oh, yes. The folders:
`/etc/init.d/openhab2`
`/usr/share/openhab2`
are correct!

**Comment by kaikreuzer** [comment]
ok, fixed with https://github.com/openhab/openhab-docs/commit/58704a93009573f299be1b908bbfbd9b4dbf017b

**Comment by Ion3** [comment]
Still errors: https://github.com/openhab/openhab-docs/commit/acdf1717b9ff3fb8c5942975e77e18c16daba29d

Regard comments in line 46 & 97

Is there a possibility to modify https://github.com/openhab/openhab-docs/blob/gh-pages/installation/rasppi.md directly like in a MediaWiki?

**Comment by kaikreuzer** [comment]
You should see the "pen" symbol for editing the page:

<img width="204" alt="screen shot 2016-06-27 at 16 41 42" src="https://cloud.githubusercontent.com/assets/3244965/16383610/1ad41524-3c86-11e6-8676-da3e7010b04b.png">

**Comment by Ion3** [comment]
For me it is only possible to fork the projekt and "edit the file in [my] fork of this project":

![edit_in_your_fork](https://cloud.githubusercontent.com/assets/6546080/16384964/4a1d665a-3c8b-11e6-83f8-ee7487b1b218.png)

**Comment by kaikreuzer** [comment]
If you do so, it should automatically create a PR with your change - does it?

**Comment by Ion3** [comment]
Yes, it automatically creates a fork:

![fork](https://cloud.githubusercontent.com/assets/6546080/16385651/fc86ba7e-3c8d-11e6-95f7-1c9bf7a5f99b.png)

...but I believe you will not be notified about changes I do there: https://github.com/Ion3/openhab-docs/commit/7c40605be20aa65fe5d782ffc758a85a7df3ab03

**Comment by kaikreuzer** [comment]
No, but I would have hoped that it is a single click somewhere to create a PR from this change in your fork?

**Comment by Ion3** [comment]
I didn't find where to pull the request. I would like to contribute. I did a couple of small things in the openHAB1 Wiki and I will find a way to do so in openHAB2! :-)

**Comment by kaikreuzer** [comment]
I have just changed some settings on github, could you try again?

Editing should actually open an editor with this header:

<img width="996" alt="screen shot 2016-06-28 at 00 16 19" src="https://cloud.githubusercontent.com/assets/3244965/16397573/a21ca69c-3cc5-11e6-8ea4-d3020b4ded2b.png">

And this footer:

<img width="1033" alt="screen shot 2016-06-28 at 00 16 29" src="https://cloud.githubusercontent.com/assets/3244965/16397576/aa2846a2-3cc5-11e6-895c-e7ea2b590140.png">

**Comment by Ion3** [comment]
Dear Kai,

I tried again, this is what I get:

![comparing_changes](https://cloud.githubusercontent.com/assets/6546080/16406236/52321fa2-3d0d-11e6-9bd8-ffbee6d7f0ea.png)

It seems to work. I created a pull request as seen above. Is this the right way to do it?

Greetings,
Timo

**Comment by kaikreuzer** [comment]
>  Is this the right way to do it?

If it works, it is at least not a bad way to do it ;-)

Thanks!

**Comment by Ion3** [comment]
Great! Have a good day!
