### ISSUE TITLE
Add stop.sh / stop.bat file

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab-distro#233]
Add a stop.sh and a stop.bat file for easy shutdown openHAB2.
We need it for other platforms (Synology, RPi, Windows, ...)

**Comment by kaikreuzer** [comment]
If you start openHAB with start.sh, you are not running it in the foreground, so the way to stop it is through `system:shutdown`.
To start it as a service for Synology etc., you should use what is available in `runtime/karaf/bin`.
