### ISSUE TITLE
wrapper.working.dir=%KARAF_BASE% pointing to ../userdata instead of ./ -> mixes up multimedia actions

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#245]
When installing the KAraf runtime as a service, the folder set by wrapper.working.dir=%KARAF_BASE% in the openHAB-wrapper.conf is pointing to ../userdata, not the root folder of the distribution, and therefore multimedia actions do not work anymore unless runtime/sounds/ is copied to ../userdata . 
##

**Comment by kaikreuzer** [comment]
I guess now that the sounds are in conf/sounds, this problem does not appear anymore?

**Comment by kgoderis** [comment]
@kaikreuzer need to check, just thought of this cfr https://github.com/openhab/openhab-distro/pull/318

**Comment by kaikreuzer** [comment]
As you didn't complain anymore, I close it.
