### ISSUE TITLE
Mechanism to include 3rd party code beyond the content of the official distro

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#257]
As it stands there is a feature defined that allow to install experimental ESH automation bits, but nothing else. 

Given the fact that some PR for new bindings are now pending almost 2 (!) years due to a time constraint of Kai, and given the demand from users migrating to OH2 and willing to try out experimental code, the mechanism to share new code has to be elaborated or boosted.

My suggestion is to create a new "experimental" repo that is picked up by openhab-distro and where any author can pull PR's into, and so that users can choose to install or uninstall features from the karaf CLI. 

Sorry for hijacking the openhab forum and having the discussion here, as it is really an "issue", with technical implications/aspects for the distro repo

**Comment by kaikreuzer** [comment]
> some PR for new bindings are now pending almost 2 (!) years

Hey, I thought they are waiting, because you wanted to revamp them to be up to date with the latest features? But right, we are still heavily lacking maintainers and it is not good that I am the only one doing this...

Regarding your request: I doubt that it will bring much to create a new source repo - after all, the code is visible to everyone in the PRs and it is easiest to comment and discuss on them when they are a PR.
I assume what you really need is an easy way to share binary builds for other people to try out. Not sure if the catalogue really need to be within the official distro, though? Installation of features can also be nicely done through the command line from ANY location, so this should pretty much cover your request.

**Comment by kgoderis** [comment]
Mmmhh if it can be done from any location maybe you//some expert might want to describe how that can be done, knowing that the source is shared but not necessarily the .jars - anyway, it also boils down how to install jars from my own branches as I still have to export them from the IDE every time they change. Would love to be able to do that from the karaf CLI.

That being said, i still prefer the "agile" approach to open source code. It is ok to have crap code in a side-repo and improve that instead of having stuff not being used at all.... Is there an alternative  to the you/resource bottleneck? IMHO there isn't......

**Comment by maggu2810** [comment]
One option would be that you create the binding and a feature repository file in your private (e.g. Github) repo. Then you need to deploy it to some Maven repo (e.g. a Github repo, Bintray, jfrog for snapshots, ...).
A consumer only needs to add the feature repo to its online distribution and should be able to install the stuff by the common Paper UI extension mechanism.

**Comment by kgoderis** [comment]
@kaikreuzer I fact what I would really like to have is an CI environment for experimental stuff so that these things can be installed in the same way as the current distro, and that the speed of development and progress can be increased so that you as sole maintainer only have to review contributions that are feature complete, revised, etcetera. Maybe an additional repo is not "picture perfect" but it is a tool to reduce the burden on you. Let us just give it a try. I mean, 2 years to get through some binding PR is very very long (they are API-updated since a long time btw)...... And then, for development-under-discussion like the Knx binding it is a plus. Not everyone, including myself, are software engineers by profession, and thus not fluid in tooling to share binaries and so forth. This is still a hobby project and I would like to keep it fun but also advance

**Comment by kaikreuzer** [comment]
>  I still have to export them from the IDE every time they change. Would love to be able to do that from the karaf CLI.

No, all you have to do to build the jar is to run "mvn install" from within the binding folder. You could then upload it to some public place (your dropbox, GDrive, whatever) and ask people to simply install it through `bundle:install http://somewhere.com/yourbinding.jar`. It is that easy.

Feel free to document this somewhere and suggest a place where jars can be uploaded.

**Comment by kgoderis** [comment]
Ok but that is still a cumbersome process. I was more thinking in the lines of having a cloudbees job that also compiles features, and have the cloudbees Maven repo added to karaf, maybe without passing through jfrog bintray

Nonetheless, it is not only about others testing simple jars.

**Comment by kaikreuzer** [comment]
FTR, I have just adapted the issue title slightly; the are currently discussions of creating an Eclipse SmartHome Marketplace (as a sub-section of the Eclipse Marketplace), which would allow anyone to  host add-ons and add them to this central catalogue, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=506792. We could then add a functionality in the openHAB distro that allows browsing those entries and installing them.

**Comment by ThomDietrich** [comment]
Slightly off-topic:
Kai proposed, that *someone* could document what he said about installing addons from another source "somewhere". I would be willing to do this [here](http://docs.openhab.org/administration/bundles.html) if someone (@kgoderis maybe?) could summarize what's important in a few bullet points. Thanks.

The topic actually discussed here is something I would welcome as well. The Marketplace idea sounds good and with "Status – alpha, beta, production" this would probably cover what @kgoderis is looking for!?

**Comment by kgoderis** [comment]
> The topic actually discussed here is something I would welcome as well. The Marketplace idea sounds good and with "Status – alpha, beta, production" this would probably cover what @kgoderis is looking for!?

Yes, partly. It very much covers the sharing aspect, but one would still need a way to integrate experimental source (e.g. a GitHub repo) code into a running instance. e.g. should/could there be a link between the Eclipse Marketplace, and a CI server, which compiles for the marketplace, but picks up source from  a given repo?

**Comment by kaikreuzer** [comment]
> could there be a link between the Eclipse Marketplace, and a CI server

No, Eclipse Marketplace won't do the build from sources, this is left to the developer.

**Comment by kaikreuzer** [comment]
See https://community.openhab.org/t/distributing-bindings-through-the-iot-marketplace/24491 - I hope you like it :-)
