### ISSUE TITLE
Unresolved requirement: Import-Package: com.google.common.collect

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#263]
When I add some of my own bundles to the add-ons folder, I get the above error message when the bundles is started. Is there no core bundle that exports this package?

**Comment by kgoderis** [comment]
to be complete, this happens when removing /userdata/cache

**Comment by hugofernandes3** [comment]
Any solution to this?

**Comment by maggu2810** [comment]
You could Install the Guava bundle.
