### ISSUE TITLE
openHAB does not watch sym-linked directories

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-distro#265]
While working on my QNAP packages for openHAB2, I noticed that whenever I make changes to "addon", "config" or "userdata", which are linked to different locations, that, for example, the sitemap only gets reloaded when restarting openHAB.

I would expect that openHAB takes care about the sym-links and will watch these directories.

**Comment by kaikreuzer** [comment]
This should be actually solved through https://github.com/eclipse/smarthome/pull/2036, which is part of the latest distro - could you please test and report back?

**Comment by thopiekar** [comment]
Yes, will bookmark it here and report back as soon as possible.
Thank you for the update!

**Comment by thopiekar** [comment]
Made a simple symlink by:
```
mv conf conf-test
ln -s conf-test conf
```
and started openHAB again and works now.

Thanks!
