### ISSUE TITLE
Upgrade path from release version to snapshot

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-distro#266]
When OH2 goes live with a 'version 1' I think we will get some issues with people wanting to keep the release build, but to use a snapshot version of bindings. Currently, people think that they can simply uninstall a binding from PaperUI, and reinstall it, and they will get the latest version, and this isn't the case.

There should be some way that we can allow people to easily upgrade to the latest snapshot of a binding without having to upgrade the whole runtime?

**Comment by kaikreuzer** [comment]
Bindings will naturally also be adapted to new/changes features of the runtime - so there cannot be a general guarantee that snapshot addons will work on (older) releases.

So imho, we should provide first of all upgrade paths from rel->rel and snapshot->snapshot - even on this, we are still struggling...

**Comment by knosalaa** [comment]
Kai, any chance you could help me with getting this binding installed onto openHAB2 (QNAP Intel) https://community.openhab.org/t/generic-ip-camera-binding/12625
Thanks

**Comment by reyem** [comment]
I agree with Chris, that this is an important topic. Especially for the zwave binding, as the database is part of the binding and new devices are added constantly. If it is not possible to simply install the newest snapshot of the zwave binding in a release, this will force users to go to OH2 snapshot installations causing potential unstable systems. If not solved via this topic, the zwave binding should somehow split the database out of the binding jar to be able to update this in another way... Maybe online database!? I would prefer the simple approach of installing snapshots though.

**Comment by kvaster** [comment]
+1 I need to update zwave binding (it's database) now and I can't do it...
