### ISSUE TITLE
Error installing openhab-binding-freeswitch feature

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#268]
openhab> feature:list | grep mary
openhab-voice-marytts                     | 1.9.0.SNAPSHOT   | x        | Started     | openhab-aggregate-xml                      | Mary TTS

openhab> bundle:list -s | grep mary
213 | Active   |  80 | 1.9.0.201608070111    | org.openhab.io.multimedia.tts.marytts

openhab> feature:install openhab-binding-freeswitch 
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-voice-marytts; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-voice-marytts)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))" [caused by: Unable to resolve openhab-voice-marytts/1.9.0.SNAPSHOT: missing requirement [openhab-voice-marytts/1.9.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.io.multimedia.tts.marytts; type=osgi.bundle; version="[1.9.0.201608170111,1.9.0.201608170111]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.io.multimedia.tts.marytts/1.9.0.201608170111: missing requirement [org.openhab.io.multimedia.tts.marytts/1.9.0.201608170111] osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.io.multimedia.tts)"]]

anyone any clue?

**Comment by kaikreuzer** [comment]
I have seen this as well - will try to provide a fix soon!

**Comment by kaikreuzer** [comment]
Looks as if you are using no recent snapshot - marytts is not available as 1.9.0 anymore, but only as a 2.0.0 version; so you should uninstall the old version and your problem should go away.
(And there is a problem with the mary 2.0.0 which I am going to fix soon!)

**Comment by kgoderis** [comment]
Yikes....

openhab> feature:uninstall openhab-voice-marytts 
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-runtime-compat1x; type=karaf.feature; version=0 [caused by: Unable to resolve openhab-runtime-compat1x/2.0.0.SNAPSHOT: missing requirement [openhab-runtime-compat1x/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.core.compat1x; type=osgi.bundle; version="[2.0.0.201608201909,2.0.0.201608201909]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.compat1x/2.0.0.201608201909: missing requirement [org.openhab.core.compat1x/2.0.0.201608201909] osgi.wiring.package; filter:="(osgi.wiring.package=org.eclipse.smarthome.core.audio)"]]

openhab> feature:list | grep compat1
openhab-runtime-compat1x                  | 2.0.0.SNAPSHOT   |          | Started     | openhab-aggregate-xml                      | Compatibility layer for openHAB 1 add ons

**Comment by kaikreuzer** [comment]
Interesting that it even does not allow uninstalling features...
We should add some note that the online distro should not be used with snapshot releases, I guess...

**Comment by kgoderis** [comment]
Is there a way to migrate an online distro to the offline base?

**Comment by kaikreuzer** [comment]
Never tried myself, but probably something similar to https://github.com/xsnrg/OpenHAB2-tools/blob/master/makeHAB

**Comment by kgoderis** [comment]
I have something similar as well that copies over all the configuration files as well (or at least, it tries to) but is not perfect at all. From your comment I understand that overwriting the installation with the offline distro should work.

**Comment by kgoderis** [comment]
@kaikreuzer the off-line distro feels snappier (ok that is logical), resolves bundles faster and has less side-effects than the online distro. Copying over as such does not seem to break things massively so that is good news

**Comment by kaikreuzer** [comment]
Indeed, that's good news. Maybe we should really remove the online distro for snapshot builds and only publish it for beta releases?
