### ISSUE TITLE
MaryTTS fails to start on distro with a NCDFE

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#269]
Running the MaryTTS add-on, it fails at startup with:

```
java.lang.NoClassDefFoundError: org/apache/log4j/LogManager
	at marytts.util.MaryUtils.isLog4jConfigured(MaryUtils.java:828)
	at marytts.server.Mary.configureLogging(Mary.java:310)
	at marytts.server.Mary.startup(Mary.java:227)
	at marytts.server.Mary.startup(Mary.java:205)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:71)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:63)
	at org.openhab.voice.marytts.internal.MaryTTSService.getMaryInterface(MaryTTSService.java:203)
```
while it works well from within the IDE.

Analyzing it, I noticed that slf4j contains org/apache/log4j/LogManager, while org.ops4j.pax.logging (which is used by Karaf) does not.

**Comment by maggu2810** [comment]
> I noticed that slf4j contains org/apache/log4j/LogManager

I assume it depends which slf4j bundle you are refer to.
The slf4j API bundle does not contain such a class.

What you want to use is log4j-over-slf4j, so the bundle using a log4j implementation will provide its log to slf4j without using that interface.

**Comment by kaikreuzer** [comment]
Yes, I compared the two bundles that claim to export org.apache.log4j:

In the IDE, this is https://github.com/qos-ch/slf4j/tree/master/log4j-over-slf4j/src/main/java/org/apache/log4j

In the distro, this is https://github.com/ops4j/org.ops4j.pax.logging/tree/master/pax-logging-api/src/main/java/org/apache/log4j.

As you can see, LogManager is not contained in the latter one.

**Comment by maggu2810** [comment]
I can give you an idea for a workaround only:

The bundle org.openhab.voice.marytts does not bundle the marytts only but also log4j-over-slf4j and add it to the "private" classpath.
The bundle should then not export org.apache.log4j but import org.slf4j, org.slf4j.helpers and org.slf4j.spi.
So, from a external point of view the logging is done using slf4j and internally the logging could be done using log4j, too.

**Comment by kaikreuzer** [comment]
I can give it a try - I already tried to implement a fake LogManager, but unfortunately that didn't work, since the package is still resolved from externally and the internal class is not seen by Mary.
