### ISSUE TITLE
Mismatch in UI controls for RollerShutters

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#273]
Imagine a RollerShutter Item. It accepts UpDown, Percent as DataTypes, and  UpDown, StopMove, Percent as CommandTypes

When declared as Switch in .sitemap, then that Item is rendered as 
 - a control with an up, x button and down arrow in Classic UI
 - a control with an up, x button and down arrow in Basic UI
 - a switch in the iOS app, but to which the RollerShutter does not react when toggling the switch (which is logical cfr here above)

When declared as a Slider in the .sitemap, then it is rendered as
 - a control with up and down arrow, but that does not react to any interaction in the Classic UI
 - a slider in the Basic UI
 - a slider in the iOS app

This is quite inconsistent in terms of behaviour and control

**Comment by kaikreuzer** [comment]
The first is a known bug (reported for Android, but the same in iOS): https://github.com/openhab/openhab.android/issues/219

The second is a limitation of the Classic UI. There were tries to implement a slider for it, but you might remember that that led to 4 months of a broken 1.8 release earlier this year (and the reason that we are at 1.8.3 patch level now).
