### ISSUE TITLE
Charts with multiple items not displayed within iOS App

### ISSUE THREAD

**Issue by foxytocin** [openhab/openhab-distro#277]
Hi,
can't say since when, but charts with multiple items are empty within the iOS app. By refreshing the app, the following WARN is displayed in the log file. I didn't changed the sitemap. Just updated to the latest snapshot.

> 2016-09-10 14:54:51.974 [WARN ] [o.myopenhab.internal.MyOpenHABClient] - Jetty request 1637 failed: null

Calling "http://raspberry2.local:8080/chart?items= ... " from the browser still is working perfectly. The charts data are there. But not displayed in the app.

Single items charts are working in the app.
##

**Comment by kaikreuzer** [comment]
This seems to be a bug related to openhab-cloud, right? I do not have any issues with local access at least. So if you still see this issue when using the new myopenhab.org service, you might want to enter an issue at https://github.com/openhab/openhab-cloud/issues or first check with others on the forum at http://community.openhab.org/.
