### ISSUE TITLE
Ssh connexion to the console failing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#278]
With recent snapshots, I am mo more able to connect to the console.
I tried the following commands:
ssh karaf@localhost -p 8101
ssh openhab@localhost -p 8101
Password request does not appear.

**Comment by ThomDietrich** [comment]
This might be connected? https://community.openhab.org/t/ssh-session-timing-out-on-slow-hardware/14008/1

**Comment by lolodomo** [comment]
@ThomDietrich : thank you
I suppressed the file .ssh/known_hosts and then I was able to connect again.
