### ISSUE TITLE
Generating the SSL certificate through the demo-package requires a restart

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#28]
Using the downloadable distribution, the ssl certificate is generated by the bundle when the demo-package is installed - which is after the base runtime has been already started (including Jetty). Therefore the SSL support does not become active - it is only there, once the runtime is restarted.

How shall we solve this? Either we could include the certificate feature in the runtime-base already or we accept the fact that it only becomes active after a restart.

**Comment by maggu2810** [comment]
If the bundle and the feature of the generation does not depend on any other openhab stuff (it should be the case, because it is using a start level that is lower then the other ones) you could mark it as a prerequisite.

**Comment by dvanherbergen** [comment]
I would move the certificate feature in the runtime base. It currently has start level 20 so that it starts before jetty does at level 30.
