### ISSUE TITLE
Removing openhab2-online failed with errors on ubuntu

### ISSUE THREAD

**Issue by ollie-dev** [openhab/openhab-distro#284]
Removing openhab2-online via `sudo apt-get remove openhab2-online` failed with errors, because stopping the server failed:

`$ sudo dpkg --remove -D 777 openhab2-online
D000001: ensure_diversions: new, (re)loading
D000001: deferred_remove package openhab2-online:all
D000001: checking dependencies for remove 'openhab2-online:all'
(Reading database ... 196427 files and directories currently installed.)
D000200: oldconffsetflags '/etc/default/openhab2' namenode 0x1676d58 flags 4
D000200: oldconffsetflags '/etc/openhab2/html/index.html' namenode 0x16830f8 flags 4
D000200: oldconffsetflags '/etc/openhab2/html/readme.txt' namenode 0x1683130 flags 4
D000200: oldconffsetflags '/etc/openhab2/icons/classic/readme.txt' namenode 0x1683168 flags 4
D000200: oldconffsetflags '/etc/openhab2/items/readme.txt' namenode 0x16831a0 flags 4
D000200: oldconffsetflags '/etc/openhab2/persistence/readme.txt' namenode 0x16831d8 flags 4
D000200: oldconffsetflags '/etc/openhab2/rules/readme.txt' namenode 0x1683210 flags 4
D000200: oldconffsetflags '/etc/openhab2/scripts/readme.txt' namenode 0x1683248 flags 4
D000200: oldconffsetflags '/etc/openhab2/services/readme.txt' namenode 0x1683280 flags 4
D000200: oldconffsetflags '/etc/openhab2/services/runtime.cfg' namenode 0x16832b8 flags 4
D000200: oldconffsetflags '/etc/openhab2/sitemaps/readme.txt' namenode 0x16832f0 flags 4
D000200: oldconffsetflags '/etc/openhab2/things/readme.txt' namenode 0x1683328 flags 4
D000200: oldconffsetflags '/etc/openhab2/transform/de.map' namenode 0x1683360 flags 4
D000200: oldconffsetflags '/etc/openhab2/transform/en.map' namenode 0x1683398 flags 4
D000200: oldconffsetflags '/etc/openhab2/transform/readme.txt' namenode 0x16833d0 flags 4
D000200: oldconffsetflags '/var/lib/openhab2/etc/java.util.logging.properties' namenode 0x1683440 flags 4
D000200: oldconffsetflags '/var/lib/openhab2/etc/jetty.xml' namenode 0x1683478 flags 4
D000200: oldconffsetflags '/var/lib/openhab2/etc/keystore' namenode 0x16834b0 flags 4
D000200: oldconffsetflags '/var/lib/openhab2/deploy/README' namenode 0x1683520 flags 4
D000200: oldconffsetflags '/var/lib/openhab2/tmp/README' namenode 0x1683590 flags 4
D000200: oldconffsetflags '/etc/openhab2/services/addons.cfg' namenode 0x1683600 flags 4
Removing openhab2-online (2.0.0~b4) ...
D000002: fork/exec /var/lib/dpkg/info/openhab2-online.prerm ( remove )
 * Stopping openHAB2 server openhab2                                                                                                                                         stop: Ignoring predefined value for KARAF_HOME
Can't connect to the container. The container is not running.
                                                                                                                                                                      [fail]
invoke-rc.d: initscript openhab2, action "stop" failed.
dpkg: error processing package openhab2-online (--remove):
 subprocess installed pre-removal script returned error exit status 1
D000001: ensure_diversions: same, skipping
D000002: fork/exec /var/lib/dpkg/info/openhab2-online.postinst ( abort-remove )
D000001: ensure_diversions: same, skipping
Errors were encountered while processing:
 openhab2-online`

I could finally fix it by editing `/var/lib/dpkg/info/openhab2-online.prerm` and commenting out the stop-server. @theoweiss, maybe you could have a look on the removal-skript. Thanks! :)

**Comment by theoweiss** [comment]
Hi @ollie-dev,

thanks for reporting this.
@kaikreuzer maybe you could give me rights to assign this ticket to myself?

Regards,
Theo

**Comment by kaikreuzer** [comment]
> @kaikreuzer maybe you could give me rights to assign this ticket to myself?

Done!

**Comment by theoweiss** [comment]
Hi @ollie-dev,

could you test if these packages fix your reported issue (testing one of both would be sufficient):
https://bintray.com/theoweiss/generic/download_file?file_path=1%2Fopenhab2-offline-2.0.0-SNAPSHOT.deb
https://bintray.com/theoweiss/generic/download_file?file_path=1%2Fopenhab2-online-2.0.0-SNAPSHOT.deb

Thanks,
Theo
