### ISSUE TITLE
Warning if no JAVA_HOME is set

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#29]
When launching the runtime without $JAVA_HOME being set, the message
```
karaf: JAVA_HOME not set; results may vary
```
is displayed. I don't think we really require JAVA_HOME anywhere and all seems to work well without it - so I wonder if we should remove this message.

**Comment by dvanherbergen** [comment]
This message is generated by the karaf start shell script. I don't think we should modify that one.
Isn't setting JAVA_HOME a good practice anyway?

**Comment by kaikreuzer** [comment]
> Isn't setting JAVA_HOME a good practice anyway?

Well, I came across it because I simply setup Raspian, installed the JDK through apt-get and then openHAB. Since the JDK install did not set JAVA_HOME this was missing and I guess I won't be the only one coming across it. And if a missing JAVA_HOME has no consequence, why bother?

**Comment by dvanherbergen** [comment]
I guess we should ask the Karaf guys why "results may vary" :smile:

**Comment by maggu2810** [comment]
IIRC JAVA_HOME was used in the past by various software component to locate the path of the JDK (and so the bundled JRE). Some linux distributions uses it, some not.
The simplest workaround if you want to get rid of this message till monday is IMHO to copy locateJava function (e.g. of the bin/karaf script) to the start.sh file (same for .bat) and set JAVA_HOME the same way it is done there if it is not set already.

No consequence is not granted as long as you do not know every line of code if someone is using that environment variable.

Just my two cents if you need a workaround to remove this message...

**Comment by kaikreuzer** [comment]
On my RasPi, I now see the following at startup:
```
pi@raspberrypi:~/oh $ ./start.sh 
Launching the openHAB runtime...
java is /usr/bin/java
/usr/bin/java
```
This does not look like the final solution yet :-)

**Comment by dvanherbergen** [comment]
oops. Looks like I somehow left ome debug info in there :-)
A fix is on its way..
