### ISSUE TITLE
[Fatal Error] :1:3: Markup im Dokument vor dem Root-Element muss ordnungsgemäß formatiert sein.

### ISSUE THREAD

**Issue by rkleinert** [openhab/openhab-distro#295]
Hello,
I am getting the fatal error "[Fatal Error] :1:3: Markup im Dokument vor dem Root-Element muss ordnungsgemäß formatiert sein." after following the installation guide for linux on a Raspberry Pi 2 with Raspbian Jessie.

Is this a known issue? And how can I solve it. I already have OH 1.8 on the Pi, is this a problem?

Thanks,

Robert

**Comment by kaikreuzer** [comment]
See https://github.com/openhab/openhab-distro/issues/121.
