### ISSUE TITLE
Minor issue in title tag

### ISSUE THREAD

**Issue by xrow** [openhab/openhab-distro#296]
Hi,

It seems that for example german umlaut "ü" out of "Menü" is not properly encoded in the HTML title of the basic ui. If the files and text are properly encoded you don't need special HTML encoding.

<img width="202" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/295491/19315117/cfe80b0e-909c-11e6-8096-a6eb3988e3eb.PNG">

**Comment by kaikreuzer** [comment]
Could you please report this here? https://github.com/eclipse/smarthome/issues (this is where the code of the Basic UI resides) - thanks!

**Comment by xrow** [comment]
Sorry I wasn`t able to figure that out.

Done. 

https://github.com/eclipse/smarthome/issues/2308
