### ISSUE TITLE
Move debian package building to a separate repo

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#298]
The issues on this repo are a wild mix of problems of the distro itself and the debian packaging.
We have separate repos for Docker, Synology and possibly soon Snappy, so I would claim that it makes sense to move the debian package build as well to a separate repository.

As a side effect, this would also heavily decrease the size of our build jobs as discussed with @theoweiss a while ago.

@theoweiss Would you be ok with this and take the lead on it?

**Comment by theoweiss** [comment]
@kaikreuzer I'm ok with that, but it will take some time to get this done.
Do you know a maven plugin to download a file (distro tar.gz) from a url?

**Comment by kaikreuzer** [comment]
Yes, see right here: https://github.com/openhab/openhab2-addons/blob/master/addons/voice/org.openhab.voice.marytts/pom.xml#L22

**Comment by theoweiss** [comment]
Looks good. How should we proceed?

**Comment by kaikreuzer** [comment]
Make a suggestion on the repo name and I'll create it and assign you as the maintainer.
How about "openhab-debian"? Or better "openhab-apt"?

**Comment by theoweiss** [comment]
What do you think about openhab-common-linux (or openhab-ospackage) so we're free to add rpm packaging sometime? There is a gradle plugin to achieve this: https://github.com/nebula-plugins/gradle-ospackage-plugin, e.g. elasticsearch used it https://github.com/elastic/elasticsearch/blob/master/distribution/build.gradle.

**Comment by kaikreuzer** [comment]
Hm, neither common-linux nor ospackage seem to be common terms in the Linux community, so the name does not mean a lot for most people. Would "openhab-linuxpkg" maybe be an alternative?

**Comment by theoweiss** [comment]
Sounds good.
I've thought about common-linux because Synology and Snappy are also linux packages.

**Comment by kaikreuzer** [comment]
Yes, and we have separate repos for them, so this was exactly the reason, why I didn't want to call it common-linux :-)

**Comment by theoweiss** [comment]
Expressive names are always difficult to find :-( .

**Comment by kaikreuzer** [comment]
Yeah, one of the biggest problems in software engineering...

Repo is set up and you're the admin: https://github.com/openhab/openhab-linuxpkg

Have fun :-)

**Comment by theoweiss** [comment]
I thought of common in the sense of "well known" or "widespread".

**Comment by theoweiss** [comment]
Let's roll!

**Comment by theoweiss** [comment]
BTW your aware of this #302 ?

**Comment by kaikreuzer** [comment]
@theoweiss Any progress on this? I would really love to have a separation of concerns between these repos.

**Comment by theoweiss** [comment]
I've started some dev here: https://github.com/theoweiss/openhab-linuxpkg/tree/dev
I'm struggling with some gradle/groovy stuff which is new to me. But I think it's a good way to go.
I'm sure to get this done, but moreover the end of year race has begun for paid work and family stuff, therefore don't expect fast results. If there are any volunteers (with gradle experience) your very welcome to help out (may be @BClark09 ?).

**Comment by kaikreuzer** [comment]
Would be great to have @BClark09 joining the effort - I would want to wait too long; I plan a new beta release mid of December and it would be perfect to have the repos separated by then.

**Comment by BClark09** [comment]
I don't know much about gradle experience I'm afraid, but will help where I can. I've just sent a PR to the dev branch to update the paths.

**Comment by theoweiss** [comment]
I've just opened a PR https://github.com/openhab/openhab-linuxpkg/pull/1 which I'll merge the next days and an issue https://github.com/openhab/openhab-linuxpkg/issues/2 for discussing the further development. I invite everybody who's interested in deb packaging to join the discussion, especially @kaikreuzer, @BClark09 and @ThomDietrich.

**Comment by theoweiss** [comment]
Hi @kaikreuzer,

I suggest to add a new team called "LinuxPkg Maintainers" and want to envite @BClark09 to get a member of this team. If he accepts he should also become a member of the bintray openhab group https://bintray.com/openhab to be able to put releases to bintray.

Regards,
Theo

**Comment by theoweiss** [comment]
BTW: I'm away from my email for the weekend and will be back on Monday evening.

**Comment by BClark09** [comment]
I'd love to help and appreciate your confidence in me although I've never done anything like that before and am only just learning the deb packaging ropes as it were. I'm also in my final year of my PhD so you may see me drop out of radar a couple of times. I would happily help maintain the LinuxPkg distro where I can though.

**Comment by kaikreuzer** [comment]
Many thanks for your work @theoweiss! I have created the @openhab/linuxpkg-maintainers group as requested. Please also note https://github.com/openhab/openhab-linuxpkg/issues/4.

**Comment by kaikreuzer** [comment]
@theoweiss & @BClark09 Happy New Year!
Where are we regarding the move?
Once we can remove the debian code from the distro itself, please also make sure to move/close all of [these issues] over to https://github.com/openhab/openhab-linuxpkg/issues. Thanks!

**Comment by BClark09** [comment]
Hi @kaikreuzer, Happy New Year to you too!

I have had a good deb package builds running on the openhab-linuxpkg branch, but I feel that there needs to be some sort of script that removes older nightly builds from Bintray (If I've understood correctly, we'll still use Bintray for them) before it's ready to be used. I'm assuming @theoweiss will know more about what's involved in that process and what is outstanding to make that happen.

**Comment by theoweiss** [comment]
The next steps are: cleanup and merge the two open PRs. Then integrate the linuxpkg project into the cloudbees build. I had planed to tests the jenkins integration with my local test server, but had to move the test till tomorrow evening.

**Comment by theoweiss** [comment]
Jenkins test worked like a charm :-)

![openhab-linuxpkg1](https://cloud.githubusercontent.com/assets/4682281/21625482/2f5aec7c-d20c-11e6-9ff5-266b102e39e2.jpg)

At Bintray:
https://bintray.com/theoweiss/apt-repo2/openhab2/2.0.0%7E20170103231411

@kaikreuzer I would add the project to cloudbees tomorrow. Do we have a bintray api key for the openHAB organisation? Otherwise I would use mine ;-(

**Comment by kaikreuzer** [comment]
@theoweiss Yes, we have! You will find it configured as BINTRAY_API_KEY and BINTRAY_USER at https://openhab.ci.cloudbees.com/configure.

**Comment by shoeper** [comment]
I'd like to mention that the current snapshot repository (https://openhab.ci.cloudbees.com/) is quite slow. Would it be possible to move the downloads to another (faster) mirror?

**Comment by kaikreuzer** [comment]
As mentioned by Theo above: It will be hosted on Bintray.

**Comment by shoeper** [comment]
Sorry, overread that. Good news :+1:

**Comment by theoweiss** [comment]
@kaikreuzer it seems like we've already used up the disk usage quota?
![cloudbeesquota](https://cloud.githubusercontent.com/assets/4682281/21659284/52dfbeca-d2ca-11e6-82ae-960d7d534ef6.jpg)

**Comment by kaikreuzer** [comment]
So we should first remove the debian package from the distro build - then we will use much less space!

**Comment by theoweiss** [comment]
Hmm, I hoped to get a smooth transition to the new apt snapshot repo, with both repos available.

**Comment by kaikreuzer** [comment]
I have reconfigured the distro build plan to only keep the artifacts of a single build (before of the last two builds), so I hope this frees up enough disk space for your new plan to set up!

**Comment by theoweiss** [comment]
I've just thought about a similar solution. Can we just manually delete some of the older builds?
![openhabbuild jgp](https://cloud.githubusercontent.com/assets/4682281/21660541/16665160-d2d0-11e6-8516-fe22a70a8f92.jpeg)

**Comment by kaikreuzer** [comment]
These older ones don't take any space, because the artifacts are already removed.
As I said, only for the very latest build, the artifacts are kept.

**Comment by kaikreuzer** [comment]
The "disk used" value is probably not updated yet. Just go ahead and create your build, it should work.

**Comment by theoweiss** [comment]
Ok.

**Comment by theoweiss** [comment]
Nice, it worked (,so far)! 
![openhab-linuxpkg-bintray](https://cloud.githubusercontent.com/assets/4682281/21662094/44a93a12-d2d8-11e6-9629-0e65bf80e657.jpg)

@BClark09 could you please test the snapshot from the official openHAB repo. Thanks in advance.

**Comment by BClark09** [comment]
@theoweiss Will do as soon as I can! From what I noticed in the cloudbees log, calculateMetadata also needs to be run right?

**Comment by theoweiss** [comment]
Not necessarily, we will see.

**Comment by BClark09** [comment]
```
Input:
echo "deb https://dl.bintray.com/openhab/apt-repo2 unstable main" | sudo tee /etc/apt/sources.list.d/openhab.list
sudo apt-get update

Output: 
W: GPG error: https://dl.bintray.com unstable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 075721F6A224060A
```

```
Input:
gpg --keyserver pgpkeys.mit.edu --recv-key 075721F6A224060A
gpg -a --export 075721F6A224060A | sudo apt-key add -

Output:
gpg: key A224060A: public key "openHAB Bintray Repositories <owner@openhab.org>" imported
OK
```

```
Input:
sudo apt-get update && sudo apt-get upgrade

Output:
The following packages will be upgraded:
  openhab2-offline
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Get:1 https://dl.bintray.com/openhab/apt-repo2/ unstable/main openhab2-offline all 2.0.0~20170104233230-1 [186 MB]
Fetched 186 MB in 2min 9s (1,430 kB/s)
Unpacking openhab2-offline (2.0.0~20170104233230-1) over (2.0.0~20170103232707) ...
Processing triggers for systemd (215-17+deb8u5) ...
Setting up openhab2-offline (2.0.0~20170104233230-1) ...
```

And were done, upgraded and it seems to be working! a further sudo apt-get update told me I was already up to date too.

**Comment by theoweiss** [comment]
I also was also curious if it would work. I've tested an installation (raspberry pi 3) of "unstable" and an upgrade to "testing". Looks good!

![openhab-linuxpkg-install](https://cloud.githubusercontent.com/assets/4682281/21663071/0b37c4e6-d2de-11e6-92a5-1a27fbac8bfd.jpg)

![openhab-linuxpkg-upgrade](https://cloud.githubusercontent.com/assets/4682281/21663073/16bad42a-d2de-11e6-9ac3-5867704207f6.jpg)

**Comment by theoweiss** [comment]
High five @BClark09

**Comment by BClark09** [comment]
:party:

**Comment by kaikreuzer** [comment]
Well done, guys!

So we will have to ask people to switch to the new Bintray repository, right?
I am wondering, if we should combine this request with another change: While you were working on the packaging, I was busy last night restructuring the distro, so that we get rid off online/offline and will only have a single one. Additionally, there would then be an "addons" package that can be (optionally) downloaded to make everything available offline as well. This clearly will require some further changes to the debian package as well as communication to the users. I'll probably have my side ready this weekend. Wdyt?

**Comment by BClark09** [comment]
Yes, I can prepare a PR for the docs with the instructions above to apt-get from bintray.

To clarify, you're planning on keeping just the openhab2-online package (perhaps renaming it to "openhab2" and allowing users to download a seperate package containing all the addons if required? How will this addons package work? If all that is required is to have files in a particular folder then in debian package terms, we could add a separate openhab2-addons package which installs them for a user.

Otherwise is it possible to add an "offline=true" configuration for openHAB which downloads the addons on first launch? Changing the default false to true would be all that is necessary to change the openHAB2 install from an online distribution to an offline distribution.

**Comment by kaikreuzer** [comment]
I have just pushed my (WIP) current version to https://github.com/openhab/openhab-distro/pull/369.

Yes, for the manual download, there will be only one distro, simply openhab-2.0.0.zip, which is the online variant. Additionally, there is a addons-2.0.0.kar, which is a KAR (Karaf Archive) that contains all add-ons. This kar file can be put in the "addons" folder of the distro and is automatically picked up by it.

> add an "offline=true" configuration for openHAB which downloads the addons on first launch

Haha, this somehow contradicts each other, doesn't it?

> in debian package terms, we could add a separate openhab2-addons package which installs them for a user.

Yes, I think this would be the best. I'll probably also add a addons-legacy.kar, which contains all the legacy 1.x add-ons (which are currently only available online, but I think we can make them easily available through this mechanism as well).

**Comment by BClark09** [comment]
> Haha, this somehow contradicts each other, doesn't it?

Eek, I didn't have my thinking cap on! :laughing: 

That's fair enough, does openHAB need to be restarted when the KAR files are updated? Just thinking of how the new Debian package should be created. @theoweiss do you think there will be few issues in adding such a package?

The changes seen to the normal Linux user are pretty straight forward but I don't think there's a reasonable way of updating a package name, therefore I'm hoping that all the user has to do is:

```
sudo apt-get remove openhab2-o*
sudo apt-get install openhab2
```

And for people still wanting the "offline" approach, finish with:

```
sudo apt-get install openhab2-addons
```

This way, a  `sudo apt-get upgrade` will update either when necessary. Speaking of which, how often do you expect to publish new kar files? I'm a little worried about how often we might publish to bintray.

**Comment by kaikreuzer** [comment]
>  does openHAB need to be restarted when the KAR files are updated? 

No.

> how often do you expect to publish new kar files?

Same as new distro, it comes out of the same build. I also publish the snapshot version to Bintray, but I always overwrite the previous version of it, so the size won't grow.

**Comment by theoweiss** [comment]
It shouldn't be to hard to get this change into the deb packaging. The way to go is like @BClark09 just described. Furthermore we should add openhab2-o* as conflicting packages of the new openhab2 package and openhab2 as required package of the new "addons" package.

Now we'll have to wait for the new packages being available. I think at this time the cloudbees snapshots won't be available any longer because it makes no sense to adapt the deb package build of the openhab-distro project.

Maybe @ThomDietrich could nevertheless announce the new unstable repo to the community, to get some testers of the new packages and repo.

**Comment by kaikreuzer** [comment]
> it makes no sense to adapt the deb package build of the openhab-distro project.

Right, I will actually remove the debian parts in my PR already.

> Maybe @ThomDietrich could nevertheless announce the new unstable repo to the community, to get some testers of the new packages and repo.

Why don't you do it yourself here? https://community.openhab.org/c/openhab-2/news-important-changes

**Comment by ThomDietrich** [comment]
Hey guys,
I've been traveling for the last couple of days and am getting back to speed right now. I very much like what I read here! ;) Nice to see that you are making progress and that you thought about https://github.com/openhab/openhab-linuxpkg/issues/2#issuecomment-267841567 👍 
@theoweiss thanks for mentioning me. In general I would be happy to help but regarding this topic I feel that you or @BClark09 have all the needed info and hence should post this announcement ;)

**Comment by BClark09** [comment]
Alas, the board is locked for administrator/moderator use only I believe.

**Comment by ThomDietrich** [comment]
@kaikreuzer: Nominating @BClark09 as moderator

**Comment by shoeper** [comment]
I've just tried the new repository and am also using a local apt mirror which is run using apt-mirror.

apt-mirror has a problem with MD5Sum in the Release file. Could you change it to MD5sum?

see also https://projects.puppetlabs.com/issues/12677

**Comment by BClark09** [comment]
Thanks @ThomDietrich, funnily enough it's the day of my forum anniversary! :laughing: However, I think I do not suite that role just yet, @theoweiss has more of the technical know-how and the administrative ability.

Hi @shoeper, we can start taking issues on at [openhab-linuxpkg/issues](http://github.com/openhab/openhab-linuxpkg/issues) for debian package related issues The [Debian RepositoryFormat](https://wiki.debian.org/RepositoryFormat#MD5Sum.2C_SHA1.2C_SHA256) dictates that the release file contains the uppercase 'S'. But on reading the related issue you linked, this is more likely to do with MD5sum not being present in the packages file.

**Comment by shoeper** [comment]
> But on reading the related issue you linked, this is more likely to do with MD5sum not being present in the packages file.

Ok, this is even more likely, because I get the "error" multiple times (think it was 4).

**Comment by theoweiss** [comment]
I'll prepare the announcement.

**Comment by kaikreuzer** [comment]
>  the board is locked for administrator/moderator use only I believe.

Everyone from the "maintainers" group in Discourse can post news there. You weren't yet in this group.

> I think I do not suite that role just yet

Well, you are already listed as a maintainer on https://github.com/orgs/openhab/teams/linuxpkg-maintainers, so I added you in the Discourse group now as well. No way to escape it ;-)

**Comment by theoweiss** [comment]
The announcement is online! 
https://community.openhab.org/t/replacement-of-the-apt-snapshot-repository/
Tomorrow I'm away for skiing with the kids ;-)

**Comment by BClark09** [comment]
> No way to escape it ;-)

Haha, thanks Kai!

Enjoy your well earn skiing @theoweiss! :)

Shall we set this issue to close automatically when #369 is merged?

**Comment by kaikreuzer** [comment]
We can also close it manually then :-)

**Comment by BClark09** [comment]
Hi @kaikreuzer, I noticed this distro build is getting stuck on the bintray upload, which prevents the deb packaging from running. When triggered manually, the deb build's own upload works without a problem, could this be due to the difference in syntax?:

```
response=$(curl -s -X PUT --data-binary @$PACKAGE_ARCHIVE -u ${BINTRAY_USER}:${BINTRAY_API_KEY} "$BINTRAY_URL/content/$BINTRAY_SUBJECT/$BINTRAY_REPO/$PACKAGE_PATH/addons.zip;bt_package=$BINTRAY_PACKAGE;bt_version=$PACKAGE_VERSION;publish=1;explode=1;override=1" -H "Content-Type: application/zip")

```

Is used now, rather than:

```
response=$(curl -s -X PUT -H "Content-Type: application/zip" -T {PACKAGE_ARCHIVE -u${BINTRAY_USER}:${BINTRAY_API_KEY} "$BINTRAY_URL/content/$BINTRAY_SUBJECT/$BINTRAY_REPO/$PACKAGE_PATH/addons.zip;bt_package=$BINTRAY_PACKAGE;bt_version=$PACKAGE_VERSION;publish=1;explode=1;override=1"
```

I also didn't understand the "addons.zip" part of the path to bintray, is it worth trying without that or using the $PACKAGE_ARCHIVE name?

**Comment by kaikreuzer** [comment]
Yes, I noticed it hanging as well and couldn't yet find a reason for it (especially as it worked before).

I do not really see the syntax change in your example... Feel free to create a PR and we will have a try if it makes a difference!

**Comment by BClark09** [comment]
```
curl -s -X PUT --data-binary addons.zip -u ${BINTRAY_USER}:${BINTRAY_API_KEY} "https://api.bintray.com/content/$BINTRAY_SUBJECT/$BINTRAY_REPO/$PACKAGE_PATH/addons.zip;bt_package=$BINTRAY_PACKAGE;bt_version=$PACKAGE_VERSION;publish=1;explode=1;override=1" -H "Content-Type: application/zip"
{"message":"success"}

curl -s -X PUT -T addons.zip -u${BINTRAY_USER}:${BINTRAY_API_KEY} "https://api.bintray.com/content/$BINTRAY_SUBJECT/$BINTRAY_REPO/$PACKAGE_PATH/addons.zip;bt_package=$BINTRAY_PACKAGE;bt_version=$PACKAGE_VERSION;publish=1;explode=1;override=1"
{"message":"success"}
```

:(

**Comment by BClark09** [comment]
Hi @kaikreuzer, all seems well and stable for the time being. Shall we close this issue?

**Comment by kaikreuzer** [comment]
Certainly - thanks!
