### ISSUE TITLE
Things not correctly initializing at startup on slow hardware

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#306]
As a remember, using snapshot 505 on a RPI 2, all my things initialized correctly at startup except the astro thing that remained in INITIALIZING state around half of the time. The workaround I found was to build myself the jar file for the astro binding and simply put it in the addons dirrectory.

After a supposed crash of my microSD card, I tried to install snapshot 554 on an old RPI 1. Now at startup, that is a disaster. Most of my things remain in INITIALIZING (or even UNINITIALIZED) state. Things concerned are astro, freebox, hue, sonos, ... so every OH2 bindings.
As a workaround, after the startup process, I can run in the console for each binding a bundle:stop followed by a bundle:start and then all my things are again ONLINE.

There is clearly a critical issue with thing management at openHAB startup, at least on slow machines. My assumption is that at startup, the hardware has difficulties to handle all jobs and the timing of 5s used by the thing manager is too small.
Can someone confirm the timeout of 5s used by the thing manager for each call to initialize() and dispose() ? Could this timeout be made adjustable (parameter) ? I would be curious to see if there is a difference with a timeout set to 10s for example.

Did someone test OH2 on a RPI 1 ? I cannot be alone to notice that behavior. Is OH2 supposed to work well on a RPI 1 ?

As soon as possible (when I get a new MicroSD card), I will try the same snapshot on a RPI 2 to see if this can be a regression between snapshot 505 and 554 or if the problem is only relative to the slower hardware.

**Comment by kaikreuzer** [comment]
I would suggest to wait with further testing until https://github.com/eclipse/smarthome/pull/2087 is merged as it will heavily change the ThingManager startup behavior.

> Is OH2 supposed to work well on a RPI 1 ?

No, the recommendation is at least a RPi2.

**Comment by ThomDietrich** [comment]
It's highly recommended to run OH2 at least on a RPi2: [docs](http://docs.openhab.org/installation/rasppi.html#recommended-setup)
Nevertheless, I had openHAB 2 running without problems on a "Raspberry Pi Model B Plus Rev 1.2" ([comparison](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications)).

**Comment by lolodomo** [comment]
Same snapshot is working well on a RPI 2.
My conclusion is that startup of OH 2 is not working well on very slow machines.

**Comment by kaikreuzer** [comment]
@lolodomo I think this should be fixed by all the latest refactorings - if you still see such problems, please re-open and provide logs!
