### ISSUE TITLE
Site icon is not displayed

### ISSUE THREAD

**Issue by marcolino7** [openhab/openhab-distro#308]
With openhab 1.X, in the browser, openhab icon is shown. This make faster to open the right TAB.

In OpenHab 2.X favicon.ico is not shown.

**Comment by lolodomo** [comment]
It is now OK for the dashboard and Basic UI but still missing for Paper UI and Classic UI.

**Comment by lolodomo** [comment]
It seems to be ok now for Paper UI.
Still missing for Classic UI.

**Comment by kaikreuzer** [comment]
> Still missing for Classic UI.

This has been added in distro 1025!
