### ISSUE TITLE
apt-get package repo unavailable

### ISSUE THREAD

**Issue by APajonk** [openhab/openhab-distro#309]
Hi guys,

it seems for me that the HowTo (http://docs.openhab.org/installation/linux.html) is not up to date anymore, is it?

Neither https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/ nor https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-online/target/apt-repo/ is available anymore.
![2016-10-26_19-49-04](https://cloud.githubusercontent.com/assets/16516509/19737841/5daf828c-9bb5-11e6-838c-c655f4e9da45.png)

**Comment by ThomDietrich** [comment]
Hello @APajonk,
neither the documentation nor the links are outdated. The reason for the problem you are describing is a simple server error. The last build of openHAB snapshots failed. This does not normally happen and will be resolved soon.

**Comment by APajonk** [comment]
There are still developers out there breaking the build? Bad bad world ;)

**Comment by ThomDietrich** [comment]
As far as I saw it it's not a commit responsible. Somebody else might provide more details.

**Comment by jameshiscott** [comment]
Its fixed

**Comment by isigmund** [comment]
I can confirm that - apt upgrade works as normal again

**Comment by APajonk** [comment]
Same here. apt-get works again as the howto document describes. It´s fixed.
