### ISSUE TITLE
online distro writes into user home directory

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#31]
When launching the online distro, it writes maven artefacts to ~/.m2/repository.
This should imho not happen - we should make sure that the runtime only writes to the userdata folder.

**Comment by dvanherbergen** [comment]
Any preference for a target location name? userdata/.m2?

**Comment by kaikreuzer** [comment]
Is the content required at all? If not, what about /dev/null? 8-)
I assume it is only a temporary cache when downloading the features from the remote repo. So maybe it should go under userdata/tmp/mvn? I would not use a hidden folder.

**Comment by dvanherbergen** [comment]
> what about /dev/null

If only that would work on windows...  I guess we could build an automatic clean of this directory into the start script.

userdata/tmp/mvn it is...
