### ISSUE TITLE
My.openhab.org not showing items

### ISSUE THREAD

**Issue by yp87** [openhab/openhab-distro#310]
Hello, 
I just enabled my.openhab.org service on latest OH2 build. Logs look fine. I can connect to paper ui from the cloud. 
Each time I update an item, I see logs for MyOpenHABClient like "Sending update..  for item..."  and I can see some ssl traffic between me and my.openhab.org in Wireshark at the same time. 
The problem is that there is nothing under the item list in my.openhab.org. 

Any idea? 

Thanks

**Comment by watou** [comment]
FTR: others are reporting same on the forum:

https://community.openhab.org/t/cant-get-items-to-show-up-in-my-openhab/15844

**Comment by yp87** [comment]
Thanks! Will Use The Rest Api Instead
