### ISSUE TITLE
On the topic of v2.0 GitHub projects 

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-distro#311]
@kaikreuzer I was disappointed to see the course Github went with the new projects tab... Now that changed. 
https://github.com/blog/2272-introducing-projects-for-organizations
openHAB needs this :)

**Comment by kaikreuzer** [comment]
That's just what we need indeed! Now I only have to figure out how to add issues from other repos to the existing project...

**Comment by ThomDietrich** [comment]
I think it's the other way around. You'll need to create a new organization wide project:

![2016-10-31 17_34_10-projects tuisse](https://cloud.githubusercontent.com/assets/2870104/19862376/498358e0-9f90-11e6-87ec-de5a1f09013b.png)

**Comment by kaikreuzer** [comment]
Ok, cool, so now I have created https://github.com/orgs/openhab/projects/1 - all maintainers should be able to add stuff there, so please feel free to add relevant tasks for the documentation as well.

**Comment by ThomDietrich** [comment]
Wonderful. Probably a good time to add a few people to the organization ;) I for one am currently not able to access the projects tab...

**Comment by kaikreuzer** [comment]
Ok - I have started a new team for the maintainers that need to collaborate for such projects, see https://github.com/orgs/openhab/teams/maintainers. You are part of it, so let me know, if this gives you access to the 2.0 project now!

**Comment by ThomDietrich** [comment]
It does. Thank you! I'll add my ideas shortly
