### ISSUE TITLE
Integration of the  Automatic Certificate Management Environment (ACME) protocol

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#312]
Integration of  the Automatic Certificate Management Environment protocol. ACME is a protocol that a certificate authority (CA) and an applicant can use to automate the process of verification and certificate issuance. By integrating this protocol in openHAB's core, we can step away from self-signed X.509 certificates and instead use valid and verified certificates from a provider such as Let's Encrypt. This integration should also implement an http servlet that can handle the verification challenge procedure of Let's Encrypt so that no end-user involvement is necessary for the renewal of certificates.

By stepping away from self-signed certificates we will have a better integration with third-party service providers like ifttt.com. The ACME integration can also be linked into the Authentication efforts at the core of ESH (https://github.com/eclipse/smarthome/issues/579, https://github.com/eclipse/smarthome/pull/2359) so that a Basic Authentication over HTTPS can be done without the need for a reverse proxy as described in http://docs.openhab.org/configuration/nginx.html

I have never been involved with the Jetty part of OH, but as far as I can see this sits in the openhab-distro repo, hence the reason for positing this issue here. Just let me know if the proposed solution should be put elsewhere (ESH core?).

And yes, I volunteer to provide an initial implementation of this integration ;-)

**Comment by kaikreuzer** [comment]
I do not see exactly what use cases you have in mind here; what will be better than with self-signed certificates? Does Let's Encrypt allow certificates for local domains like "openhab.local" or for DynDNS services like openhab123.dyndns.org? If not, I don't see any benefit.

**Comment by watou** [comment]
I think the reason is [here](https://letsencrypt.org/getting-started/):

> If your hosting provider doesn’t want to integrate Let’s Encrypt, but does support uploading custom certificates, you can install Certbot on your own computer and use it in manual mode. In manual mode, you upload a specific file to your website to prove your control. Certbot will then retrieve a certificate that you can upload to your hosting provider. We don’t recommend this option because it is time-consuming and **you will need to repeat it several times per year as your certificate expires**.

**Comment by ThomDietrich** [comment]
Local domains are of course not supported but dynamic dns providers are with some exceptions.

I'm not sure if this really needs to be part of openHAB itself... 
This will only really be interesting to users with their own domain. These can install certbot and will have a Let's Encrypt certificate after executing one command, including a cronjob for automatic renewal of the certificate. @kgoderis why do you want to implement this process in openHAB rather than utilizing certbot/similar exiting software? The only reason I can think of is the wish to install the certificate in openHAB as a last step automatically...

Fun fact: A Let's Encrypt certificate creation is part of openHABian since Tuesday :smiley: [commit 0168b19](https://github.com/ThomDietrich/openhabian/commit/0168b19f331732bff7e02394e5ca8aaaa1f7f770) and following

**Comment by kgoderis** [comment]
1. Compatibility with web services that do not support self-signed certificates. For example. ifttt.com
2. Remove requirement to use nginx or other reverse proxy, just to respond to the http challenges of letsencrypt
3. Remove requirement to run certbot in a cron job for certificate renewal
4. Automatically integrate the let's ecrypt certificate in the OH keystore without any having to issue a bunch of commands on the command line
5. world+dog is moving away from self-signed certificates. ACME is good practice for any server

I would make it a configurable switch so that those without a domain name can still revert back to a self-signed certificate.

**Comment by BClark09** [comment]
> dynamic dns providers are with some exceptions.

To be more specific, any suffix that is on the [public suffix list](https://publicsuffix.org/list/), including dyndns.org

**Comment by kaikreuzer** [comment]
> Compatibility with web services that do not support self-signed certificates. For example. ifttt.com

Hm, isn't that only relevant if you have your own IFTTT channel? How many people have that?

I wonder if it is really worth the hassle trying to squeeze this in Karaf / Pax-Web / Jetty in Java. The much easier approach is probably what @ThomDietrich did in https://github.com/ThomDietrich/openhabian/commit/0168b19f331732bff7e02394e5ca8aaaa1f7f770...
But it is up to you; if you want to implement that, have a try, but I would say that it should definitely be only an optional (Karaf) feature and not tied deeply into the distro.

**Comment by ThomDietrich** [comment]
> ... self-signed ...

I would argue that a self-signed certificate should not be used at all if any static DNS name is available.

The steps in openHABian were actually contributed by @BClark09. It's a great step for openHABian but I have to agree that getting rid of the additional proxy layer should be a goal. Having nginx for auth and ssl will never be more than a hack...

@kgoderis All points you are making are fair and with no doubt it would be a nice addition to have the automation. My first thought was actually that this sounds like a lot of work with many possible tripwires for only a fraction of openHAB users.
I have no practical experience with "Karaf / Pax-Web / Jetty in Java" related coding. Do you think the described task will be easy? Is a project to integrate ACME in this environment already available? Would your implementation be such a more general solution (mostly) independent from openHAB?

**Comment by kgoderis** [comment]
> Hm, isn't that only relevant if you have your own IFTTT channel?

The Maker channel is a nice example here

> if you want to implement that, have a try, but I would say that it should definitely be only an optional (Karaf) feature and not tied deeply into the distro.

At first  sight I only need to adjust the Jetty specific code signing bundle that currently creates the X.509 certificate. There is a java lib for the ACME stuff, and then only a servlet for the challenge handling needs to be registered on /.well-known/acme-challenge/

**Comment by hakan42** [comment]
> Having nginx for auth and ssl will never be more than a hack...

Actually, I beg to differ. Having an nginx on a properly hardened border machine allows me to use my openhab from the internet and integrate it with external services. Without exposing my poor Raspberry to the big bad internet 😄 

On the other hand, this might be my Unix upbringing 😈

**Comment by kaikreuzer** [comment]
I personally also like the idea to have nginx be the only gate from the Internet and have Jetty not directly exposed. But of course, it makes the infrastructure setup more difficult...

**Comment by kgoderis** [comment]
Side note @kaikreuzer I do not remember if you run OH on a Mac OS X Server instance, but already tried to replace nginx with the custom apache reverse-proxy that is part of Server? 

I understand the value of nginx (I also run it), but I also feel that OH(2) should be able to run stand-alone without any dependency, let alone that sometimes one wants to tie this into existing infrastructure (sometimes managed by others etc)

Will give it a try when I find the time

**Comment by marziman** [comment]
@kgoderis,
you can soon integrate with IFTTT by own myopenhab and your own maker Channel
Your approach with ACME makes sense..but of course we need to look for the usecases.

I agree with @hakan42 that we should have multiple layers of security ...defense in depths.

**Comment by kgoderis** [comment]
@marziman I have direct connections between IFTTT and my openhab instance without using my.openhab, effectively using the Maker Channel doing REST calls on the OH server

**Comment by kgoderis** [comment]
See https://github.com/openhab/openhab-core/pull/92

**Comment by kgoderis** [comment]
Can anyone with an interest in this topic have a look at https://github.com/openhab/openhab-core/pull/92 ?

**Comment by kaikreuzer** [comment]
Or by now better have a look at https://github.com/eclipse/smarthome/issues/4088 :-)
