### ISSUE TITLE
Configuration changes must not be written in runtime folder, but to userdata

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#315]
Configuration changes done through UIs or console are written by Karaf to runtime/karaf/etc.
This causes the configuration being lost on updates, since we replace the complete runtime folder in that case.

I would expect the ConfigAdmin changes to be stored somewhere under userdata.
Unfortunately, I couldn't yet figure out, how to do this, [see also here](http://karaf.922171.n3.nabble.com/felix-fileinstall-enableConfigSave-false-ignored-tp4047867p4048570.html).
@maggu2810 @dvanherbergen @cschneider Any helpful suggestions are more than welcome!

**Comment by hakan42** [comment]
This appllies to the log file configuration with issue #225 too.

**Comment by kaikreuzer** [comment]
Yep, that's what I hope to resolve with it as well.

**Comment by splatch** [comment]
An note here about loosing updates - if configuration is created externally you can specify "felix.fileinstall.filename" property to cause file creation in given path. By this way you can controll where it will be stored depending on ownership or domain it belongs.

**Comment by kaikreuzer** [comment]
> if configuration is created externally you can specify felix.fileinstall.filename property

Right, this is what also has been discussed [here](http://karaf.922171.n3.nabble.com/felix-fileinstall-enableConfigSave-false-ignored-tp4047867p4048570.html). But this is imho no option as we do not have under control who creates configs (and we must not force ESH bundles to care about felix fileinstall in any way).
