### ISSUE TITLE
Content of 'deb' not in sync with recent changes

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-distro#321]
Related to https://community.openhab.org/t/oh2-upgrade-of-today/15560/16

The file `addons.cfg` is available two times:

[distributions/distribution-resources/src/main/resources/conf/services/addons.cfg](https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/conf/services/addons.cfg)
[distributions/distribution-resources/src/main/resources/deb/conf/services/addons.cfg](https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/deb/conf/services/addons.cfg)

As can be seen, the deb file is behind latest changes. @theoweiss probably more files are affected. Does there have to be a duplicate? This might be related to https://github.com/openhab/openhab-distro/issues/298 which would worsen the situation...

**Comment by BClark09** [comment]
I think this issue can be closed now thanks to #326,  There doesnt look like there are any deb alternatives now.

**Comment by ThomDietrich** [comment]
Agreed.
