### ISSUE TITLE
Service Start/Stop for Debian (Ubuntu 14.04) stores wrong pid number

### ISSUE THREAD

**Issue by NickWaterton** [openhab/openhab-distro#328]
This may be related to issue #327 I have found that the pid stored in /var/run/openhab2.pid is incorrect when starting openhab2 as a service (sudo service openhab2 start). This means you can start more than one instance of openhab2 (which makes it hang), and you can't stop openhab2 in the usual way (sudo service openhab2 stop). This is probably what is happening in issue #327 

I believe this is because openhab2 isn't started directly by start-stop-daemon, but is started by a series of wrapper scripts. The pid stored is probably one of the wrapper scripts (which forks and exits).

Usually you would update the pid from one of the wrapper scripts, but because the user changes to openhab:openhab, the scripts don't have permission to update /var/run/openhab2.pid.

Either the pid file needs to be moved, (to /var/run/openhab2/openhab2.pid for example - so that the ownership can be assigned to openhab) and updated by the actual scripts starting the openhab2 java executable, or a mechanism within /etc/init.d/openhab2 needs to be implemented to update the /var/run/openhab2.pid file with the actual pid of the java main process.

I implemented a quick and dirty version of the latter using pidof to get the real pid into /var/run/openhab2.pid as an immediate solution, but there are probably much better solutions out there.

**Comment by dkw99** [comment]
Can you please post your fix. cheers

**Comment by BClark09** [comment]
Hi @NickWaterton, I'm looking into this now but I can't replicate not being able to use `sudo service openhab2 stop` this stops the service as expected. I've worked around being able to start two instances by including a lookup of any openhab instance and updating the PID with the correct one on first failed attempt to start.

@NickWaterton, @dkw99 how does it run if you were to replace /etc/init.d/openhab2 with: https://github.com/BClark09/openhab-linuxpkg/blob/pid-fix/resources/deb/etc/init.d/openhab2

**Comment by NickWaterton** [comment]
I found that sometimes it works, sometimes not. This is what I see:

```
nick@proliant:/var/log/openhab2$ sudo service openhab2 stop
 * Stopping openHAB2 server openhab2                                                                                                  stop: Ignoring predefined value for KARAF_HOME
                                                                                                                               [ OK ]
nick@proliant:/var/log/openhab2$ ps aux | grep openhab
openhab   8968  0.0  0.0   4448  1696 ?        S    07:29   0:00 /bin/sh /usr/share/openhab2/runtime/bin/karaf server
openhab   9053 11.3 12.3 5381288 746524 ?      Sl   07:29   4:34 /usr/lib/jvm/java-8-oracle/jre/bin/java -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/etc/openhab2 -Dopenhab.runtime=/usr/share/openhab2/runtime -Dopenhab.userdata=/var/lib/openhab2 -Dopenhab.logdir=/var/log/openhab2 -Dfelix.cm.dir=/var/lib/openhab2/config -Dorg.osgi.service.http.port=8009 -Dorg.osgi.service.http.port.secure=8443 -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/etc/openhab2 -Dopenhab.runtime=/usr/share/openhab2/runtime -Dopenhab.userdata=/var/lib/openhab2 -Dopenhab.logdir=/var/log/openhab2 -Dfelix.cm.dir=/var/lib/openhab2/config -Dorg.osgi.service.http.port=8009 -Dorg.osgi.service.http.port.secure=8443 -Djava.awt.headless=true -XX:+UseG1GC -Djava.awt.headless=true -XX:+UseG1GC -Djava.endorsed.dirs=/usr/lib/jvm/java-8-oracle/jre/jre/lib/endorsed:/usr/lib/jvm/java-8-oracle/jre/lib/endorsed:/usr/share/openhab2/runtime/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-oracle/jre/jre/lib/ext:/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/share/openhab2/runtime/lib/ext -Dkaraf.instances=/usr/share/openhab2/runtime/instances -Dkaraf.home=/usr/share/openhab2/runtime -Dkaraf.base=/var/lib/openhab2 -Dkaraf.data=/var/lib/openhab2 -Dkaraf.etc=/var/lib/openhab2/etc -Dkaraf.restart.jvm.supported=true -Djava.io.tmpdir=/var/lib/openhab2/tmp -Djava.util.logging.config.file=/var/lib/openhab2/etc/java.util.logging.properties -Dkaraf.startLocalConsole=false -Dkaraf.startRemoteShell=true -classpath /usr/share/openhab2/runtime/lib/boot/org.apache.karaf.diagnostic.boot-4.0.4.jar:/usr/share/openhab2/runtime/lib/boot/org.apache.karaf.jaas.boot-4.0.4.jar:/usr/share/openhab2/runtime/lib/boot/org.apache.karaf.main-4.0.4.jar:/usr/share/openhab2/runtime/lib/boot/org.osgi.core-6.0.0.jar org.apache.karaf.main.Main
nick     11861  0.0  0.0  11748  2272 pts/2    S+   08:09   0:00 grep --color=auto openhab

```

your fix looks similar to mine, I'll give it a go.

**Comment by BClark09** [comment]
Note that if you stop the service then openhab will shutdown safely. This means that for a little while, (up to 15 seconds I think) there will still be a process. My changes to init.d use `pgrep java -G openhab` to obtain and update the PID file. 

Also note that this only effects Ubuntu <15.* since systemd configurations won't generate a PID file, and uses a smarter daemon configuration that ensures only one process is running regardless of how many times you use try to start it.

**Comment by NickWaterton** [comment]
I have waited for more than 15 seconds though, and it does not stop....

**Comment by BClark09** [comment]
Fair enough, let me know how you get on with my version of the init.d script. If you're still having trouble let me know the OH version you're using and I see if I can replicate it.

**Comment by BClark09** [comment]
The new debian builds on Bintray should calculate the correct PID numbers and report them when trying to start a second instance. @NickWaterton if your issues persist, please could you make a new issue over at https://github.com/openhab/openhab-linuxpkg/issues/

@kaikreuzer. could you close this issue please?
