### ISSUE TITLE
Update branding.properties on distro upgrade

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#331]
See https://community.openhab.org/t/new-folder-structure/16526/55

**Comment by xsnrg** [comment]
@kaikreuzer it seems this should be part of the runtime, not the user data that should survive an upgrade, correct?

**Comment by kaikreuzer** [comment]
Yes, this is where the etc folder was before the folder layout change. But if we move it back, we would need to reference it (and I don't think this is possible). So I rather tend to include it in a bundle.

**Comment by ThomDietrich** [comment]
Without technical background: Shouldn't the branding.properties be a static file and the version number included from somewhere else? I am parsing the properties file to get the build number - feels wrong...

**Comment by kaikreuzer** [comment]
@ThomDietrich Well, this is how Karaf branding works. It is not possible to construct it dynamically at runtime.

I tried many different solutions for this problem and eventually came up with https://github.com/openhab/openhab-distro/pull/345.
This allows us to write files at a first start after an upgrade to the userdata folder, so if necessary, we can upgrade Karaf-specific files in that folder (that users anyhow are not supposed to touch).

**Comment by ThomDietrich** [comment]
Understood. In this case the old solution is acceptable. :+1:
