### ISSUE TITLE
JS and XSLT Transforms Unavailable at Startup, Becomes Available Later

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-distro#333]
Posting this here at the advice of @watou. Please let me know if this needs to go to ESH instead.

The relevant forum thread is:

https://community.openhab.org/t/js-transformation-service-starts-too-late-when-openhab-startup/17025/5

When openHAB first starts up just after loading all the configuration files the following warning appears for every Item that uses a given transform.

```
2016-11-22 11:08:49.953 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type XSLT
2016-11-22 11:08:49.953 [WARN ] [ab.binding.http.internal.HttpBinding] - couldn't transform response because transformationService of type 'XSLT' is unavailable
```

The Items associated with that error get populated with the raw untransformed text:

![image](https://cloud.githubusercontent.com/assets/6385096/20536194/67f3dbf8-b0a5-11e6-9b42-19c74dc0d155.png)

However, upon the next refresh of the data everything works fine.

![image](https://cloud.githubusercontent.com/assets/6385096/20536223/8095edf4-b0a5-11e6-8f4f-021e3152305b.png)

I think I've also seen this behavior with MapDB once but I no longer have those logs to confirm it was the same error.

**Comment by kaikreuzer** [comment]
I didn't yet test it myself, but I would hope that https://github.com/openhab/openhab-core/pull/89 fixes the issue. Please test tomorrows build and let me know!

**Comment by kaikreuzer** [comment]
Hm, I am not sure if my fix really solved the issue. Setting a start level on a Karaf feature does not seem to have much effect - the bundles still show the default start-level (80)...

**Comment by rkoshak** [comment]
I just pulled the latest and cleared out my userdata/cache and userdata/tmp to force everything to upgrade (Docker requires some extra steps to get the latest-addons).

Once it finished reinstalling everything (and updating addons.cfg to append the 1 for the 1.9 bindings) I am no longer receiving the error. However, the Items I have that use these transforms do not appear to be updating. I'll continue to investigate and report back when I can confirm whether the change actually has fixed this problem for me despite the start level doesn't appear to have an effect on your end.

**Comment by rkoshak** [comment]
Update:

I am not seeing the errors during startup. I am now seeing the transformation throwing errors though. I'm using XSLT. I might swap over to JSONPATH and see if that changes things.

The exception is not clear enough for me to figure out what is going on (e.g. has wunderground changed their XML?). But that is a problem for another issue I think. My system startup is now free of the unknown transformation errors.

**Comment by rkoshak** [comment]
It appears the issue is back. I updated to the latest snapshot and the behavior has returned. :-(

**Comment by maggu2810** [comment]
@rkoshak As @kaikreuzer already stated it could be solved by changing the start level of the transformation bundles. I assume if you change it for the transformation bundles once using the resp. command the issue does not occur until you update again.

**Comment by kaikreuzer** [comment]
>  it could be solved by changing the start level of the transformation bundles.

To avoid having to ask all users to do that manually, I would suggest to define this within the ESH feature after all.
