### ISSUE TITLE
Wrong links in conf/*/readme.txt files.

### ISSUE THREAD

**Issue by slawekjaranowski** [openhab/openhab-distro#338]
Most of conf/*/readme.txt files have wrong links to documentation.

What should be corrected readme.txt file or documentation site?

https://github.com/openhab/openhab-distro/search?q=filename%3Areadme.txt+docs.openhab.org&type=Code&utf8=%E2%9C%93

**Comment by kaikreuzer** [comment]
They are not necessarily wrong, the pages in the documentation are just lacking...
@ThomDietrich and @rkoshak are working on it!

**Comment by slawekjaranowski** [comment]
Some page exists in different localization:

eg. in readme:
http://docs.openhab.org/configuration/items.html

and existing page:
http://docs.openhab.org/features/items.html

If somebody working on it and has this on mind we can close this issue.

**Comment by ThomDietrich** [comment]
Working on it. This was not intended but will be solved soon.
Can be closed.
