### ISSUE TITLE
Sitemap elements of same item with explicit icon set and visibility condition does not update icon

### ISSUE THREAD

**Issue by bdleedy** [openhab/openhab-distro#343]
I'm not sure if this is a feature or not. I checked the OH 2 documentation and it didn't specifically state either way.

.items
`Switch	GDoorButton		"Garage door"								(gGarage)	{ mqtt=">mosquitto:garage/openclose:command:*:default]" }`

.sitemap
`Switch item=GDoorButton label="Garage Door" icon="garagedoor-closed" mappings=[ON=Open] visibility=[GDoor=="CLOSED"]
Switch item=GDoorButton label="Garage Door" icon="garagedoor" mappings=[ON=Reverse] visibility=[GDoor=="OPENING",GDoor=="CLOSING"]
Switch item=GDoorButton label="Garage Door" icon="garagedoor-open" mappings=[ON=Close] visibility=[GDoor=="OPEN"]`

(I do this to provide a half open indicator using the default icon) This does work for me in all ways (mappings and labels change based on visibility) except for the icon. It does actually work in Internet Explorer with the Basic UI but not in any other browser or UI or on iOS. Is this an issue or is this expected behavior because of the new handling of dynamic icons?

**Comment by ThomDietrich** [comment]
Your goal is unclear. You are using the dynamic icons in the wrong/not intended way. Could you please ask the same question at https://community.openhab.org ?
@kaikreuzer I think this can be closed.

**Comment by bdleedy** [comment]
I don't understand how this isn't an issue. In a sitemap, does icon= only work with the base icon and not a specific file?? (Dynamic vs static) Is dynamic virtually forced? Why does it work in one browser/UI?

I think my goal is very clear. I set the mapping of a switch based on visibility parameters. I'd like the icon to be explicitly set based on the visibility.

**Comment by ThomDietrich** [comment]
Hey @bdleedy your description was slightly unclear (partly because you didn't use code fences).
Dynamic icons are "virtually enforced" as you said, that's correct. The following:
```java
icon="iconname-state"
```
is not parsed as you might think. The later part is cut off and "iconname.svg/.png" will be shown.

Is garagedoor a String item? Please try the following:
```
Switch item=GDoorButton label="Garage Door" icon="garagedoor" mappings=[ON=Open] visibility=[GDoor=="closed"]
Switch item=GDoorButton label="Garage Door" icon="garagedoor" mappings=[ON=Reverse] visibility=[GDoor=="opening",GDoor=="closing"]
Switch item=GDoorButton label="Garage Door" icon="garagedoor" mappings=[ON=Close] visibility=[GDoor=="open"]
```
with the three files (svg or png):
```
garagedoor.svg
garagedoor-open.svg
garagedoor-closed.svg
```

I realize that the process is not really intuitive and needs to be improved and clearer documented. Let me know if you make any progress.
