### ISSUE TITLE
REST API UI in standard package ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#349]
I am asking myself whether it makes sense to install the REST API UI by default (with the standard package). No normal user will need or use it.
We keep ithis UI while the Classic UI was suppressed while very useful (due to all bugs still remaining in Basic UI) for all users.

**Comment by kaikreuzer** [comment]
I'm ok to remove it from the standard package. Created https://github.com/openhab/openhab-core/pull/93.
