### ISSUE TITLE
Unexpected problem updating configuration org.eclipse.smarthome.folder java.lang.NullPointerException

### ISSUE THREAD

**Issue by kceiw** [openhab/openhab-distro#350]
Hi,
When I start OpenHAB 2.0 beta 4, I received this error at the beginning:

> 6:26:15.293 [ERROR] [org.apache.felix.configadmin        ] - 
> [org.osgi.service.cm.ManagedService, id=198, bundle=116/mvn:org.eclipse.smarthome.model/org.eclipse.smarthome.model.core/0.9.0.b1]: Unexpected problem updating configuration org.eclipse.smarthome.folder
> java.lang.NullPointerException
>         at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)[:1.8.0_102]
>         at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)[:1.8.0_102]
>         at org.eclipse.smarthome.model.item.internal.GenericItemProvider.createItemFromModelItem(GenericItemProvider.java:204)[117:org.eclipse.smarthome.model.item:0.9.0.b1]
>         at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:165)[117:org.eclipse.smarthome.model.item:0.9.0.b1]
>         at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:338)[117:org.eclipse.smarthome.model.item:0.9.0.b1]
>         at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:210)[116:org.eclipse.smarthome.model.core:0.9.0.b1]
>         at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:103)[116:org.eclipse.smarthome.model.core:0.9.0.b1]
>         at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:267)[116:org.eclipse.smarthome.model.core:0.9.0.b1]
>         at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:195)[116:org.eclipse.smarthome.model.core:0.9.0.b1]
>         at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:176)[116:org.eclipse.smarthome.model.core:0.9.0.b1]
>         at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
>         at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]

And I also notice that the OpenHAB doesn't pick up changes in my conf/items, conf/sitemaps, conf/rules on the fly and I have to restart it to refresh the change.
I can tell that the OpenHAB used to be able to pick up the changes because it prints some information in the log but I don't see it any more.

There's a similar issue #124 but the call stack is different.

**Comment by kaikreuzer** [comment]
Could you please check whether this still exists on the [current snapshot](https://openhab.ci.cloudbees.com/job/openHAB-Distribution/) and if so, please enter the issue at https://github.com/eclipse/smarthome/issues as all stacktrace is about org.eclipse.smarthome code. Thanks!
