### ISSUE TITLE
Paper UI Extensions vs Add-ons

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-distro#352]
To bring everything in line I want to suggest to rename the "Extensions" menu entry in Paper UI to "Add-ons". I seem to remember that bundles (Bindings, Actions,...) are called Extensions in ESH but Add-ons in OH. That's why I'm opening an issue here.

**Comment by kaikreuzer** [comment]
Yes, I planned that as well. Unfortunately, the Paper UI currently lacks a customization possibility for this. Will see what I can do.

**Comment by ThomDietrich** [comment]
Seems like this can be moved forward :+1:

**Comment by ThomDietrich** [comment]
Nice to see this implemented! Thanks @aounhaider1

**Comment by kaikreuzer** [comment]
I'll do an ESH stable this weekend, so that this becomes available to openHAB soon.

**Comment by kaikreuzer** [comment]
FYI: Latest distro not has "Add-ons" in the menu!
