### ISSUE TITLE
Feature in double for Eclipse SmartHome bindings ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#353]
For all Eclipse SmartHome bindings, I can see 2 features listed. For example, for my running NTP binding:
```
openhab> feature:list | grep ntp
esh-binding-ntp                           | 0.9.0.SNAPSHOT   |          | Started     | openhab-features                     |
openhab-binding-ntp                       | 0.9.0.SNAPSHOT   | x        | Started     | openhab-features                     | NTP Binding
```
Is it expected ? If it is, what is the reason ?

**Comment by kaikreuzer** [comment]
You can ignore all "esh" features - all that is needed by the distro is wrapped into features that are "openhab-" prefixed, see https://github.com/openhab/openhab-core/blob/master/features/openhab-esh-addons/src/main/feature/feature.xml

**Comment by kaikreuzer** [comment]
@maggu2810 I was already considering to add `hidden=true` to the ESH features. If we assume that any ESH-solution wraps the ESH-features in their own feature definitions, this would dramatically reduce the list when doing a `feature:list` and it might also prevent problems, if users start to play around with such features. Wdyt?

**Comment by maggu2810** [comment]
> If we assume that any ESH-solution wraps the ESH-features in their own feature definitions

But that assumption is wrong 😉 
This will beak all other consumer of the ESH features.
Also your idea about using a KAR (you remember your reply to my "smarthome sample packaging karaf" mail) will then only contain hidden features.

**Comment by kaikreuzer** [comment]
Well, the ESH features are very fine-grained and not really addressing users, but addressing solution developers. So hiding these internals (the used framework) from the end user seems to be the right approach to me. Note that the features are still available to install/uninstall through the console, they only wouldn't be listed anymore.

I do not see a contradiction to the sample Karaf distro idea: This could simply define a solution-feature that wraps all required ESH-features and install that feature on Karaf. This would actually nicely fit into this idea.
