### ISSUE TITLE
APT-GET Installation Resets Startup Configuration

### ISSUE THREAD

**Issue by NolanGarrett** [openhab/openhab-distro#362]
Perhaps this is by design, however, if you install openhab2-online via apt-get on Ubuntu, then disable on-boot startup of OH2 via systemctl disable openhab2, the next time you upgrade your package via apt-get openhab2 will again be set to start on boot (and will even be started at the end of the upgrade process). Tested on Ubuntu 16.04.1 LTS.

**Comment by ThomDietrich** [comment]
Thanks for reporting this bug.
The apt repository deb package is currently outsourced to https://github.com/openhab/openhab-linuxpkg by @theoweiss and @BClark09 - Ping ;)

**Comment by theoweiss** [comment]
@NolanGarrett could you please recreate this issue in openhab-linuxpkg. 
Thanks @ThomDietrich for the ping.

**Comment by NolanGarrett** [comment]
Closing per the request of @theoweiss and moving to the openhab-linuxpkg project.
