### ISSUE TITLE
FreeBSD / Unix Compatibility Issue

### ISSUE THREAD

**Issue by kmcbride3** [openhab/openhab-distro#365]
With the latest snapshot (#363), I was having troubles getting OH2 to start under FreeBSD. I had to modify the start.sh script to include a definition for JAVA_HOME -- which is fine, but even after that, I would get an error; `exec: ./runtime/bin/karaf : not found` -- which had me stumped for a while, until I looked at the contents of karaf...

Looks like it's using a Linux-specific heading of #!/bin/bash where it should be the generic #!/bin/sh. Making that change, I was able to successfully launch OH2. Might want to double check the rest of the script files included with future distros to ensure compatibility across a wider UNIX install base.

**Comment by kaikreuzer** [comment]
We are using the unmodified files from Karaf here.
It therefore probably would make sense if you would report the issue at https://issues.apache.org/jira/browse/KARAF/. If you do so, please leave a link here for future tracking, thanks!

**Comment by esdeboer** [comment]
I ran into the same issue and created an issue for it: https://issues.apache.org/jira/browse/KARAF-4975
Also created an issue to check the correct setting of JAVA_HOME, as that took me a while to figure out as cause of not creating https connections:  https://issues.apache.org/jira/browse/KARAF-4976

**Comment by esdeboer** [comment]
Karaf fixed the issue in the new release 4.0.9 (Should be released soon)

**Comment by kaikreuzer** [comment]
But unfortunately not in 4.1.0, which has just been released (and which I intended to upgrade to next...)

**Comment by esdeboer** [comment]
Actually I read it wrong, it has been fixed in 4.1.0, they want to backport it to 4.0.9

**Comment by kaikreuzer** [comment]
Ah, indeed, because KARAF-4975 is actually a duplicate of https://issues.apache.org/jira/browse/KARAF-4852, which has been fixed on 4.1.0. Even better :-)

**Comment by wborn** [comment]
@kmcbride3, @esdeboer 
Did you already try openHAB 2.2.0 (Karaf 4.1.3) to see if this issue is fixed?
In openHAB 2.3.0-SNAPSHOT Karaf 4.1.5 is used.

**Comment by kmcbride3** [comment]
Yes, when I upgraded to OpenHAB 2.2.0, I didn't have to modify /runtime/bin/karaf at all. Closing issue, thanks.

**Comment by wborn** [comment]
Thanks for confirming it's fixed @kmcbride3! :slightly_smiling_face:
