### ISSUE TITLE
/var/lib/openhab2/tmp folder is missing when doing an apt install/upgrade

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#366]
The openHAB distro contains the folder userdata/tmp, which contains a file README.
This seems to be lacking when doing the install through apt, see [these reports](https://community.openhab.org/t/oh2-not-starting-upgrade-20170101125906/19239), which causes Karaf to not start correctly.

**Comment by kaikreuzer** [comment]
@theoweiss & @BClark09 Could you please have a look?

**Comment by BClark09** [comment]
Will try to debug, karaf.data is to userdata and the debian package is aware that the tmp/README file exists, so I will assume that this is a permission error.

**Comment by BClark09** [comment]
@kaikreuzer, whilst I was unable to find out why the debian package is unable to recreate the folder. I have made the following PR as a workaround.
