### ISSUE TITLE
symbol lookup error after zwave configuration

### ISSUE THREAD

**Issue by DevUrandomFoo** [openhab/openhab-distro#368]
Hi,

after setup the zwave stick in latest snapshot (Build #693) openhab2 crashed with the following error:

/usr/bin/java: symbol lookup error: /root/openHAB2/userdata/tmp/libNRJavaSerial_HF_root_0/libNRJavaSerial_HF.so: undefined symbol: __fdelt_chk

What I did:

install openhab default (just unzip)
start it (start.sh)
select basic ui (expert ui with same problem)
install zwave addon / binding
add thing and configure the correct device ( /dev/ACM0 )
get error -1 when press save/add
see error on shell, openhab process died

In openhab 2.0.0 beta 5 zwave run stable.

I use a Z-Wave ZME_UZB1 Stick

BR,
Manuel

**Comment by DevUrandomFoo** [comment]
Same error in today build #694

**Comment by kaikreuzer** [comment]
@cdjackson Are there any other reports about problems with the current serial lib?

**Comment by DevUrandomFoo** [comment]
I already wrote to cdjackson (https://github.com/cdjackson/HABmin/issues/316)

###
Hi.
This isn't really anything to do with HABmin. I'd suggest raising a question on the OH forum - there have been some changes recently with the serial driver - the forum is the best place to discuss this though.

Cheers
Chris
###

**Comment by cdjackson** [comment]
I don't think there are other reports of errors other than the problems with the lock files that people have which I think caused you to revert the library version. This was why I suggested this was best discussed on the forum.

**Comment by kaikreuzer** [comment]
Ok, so I assume you have meanwhile discussed it on the forum? Feel free to post a link here to it.
