### ISSUE TITLE
Jenkis openhab-offline-2.0.0-SNAPSHOT.zip  old class files

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab-distro#371]
In the openhab-offline-2.0.0-SNAPSHOT.zip #696 the org.eclipse.smarthome.*.jar files have the current date, but the class files in the jar files are from 2016-12-22.

**Comment by kaikreuzer** [comment]
All fine, see https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB.
