### ISSUE TITLE
“Serial Error: Port /dev/ttyAMA0 does not exist”

### ISSUE THREAD

**Issue by carryonrewardless** [openhab/openhab-distro#373]
I think this is a nrjavaserial issue as per https://community.openhab.org/t/nrjavaserial-upgrade-causes-serial-error-port-dev-ttyacm0-does-not-exist/18783.
I am using a Debian Wheezy OS on a rPi2 and so my Razberry card is seen as /dev/ttyAMA0. The device has been shown to be working using z-way server and my OH2 installation ("online" from .zip file) has been working fine prior to upgrading with the "New Folder" changes around mid December.
I have "-Dgnu.io.rxtx.SerialPorts=/dev/tty/AMA0" in my setenv.
 From the above link I have tried the suggested solution with liblockdev1 / liblockdev1-dev but no success.
I have also tried 2.0.0b5 and both Online and Offline installs up to  and including Build #703 without success.
Log files attached. Thanks

[Openhab.log.docx](https://github.com/openhab/openhab-distro/files/693379/Openhab.log.docx)
[Events.log.docx](https://github.com/openhab/openhab-distro/files/693380/Events.log.docx)

**Comment by Fejitatete** [comment]
+1 here, since update from Build #694 to #703. But that concern the Zwave binding (/dev/ttyUSB0 not found). The MySensors binding still find the /dev/ttyS1 port.

Regards.

**Comment by carryonrewardless** [comment]
Does this come into it?
ls /dev/serial/by-id/
usb-FTDI_FT232R_USB_UART_A8008HU6-if00-port0
Maybe should be changed for the /dev/ttyAMA0 ?

**Comment by kaikreuzer** [comment]
Your log shows bundles from August 2016. It furthermore has many unrelated exceptions and I don't even see a problem with the serial lib in the log - this looks like a messed up installation.
As it works for most other people, I don't think there is a general bug, hence I suggest to first seek for further help in the forum.
