### ISSUE TITLE
Karaf missleading error message, Chromecast send command 

### ISSUE THREAD

**Issue by lejonpart** [openhab/openhab-distro#376]
Hi

I found this error message to be somewhat misleading, 

openhab> smarthome:send Projcast_Control Pause
Error: Command 'Pause' is not valid for item 'Projcast_Control'
_Valid command types are: ( PlayPauseType RewindFastforwardType NextPreviousType RefreshType )_

Why does is not say that Valid command types are PLAY PAUSE and so on ...?

openhab> smarthome:send Projcast_Control PAUSE
Command has been sent successfully.
openhab> smarthome:items
Projcast_Control (Type=PlayerItem, State=PLAY, Label=Control, Category=)

Regards
Lejonpart

**Comment by kaikreuzer** [comment]
These are "smarthome" commands, i.e. defined in ESH, so please report this issue at https://github.com/eclipse/smarthome/issues (and don't refer to Chromecast in the title, because it has nothing to do with that specifically).

**Comment by lejonpart** [comment]
Thanks kaikreuzer will do :)

/Lejonpart
