### ISSUE TITLE
project_loc:distro-resources issue

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-distro#377]
I pulled down the latest openhab-distro (replacing what I had) - when I go to run openHAB_Runtime - eclipse reports "Variable references non-existent resource: ${project_loc:distro-resources}".

I see where the variable should be pointing to but have no idea how to create it (or otherwise fix this issue).

**Comment by tmrobert8** [comment]
I see now.  The demo-resources project no longer exists and I needed to imported distro-resources (and distributions) project.

**Comment by kaikreuzer** [comment]
Correct :-)

This should actually also be done for you, if you run a Help->Perform Setup Tasks...
By this you can make sure that you always have all the latest projects imported in your workspace.
