### ISSUE TITLE
Paper UI Leaves empty categories in database resulting in no icons in UI's

### ISSUE THREAD

**Issue by eleson2** [openhab/openhab-distro#380]
Entering a category and then removing it results in a empty category field in the db.
That in turn leads to no icons in Classic and Basic UI's

Item sHallVitrin below lacks icon in UI's .
Removing the category line from the json files makes the icon appear in UI's. 

Icons should show up in the UI's.

```
  "sLivingRoomSideboardLamp": {
    "class": "org.eclipse.smarthome.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "AllLamps"
      ],
      "itemType": "Switch",
      "tags": [],
      "label": "lblsLivingRoomSideboardLamp"
    }
  },
  "sHallVitrin": {
    "class": "org.eclipse.smarthome.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "WindowLamps"
      ],
      "itemType": "Switch",
      "tags": [],
      "label": "VitrinSkap",
      "category": ""
    }
  },
```

**Comment by kaikreuzer** [comment]
Could you please enter this at https://github.com/eclipse/smarthome/issues as this is where the Paper UI lives? Thanks a lot!

**Comment by eleson2** [comment]
Hi Kai, sure I can re eenter it there.
But just to make sure, is it determined that the problem is in the Paper UI
and database, and not in the classic/Basic UI's?

Noone benefits if this case becomes a ping pong ball.
BR
Erland

**Comment by kaikreuzer** [comment]
It very much looks like the Paper UI to me. But even if it is Classic UI, Basic UI or the REST API - in all cases the ESH issue tracker is the right choice!

**Comment by eleson2** [comment]
tnx!
I could see later that the UI's are also part of smarthome. I assumed it
was part of OH.
