### ISSUE TITLE
userdata/log/

### ISSUE THREAD

**Issue by sipvoip** [openhab/openhab-distro#383]
Not sure if this is a bug, but should there be a empty userdata/log/ directory along with the userdata/logs/ directory? I see that if I delete it it is recreated, but nothing is ever stored in it.

**Comment by kaikreuzer** [comment]
No, there shouldn't. I know that MaryTTS creates such a folder (and writes stuff into it), but I also just noticed that the "normal" distro without many specific add-ons also creates it already.
If anybody knows, why this happens, please help fixing it!

**Comment by lolodomo** [comment]
This issue can probably be closed. The "log" directory is no more created with snapshot 1034. The problem probably disappeared when introducing the new karaf version in OH ?

**Comment by kaikreuzer** [comment]
Correct, I fixed with together with the Karaf 4.1.2 upgrade.
