### ISSUE TITLE
" org.apache.karaf.jaas.cfg" has space at front of filename

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-distro#385]
This caught me off guard when trying to change the conf files. Is this supposed to be like this?

**Comment by ThomDietrich** [comment]
No. Saw that too, forgot to report it. 🙈

**Comment by BClark09** [comment]
Right, there's two versions of the file with different content. (MD5 vs SHA-256)

https://github.com/openhab/openhab-distro/pull/379/files is the culprit.
