### ISSUE TITLE
First OH startup: you don't get addons you specify in addons.cfg

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#392]
After the first startup of openHAB, you don't have installed UIs that you defined in your addons.cfg file.
My addons.cfg file contains this:
```
package = standard
remote = false
ui = paper,basic,classic
```
After the first startup and after waiting a certain amount of time, HABpanel was installed and Classic UI was not, which is not what I requested.
Note that after a restart of openHAB, then HABpanel is uninstalled and Classic UI is installed.

Just after the first startup, I can see another strange thing, in Paper UI, "Access Remote Repository" is ON while I asked it to be OFF in addons.cfg. One time again, restarting openHAB solved this issue.

**Comment by kaikreuzer** [comment]
With https://github.com/openhab/openhab-distro/pull/395, I have improved the description.
If you specify specifically, what you want to install, you must not choose a package other than "minimal" at the same time as this can lead to contradictions and to the results that you are seeing.

**Comment by lolodomo** [comment]
And what about the remote setting ?

**Comment by kaikreuzer** [comment]
Same effect: If you choose `package=minimal`, it will be taken into account, all others go for the defaults on a first startup. I agree, not ideal, but I wouldn't know how to change this behavior easily 😞

**Comment by lolodomo** [comment]
I tried again and that is OK for UIs but unfortunately still not OK for the access remote repository setting. A restart is required for that.
