### ISSUE TITLE
Wrong average of Group:Number:AVG

### ISSUE THREAD

**Issue by DimitrisSar** [openhab/openhab-distro#393]
Maybe this is a bug...

The value of certain Group functions (MIN, MAX, AVG, SUM) is calculated incorrectly when using items with percentages.

Please see: https://community.openhab.org/t/wrong-average-of-group-number-avg-with-dpt-knx-5-001/20529

**Comment by kaikreuzer** [comment]
The code for the group functions is maintained at ESH, so may I ask you to enter the issue at https://github.com/eclipse/smarthome/issues? Thanks!
