### ISSUE TITLE
cannot change port number via /etc/default/openhab2

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-distro#394]
Changing the port number for http and https via /etc/default/openhab2 does not work.

The user can set the values like this:
`OPENHAB_HTTP_PORT=9090
OPENHAB_HTTPS_PORT=9091`

but the variables are empty inside /usr/share/openhab2/runtime/bin/setenv.

Reproduced on Raspbian Wheezy.

see: https://community.openhab.org/t/changing-port-number-on-openhab-2-0/2300/42

**Comment by kaikreuzer** [comment]
As mentioned [here](https://community.openhab.org/t/changing-port-number-on-openhab-2-0/2300/34?u=kai) already, this feature works for the distro in general.

You might thus want to file an issue against the apt package at https://github.com/openhab/openhab-linuxpkg/issues
