### ISSUE TITLE
Karaf console problems after key format change

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-distro#399]
The key format change I introduced here https://github.com/openhab/openhab-distro/pull/384 had two unexpected side effects I didn't catch.

1. [Password prompt](https://community.openhab.org/t/unable-to-access-karaf-console-on-rpi-with-openhabian/20737) when using the client script instead of going the SSH path.

2. Everything is working fine but an [error is logged to openhab.log](https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/532?u=thomdietrich) if the key was not generated by the user

Any suggestions?

**Comment by watou** [comment]
Also see https://community.openhab.org/t/karaf-console/7982/17

**Comment by kaikreuzer** [comment]
> Any suggestions?

Maybe roll back to "simple" for now until we have thoroughly analyzed our options?

**Comment by ThomDietrich** [comment]
Sorry for the trouble.
In light of all reported issues, including the concern mentioned by Dim [here](https://community.openhab.org/t/karaf-console/7982/23?u=thomdietrich) I would agree.

@watou I guess we are now back at https://github.com/openhab/openhab-linuxpkg/issues/15#issuecomment-272630590 :sweat_smile: I'll take care of that.
