### ISSUE TITLE
Console: Log levels not kept after restart

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-distro#402]
If I set a specific log level (for a binding) and remove it after use, the log level is set again after a restart. I expected that it is kept default. I now have to explicitly set the level to `INFO` (or any default level) to remove it permanently.

1. Set log level, e.g. `log:set DEBUG org.openhab.binding.mqtt`
2. Use log level
3. Remove log level, e.g. `log:set DEFAULT org.openhab.binding.mqtt`
4. Show log levels with `log:list` ==> gone!
5. Restart openHAB and start console
6. Show log levels with `log:list` ==> back again!

```
Logger                                                      | Level
-------------------------------------------------------------------
ROOT                                                        | WARN
javax.jmdns                                                 | ERROR
org.apache.aries.spifly                                     | ERROR
org.apache.karaf.kar.internal.KarServiceImpl                | ERROR
org.eclipse.smarthome                                       | INFO
org.jupnp                                                   | ERROR
org.openhab                                                 | INFO
org.openhab.binding.mqtt                                    | DEBUG
org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper | ERROR
smarthome.event                                             | INFO
smarthome.event.InboxUpdatedEvent                           | ERROR
smarthome.event.ItemStateEvent                              | ERROR
smarthome.event.ThingStatusInfoEvent                        | ERROR
```

(Originally posted at https://github.com/eclipse/smarthome/issues/2880)

See comment https://github.com/eclipse/smarthome/issues/2880#issuecomment-274245946 by @watou

**Comment by BrutalBirdie** [comment]
[Solved](https://community.openhab.org/t/karaf-log-settings/21300)

**Comment by rtvb** [comment]
Please reopen the issue. It is not solved at all per your link. Manually editing the logger configuration is just a workaround I needed to permanently get rid of some things. 

Setting the log level to DEFAULT should **remove** the entry from the configuration and this should persist across restarts.

**Comment by CWempe** [comment]
I would consider this a bug.

As a user I expect the `log:set` to behave equally no matter what log level I set.

**Comment by wborn** [comment]
In Karaf 4.2.1 (openHAB 2.4.0-SNAPSHOT) the log level is still `default` after a restart.
After setting it to `default` it will show no log level for such loggers with the `log:list` command.
