### ISSUE TITLE
Can't start Openhab 2 on Windows 10

### ISSUE THREAD

**Issue by ahmadooka** [openhab/openhab-distro#403]
I am using Windows 10 home 64-bit.

When I run the start.bat I get the following and it just stops there:

```
Launching the openHAB runtime...
karaf.bat: Ignoring predefined value for KARAF_HOME
```

I tried manually setting JAVA_HOME to different java versions I have and all give the same output:
```

@echo off

echo Launching the openHAB runtime...

setlocal
set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0_121
set DIRNAME=%~dp0%
"%DIRNAME%runtime\bin\karaf.bat" %*
```

I tried pointing it to the 32-bit and 64-bit versions. I tried the JRE and the JDK although I have read that OH2 does not required JDK anymore. They all give the same output with exception of 32-bit JRE which give the following output:

```
Launching the openHAB runtime...
karaf.bat: Ignoring predefined value for KARAF_HOME
WARNING: Running Karaf on a Java HotSpot Client VM because server-mode is not available.
Install Java Developer Kit to fix this.
For more details see http://java.sun.com/products/hotspot/whitepaper.html#client
```

There is nothing in openhab.log. Debug start also does not work.

**Comment by ahmadooka** [comment]
I finally got it to work after doing the following:

1. Removing all java versions and installing only latest JDK for 32-bit
2. Adding the JAVA_HOME environmental variable
3. Deleting the openhab2 directory and starting with a new one from fresh unzip of the openhab download

**Comment by kaikreuzer** [comment]
Ok, so no bug then, thanks.

**Comment by ahmadooka** [comment]
I am not sure if it can still be improved. Normally java does not need the environmental variables anymore, even Openhab 1 was working for me without them and all other java applications were also working normally.
