### ISSUE TITLE
In Sitemaps LabelColor and ValueColor not working on Group:Switches in BasicUI

### ISSUE THREAD

**Issue by rgerrans** [openhab/openhab-distro#404]
I've defined the following group switch:

`Group:Switch:OR(ON, OFF)	Motion	"Motion"	<motion>	(Sensor)`

In my sitemap I tried to apply the following label/value colors:

`Group item=Motion		label="Motion [%s]"	labelcolor=[ON="Red"] valuecolor=[ON="Red"]`

But in the BasicUI it doesn't show up in Red though it does in the Android App

**Comment by lolodomo** [comment]
Basic UI is part of the Eclipse SmartHome framework.
You should declare your issue in https://github.com/eclipse/smarthome/issues
For your information, I already delcared an issue relative to groups in Basic UI that is different from yours: https://github.com/eclipse/smarthome/issues/2443

**Comment by rgerrans** [comment]
Thanks @lolodomo .  I'll move it over there.

Ron
