### ISSUE TITLE
Wrap url handler not available by default

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-distro#406]
For wrapping simple JARs which might be necessary for deployment of simple libs used in various parts of OpenHab wrap protocol will provide more reliable way than copying over binary file to bundle contents. Would be great if we could make it available in local repository by default so it will not require outside network connection and will work with 3rd party KAR files.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab-distro/pull/407
