### ISSUE TITLE
Allow to set OPENHAB_CONF and other OPENHAB_* environment variables

### ISSUE THREAD

**Issue by heziegl** [openhab/openhab-distro#408]
I ran into an issue using the openhab2 docker image as a base image for my specific docker image which includes my specify configuration directory:

It is not possible to start openhab2 with a different configuration directory location.
Looking at [oh2_dir_layout](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/oh2_dir_layout) and [setenv ](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/setenv)only OPENHAB_HTTP_PORT and OPENHAB_HTTPS_PORT are used if set before start.

Could you please add OPENHAB_CONF to the list and maybe it's a good idea to add most of OPENHAB_* environment variables (OPENHAB_CONF, OPENHAB_USERDATA, OPENHAB_LOGDIR).

e.g. by adding something like this to oh2_dir_layout:
if [ -z ${OPENHAB_CONF } ]; then
    export OPENHAB_CONF="${OPENHAB_HOME}/conf"
fi

**Comment by kaikreuzer** [comment]
Feel free to create a PR with your suggested changes.
