### ISSUE TITLE
UTF-8 encoded page displays broken text -> Umlauts broken

### ISSUE THREAD

**Issue by Seikilos** [openhab/openhab-distro#409]
Following the beginner tutorial with 2.0.0 release on a Win 10 x64 with JAVA 8 x86 I added a device in the network binding and clicked onto it to see its channels.
However the help text for each channels seems to contain broken UTF-8 encoding:
```Gibt an ob das GerÃ¤t aktuell online oder offline ist.```

I can rename the thing to contain umlauts and it is displayed **correctly**.
I have explicitly set the UI language to english and added a new thing and it still displays a german localized but broken string.

**Comment by kaikreuzer** [comment]
This has been fixed with https://github.com/openhab/openhab2-addons/pull/1751.
