### ISSUE TITLE
Umlaute are not shown correctly

### ISSUE THREAD

**Issue by Lucurus** [openhab/openhab-distro#411]
Umlaute (äöü) are not displayed correctly on the webapp. Instead of the letter, _Ã¤_ (i.e. NetzwerkgerÃ¤t) is displayed.

**Comment by Lucurus** [comment]
I'm not entirely sure to which distro to post this, so if this is incorrect, please delete it.

**Comment by kaikreuzer** [comment]
Looks like a duplicate of https://github.com/openhab/openhab-distro/issues/409, which is a duplicate of https://github.com/openhab/openhab2-addons/issues/1750

**Comment by Lucurus** [comment]
Thanks. Sorry, I should have checked.
