### ISSUE TITLE
 Startup rule "system started" fired >=3x 

### ISSUE THREAD

**Issue by stefaanbolle** [openhab/openhab-distro#413]
I have defined a rule which should only run once when system is started on a RPI3 running OH2.0 stable.
I notice that after each reboot or restart of OH2 this rules is fired >=3x.

A possible bug with the System started trigger mechanism?

I do not known whether it would be possible to define a trigger in OH2 that indicates a full system started (everything loaded) which can than trigger a switch to be used as condition for activating other rules execution.

Below my rule (simplified) 

> rule "System started"
>     when
>     System started
>     then
>     var Timer waitTimer = null
> 
>     SystemStarting.sendCommand(ON)
>     logDebug("startup", "System started")
>     waitTimer = createTimer(now.plusMinutes(4)) [|
>     	LichtenUit.sendCommand(OFF)
>     	Thread::sleep(10)
>     	LichtenAan.sendCommand(OFF)
>     	Thread::sleep(10)
>     	Sfeerlicht.sendCommand(OFF)
>     	Thread::sleep(100)
>     	SystemStarting.sendCommand(OFF)
>      	logDebug("startup", "Rule System starting ended")
>      	logDebug("startup", "System is ready!")
>         ]
> 
>     end

**Comment by lopez1de** [comment]
For me it's fired two times. I'm on the latest stable release.

**Comment by stefaanbolle** [comment]
A complete reinstall solved the issue. Apparently when adding/removing a lot in the config files, some items remain cached somewhere causing issue in the long run.
