### ISSUE TITLE
Can't login to ssh karaf console on Raspberry Pi 3

### ISSUE THREAD

**Issue by ps915** [openhab/openhab-distro#415]
I cant login my ssh console. 

I installed OpenHAB on the Raspberry Pi 3 now for the third time. The only thing i changed during setup was the username and password.

Thats what it looks like when i try to connect:
![openhabn](https://cloud.githubusercontent.com/assets/3420935/22568743/433b728e-e995-11e6-9a14-c656731fdc8e.PNG)
 `[22:12:43] pi@openHABianPi:~$ ssh ps915@localhost -p 8101
Password authentication
Password:
Password authentication
Password:
Password authentication
Password:
ps915@localhost's password:
Permission denied, please try again.
ps915@localhost's password:
Permission denied, please try again.
ps915@localhost's password:
Permission denied (keyboard-interactive,password,publickey).
[22:12:57] pi@openHABianPi:~$
`
What am i doning wrong?

![openhabn2](https://cloud.githubusercontent.com/assets/3420935/22568850/9639666c-e995-11e6-9501-7d9b3dc31190.PNG)

**Comment by ThomDietrich** [comment]
Hello,
please do not use the Issue tracker for usage support, we have a great community forum for that. https://community.openhab.org

I do not know why you are using the username "ps915". Please use "openhab" as described here: http://docs.openhab.org/administration/console.html
