### ISSUE TITLE
SimpleDateFormat not usable with Timer?

### ISSUE THREAD

**Issue by solars** [openhab/openhab-distro#420]
Hi there,

I'm not sure if this is a bug, it's weird certainly: I have a timestamp like "2017-2-1 8:10" so I used a SimpleDateFormat to parse it - which seems to work fine.
I then wanted to use it with a timer, which did not work.
If I output the timestamp in ISO format, and use .parse to parse it again, it works.

Example: https://gist.github.com/solars/0eff2aa8af3ea91e6e600b45d7106c76

Can anyone tell me why this happens?

**Comment by wborn** [comment]
The `SimpleDateFormat.parse` method returns a `Date` and not a `DateTime`. Maybe that was causing issues?

For these support questions it's better to use the [community forums](https://community.openhab.org).
