### ISSUE TITLE
Switch Groups changing to UNDEF

### ISSUE THREAD

**Issue by lopez1de** [openhab/openhab-distro#424]
With OH2 GA (might also occur with other versions) I do face an issue with Group:Switch:OR going to "UNDEF" instead of ON or OFF.

I do own some motion sensors (Homematic HM-Sen-MDIR-O-2) and "itemized" them as follows:

    Group:Switch:OR(ON,OFF) gMotion "Motion detected"
    Switch M1 "Motion Sensor #1" <motion> (gMotion) { channel="homematic:..." }
    Switch M2 "Motion Sensor #2 " <motion> (gMotion)  { channel="homematic:..." }
However, the group's state only is ON or OFF if both sensors have the same state. If their state's differ, the group reports itself as UNDEF.

On motion, the event.log prints

```
[GroupItemStateChangedEvent] - gMotion changed from OFF to UNDEF through M1
[ItemStateChangedEvent     ] - M1 changed from OFF to ON
```
later:
```
[ItemStateChangedEvent     ] - M1 changed from ON to OFF
[GroupItemStateChangedEvent] - gMotion changed from UNDEF to OFF through M1
```

Source of Issue (issue reported by m0wlheldChristoph Dahlen):
https://community.openhab.org/t/issue-with-group-switch-or-going-to-undef/21403

My findings:
If all switches are OFF, the group is OFF
If only one or several are ON, then the group is UNDEF
If all are ON, the group is ON

**Comment by lopez1de** [comment]
My fault. One item had a wrong channel config which forces the group to UNDEF.

**Comment by lopez1de** [comment]
One item might be NULL. But this should not be a problem?

**Comment by lopez1de** [comment]
I checked another group of 30 switches. All have changed from NULL to OFF after starting OH. The group then switches from NULL to ON too, when the last item of the group switches to OFF.
`gStickyUnreach changed from NULL to OFF through Win_Kind1_StickyUnreach`

So far so good.

But when I change one switch to ON, the group gous UNDEF for some reason.
```
2017-02-18 11:34:46.020 [ItemStateChangedEvent     ] - Heiz_WohnZ_StickyUnreach changed from OFF to ON
2017-02-18 11:34:46.023 [GroupItemStateChangedEvent] - gStickyUnreach changed from OFF to UNDEF through Heiz_WohnZ_StickyUnreach
```

**Comment by tavalin** [comment]
You might want to take the issue to the ESH repo. This issue isn't related to this repo.

**Comment by lopez1de** [comment]
ESH repo? Please tell me more.

**Comment by lopez1de** [comment]
moved to https://github.com/eclipse/smarthome/issues/3051

**Comment by kaikreuzer** [comment]
Glad you found the repo yourself 👍
