### ISSUE TITLE
[Rules] boolean types cause error in if()

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-distro#429]
### Expected Behavior

How "equal" various boolean types should be considered is a philosophical debate. Regardless, simple use of a boolean datatype in an if() expression should not cause an error.

### Current Behavior

I think this creates a Java primitive?

```
var boolean myTest = "true"
 if (myTest) {
 logInfo("here","true")
 }
```
**error Could not invoke method: org.eclipse.xtext.xbase.lib.BooleanExtensions.operator_equals(boolean,boolean) on instance: null**

I think this creates a Java Boolean object?

```
var Boolean myTest = "true"
 if (myTest) {
 logInfo("here","true")
 }
```
**error Could not invoke method: org.eclipse.xtext.xbase.lib.BooleanExtensions.operator_equals(boolean,boolean) on instance: null**

I think this creates a DSL Boolean object?

```
var myTest = new Boolean("true")
 if (myTest) {
 logInfo("here","true")
 }
```
This method works as expected

I think this forces the variable to be a DSL Boolean object?

```
var myTest = true
 if (myTest) {
 logInfo("here","true")
 }
```
This method works as expected

From community discussion
https://community.openhab.org/t/true-isnt-true-anymore/24099

### Possible Solution

No idea, more robust if() typing/casting I suppose.
On the face of it, it seems that are two different types of Boolean (big B) that might be invoked in Rules, which does not seem healthy.

Steps to Reproduce (for bugs)

Include above samples in a Rule

### Context

Root cause of rule errors is non-obvious, but workaround is simple once discovered.

### Your Environment

Appears to affect both OH 1.8.3 and OH 2.0

**Comment by tavalin** [comment]
I don't if this is different in Xtext/Xtend for the DSL but `"true"` isn't a valid Java boolean value - which may explain why the first two don't seem to work.

**Comment by kaikreuzer** [comment]
I agree with @tavalin, this is simply invalid code, so no bug in the rule engine.

**Comment by Rossko57** [comment]
I know that "true" is a string, I know that **true** is a genuine boolean constant.

The context this issue was found in was parsing from Json, which may or may not contain string "true", to a boolean.  It's not an unreasonable thing to do?
Java will parse a string to boolean, yes I know this is not Java

Further detail - 
var Boolean myTestX = "rhubarb"   Does not cause a runtime error.
var Boolean myTestY = "true"   Does not cause a runtime error.
logInfo("message", "X " + myTestX)   Does not cause an error, rhubarb is displayed (Not null or false).
logInfo("message", "Y " + myTestY)   Does not cause an error, true is displayed (Not null).

The issue was that **if()** blows up when supplied with these odd variables.

There is a workaround, var xxx = new Boolean("rhubarb") will return a 'proper' false, var xxx = new Boolean("true") will return a proper true; string parsing to booleans is entirely possible.

**Comment by ThomDietrich** [comment]
The real issue here seems to be `var boolean myTest = "true"`. You are trying to assign a string to a boolean. This seems to result in `null`, what would justify the error message. You should see that by trying to log the value of myTest.
Looking at that I'd say the problem is not the if command but the way you're initializing your variable. You'd probably see the same error with:

```java
var boolean myTest
if (myTest) {
  logInfo("here","true")
}
```

**Comment by tavalin** [comment]
> parsing from Json

You seem to have answered your own issue:

```
var Boolean myTest = new Boolean(transform("JSONPATH","$.myvariable")) // or whichever transformation service you're using
if (myTest) {
  logInfo("here","true")
}
```
NB: The above hasn't been tested.

**Comment by ThomDietrich** [comment]
Looks like a good fit. [`transform`](https://www.eclipse.org/smarthome/documentation/javadoc/org/eclipse/smarthome/core/transform/TransformationService.html#transform-java.lang.String-java.lang.String-) will always return String, hence [Boolean](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#Boolean%28java.lang.String%29) will evaluate correctly.

Boolean documentation indicates that `Boolean.valueOf(transform("JSONPATH","$.myvariable"))` might be the more efficient choice.

**Comment by Rossko57** [comment]
One last try.
Yes, there is more than one way to successfully parse a string into a boolean.  
The lack of error indication is the root issue, I thought there was a general wish to make the product more user friendly.
Obviously this case would be a very low priority issue.  I do have a feeling that it may just be one manifestation of something more widespread, but that is completely unfounded.

> The real issue here seems to be var boolean myTest = "true"

I agree

> this is simply invalid code,

If that is the case (its a reasonable assertion), should I expect it to throw a runtime error?
It doesn't.
Should this be an enhancement request?  It does make for usability for rules authors if errors are generated for invalid code.

> You are trying to assign a string to a boolean variable. This results in null just as the error message says.

It is legimate to do if-comparisons with null and null variables, without runtime errors.

Here I failed to include all the detail, being lazy as it is more apparent in the linked community thread.
To be clear.
`	var boolean testX = "rhubarb"
	logInfo("test", "value X " + testX)`
displays **value X rhubarb**
And the big-B typed case, for completeness - 
`	var Boolean testY = "custard"
	logInfo("test", "value Y " + testY)`
displays **value Y custard**

I think it would be reasonable if it did return **null**, but it does not.
Should this be an enhancement request, to return null?  

Lets play some more
`	var boolean testX = "rhubarb"
	logInfo("test", "value X " + testX)           // as described, outputs rhubarb
	if(testX == "rhubarb") {                 // so lets treat it a like a string, then
		logInfo("test", "X matched a string")    // outputs this path
	} else {
		logInfo("test", "X didn't match string")
	}
`
On the face of it, it seems to have ignored the var typing (var boolean) and produced _something_ with string content - we can recover the original string in the logInfo.

Is ignoring typing expected in Rules DSL (I could find nothing to suggest it, nor for Xtend)?
Have I completely misunderstood the purpose of typing, i.e. to ensure the var is of the given type?
If not, is there a need to document it somewhere? (not sure where)

Now for the weird stuff, bear with me ...
I was intrigued why the original problem if() blew up.
As above, our var boolean has made a variable that seems to be a string - why would that break if()?

Just to confirm we can mix booleans and strings in an if-evaluation -
`	var boolean testbb = true      // a really truly boolean
	logInfo("test", "value bb " + testbb)      // outputs value bb true, as we expect
	if(testbb == "custard") {
		logInfo("test", "bb matched a string")
	} else {
		logInfo("test", "bb didn't match string")  // outputs this
	}
`
No surprises there, of course "custard" is not true, and nothing blows up.
Just to be really sure, lets reverse and use a string variable with a bool constant
`	var testS = "somestring"
	if(testS==false) {
		logInfo("test", "string test true")
	} else {
		logInfo("test", "string test false")  // outputs this
	}
`
Again no suprise, "somestring" is not boolean-false so we execute the else expression.

Which leaves the mystery of the exploding if(), easily recreated
`	var boolean testX = "rhubarb"
	logInfo("test", "value X " + testX)    // shows rhubarb, looks like a string then ?
	if(testX == "rhubarb") {
		logInfo("test", "X matched a string")     // outputs here, still looks like a string?
	} else {
		logInfo("test", "X didn't match string")
	}
	if(testX==true) {                                // umm, this gives runtime error unlike a string, unlike a bool
		logInfo("test", "psuedo bool test true")
	} else {
		logInfo("test", "psuedo bool test false")
	}
`
**Could not invoke method: org.eclipse.xtext.xbase.lib.BooleanExtensions.operator_equals(boolean,boolean) on instance: null**

Well, that stringy looking var is not a proper string, it is not null, it certainly isn't a boolean.
We seem to have created a Frankenstein's Monster variable type?
The fix might be to not execute invalid code of course, or to return null in the declaration, or to enforce typing, or ... i don't know
My worry is that there is something distinctly odd about the whole if-error part.

Similar things happen with
 	**var boolean testX = 22**
it logInfos as 22, but you cannot add to it for example

**Comment by ThomDietrich** [comment]
Now you made your point.
@kaikreuzer
