### ISSUE TITLE
Windows service install works however service fails to start

### ISSUE THREAD

**Issue by bdleedy** [openhab/openhab-distro#436]
Running the command in the console works. Running the batch file with install works.

The service fails to start though. Changing the openHAB-wrapper.conf line
`set.default.KARAF_BASE=C:\OpenHAB\userdata`
to read
`set.default.KARAF_BASE=C:\OpenHAB\runtime`
allows the service to run. I can't say that this is correct but it allows it to run.

**Comment by AngelosF** [comment]
Check http://docs.openhab.org/installation/windows.html#starting-openhab-as-a-service on how to fully configure the openHAB2-wrapper.conf file to have a working windows service for openHAB.

I think that we can close this issue.

There is another one, tracking the same: https://github.com/openhab/openhab-distro/issues/467
