### ISSUE TITLE
BasicUI: Insecure EventSource Endpoint used (no HTTPS)

### ISSUE THREAD

**Issue by hotzen** [openhab/openhab-distro#441]
using basicUI behind NGINX with HTTPS via LetsEncrypt, the basicUI failes to load the events-endpoint to be notified about updates:

Mixed Content: The page at 'https://openhab.foo/basicui/app?sitemap=kk16' was loaded over HTTPS, but requested an insecure EventSource endpoint 'http://openhab.foo/rest/sitemaps/events/db1e7616-c10b-4664-bae8-94fac82d6c47?sitemap=kk16&pageid=kk16'. This request has been blocked; the content must be served over HTTPS.

This effectively blocks the sitemaps from any updates :(

**Comment by kaikreuzer** [comment]
I would assume that this is due to a wrong configuration of NGINX.
openHABian also uses NGINX as a reverse proxy and afaik there are no issues with the BasicUI (correct, @ThomDietrich?).

**Comment by hotzen** [comment]
the basicUI webclient decides to choose an HTTP-endpoint instead of requesting an HTTPS-endpoint - how could this be NGINX-related in any way?

**Comment by ThomDietrich** [comment]
I'm not seeing this problem. Neither is my sitemap not updating, nor can I find any errors in my browser (firefox and chrome). The "events" request is send via http.

**Comment by hotzen** [comment]
just did a little debugging.
subscription is done via HTTPS:

Request URL:https://openhab.foo/rest/sitemaps/events/subscribe
Response: `{"status":"CREATED","context":{"headers":{"Location":["http://openhab.foo/rest/sitemaps/events/ab72b881-e229-40a5-9bbd-8e02be4deeec"]},"committingOutputStream":{"bufferSize":0,"directWrite":true,"isCommitted":false,"isClosed":false},"entityAnnotations":[],"entityStream":{"bufferSize":0,"directWrite":true,"isCommitted":false,"isClosed":false}}}`

as you can see an HTTP endpoint is returned - how can I control this?

**Comment by hotzen** [comment]
@ThomDietrich thanks a bunch for posting your nginx-config, i was missing
`proxy_set_header X-Forwarded-Proto $scheme;`

working now like a charm

**Comment by ThomDietrich** [comment]
Wonderful. Why didn't you have that to begin with? It's documented here: http://docs.openhab.org/installation/security.html#nginx-setup-config

If your issue is resolved, please close it ;)

**Comment by hotzen** [comment]
didn't pay the proper attention to the X-headers :(
thanks! solved
