### ISSUE TITLE
Webview is not updated

### ISSUE THREAD

**Issue by Loidt** [openhab/openhab-distro#447]
It looks like a webview defined in sitemaps configuration is not updated if item values are changing.

I integrated weather information from OpenWeatherMap using the [weather binding](https://github.com/openhab/openhab1-addons/wiki/Weather-Binding). I followed the documentation on the binding page and defined weather provider in openhab.cfg, weather items in default.items and a webview pointing to weather servlet in default.sitemaps. In openhab.cfg update of weather provider is configured to 19 minutes:

> weather:location.myprovider.name=Berlin
> weather:location.myprovider.latitude=52.5244
> weather:location.myprovider.longitude=13.4105
> weather:location.myprovider.woeid=12831651
> weather:location.myprovider.provider=OpenWeatherMap
> weather:location.myprovider.provider=WorldWeatherOnline
> weather:location.myprovider.language=de
> weather:location.myprovider.updateInterval=19

However the weather widget is not updated. There is only an update if I refresh the browser window manually.

This issue could be reproduced with OpenHAB 1 Web App UI and OpenHAB 2 Basic UI. This issue does not appear on OpenHAB 2 Classic UI. See also following [dicussion in OpenHAB forum](https://community.openhab.org/t/weather-not-updated/27226).

**Comment by ThomDietrich** [comment]
@Loidt thanks for reporting this problem.
@kaikreuzer seems this was confirmed by other users. Regarding openHAB 2 this seems to be related to BasicUI hence @Loidt should move this issue to eclipse/smarthome !?

**Comment by kaikreuzer** [comment]
Might this be the same issue as https://github.com/eclipse/smarthome/issues/3308?

**Comment by Loidt** [comment]
This issue is different to 3308. In 3308 two issues are reported 
- Based on UI style (ClassicUI, BasicUI) refresh rate value defined in sitemap configuration for a chart or image is interpreted differently.
- In BasicUI images are displayed correctly on initial load but are not displayed after update

The issue described here is regarding weather binding using webview to display weather information in a custom html layout. Weather information are updated only if browser page is manually refreshed.

**Comment by lolodomo** [comment]
Looking at the Basic UI code, I see no refresh mechanism implemented for webview.

**Comment by pjhaucke** [comment]
Hello,

the same happens with ntp-binding. The time ist updated in PaperUI (and even in IOS-app) but not in BassicUI! Beyond, the day of the week is shown in german (correct) in PaperUI, but not in BasicUI and IOS-app. There it is indicated in english (wrong (for me)).

Regard. PJH

**Comment by kaikreuzer** [comment]
> Looking at the Basic UI code, I see no refresh mechanism implemented for webview.

Ok, so simply a missing feature in the Basic UI then.
I'd suggest to open an issue at https://github.com/eclipse/smarthome/issues.
