### ISSUE TITLE
PaperUI does not store Things' Location in Build #914

### ISSUE THREAD

**Issue by marcus-schneider** [openhab/openhab-distro#452]
Location can still be edited from HABmin

**Comment by kaikreuzer** [comment]
Not sure what you want to report here.
A bug in the Paper UI? Then please file it at https://github.com/eclipse/smarthome/issues.
A bug in HABmin? Then please file it at https://github.com/openhab/org.openhab.ui.habmin/issues.

Thanks!

**Comment by kaikreuzer** [comment]
Ok, I just tested Paper UI and I see that there indeed seems to be a bug when editing locations of Things, thanks for finding that.
