### ISSUE TITLE
Bintray OH2 Release Build (2.0.0) Repo gives HTTP 405 error

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-distro#453]
When running `apt-get update` after following the [apt-based Linux installation instructions](http://docs.openhab.org/installation/linux.html#package-repository-installation) on a Raspberry Pi 3, the user gets the following error: `Failed to fetch http://dl.bintray.com/openhab/apt-repo2/dists/stable/main/binary-armhf/Packages  405  Not Allowed`

The repo key has been added correctly in the first step.
Of course, the next step (`apt-get install openhab2`) fails ("Unable to locate package openhab2")

Something is wrong with the stable OH2 Repo on bintray?

OH2 Community Thread: https://community.openhab.org/t/issue-cant-initialized-thing-from-coolmasternet-binding/28033

**Comment by AngelosF** [comment]
Update: Tried also on a regular Debian Jessie system (amd64 arch) and I get the same error:
`Failed to fetch http://dl.bintray.com/openhab/apt-repo2/dists/stable/main/binary-amd64/Packages  405  Not Allowed`

**Comment by kaikreuzer** [comment]
Might this have been a temporary issue? If I try
```
curl http://dl.bintray.com/openhab/apt-repo2/dists/stable/main/binary-armhf/Packages
```
I get the response just as expected and no 405.

**Comment by DimitrisSar** [comment]
I still get the same error... using apt-get update
I am not sure how apt tool uses the http commands (post, get, etc)

**Comment by kaikreuzer** [comment]
Ok, but clearly some APT issue and not related to the openHAB distro itself - so you will have a better chance to get help if you report the issue at https://github.com/openhab/openhab-linuxpkg.

**Comment by BClark09** [comment]
Bintray wants us to use HTTPS instead of HTTP now, I'll change the docs accordingly.

**Comment by wandth** [comment]
Followed your updated instructions but despite supporting now https downloads via apt-get, I still experienced "Some index files failed to download. They have been ignored, or old ones used instead." messages when updating my minimal Debian system. Turned out, the Bintray SSL certificate was unknown to the Debian system (thats why apt-get update still failed). Installing ca-certificates (apt-get install ca-certificates) fixed everything. Works now!

**Comment by kaikreuzer** [comment]
@wandth Bintray had download issues today (see http://status.bintray.com/) - your issues might be related to that.

**Comment by semaf** [comment]
I get an Error if I try to install anything.

pi@openhab:~ $ sudo apt-get install ca-certificates
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libc6-dbg : Depends: libc6 (= 2.19-18+deb8u9) but 2.19-18+deb8u7 is to be installed
 libc6-dev : Depends: libc6 (= 2.19-18+deb8u9) but 2.19-18+deb8u7 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by semaf** [comment]
After apt-get install -f

N: Is the package apt-transport-https installed?
pi@openhab:~ $ sudo apt-get autoremove -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  libc6
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc6
1 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.
2 not fully installed or removed.
Need to get 0 B/4,082 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  libc6
Install these packages without verification? [y/N] yReading changelogs... Done
debconf: Perl may be unconfigured (Unrecognized character \xEF; marked by <-- HERE after ckage DEbc<-- HERE near column 13 at /usr/share/perl5/Debconf/Log.pm line 4.
Compilation failed in require at (eval 1) line 4.
BEGIN failed--compilation aborted at (eval 1) line 4.
) -- aborting
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'libraspberrypi-bin' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by rickardp** [comment]
I recently got this problem and had to switch from

    http://dl.bintray.com/openhab/apt-repo2

to 

    https://dl.bintray.com/openhab/apt-repo2


(That is, HTTP->HTTPS). It appears bintray forces https recently, and it makes good sense. I probably followed old instructions a long time ago.
