### ISSUE TITLE
[Feature Request] Add Build # on OH2 Pages

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-distro#454]
I hope this belongs here (not sure which github repo to use to open up this request)... maybe [here](https://github.com/eclipse/smarthome/issues/3318)?
This is super minor, but it would be useful for many (I believe):

Add the Build/Version number on either the start page (`http://<OH2>:8080/start/index`) or the PaperUI index page (`http://<OH2>:8080/paperui/index.html`) of openHAB2

Example:
![oh2_version_number](https://cloud.githubusercontent.com/assets/25465966/26045260/12aefa48-3952-11e7-9bab-debdd510fb29.jpg)

**Comment by ThomDietrich** [comment]
I'd support the idea and vote for the position at the bottom of the dashboard (start page).

**Comment by VanHogan** [comment]
+1

**Comment by kaikreuzer** [comment]
Does this look ok? https://github.com/openhab/openhab-core/pull/149#issuecomment-301581640
