### ISSUE TITLE
Upgrade to Karaf 4.1.x

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#455]
We should try to stay up-to-date with latest Karaf releases.
A switch to Karaf 4.1.x will bring us a more recent Jetty (9.3) version, a cleaned up etc folder and the possibility to move to the much more powerful log4j2.

Current release is 4.1.1, but 4.1.2 is expected anytime soon.

**Comment by martinvw** [comment]
They do no seem to reach their plans:

4.1.2	eta 08/05/17

Or is it some non-european notation referring to august...

**Comment by kaikreuzer** [comment]
Hehe, they so far hardly ever reached their plan and they even fail to update the ETAs ;-)

I am actually wondering whether it is safer to go for an openHAB 2.1 release on the current Karaf and do the upgrade directly afterwards - this will leave us more time to get everything stable again. Wdyt?

**Comment by maggu2810** [comment]
> Hehe, they so far hardly ever reached their plan and they even fail to update the ETAs ;-)

We should use a respectful treatment with the work of other communities!

**Comment by martinvw** [comment]
Agree on that, I did not intend any harm, I was seriously doubting the date format. With dashes is is always clear that it is European, in this case I'm in doubt.

And yes our own ETA's are also hardly ever reached :-)

**Comment by kaikreuzer** [comment]
I am deeply respectful that they dare to provide ETAs, which I completely fail to do for openHAB :-)
So "failing to reach the ETA" is already one quality level higher than my own project management. I hope this proofs that I definitely didn't mean to blame anyone 😎

**Comment by martinvw** [comment]
@kaikreuzer do you agree that it is getting a little late to switch to this version, if it gets released. Maybe for the next version...?

**Comment by kaikreuzer** [comment]
Yes, see my https://github.com/openhab/openhab-distro/issues/455#issuecomment-305723011.

**Comment by kaikreuzer** [comment]
@martinvw A first try using 4.1.1 (4.1.2 is still not available...) is here: #484
