### ISSUE TITLE
Binary Sensors not triggered on Rules

### ISSUE THREAD

**Issue by manswiss** [openhab/openhab-distro#459]
I have two binary sensors items with type contact and both work pretty on "Paper UI -> Control", it changes correct to triggered or untriggered.
The problem is, that I don't see any entry on /srv/openhab2-logs/events.log and it is not possible to write any rules with this device as trigger.

My system:
- Release = Raspbian GNU/Linux 8 (jessie)
- Kernel = Linux 4.9.24-v7+
- Platform = Raspberry Pi 3 Model B Rev 1.2
- openHAB 2.1.0~20170604033302-1 (Build #938)
- Devices: ZW100 MultiSensor 6 and ZG8101 Garage Door Tilt Sensor
- All things and items are set up on Paper UI

**Comment by kaikreuzer** [comment]
This will need additional analysis to figure out whether there is a bug or if it just a wrong configuration.
I assume it is related to Z-Wave, so I would suggest to discuss the issue at the forum (https://community.openhab.org/) first and potentially afterwards file a bug report for the Z-Wave binding (https://github.com/openhab/org.openhab.binding.zwave).
