### ISSUE TITLE
Feature Request: SendFrequency Suppport for Setpoint

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-distro#463]
I request, that the SendFrequency option in the sitemap configuration will also be made available to Setpoint items. The goal of this is, to keep the Up or Down button pressed while the values are increasing/decreasing. This will be helpful especially on touch-devices as it takes forever now to switch over a big range (for example when configuring a time I don't want to click 60 times to switch from 12:59 to 13:01 but instead hold the - or + button and wait until it reaches the target value or comes close to it).

**Comment by kaikreuzer** [comment]
I think it would be even better to not send commands for every step, but only for the one, when the user releases the button.

Note that this feature needs to be built into the UIs themselves, so you would have to open issues in the respective repos of the UIs - that's be quite some effort though.

**Comment by Flole998** [comment]
The basic UI is part of the eclipse smarthome project, right? It's becoming more and more complicated to see where each part of the code is coming from. When I opened this issue I was almost sure that this is not the right repo, I was however unable to find a better one.

**Comment by ThomDietrich** [comment]
Yes, the eclipse smarthome project is the right one:
https://github.com/eclipse/smarthome/tree/master/extensions/ui/org.eclipse.smarthome.ui.basic
