### ISSUE TITLE
Windows - Karaf Service Wrapper fails to start

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-distro#478]
Here's a really weird issue and I'm not sure why the workaround works.  I installed the latest 2.2 snapshot - followed  [Windows Install](http://docs.openhab.org/installation/windows.html) and copied the conf file directly from the article.  

My JAVA_HOME is set to "C:\Program Files\Java\jdk1.8.0_131" (as verified from the command line and from the GUI).

When I start the service, it fails with the log message below.  
```
STATUS | wrapper  | 2017/07/02 17:19:06 | --> Wrapper Started as Service
STATUS | wrapper  | 2017/07/02 17:19:06 | Launching a JVM...
FATAL  | wrapper  | 2017/07/02 17:19:06 | Unable to execute Java command.  The system cannot find the file specified. (0x2)
FATAL  | wrapper  | 2017/07/02 17:19:06 |     "%JAVA_HOME%\bin\java" -Dkaraf.home="C:\openHAB2\runtime" -Dkaraf.base="C:\openHAB2\userdata" -Dkaraf.data="C:\openHAB2\userdata" -Dkaraf.etc="C:\openHAB2\userdata\etc" -Dcom.sun.management.jmxremote -Dkaraf.startLocalConsole=false -Dkaraf.startRemoteShell=true -Djava.endorsed.dirs="%JAVA_HOME%/jre/lib/endorsed;%JAVA_HOME%/lib/endorsed;C:\openHAB2\runtime/lib/endorsed" -Djava.ext.dirs="%JAVA_HOME%/jre/lib/ext;%JAVA_HOME%/lib/ext;C:\openHAB2\runtime/lib/ext" -Dopenhab.home="C:\openHAB2" -Dopenhab.conf="C:\openHAB2\conf" -Dopenhab.runtime="C:\openHAB2\runtime" -Dopenhab.userdata="C:\openHAB2\userdata" -Dopenhab.logdir="C:\openHAB2\userdata\logs" -Dfelix.cm.dir="C:\openHAB2\userdata\config" -Dorg.osgi.service.http.port=8080 -Dorg.osgi.service.http.port.secure=8443 -Xmx512m -Djava.library.path="C:\openHAB2\userdata/lib/wrapper/" -classpath "C:\openHAB2\runtime/lib/boot/org.apache.karaf.diagnostic.boot-4.0.8.jar;C:\openHAB2\runtime/lib/boot/org.apache.karaf.jaas.boot-4.0.8.jar;C:\openHAB2\runtime/lib/boot/org.apache.karaf.main-4.0.8.jar;C:\openHAB2\runtime/lib/boot/org.osgi.core-6.0.0.jar;C:\openHAB2\userdata/lib/wrapper/karaf-wrapper-main.jar;C:\openHAB2\userdata/lib/wrapper/karaf-wrapper.jar" -Dwrapper.key="4LXy2OFJ4il4WR9R" -Dwrapper.port=32000 -Dwrapper.jvm.port.min=31000 -Dwrapper.jvm.port.max=31999 -Dwrapper.pid=13044 -Dwrapper.version="3.2.3" -Dwrapper.native_library="wrapper" -Dwrapper.service="TRUE" -Dwrapper.cpu.timeout="10" -Dwrapper.jvmid=1 org.apache.karaf.wrapper.internal.service.Main
FATAL  | wrapper  | 2017/07/02 17:19:06 | Critical error: wait for JVM process failed
STATUS | wrapper  | 2017/07/02 17:21:30 | --> Wrapper Started as Service

```

However, if I change the line in the conf file from:
`wrapper.java.command=%JAVA_HOME%\bin\java`
to
`wrapper.java.command=C:\Program Files\Java\jdk1.8.0_131\bin\java`

the service started fine (even though they should be entirely equivalent).  I personally don't see the difference between the two and %JAVA_HOME% worked fine in the rest of the conf file (i.e. the ext/endored directory lines).

As a side issue - the conf in the article has mixed slashes ("/" and "\\").  Doesn't matter when running but you might want to update to be consistent.

**Comment by ThomDietrich** [comment]
Hello @tmrobert8 :wave: 
I have the feeling @AngelosF can be of help here :wink:

**Comment by AngelosF** [comment]
checking now...
from a first look.. I don't understand why the environment variable would work in the `Java Parameters` section and not work in the `Java Application` section...

I will deploy OH 2.2.0 on a clean win 10 system to see what is going on...

**Comment by tmrobert8** [comment]
@AngelosF 
Just some more information - and feel free to ask me to try anything...

I tried the following (results were pretty much as expected):

1. Set java_home to a path without a space - worked
2. Used a different environment name "tim_java_home" with a non-space path - worked
3. Used a different environment name "tim_java_home" with a space path - didn't work

I then tried to duplicate the commands:
1. Running the command from the log file above directly from the prompt (ie `"%JAVA_HOME%\bin\java" -blahblahblah`) - worked fine (up until it couldn't connect to the wrapper port).
2. Run the service command directly from the prompt (`C:\openHAB2\userdata\bin\openHAB2-wrapper.exe -s C:\openHAB2\userdata\etc\openHAB2-wrapper.conf`) - did not work - same exception in the log

I then remove the "-s" argument (`C:\openHAB2\userdata\bin\openHAB2-wrapper.exe  C:\openHAB2\userdata\etc\openHAB2-wrapper.conf`) - and that worked fine!

Has something to do with running it as a service (using the -s argument) - something in that code path isn't delimiting the "wrapper.java.command"...

Note: I did try: `wrapper.java.command="%JAVA_HOME%\bin\java"` - but that didn't work as well.

**Comment by AngelosF** [comment]
I tried several things... I can't replicate this issue... :(

Originally, I had JDK 121 and JRE 131 in my system... (with %JAVA_HOME% pointing to `C:\Program Files\Java\jdk1.8.0_121`.  All was fine.

I uninstalled both and deployed JDK 131.
Changed System Environment variable for JAVA_HOME to the new `C:\Program Files\Java\jdk1.8.0_131`, downloaded OH2 2.1.0 Stable Release.
Followed the installation instructions... all worked fine

I will try again with OH2 2.2.0 snapshot but I believe that I won't have any issues also.

My openHAB2-wrapper.conf is exactly the one from the docs entry
```
wrapper.java.command=%JAVA_HOME%/bin/java
```

**Comment by AngelosF** [comment]
Try the following:

Since the path contains spaces, use the shortened path name. For example, C:\Progra~1\Java\jdk1.8.0_131

Note for Windows 64-bit:
Progra~1 = 'Program Files'
Progra~2 = 'Program Files(x86)'

**Comment by BClark09** [comment]
Also, is your Windows configuration running separated environment variables? This sounds similar to an issue I had with maven. E.g, is %JAVA_HOME% defined in user, but not in system?

**Comment by tmrobert8** [comment]
Yes - the test I did above (removing the space) was doing the Progra~1 instead and that did work.

However - I realized what I did - the JAVA_HOME was defined as a user rather than a system variable and once I redefined that - it worked

**Comment by ThomDietrich** [comment]
Wonderful. Glad you got it working. 
Is the issue solved with that? Do you see any room for improvement for the documentation article?

**Comment by tmrobert8** [comment]
Yes it is - thank you.  As for documentation - I'd definitely fix the "/" and "\\" inconsistency.  I'm not sure you need to address the "user vs system" environments as I had specifically defined a user one (awhile back) as a workaround to an issue I had and completely forgot about that.  I guess if you are modifying the doc that putting in a quick note about it needing to be a system variable may not be a bad thing..

**Comment by AngelosF** [comment]
I think that the "system" part of the variable is pretty clear in the doc entry (2 times mentioned in the written text and once more in the image)

The slashes should be corrected... definitely :)

**Comment by ThomDietrich** [comment]
Nice. So let's close this one here. Waiting for a PR against docs :stuck_out_tongue_winking_eye:
