### ISSUE TITLE
HTTPS Mixed Content

### ISSUE THREAD

**Issue by frnck** [openhab/openhab-distro#483]
The web interface (BasicUI) is accessed using https. But some resources are still requested using HTTP. First, this is a bad web practice. Second, this brakes the web interface because it is only served using HTTPS.

Mixed Content: The page at 'https://***/basicui/app' was loaded over HTTPS, but requested an insecure EventSource endpoint 'http://***/rest/sitemaps/events/b4e94801-b1b7-4bae-8b7c-5b6c6edb7235?sitemap=thuis&pageid=thuis'. This content should also be requested over HTTPS.

Version info
openhab2/stable,now 2.1.0-1 all [installed]
openhab2-addons/stable,now 2.1.0-1 all [installed]

**Comment by ThomDietrich** [comment]
Hello @frnck,
I can't confirm with my testing system. You didn't describe how you configured HTTPS, which would be crucial. There was another user with this problem: https://github.com/openhab/openhab-distro/issues/441

Please check your settings and report back. Good luck!

**Comment by lolodomo** [comment]
I also checked with the Firefox console and all requests are done by Basiuc UI with HTTPS.

Maybe you have a problem with your NGINX setup (I have no reverse proxy installed).

**Comment by frnck** [comment]
The problem is resolved.

Now I have the following apache configuration:
ProxyPass / http://localhost:8080/
ProxyPassReverse / http://localhost:8080/
RequestHeader set X-Forwarded-Proto "https"

Adding the last line (RequestHeader ...) resolved the issue. 

I still do not understand why this is a preferable solution. The web client alsco could find out it's base url.

**Comment by BClark09** [comment]
You've specified that the communication between the reverse proxy and the webclient as http://. So the webclient is doing as it's told in that respect, in a way the webclient is unaware of the connection you have to your reverse proxy. Just as you have found out, you need to let the system know that this needs to be forwarded as https. AFAIK, this is standard practice for any proxy or load balancer.
