### ISSUE TITLE
Outdated copyright on myopenhab.org

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-distro#486]
Is this website code hosted on github?

On http://www.myopenhab.org/ "Amazon Echo (available soon!)". Isn't this outdated?

**Comment by kaikreuzer** [comment]
Thanks for noticing, I had missed that indeed when the skill was approved.
Updated the page now with https://github.com/openhabfoundation/myopenhab.github.io/commit/0a1cd33b3b606ddc9b9fabe08d5c6bcb39daecd9.
