### ISSUE TITLE
multiple google charts with a switch to set the chart period. Wrong chart's dimensions

### ISSUE THREAD

**Issue by lucarui** [openhab/openhab-distro#488]
Hello,
I noticed that using a chart switch on sitemap in order to change the chart period, when I change from a a period to another, the new chart has very small dimensions. **All html elements below the charts are the same** (change only the json object passed to them) but the first chart that is shown at the page load has correct dimensions; the others, when I press on switch periods, have a very small dimensions.
If I came back to the first, the chart continues to have correct dimensions. It's like only the first "period" works well and the others set wrong dimensions to the charts.

chart shown at the page start:
![image](https://user-images.githubusercontent.com/22214152/28465316-93881d2e-6e28-11e7-91e5-b3511c046389.png)

If I click on other period values....:
![image](https://user-images.githubusercontent.com/22214152/28465328-a1cdbd9e-6e28-11e7-844d-0619c61c043c.png)

**Comment by kaikreuzer** [comment]
I'd assume that this problem only happens in the Basic UI - if so, please report it at github.com/eclipse/smarthome/issues, where the Basic UI is maintained. Thanks!

**Comment by lucarui** [comment]
closed. Wrong section
