### ISSUE TITLE
Warnings when launching distro on Windows

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#49]
I have just tried the very latest (online) distro on Windows 10. Launching it, I see the following warnings from Karaf:
```
C:\oh 2>start.bat
Launching the openHAB runtime...
karaf.bat: Ignoring predefined value for KARAF_HOME
karaf.bat: JAVA_HOME not set; results may vary
```
The second on corresponds to https://github.com/openhab/openhab-distro/issues/29, the first one looks like some bug.

**Comment by dvanherbergen** [comment]
Works now on Windows 7.

**Comment by kaikreuzer** [comment]
@dvanherbergen Could you have a look at https://community.openhab.org/t/oh2-karaf/5992/1?

**Comment by shorty707** [comment]
not fixed for win10

**Comment by kaikreuzer** [comment]
Hm, I just tried the latest build (71) on my Windows 10 and it all works well...

**Comment by dvanherbergen** [comment]
Could it be related to access rights? When I tried on Windows7, if I wasn't logged in as admin, I got prompted for a admin user/password when starting, because it tries to read the registry.

**Comment by kaikreuzer** [comment]
Closing it again. @shorty707, feel free to create a new issue with an exact problem description.

**Comment by dvanherbergen** [comment]
Retested this with build 111 on win7. Appears to work.

**Comment by DuncanSpain** [comment]
I've just tried to install OpenHab2 and get the same JAVA_HOME not set.
Tried getting the latest install, updated java, installed Java JTK.
Do you need to manually set JAVA_HOME, if so where.
I also have OpenHab 1.8 installed but was not running.
Running windows 7, CMD batch file opens and give the error. If run as Admin then runs and closes and disappear, so error is difficult to grab.
The batch file seems to be looking in the Registery for the location of Java, but it was looking in HKEY_LocalMachine, mine is in HKEY_CurrentUser.
Waited till now, to let someone else iron out the inital bugs, but it wont install for me! . 
Where do I check the build number?

**Comment by phoenix-blue** [comment]
I have here almost the same message:
``karaf.bat: Ignoring predefined value for KARAF_HOME ``

And when i try to check the html page i get an 404 error.
Are those errors related to each other?
