### ISSUE TITLE
Weather Underground binding not present in distribution ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#492]
I was disappointing to not see my Weather Underground binding after installing OH distribution 990.
The binding is not listed in Paper UI.
The binding is not installed when I use "weatherunderground" as binding in my addons.cfg file.
But I got this result when running the command `feature:list | grep weather` in the console:
```
esh-binding-weatherunderground              | 0.9.0.SNAPSHOT   |          | Uninstalled | openhab-addons-2.2.0-SNAPSHOT |
esh-binding-yahooweather                    | 0.9.0.SNAPSHOT   |          | Uninstalled | openhab-addons-2.2.0-SNAPSHOT |
openhab-binding-yahooweather                | 2.2.0.SNAPSHOT   |          | Uninstalled | openhab-addons-2.2.0-SNAPSHOT | Yahoo Weather Binding
openhab-binding-weather1                    | 1.11.0.SNAPSHOT  |          | Uninstalled | openhab-addons-2.2.0-SNAPSHOT | Weather Binding
esh-binding-weatherunderground              | 0.9.0.SNAPSHOT   |          | Uninstalled | addons-2.2.0-SNAPSHOT         |
esh-binding-yahooweather                    | 0.9.0.SNAPSHOT   |          | Uninstalled | addons-2.2.0-SNAPSHOT         |
openhab-binding-yahooweather                | 2.2.0.SNAPSHOT   |          | Uninstalled | addons-2.2.0-SNAPSHOT         | Yahoo Weather Binding
openhab-binding-weather1                    | 1.11.0.SNAPSHOT  |          | Uninstalled | addons-2.2.0-SNAPSHOT         | Weather Binding
```

@kaikreuzer: your are one of the specialists for that ;) Can you tell us what's wrong ?

**Comment by lolodomo** [comment]
Running `feature:install esh-binding-weatherunderground` in the console correctly installed the binding.
But still not displayed as extension in Paper UI.

**Comment by kaikreuzer** [comment]
I simply didn't yet have the time to add it to the distro. It needs to be added here: https://github.com/openhab/openhab-distro/blob/master/features/addons-esh/src/main/feature/feature.xml

Feel free to create an according PR!

**Comment by lolodomo** [comment]
Ok, I am doing it immediately ;)

**Comment by lolodomo** [comment]
Done
