### ISSUE TITLE
Error if <iconname> equals Item Type in .items file

### ISSUE THREAD

**Issue by rgerrans** [openhab/openhab-distro#494]
Only tested with Switch, but if you define an item in a .items file and use <Switch> (propercase) as your iconname it generates the following errors when openhab tries to load the .items file.

```
[38,65]: mismatched input '>' expecting RULE_ID
[38,78]: mismatched input ')' expecting RULE_ID
[38,132]: mismatched input '=' expecting RULE_ID
[38,184]: mismatched input '=' expecting RULE_ID
[59,36]: no viable alternative at input 'Switch'
```

Low priority issue since the workaround is lowercase <switch> but that isn't compatible with HABmin which uses propercase icon / category names

**Comment by ThomDietrich** [comment]
Hey :wave: Thanks for reporting the issue!
@lolodomo

**Comment by kaikreuzer** [comment]
This isn't a bug, you simply have to escape keywords.
This is done by prepending a ^. This is true for ALL DSL files, so you will have the same in sitemaps, rules, etc.
