### ISSUE TITLE
Add backup/restore scripts

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-distro#499]
Continuing on from #299...

Separate files that backup and restore the openHAB configuration should be made. Users should be able to specify a file for the archive to be created/extracted depending on the script.

---
### General
 - Assume that the scripts are being called from openHAB's root directory or work backwards from the script path (`../../`).
 - If no filepath is specified, save to `[openHAB]/backups`.
 - If no filename is specified, use a timestamp.
 - Backups should not contain `userdata/cache` , `userdata/tmp` and any of the following files:
    - `/userdata/etc/all.policy`
    - `userdata/etc/branding.properties`
    - `userdata/etc/branding-ssh.properties`
    - `userdata/etc/config.properties`
    - `userdata/etc/custom.properties`
    - `userdata/etc/version.properties`
    - `userdata/etc/distribution.info`
    - `userdata/etc/jre.properties`
    - `userdata/etc/profile.cfg`
    - `userdata/etc/startup.properties`
    - `userdata/etc/org.apache.karaf*`
    - `userdata/etc/org.ops4j.pax.url.mvn.cfg`

---

### Specific to Linux/Mac OS 
  - Use $OPENHAB_CONF and $OPENHAB_USERDATA first if they exist.
  - Files should be `backup` and `restore` with no extension and executable rights set (755).

@whopperg, you have already done most of this, care to finish it off and send a PR?

---

### Specific to Windows
  - Use %OPENHAB_CONF% and %OPENHAB_USERDATA% first if they exist.
  - Files should be `backup.bat` and `restore.bat`, there should be no need to use powershell here.

@bdleedy and @ghys, I'm not sure if anything exists here yet, care to take a look?

**Comment by ghys** [comment]
I'm not aware of anything existing for backup and restore on Windows.
I have the same opinion about PowerShell vs batch files as in #500.

**Comment by BClark09** [comment]
Another thought, backups should be platform independent. It should be perfectly reasonable for a user to move their windows installation to a Linux server, or visa versa. For this reason, we should use zip.

Some methods of compressing with zip will remove previous file ownership. I'd suggest using a file inside the backup to determine a couple of things so that they can be restored later:

backup.properties
```
version=2.1.0
user=openhab
group=openhab
```

Secondly, if no path is specified where should the zip file be stored? For manual installations this can be `openhab2/backup` but for apt/rpm? @ThomDietrich, do you have any ideas?

**Comment by BClark09** [comment]
@whopperg, I'm happy to do it if you've not got the time. I'll start on the weekend.

**Comment by ThomDietrich** [comment]
Hey! Good idea. I will not be of much help with the project but will try to annoy all of you with comments as good as I can ;)

Regarding the backup location: Hmmm I'd say `/var/backups/openhab2` would be the most linux-way-of-things location. I agree that it is not the most convenient location for our fellow Linux newbies. The users home is the other extreme and would be  easy to find, even WinSCP will start browsing there. I'd not vote for it. A location below `/var/lib/openhab2` is also not a good idea as the whole directory itself is included in the backup.
I might add that the location of the backups, wherever they might end up is easily mounted to `/srv/openhab2-backup` under openHABian just like the rest of the interesting openHAB folders. Hence I'd say we don't need to worry about our Linux newbies too much...

So yeah. Wdyt about `/var/backups/openhab2`?

**Comment by BClark09** [comment]
/var/backups is [specific to debian](https://unix.stackexchange.com/questions/68698/is-it-bad-dangerous-inappropriate-to-put-arbitrary-backups-in-var-backups) I think.

I'd prefer "/home/backups" but I think it shouldn't matter too much if we make it clear where to define the default path (`/etc/default/openhab2`).

Another option is using "/var/lib/openhab2/backup", but not including that folder in the actual backup.

**Comment by ThomDietrich** [comment]
that might be but what gives. We can simply create the backups folder on other OSs. The answer you linked to suggests "you could put them in /backups, or even /home/backups"  which both are very bad choices in my eye. Noone should start to mess up the root folder and home should stay restricted to user accounts. Before we mess around in these areas ask yourself this: who will be mad at us for creating /var/backups?

**Comment by ThomDietrich** [comment]
Okay I've read up on the meaning of "/var/backups is reserved". It may not be the best solution after all. 
https://askubuntu.com/questions/575679/what-is-the-default-location-for-backup-files-of-another-server

**Comment by BClark09** [comment]
Another option would be to place it inside whichever directory it was called from (or something similar to this). For manual users, who haven't defined $OPENHAB_HOME this must be in the openHAB root directory anyway. For apt/rpm users, this would usual be their own home directory, but that doesn't seem so bad if the script told them where the generated zip file is.

**Comment by whopperg** [comment]
@BClark09: Please do so! Feel free to use what ever you can / need from the script!

**Comment by BClark09** [comment]
Thanks @whopperg, I'll have a go this evening.

@ThomDietrich, [FHS 3.0](http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf) defiantly points to /var/lib/openhab2/backups being the most appropriate directory to use, and to me having it under where every other "user-initiated" file is makes sense. It shouldn't be too hard to stop backups appearing in the backups. You'd know openHAB's Linux users best though, any other suggestions as which to use?

**Comment by ThomDietrich** [comment]
After reading though quite a few recommendations and checking with other applications, I'm convinced of `/var/lib/openhab2/backups`. Let's do that.

**Comment by bdleedy** [comment]
@ghys Agreed, stick with PS. Are OPENHAB_CONF and OPENHAB_USERDATA new environment variables that get set?

**Comment by bdleedy** [comment]
@BClark09 I'm trying to keep in line with what you have envisioned for the non-MS side. Are you thinking one script that contains both functions or a discrete script for backup and restore?
@ghys Graphical folder picker or just all command line?

**Comment by ghys** [comment]
> @ghys Graphical folder picker or just all command line?

I'm partial to always avoid invoking blocking dialogs and other GUI in command line scripts. Those scripts could be called from another one without user interaction - or from a PS remoting session, Windows Core Edition etc.

**Comment by BClark09** [comment]
Hi @bdleedy, I've separated the scripts. You can see my attempt for a Linux/MacOS implementation [here](https://github.com/openhab/openhab-distro/pull/507)

**Comment by bdleedy** [comment]
Need tester for backup script. Hoping to have restore script done tonight.

**Comment by JohnnyXXX** [comment]
@bdleedy I'm a windows user and still on the migration of 1.8.3 to OH2.x but willing to play aroung with your script. Please tell me what/how to test and what kind of feedback do you need? Any specific test cases to run? Any pre-conditions required?

**Comment by bdleedy** [comment]
update.ps1 and backup.ps1 should be in \runtime\bin. Open powershell as admin, cd to the root of your OH install. run ". .\runtime\bin\update.ps1" then "update-openhab"

**Comment by kaikreuzer** [comment]
This is available by now.
