### ISSUE TITLE
Formalise CSV transition strategy

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-distro#501]
Following on from #299 

The majority of systems can now be upgraded in the basic sense, but we need to define a CSV format to tell the upgrade scripts what to do in special cases. The proposal in #299 was to read through a simple list of instructions e.g:

```
MOVE,$OPENHAB_USERDATA/etc/some_karaf_file.profiteroles,$OPENHAB_RUNTIME/some_karaf_file.profiteroles
DELETE,$OPENHAB_USERDATA/etc/some_other_file.xml
```

We should discuss the exact stategy here.

CC all who discussed this previously: @kaikreuzer, @mhilbush, @BClark09, @xsnrg, @whopperg, @ThomDietrich, @bdleedy, @ghys

**Comment by BClark09** [comment]
I do think we'd need some versioning here. The update scripts already check which version is currently running, and what version is required to update. Say the system is on 2.1.0 the user wants to upgrade to 2.3.0. The CSV file in 2.3.0 should contain:

```
[2.1.0]
MOVE,***,***
DELETE,***

[2.2.0]
MOVE,$$$,$$$
DELETE,$$$

[2.3.0]
MOVE,£££,£££
```

The script parses the CSV file and should performs:

```
MOVE,$$$,$$$
DELETE,$$$
MOVE,£££,£££
```

**Comment by ThomDietrich** [comment]
Taken from https://github.com/openhab/openhab-distro/pull/426#issuecomment-281068143 :

----

 I can't think of any higher complexity (delete file x only if file y diesn't exist and z was created on christmas eve) demanding a more sophisticated format. Here are all examples I can think of:

* `DELETE;relative/path/to/file`
* `DELETE;$OPENHAB_CONF/pseudo-relative/path/to/file`
* `MOVE;filepath_old;filepath_new`
* `MOVE;filepath_old;filepath_new`
* `TOUCH;some_file_or_folder` (probably not needed, will create folders which might be of interest)

General remarks:

* All commands are executed in the order they are given in the file
* paths are relative and can start with one of the defined $OPENHAB variables
* path delimiter is the forward slash
* paths can contain wildcards `*` and `?`

One additional idea: A second parameter could contain either of `ERROR/WARN/INFO/NONE` telling the upgrade script how to react on a problem, e.g. file to move doesn't exist, ...

**Comment by ThomDietrich** [comment]
Hey @BClark09, I agree we should include a versioning.

* CSV doesn't support sections. We should discuss if or if not staying with the CSV syntax is of interest
* Your example only covers Upgrading. While I'm not saying we should support upgrade, the part which is currently `[2.2.0]`script should at least make clear that these are the upgrade steps from-to.

**Comment by bdleedy** [comment]
INI files? INI files have sections and there are usually great tools/extensions for using them. I know it's an odd use of the format but it might fit nicely.

**Comment by ThomDietrich** [comment]
INI creates the same issue. You have sections but only key=value pairs.

**Comment by BClark09** [comment]
When I was thinking csv, I was also thinking that whatever script could implement sections itself. In Psudocode:

```c
currentVersion=getCurrentVersion()
if (firstParam == "[*") then
  if ( * < currentVersion ) then 
    skipToNextSection 
  end
end
```

**Comment by ThomDietrich** [comment]
Well no doubt that is possible! It's just not following the standard idea of [CSV](https://tools.ietf.org/html/rfc4180) - which would be okay with me...

**Comment by BClark09** [comment]
Ah, I see. Quite honestly I didn't know there was a CSV standard as such. Every day is a school day!

**Comment by bdleedy** [comment]
@ThomDietrich 
> INI creates the same issue. You have sections but only key=value pairs.

I'm not seeing a situation in which this couldn't be used.

```
[2.0.0-2.1.0]
Move1="Here","There"
Move2="Here1","There1"
Delete1="This"

[2.0.0-2.2.0]
and so on....
```
Each possible scenario has it's own section. Keys are simply TypeNumber and some sort of delimitation if needed. Is that not what @BClark09 is describing in the 2nd comment but without the impossible nested Sections?

**Comment by BClark09** [comment]
Whilst that would be a fairly simple strategy, what would you do if you introduced 2.3.0 which has the same structure as 2.2.0? Add one for each version anyway?

In addition, The number of [From-To] you would need would be start becoming too large. For the number of versions openHAB may have (n), the number of sections would equal `(n^2)/2 + 1`

**Comment by bdleedy** [comment]
Yeah, it would be a vertically large file, whereas a .csv could be horizontally large. The two could be 'combined' even more than I am suggesting like 
`Moves=here1,there1;here2,there2;here3,there3;...`
Using the two delimiters could vertically simplify the file.

I also use an .ini with 'nesting' much like .inf drivers do.

`[MAIN SECTION]
Key1=Value1
Key2=Value2
Key3=Value3

[Value1]
Key=Value

[Value2]
...
`

This could solve the same structure between versions. 2.2.0=2.2.0 and 2.3.0=2.2.0 as well. I'm not saying this is the best or better option. But I think it's a viable one to consider.

**Comment by BClark09** [comment]
Notes for what is necessary so far:

```
[2.2.0]
MOVE $OPENHAB_USERDATA/etc/org.ops4j.pax.logging.cfg $OPENHAB_USERDATA/etc/org.ops4j.pax.logging.cfg.bak

[2.3.0]
DELETE $OPENHAB_USERDATA/etc/overrides.properties
DELETE $OPENHAB_USERDATA/org.openhab.addons.cfg
```

**Comment by BClark09** [comment]
If I might add another feature to this: Would it be worth placing breaking change messages here? For example

```
[2.2.0]
ALERT Logging configuration has changed, org.ops4j.pax.logging.cfg has been backed up and restored to defaults

[2.3.0]
ALERT Z-Wave binding has changed, users must delete and re-add Z-Wave things.
```

This way, the respective repos can use these messages to display important change logs.

**Comment by kaikreuzer** [comment]
I like the idea!

**Comment by whopperg** [comment]
Me too! Should be very useful and could minimize the support threads and troubleshooting....

**Comment by BClark09** [comment]
Alright! I've got the basics setup: With the following `update.trans` file...

```
[[PRE]]
[2.2.0]
MOVE,$OPENHAB_USERDATA/etc/org.ops4j.pax.logging.cfg,$OPENHAB_USERDATA/etc/org.ops4j.pax.logging.cfg.bak

[[POST]]
[2.2.0]
ALERT,Logging configuration has changed. 'org.ops4j.pax.logging.cfg' has been backed up and restored to defaults!

[2.3.0]
DELETE,$OPENHAB_USERDATA/etc/overrides.properties
DELETE,$OPENHAB_USERDATA/etc/org.openhab.addons.cfg
ALERT, Z-Wave binding has changed. Users must delete and re-add all Z-Wave things!
```

And the shellscript in [this gist](https://gist.github.com/BClark09/11b0cdd32f49c65fc2def1236df54b6b). I get the following output:

```
Running pre-update tasks...

Performing tasks for version 2.2.0...
Moving file: From /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg to /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg.bak

Running post-update tasks...

Performing tasks for version 2.2.0...
Warning: Logging configuration has changed. 'org.ops4j.pax.logging.cfg' has been backed up and restored to defaults!
Performing tasks for version 2.3.0...
Deleting file: /var/lib/openhab2/etc/overrides.properties
Deleting file: /var/lib/openhab2/etc/org.openhab.addons.cfg
Warning:  Z-Wave binding has changed. Users must delete and re-add all Z-Wave things!
```

I realised that there should be a distinction between tasks that we want to execute before the main upgrade, and tasks we want to execute after the upgrade.

WDYT?

**Comment by wborn** [comment]
We've been using these automated upgrades using the [update.lst](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/update.lst) and some scripts on Linux and Windows for a while now. :+1: 

Do you think we can now close this issue?

**Comment by kaikreuzer** [comment]
Sounds fair to me.
