### ISSUE TITLE
Rules not working correctly

### ISSUE THREAD

**Issue by Mr-iX** [openhab/openhab-distro#502]
I have a rule defined in OpenHAB that works fine when OpenHAB starts up.
But when I enter the file and say save and close, I get the error 

```
2017-07-29 15:08:43.433 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'mqtt-alarm.rules' is either empty or cannot be parsed correctly!
```

The mqtt-alarm.rules file:
```java
rule "Update Switch Alarm aktiviert"
when
    Item ESP8266_Switch_String received update
then
    logInfo("mqtt-alarm.rules","ESP8266_Switch_String received update")
    if(Activate_Alarm.state == ON){
        Activate_Alarm.postUpdate(OFF)
        sendCommand(ESP8266_Switch_LED, ON)
        logInfo("mqtt-alarm.rules","Alarm Switch deaktiviert")
    } else {
        Activate_Alarm.postUpdate(ON)
        sendCommand(ESP8266_Switch_LED, OFF)
        logInfo("mqtt-alarm.rules","Alarm Switch aktiviert")
    }
end
```

When I restart OpenHAB the rule works fine again

**Comment by lolodomo** [comment]
Probably not the right repo to declare the issue but you're right it is an issue, I got it yesterday.

**Comment by Mr-iX** [comment]
What would be the right repo?

**Comment by ThomDietrich** [comment]
Does this happen every time you save the rule? Could you try to reduce the rule to a Minimal Not-Working Example?

**Comment by lolodomo** [comment]
I think it was systematic in m case (I am running snapshot 988) but I have saved just few times.
It could be the same issue as with the sitemap file updated through Samba that was of size 0 during a short time ? It was recently fixed for the sitempa.

**Comment by SuperOok** [comment]
I experience the same issue. 
I got a hint from this thread: https://community.openhab.org/t/configuration-model-default-rules-is-either-empty-or-cannot-be-parsed-correctly/26309/7

It seems to be a timing issue when saving config files via some network share. I get the exception about every other save-action. I can simply save the file again and the exception might have vanished or not. In most cases I also get the message twice. 

Workaround for me is to ssh-login into my machine (RaspberryPi with openhabian in my case) and touch the corresponding file:
`touch /etc/openhab2/rules/aussenbeleuchtung.rules`

**Comment by Mr-iX** [comment]
I always edit the files directly on the server with vim and I got this error too. 
It sound logic, that this is a timing issue. So the touch command is a great workaround. Thanks for the hint!

**Comment by kaikreuzer** [comment]
Please allow me to close this issue here as it is also reported and tracked as https://github.com/eclipse/smarthome/issues/4161.
