### ISSUE TITLE
File pax-web-api-4.3.0.jar in binary release does not have read permission for others

### ISSUE THREAD

**Issue by satish-nikam** [openhab/openhab-distro#503]
When we extract openhab-2.1.0.tar.gz file, all files have read attribute to others, but the file pax-web-api-4.3.0.jar does not have read permission to others. This causes recursive copy (cp -r) to fail when issued using some other user.

Look at file permission for pax*.jar files after extraction:
-rw-r--r-- pax-logging-api-1.8.5.jar
-rw-r--r-- pax-logging-service-1.8.5.jar
-rw-r--r-- pax-url-aether-2.5.2.jar
-rw-r--r-- pax-url-wrap-2.5.2-uber.jar
**-rw------- pax-web-api-4.3.0.jar**
-rw-r--r-- pax-web-jetty-4.3.0.jar
-rw-r--r-- pax-web-runtime-4.3.0.jar
-rw-r--r-- pax-web-spi-4.3.0.jar

**Comment by kaikreuzer** [comment]
This must be due to the fact that we repackage this specific jar in the build process. If you have a fix for this, please feel free to come up with a PR!

**Comment by ThomDietrich** [comment]
looks like a umask related issue to me. 

This might be the solution: https://stackoverflow.com/questions/7478495/how-do-i-set-directory-permissions-in-maven-output

**Comment by kaikreuzer** [comment]
That's what I tried yesterday, but so far without success. Might have to fiddle around with it a bit more...
