### ISSUE TITLE
Starting openHAB service fails after upgrading to 2.1 / 2.2-SNAPSHORT

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-distro#508]
After upgrading my running 2.0 installation using the update script ("runtime/bin update") the openhab2 service doesn't start anymore properly. In an endless loop it tries starting, fails, tries starting etc.

syslog shows the following error:
Aug  6 13:03:40 raspi start.sh[16471]: Launching the openHAB runtime...
Aug  6 13:03:42 raspi start.sh[16471]: Unable to update instance pid: /usr/share/openhab2/runtime/instances/instance.properties (Permission denied)
Aug  6 13:03:42 raspi start.sh[16471]: /usr/share/openhab2/userdata/logs/openhab.log (Permission denied)
Aug  6 13:03:42 raspi start.sh[16471]: Unable to update instance pid: /usr/share/openhab2/runtime/instances/instance.properties (Permission denied)
Aug  6 13:03:42 raspi systemd[1]: openhab2.service: main process exited, code=exited, status=255/n/a
Aug  6 13:03:43 raspi stop[16631]: stop: Ignoring predefined value for KARAF_HOME
Aug  6 13:03:44 raspi stop[16631]: Can't connect to the container. The container is not running.
Aug  6 13:03:44 raspi systemd[1]: openhab2.service: control process exited, code=exited status=1
Aug  6 13:03:44 raspi systemd[1]: Unit openhab2.service entered failed state.
Aug  6 13:03:44 raspi systemd[1]: openhab2.service holdoff time over, scheduling restart.
Aug  6 13:03:44 raspi systemd[1]: Stopping openHAB 2 - empowering the smart home...
Aug  6 13:03:44 raspi systemd[1]: Starting openHAB 2 - empowering the smart home...
Aug  6 13:03:44 raspi systemd[1]: Started openHAB 2 - empowering the smart home.
Aug  6 13:03:44 raspi start.sh[16799]: Launching the openHAB runtime...
Aug  6 13:03:46 raspi start.sh[16799]: Unable to update instance pid: /usr/share/openhab2/runtime/instances/instance.properties (Permission denied)
Aug  6 13:03:46 raspi start.sh[16799]: /usr/share/openhab2/userdata/logs/openhab.log (Permission denied)
Aug  6 13:03:46 raspi start.sh[16799]: Unable to update instance pid: /usr/share/openhab2/runtime/instances/instance.properties (Permission denied)

Starting manually with "sudo ./start.sh" works and brings up the console.

pi@raspi:/usr/share/openhab2 $ ls -l
total 40
drwxr-xr-x 2 root root  4096 Aug  5 22:15 addons
drwxr-xr-x 5 root root  4096 Jul 29 22:18 bin
lrwxrwxrwx 1 root root    14 Mar  4 01:38 conf -> /etc/openhab2/
-rw-r--r-- 1 root root 11232 Jan 22  2017 LICENSE.TXT
lrwxrwxrwx 1 root root    22 Aug  5 20:24 log -> /var/lib/openhab2/logs
drwxrwxr-x 7 root root  4096 Aug  6 12:31 runtime
-rw-r--r-- 1 root root   121 Jan 20  2017 start.bat
-rw-r--r-- 1 root root    72 Jan 20  2017 start_debug.bat
-rwxr-xr-x 1 root root    73 Jan 22  2017 start_debug.sh
-rwxr-xr-x 1 root root   116 Jan 22  2017 start.sh
lrwxrwxrwx 1 root root    17 Mar  5 18:23 userdata -> /var/lib/openhab2

-rw-r--r-- 1 root root 94 Aug  6 12:51 instance.properties

pi@raspi:/usr/share/openhab2/runtime/instances $ cat instance.properties 
count = 1
item.0.name = main
item.0.loc = /var/lib/openhab2
item.0.pid = 0
item.0.root = true

pi@raspi:/usr/share/openhab2 $ systemctl status openhab2
● openhab2.service - openHAB 2 - empowering the smart home
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled)
   Active: deactivating (stop) (Result: exit-code) since Sun 2017-08-06 13:06:24 CEST; 1s ago
     Docs: http://docs.openhab.org
           https://community.openhab.org
  Process: 30912 ExecStart=/usr/share/openhab2/start.sh server (code=exited, status=255)
 Main PID: 30912 (code=exited, status=255);         : 31072 (karaf)
   CGroup: /system.slice/openhab2.service
           └─control
             ├─31072 /bin/bash /usr/share/openhab2/runtime/bin/karaf stop
             └─31227 /usr/lib/jvm/java-8-oracle/jre/bin/java -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/usr/share/openhab2/conf -Dopenhab.runtime=/usr/share/openhab2/runtime -Dop...

Reboot doesn't fix it.
Same happens with 2.2.0-SNAPSHOT from tonight.
Running OH2 on a Pi3 with Jessie.

**Comment by BClark09** [comment]
Hi @Markus7017,

I'm not quite sure I understand your paths. They indicate that you installed openhab with apt-get, but the update script is for manual installs so it would have tried updating things as if the paths were in one directory. 

Either way, all the files are owned by root, by default this should be "openhab:openhab". Have you changed this yourself?

**Comment by markus7017** [comment]
Hi @BClark09,

yes, it's an apt-get installation

If this script handles manual installations only it should be extended to 
a) detect the type of installation, show a message and abort or even better
b) update the repository information and do an apt-get update/upgrade automatically (I was assuming it does)

everything is installed under /usr/share/openhab2 and update was performed there.

which files/directories have to be owned by openhab:openhab?
Tried to change root dir to openhab:openhab - same result.

**Comment by BClark09** [comment]
Hi @markus7017, yes in the new versions of linuxpkg replace the script to tell you to update using the usual method for packages. Can I ask where you found instructions for using update?

Are you sure everything is installed under `/usr/share/openhab2`? I would expect to have your userdata in `/var/lib/openhab2` and your configuration text files in `/etc/openhab2`. 

If so, you'll need to use apt-get to fix a few things and bring you up to the expected version for all directories:

```
wget -qO - 'https://bintray.com/user/downloadSubjectPublicKey?username=openhab' | sudo apt-key add -
sudo apt-get install apt-transport-https
echo 'deb https://openhab.jfrog.io/openhab/openhab-linuxpkg unstable main' | sudo tee /etc/apt/sources.list.d/openhab2.list
sudo apt-get update
sudo apt-get upgrade
```

Then, we'll reset the ownership:

```
sudo chown -R openhab:openhab /var/lib/openhab2
sudo chown -R openhab:openhab /etc/openhab2
sudo chown -R openhab:openhab /usr/share/openhab2
```

**Comment by markus7017** [comment]
Hi @BClark09 , I went though Kai's post
https://community.openhab.org/t/openhab-2-1-is-out/30676
- it links directly to the manual update. Due to the fact that I was looking for updaing the existing installation... If you read carefully: it's directly under Manual installation - maybe a note would point it out better

yes all other directories match the standard install, I just created some sym links to point to log files, configs etc. - makes navigating the directories easier. I confuses me every time when the standard dirs change (like moving logs form /var/log/openhab2 to /var/lib/openhab2/logs)

I executed the commands you mentioned, proceed with apt-get update/upgrade and applied the chown commands. "Please stand by while UIs are being installed. This can take several minutes." took some time, but now it seems to work. Good job so far!! ;-)

The Web Ui as well as the console show " 2.2.0-SNAPSHOT" - so I upgraded to the SNAPSHOT and not 2.1.0? How to get to 2.1.0 stable - it seems that the current zwave binding has some trouble with my zwave setup, because I already saw a bunch of exceptions.

I noticed that HABMIN still displays "Version: 2.0.0, 2017-08-04T16:11:17" rather than 2.1.0/2.2.0-SNAPSHOT - it that "normal"?

**Comment by BClark09** [comment]
For the standard install, /var/log/openhab2 should always be the log directory.

Glad it's somewhat working now. I sent the instruction for snapshot because that was the last version you mentioned. Although it shouldn't be a problem to go back to 2.1.0. We just need to change to the stable repo and tell apt that you want to go to a specific version (from [the docs](http://docs.openhab.org/installation/linux.html#changing-versions)).

```
echo 'deb https://openhab.jfrog.io/openhab/openhab-linuxpkg stable main' | sudo tee /etc/apt/sources.list.d/openhab2.list
sudo apt-get update
sudo apt-get install openhab2=2.1.0-1
```

Hope that helps.

**Comment by markus7017** [comment]
great - 2.1 up and running, thanks a lot!!
new more time on fighting with the Fibaro KeyFob (gets connected, but doesn't send the keys grrr)
have a nice weekend!

**Comment by BClark09** [comment]
Glad to hear it! If you're still struggling with it, hopefully the [community forums](https://community.openhab.org/) can help!

Hope you have a good weekend too!

**Comment by markus7017** [comment]
fyi: KeyFob problem has also fixed
https://community.openhab.org/t/fibar-group-keyfob-fgkf-601-no-node-xml/26100/24
