### ISSUE TITLE
Chart Labels Scrambled

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-distro#514]
I hope this is the right place to report this bug, if it's not please point me in the right direction.

When creating chart in the 2.1.0 release the text looks scrambled. See attached image.

![chart](https://user-images.githubusercontent.com/9951871/29118772-b078c64c-7d03-11e7-8614-5585c476fc18.png)

**Comment by kaikreuzer** [comment]
Looks as if this is a local font problem on your system.
Check http://demo.openhab.org:8080/basicui/app?w=0100&sitemap=demo, where all is fine (demo server is running 2.1 release on Ubuntu).
I'd suggest you ask for help in our community at https://community.openhab.org/ to figure out what is wrong on your system.

**Comment by Flole998** [comment]
Kinda weird as it was working before the upgrade. I will ask in the community though, maybe someone has an idea over there.

**Comment by Flole998** [comment]
I asked in the community (https://community.openhab.org/t/oh2-1-fonts-scrambled/33050) but haven't received an answer. I reinstalled the fonts, this has not fixed the issues. What can be done to debug this issue? Which font is supposed to be used for the Labels?

**Comment by Flole998** [comment]
This issue does not happen when using rrdchart.png. This looks more and more like a bug to me, I reinstalled java including all the fonts, the issue is still present.
