### ISSUE TITLE
Time cron rules stop working every few days

### ISSUE THREAD

**Issue by FrankR59** [openhab/openhab-distro#521]
All of my Time cron rules stop working every few days. There are no entries in the logs showing an error regarding my rules.
This problem started with 2.1.0 stable and also exists in 2.2.0 build #1003.

**Comment by kaikreuzer** [comment]
Please try to analyze what causes your problem. There is no general issue as you can see on our demo server, which runs 2.1.0: http://demo.openhab.org:8080/basicui/app?w=0100&sitemap=demo
The demo.rules resets the min/max every day by a cron rule.
If you can provide a short example rule that indeed reproducibly causes an issue, please report it at github.com/eclipse/smarthome/issues. Thanks!
