### ISSUE TITLE
Using secure lock in openhab2

### ISSUE THREAD

**Issue by rindraloic** [openhab/openhab-distro#522]
Hello,
I'm currently trying to integrate my lock to openhab2. 
The device is a [Danalock v2 circle](https://products.z-wavealliance.org/products/1251), z-wave enabled. I use the binding found [here](https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653) which currently supports security.
I've successfully added the thing using HABmin and linked the item to the channel, but I can't lock/unlock the danalock from openhab.
I'm currently new to openhab, but I think it might have something to do with secure inclusion, but I don't know how to do it.
In the logs, it says: ``Command class COMMAND_CLASS_DOOR_LOCK not found``
What am I doing wrong? What am I missing?

Thanks in advance

**Comment by kaikreuzer** [comment]
I'd guess our community is the best place to find help on that: https://community.openhab.org/

**Comment by rindraloic** [comment]
Okay thanks, I've posted the issue on both platforms just in case
