### ISSUE TITLE
Umlaut problem in openHAB 2.2.0 Build 1023 

### ISSUE THREAD

**Issue by claell** [openhab/openhab-distro#525]
Umlauts are not displayed correctly for me in PaperUI.
Example:
"Pingable NetzwerkgerÃ¤t

Die VerfÃ¼gbarkeit des GerÃ¤ts wird mit ICMP Ping, ARP Ping und DHCP Paketen festgestellt."

I have set the language and region to German/Germany.

**Comment by kaikreuzer** [comment]
@davidgraeff Can you confirm this problem?

**Comment by davidgraeff** [comment]
Confirmed, i'll add the fix to https://github.com/openhab/openhab2-addons/pull/2580

**Comment by davidgraeff** [comment]
@kaikreuzer The file has broken umlaute in eclipse, because it is in utf8 and eclipse expect it an iso 8859-15, I guess. What is the official encoding for i18n files to be transferred correctly via the rest interface?

**Comment by kaikreuzer** [comment]
According to the Java specification, any property file has to be in ISO8859-1 format, so Eclipse is right here - make sure you edit the files in Eclipse and not in any (UTF-8) editor.

**Comment by davidgraeff** [comment]
Puh, that java specification must be really dated. I thought the IT world agreed on UTF-8.
I convert the file and upload.

**Comment by kaikreuzer** [comment]
Well, Java is from the mid 90s and property files were one of the first things to be specified :-)

**Comment by claell** [comment]
Oh, I guess it was my fault, I corrected a typo in that file with the GitHub editor and it has been changed to utf8 there. I didn't know that would be an issue: https://github.com/openhab/openhab2-addons/pull/2576

Sorry for the inconvenience.

**Comment by claell** [comment]
Can confirm this is fixed, thanks again!
