### ISSUE TITLE
openhab2 incorrectly does not depend on java

### ISSUE THREAD

**Issue by RREE** [openhab/openhab-distro#526]
I could install openhab2 on a raspian (Jessie) system without previous installation of any java runtime. 

I created /etc/apt/sources.list.d/openhab2.list with the following contents: 
deb https://dl.bintray.com/openhab/apt-repo2 stable main
$ aptitude update
$ aptitude install openhab2
worked without any mention of java.

Only when looking into journalctl I saw the following lines:
Aug 28 21:15:51 z3 start.sh[524]: /usr/share/openhab2/runtime/bin/setenv: line 176: type: java: not found
Aug 28 21:15:51 z3 start.sh[524]: /usr/share/openhab2/runtime/bin/setenv: line 179: die: command not found

**Comment by kaikreuzer** [comment]
Could you please report this at https://github.com/openhab/openhab-linuxpkg/issues as this is the repo that deals with Linux packaging? Thanks!

**Comment by BClark09** [comment]
Please note that for the later versions of openHAB, apt will now _recommend_ Java. 

We cannot depend on it as there are many different ways of including it. For example, via manual extraction, or by installing either one of Zulu/Oracle/open JDK.
