### ISSUE TITLE
Cannot build sources of the 2.1.0 release

### ISSUE THREAD

**Issue by mcloarec** [openhab/openhab-distro#529]
Hi, 

I need to use the 2.1.0 branch of openhab for a project for my company.
To do that I follow the steps for setting up the IDE via eclipse-installer.
Then I check out the 2.1.0 tags of openhab and the 0.9.0.b5 tag of smarthome.

The problem is that the file openhab.target in the openhab-distro/launch directory cannot retrieve artefacts from : 
- https://dl.bintray.com/openhab/p2/openhab-core/2.1.x/
- https://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.12/
- http://download.eclipse.org/releases/luna/201502271000

It seems that these repo are empty or that the artefacts are missing

The consequences are that the IDE cannot compile the sources and that I cannot develop because all the projects and plugins are showing errors everywhere.

Is ther a way to stick to a tag in order to not be disturbed by irrelevant commits or by bugs like #519 

Thanks in advance

Regards

Matthieu

**Comment by kaikreuzer** [comment]
Did you make any progress on this?

> It seems that these repo are empty or that the artefacts are missing

Well, if you look into them, they are all filled. The only problematic one might be the first one as its content is regularly replaced (as the 2.1.x name suggests). But you should be able to simply import all openhab-core projects in your workspace and completely remove that repo from your targetplatform, if it causes issues.

**Comment by kaikreuzer** [comment]
Assuming you found a solution, I close this issue. Feel free to reopen it any time.

**Comment by maniac103** [comment]
I, for one, still have this problem. When checking out the tags above (checking out the 2.1.0 tag in openhab-distro is sufficient), I get the following resolving error:

`Eclipse SmartHome Item Model IDE 0.9.0.201712011551 (org.eclipse.smarthome.model.item.ide 0.9.0.201712011551) requires 'bundle org.eclipse.xtext.ide 0.0.0' but it could not be found`

This dependency seems to be supposed to be satisfied from the http://download.eclipse.org/smarthome/updates-stable repo, but seemingly can't be resolved from there?
How am I supposed to continue from there?

**Comment by kaikreuzer** [comment]
@maniac103 That indeed looks as if the target platform that it builds again is a moving target. We really should avoid to build against dynamic p2 repos. I'd have to analyze it in detail, but won't find much time the next days.

Will it help you if I tell you that there will be a 2.2 release next Monday, which will hopefully work better?

**Comment by maniac103** [comment]
@kaikreuzer It would certainly help if https://github.com/openhab/openhab2-addons/pull/2932 was included, which is why I wanted to build 2.1.0 in the first place :-) (intention was deploying an updated Homematic binding for the existing installation)

**Comment by kaikreuzer** [comment]
Ok, thanks, then let's focus on getting that PR in the release and not spend time on 2.1 reconstructions...
