### ISSUE TITLE
Please add support for GoControl GC-TBZ48

### ISSUE THREAD

**Issue by justinpitts** [openhab/openhab-distro#532]
I have included two of these thermostats in my zwave network, but both show as unknown devices with populated mfg and device id.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/622

**Comment by kaikreuzer** [comment]
The repo you are looking for is probably https://github.com/openhab/org.openhab.binding.zwave/issues.
