### ISSUE TITLE
playSound not working

### ISSUE THREAD

**Issue by rgerrans** [openhab/openhab-distro#536]
I'm running the 20170910 build and playSound isn't working.  I verified the rule is running and the sound sink is still configured.  I don't see any errors in the log file

**Comment by kaikreuzer** [comment]
```
rule "Test playSound"
    when
        System started
    then
        playSound("doorbell.mp3")
end
```

works perfectly for me with a plain install and the demo setup.

Please seek for help in our forum https://community.openhab.org/ on how to figure out what is wrong in your setup.
