### ISSUE TITLE
 Jar files are touched and fill up ramdisk although they are not modified

### ISSUE THREAD

**Issue by lauhub** [openhab/openhab-distro#539]
## Context

I run OpenHab on a development box under Debian 8 (Armbian Jessie) and I set an [`overlayfs`](https://www.datalight.com/blog/2016/01/27/explaining-overlayfs-%E2%80%93-what-it-does-and-how-it-works/). This makes the mass storage device to be safe (mounted as read-only), even with power breakage.

This overlay FS is schematically a RamDisk that receives all write operations and store them while the permanent storage is read as an underlayer. Writing on the overlay FS effectively writes in the ramdisk, not in the permanent storage device.

If electric power is lost, all changes in RamDisk are lost, but the permanent storage is not altered.

Any file that is [`touch`ed](https://en.wikipedia.org/wiki/Touch_(Unix)) is copied (duplicated) from the underlying permanent storage to the RamDisk. So it occupies some RAM even if its content did not change

## Expected Behavior

When running `openhab2` only some files should be modified and the footprint in RamDisk should be kept low. Installed addons JAR files should not be modified since they are not updated or re-installed.

## Current Behavior

At startup or after startup, `openhab2` `touch`es (in the UNIX way of the term) several jar files [(see link with list of addons' touched files)](https://gist.github.com/lauhub/09db500a12543d6c7f7dd49eb9d2751c) and fills up the RamDisk with about 141MB of unuseful data

By unuseful I mean that these files are not modified: md5 sum of both RamDisk and permanent storage are identical

Current ramdisk is 512MB, which leads to some crash if it is filled up. I am limited to this size (total amount of RAM : 1GB) and this *cannot* be changed since the box cannot have more RAM 

## Possible Solution

 - Remove the `touch` operation for the file if it already exists. And if the file does not exist, create it
 - Setup the `/var/lib/openhab2/kar/openhab-addons-2.1.0` as read-only (but this may lead to bug when installing or updating addons ?)

## Steps to Reproduce (for Bugs)

1. Create a read-only system with an overlayroot (under Ubuntu using the overlayroot package).
2. Install openhab2
3. use `df -h` to show ramdisk usage

## Environment

* Version used: 2.1.0
* Addons list: see [this gist](https://gist.github.com/lauhub/09db500a12543d6c7f7dd49eb9d2751c)
* Environment name and version : java version "1.8.0_131"
* Operating System and version: Armbian Jessie

**Comment by kaikreuzer** [comment]
A mentioned [here](https://github.com/openhab/openhab2-addons/issues/2721#issuecomment-331085962), I doubt that this can be changed in openHAB itself as it is a mechanism of Apache Karaf.

Did you already seek for help in the Karaf community? If there is an issue in their tracker about this, please make sure to link to it here.

**Comment by lauhub** [comment]
@kaikreuzer I filled an [issue (#5386)](https://issues.apache.org/jira/browse/KARAF-5386) on Karaf project: https://issues.apache.org/jira/projects/KARAF

**Comment by kaikreuzer** [comment]
@lauhub It would probably be better if you would report it there more tailored to Karaf - I am not sure if they are very eager trying to reproduce the problem by installing openHAB. You could verify that the very same behavior is there with a plain Karaf installation.

**Comment by lauhub** [comment]
@wborn I am not sure it is fixed: I had some similar issue (memory filled up) with 2.2.0 but I cannot not confirm for now (I could not check which files were involved). As soon as I have some time, I will check and let you know (next week or the week after)

**Comment by wborn** [comment]
Is this still an issue in openHAB 2.4.0 or newer?

**Comment by wborn** [comment]
Since there has been no response, let's assume this is no longer an issue.
