### ISSUE TITLE
OpenHAB 2 snap package outdated

### ISSUE THREAD

**Issue by DarkLite1** [openhab/openhab-distro#542]
When trying to install the OpenHAB 2 snap package from the command line it appears only version `2.0.0` is published as `Stable` while the website advertises version `2.1.0` to be the latest `Stable` available:

```
[b@machine~] sudo snap info openhab 
name:      openhab
summary:   "openHAB smart home server"
publisher: openhab
contact:   snappy-canonical-storeaccount@canonical.com
description: |
  openHAB - a vendor and technology agnostic open source automation software for
  your home.
  
snap-id: WpdPxW72JupkC8XTgaJsig3LEHdrR56x
commands:
  - openhab.clean
  - openhab.client
  - openhab.debug
  - openhab.help
  - openhab.start
  - openhab.status
  - openhab.stop
tracking:    stable
installed:   2.0.0 (167) 85MB -
refreshed:   2017-03-09 01:35:32 +0100 CET
channels:                         
  stable:    2.0.0          (167) 85MB -
  candidate: 2.0.0          (180) 85MB -
  beta:      2.0.0-SNAPSHOT (179) 85MB -
  edge:      2.1.0-SNAPSHOT (190) 86MB -
```

I've also read somewhere that version `2.2.0` is in development now. Should that not be the one that should be in the `Edge` channel?

Is it possible to update the packages in the snap store to the latest and greatest? 

Thank you for your help.

**Comment by kaikreuzer** [comment]
Please note that the snap package is maintained at https://github.com/openhab/openhab-snap, so that would be the better repo to ask - best if you directly ping @kubiko and @r2geo there as they are the maintainers.

**Comment by DarkLite1** [comment]
Thank you @kaikreuzer , opened an `issue` [there](https://github.com/openhab/openhab-snap/issues/8) now.
