### ISSUE TITLE
apt-repo2 testing is older than stable

### ISSUE THREAD

**Issue by klaernie** [openhab/openhab-distro#545]
Hi there,

I installed openHAB for the first time and decided to go for testing packages, as they promise a trade off between freshness and stability. Two days later I noticed that openhab.org offers downloads for version 2.1 where I had 2.0.0-RC1 installed.

My expectation was, that the versions in the repositories always fulfill `unstable >= testing >= stable`.
If this promise is not fulfilled the documentation should state that testing and stable repositories should be active at the same time (the only other possibility interpreting the docs).

Thanks and kind regards,
Andre

**Comment by kaikreuzer** [comment]
Please report this at https://github.com/openhab/openhab-linuxpkg/issues - thanks!

**Comment by ThomDietrich** [comment]
@BClark09
