### ISSUE TITLE
Update setenv to reflect changes in new Karaf

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-distro#546]
From https://github.com/openhab/openhab-linuxpkg/issues/79#issuecomment-325964858 

>thinking about it, we should probably update setenv and remove the duplicated functions that are already set in inc. Since inc is called first, I'm assuming the definitions in setenv are useless.

`setenv` now contains functions that aren't used, and are improved upon in `inc`. So I'd suggest removing these from `setenv`, and if necessary sourcing `inc` as a replacement.

**Comment by kaikreuzer** [comment]
@BClark09 Just updated to Karaf 4.1.3 - might be a good moment to sync the setenv changes (I didn't touch it in for upgrade)!

**Comment by kaikreuzer** [comment]
@BClark09 Do we have to do anything here?

**Comment by BClark09** [comment]
Nothing vital at the moment. None of the functions in openHAB's version of the script are used.

I will be submitting a PR though so if you could add me to the assigned list that would remind me to do it 😁

**Comment by BClark09** [comment]
Hi @kaikreuzer I completely forgot about this and had a chance to look into it. Removing the duplicated functions brings back the warning that JAVA_HOME is not set (I figure this is why they were here in the first place).

Is suppressing that warning still desirable? IMO setting JAVA_HOME is good practice and at least it will give some indication of what could be happening if openHAB isn't starting up because the default Java is incompatible.

**Comment by kaikreuzer** [comment]
> Is suppressing that warning still desirable? 

I am uncertain about that. Is there any actual risk if JAVA_HOME is not set? If not, I would say that there mustn't be a warning either then.

**Comment by BClark09** [comment]
I can't think of any risk to a typical user. Although for us it would mean monitoring changes in Karaf `inc` functions and updating setenv each update.

**Comment by kaikreuzer** [comment]
Then I would prefer to leave the suppression in.
