### ISSUE TITLE
Karaf console hangs after some minutes Build #1051

### ISSUE THREAD

**Issue by gnalbandian** [openhab/openhab-distro#548]
Hi, I am having issues with the karaf console.
I am using a Raspberry Pi 3 with Jessie.

While reading logs (log:tail)  sometimes I press down enter key a couple of times to make some space as a reference for incoming new log lines.
When I do this, the console hangs, and after a couple of minutes the connections timeout and gives putty error.

When I reconnect to OH2, and do a log:tail there si no mention about any error.

EDIT: It's not happening all the time. Yet to discover what causes this. I am using a brand new and clean installation, no bindings nor config files

**Comment by kaikreuzer** [comment]
Is this still happening for you?
With 2.2.0, we have updated to a recent Karaf version, so I would hope that this might have fixed your issue (whatever was its cause).

**Comment by Stefan136** [comment]
Hello Kai,
I have the same behavior on my OH2.2 stable release running on QNAP.
Sometimes the output hangs when doing a log:tail.
Sometimes the session was terminated without reason.
I was alwas able to ssh to the Karaf console without problems however.

I also recognized a strange behavior when issue the ‚logout‘ command. 
Maybe this is a misunderstanding on my side however.

When accessing the Karaf console the banner is mentioning the ‚Logout‘ command  is shutting down the system.

`Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.`

Usually I use ‚logout‘ to exit the Karaf console to go back to the Linux system.
Sometimes however this command is really shutting down OH2.2 ?!
If this is happening, it is not possible to use SSH to login to the Karaf Console again.
Instead I have to restart OH.

I didn’t see this behavior in OH2.0 before.

Do you have any idea?

Thanks
Stefan

**Comment by wborn** [comment]
If this is still an issue in OH3, please let us know.
