### ISSUE TITLE
PaperUI missing

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-distro#550]
Somewhere around snapshot #1048, my PaperUI got lost. Now running #1056. 
It's still configured but does not appear on the web page next to habmin and basicui.
Then again, _occasionally_ after a OH restart, it used to be back. But after most restarts, it's gone.
Seems like a Karaf issue to me, it's not started. 

openhab> bundle:list|grep -i pap
196 │ Active    │  80 │ 0.9.0.201709260841     │ Eclipse SmartHome Paper UI
213 │ Installed │  75 │ 2.2.0.201710051832     │ openHAB Paper UI Theme Fragment

Can't start a fragment, though.
Tried to play with karaf.startlevel.bundle=75 or 100, but no difference.

I can see the 'Starting PaperUI' line in the logs, what else would I need to watch out for in the logs ?

**Comment by kaikreuzer** [comment]
Could you check whether it is only missing on the dashboard or if it is generally not available?

Try accessing it on http://localhost:8080/paperui/index.html directly to find out.

**Comment by mstormi** [comment]
Oops, you got me, I didn't check. Yes it IS there, operable, too. It was just missing on the dashboard.
And after installing #1058, it's back on the dashboard, too, and PaperUI fragment is 'Resolved' now... then again, that might be coincidence, as mentioned I had seen this intermittent behavior before. Will try a couple of restarts and report back.

**Comment by mstormi** [comment]
Following up, after my restart this morning, PaperUI is gone fishing again.
Missing on dashboard, but available on direct access. Bundle fragment in Installed state.
Noteworthy: direct access shows a different UI theme (darkblue-white, I guess it's the original ESH one ?)

**Comment by kaikreuzer** [comment]
Yes, the blue theme comes up if the fragment is not resolved (or rather not considered by the Paper UI bundle).
I have seen this effect from time to time as well. The start level of the fragment is already set to 75 (which probably does not have any effect at all as fragments are anyhow not started).
We somehow would have to make sure that Karaf installs the fragment before the bundle or at least refreshes the bundle as soon as the fragment is installed. Not sure how to best do that in Karaf, though...

**Comment by mstormi** [comment]
Worth to find out... there must be Karaf experts to be able to tell, mustn't it ? Ever tried to post a [Karaf issue](https://karaf.apache.org/community.html)  ?
My even bigger problem actually is that [I need to make sure rules are loaded after things & items](https://github.com/openhab/openhab-distro/issues/531). Today I need to manually move them away on restarts and then back. To make Karaf dependencies handle this automatically as well would be a solution to my lockup problem and it's definitely a desirable change anyway.
I talked to @davidgraeff on that. Not sure he can help but he seems to know quite some Karaf stuff and told me that comparable things had been implemented in OH before.

**Comment by mstormi** [comment]
Just found  [ESH #3771](https://github.com/eclipse/smarthome/issues/3771) which points to [ESH #1896](https://github.com/eclipse/smarthome/issues/1896).
According to @sjka this is the root that needs to be tackled. But there's no progress in several months.

**Comment by mstormi** [comment]
PaperUI missing is a slightly different story, yes, but my comment was referring to my request to not start rule execution until items are properly loaded. According to your closing comment in [ESH #3771](https://github.com/eclipse/smarthome/issues/3771), this is what [ESH #1896](https://github.com/eclipse/smarthome/issues/1896) is about. Or has that changed ?

**Comment by sjka** [comment]
Ah, sorry, I was fooled by the title and got the context wrong. Regarding rule execution your are fully correct, https://github.com/eclipse/smarthome/issues/1896 is about exactly that problem.

**Comment by mstormi** [comment]
Running #1060 now, PaperUI still missing.
Does this provide a hint ?
```
openhab> bundle:list|grep -i pap
196 │ Active    │  80 │ 0.9.0.201710101404     │ Eclipse SmartHome Paper UI
214 │ Installed │  75 │ 2.2.0.201710112009     │ openHAB Paper UI Theme Fragment
openhab> bundle:diag 214
openHAB Paper UI Theme Fragment (214)
-------------------------------------
Status: Installed
Unsatisfied Requirements:
osgi.wiring.package; filter:="(osgi.wiring.package=org.eclipse.jdt.annotation)"; resolution:="optional"
Declarative Services
openhab>  bundle:tree-show 214
Bundle org.openhab.ui.paperui [214] is currently INSTALLED
- import org.eclipse.jdt.annotation;resolution:=optional: WARNING - unable to find matching export
- import org.openhab.ui.dashboard: resolved using org.openhab.ui.dashboard_2.2.0.201710112009 [171]

Warning: the below tree is a rough approximation of a possible resolution
org.openhab.ui.paperui [214]
+- org.openhab.ui.dashboard [171]
   +- org.apache.felix.configadmin [7]
   +- javax.servlet-api [32]
   +- org.eclipse.smarthome.core [100]
   |  +- org.apache.commons.lang [39]
   |  +- org.apache.felix.scr [40]
   |  |  +- org.apache.felix.configadmin [7]
   |  |  +- org.apache.felix.metatype [2]

[...]
```

**Comment by htreu** [comment]
I experience a similar issue when adding the org.openhab.ui.paperui fragment bundle to the ESH IDE setup:
```
osgi> lb | grep Paper
   67|Active     |    4|Eclipse SmartHome Paper UI (0.9.0.qualifier)
  112|Resolved   |    4|openHAB Paper UI Theme Fragment (2.2.0.qualifier)
true
osgi> bundle 67
org.eclipse.smarthome.ui.paper_0.9.0.qualifier [67]
  Id=67, Status=ACTIVE      Data Root=/Users/henning/work/smarthome-master2/ws/.metadata/.plugins/org.eclipse.pde.core/SmartHome-Runtime/org.eclipse.osgi/67/data
  "Registered Services"
    {java.lang.String}={service.id=284, service.bundleid=67, service.scope=singleton, service.ranking=2147483647, osgi.http.whiteboard.context.select=(service.id=283), equinox.legacy.tccl=org.eclipse.osgi.internal.framework.ContextFinder@5884f90, osgi.http.whiteboard.resource.pattern=/paperui/*, osgi.http.whiteboard.target=(equinox.http.id=-6148548114651673562), osgi.http.whiteboard.resource.prefix=web}
    {org.openhab.ui.dashboard.DashboardTile}={service.id=285, service.bundleid=67, service.scope=bundle, component.name=org.openhab.ui.paperui.dashboardtile, component.id=173}
  Services in use:
    {org.osgi.service.http.HttpService, org.eclipse.equinox.http.servlet.ExtendedHttpService}={service.description=Equinox Servlet Bridge, service.id=175, service.bundleid=140, service.scope=bundle, osgi.http.endpoint=[/], equinox.http.id=-6148548114651673562, service.vendor=Eclipse.org}
    {org.osgi.service.http.context.ServletContextHelper}={equinox.legacy.context.helper=true, service.id=283, osgi.http.whiteboard.context.name=org_eclipse_equinox_http_servlet_internal_HttpServiceImpl_DefaultHttpContext-13, service.bundleid=140, service.scope=bundle, equinox.legacy.http.context.initiating.id=67, osgi.http.whiteboard.target=(equinox.http.id=-6148548114651673562), osgi.http.whiteboard.context.path=/}
    {org.osgi.service.log.LogService, org.eclipse.equinox.log.ExtendedLogService}={service.id=2, service.bundleid=0, service.scope=bundle}
  No exported packages
  Imported packages
    org.openhab.ui.dashboard; version="0.0.0" <org.openhab.ui.dashboard_2.2.0.qualifier [82]>
    org.osgi.service.component; version="1.3.0" <org.eclipse.osgi.services_3.6.0.v20170228-1906 [119]>
    org.osgi.service.http; version="1.2.1" <org.eclipse.osgi.services_3.6.0.v20170228-1906 [119]>
    org.slf4j; version="1.7.2" <org.slf4j.api_1.7.2.v20121108-1250 [4]>
  Fragment bundles
    org.openhab.ui.paperui_2.2.0.qualifier [112]
  No required bundles
```

It shows the fragment as `Resolved` which I guess is the correct status for a fragment. In comment https://github.com/openhab/openhab-distro/issues/550#issuecomment-335954929 it is shown as `Installed` which is not correct for the fragment to be picked up.

**Comment by wborn** [comment]
Perhaps the fix for [KARAF-5446](https://issues.apache.org/jira/browse/KARAF-5446) in the forthcoming Karaf 4.1.4 release will also solve our fragment resolution issues.

**Comment by kaikreuzer** [comment]
Sounds similar indeed. I have added a "Karaf" label, so that we can easily find the issues that might be solved upon the next Karaf upgrade in openHAB.
