### ISSUE TITLE
Logging in Karaf not working

### ISSUE THREAD

**Issue by nickde9999** [openhab/openhab-distro#551]
Hi, in 2.2.0 log:tail in the karaf console is blank. Was working in stable. 
Nick

**Comment by BClark09** [comment]
Hi @nickde9999,

How did you update? I'm guessing via apt or yum?: You may have missed [this notice]( https://community.openhab.org/t/karaf-upgrade/33208) and ignored the suggestion of replacing  `org.ops4j.pax.logging.cfg`

Nonetheless, you should be able to get logging back by moving the new config (which has now been temporarily stored as `org.ops4j.pax.logging.cfg.dpkg-dist`) over the old. e.g:

```
sudo mv /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg.old
sudo mv /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg.dpkg-dist /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg
```

**Comment by nickde9999** [comment]
Hi
That was indeed the problem, I assumed i needed to keep my config as I enabled debugging.
Thanks for the very quick response

**Comment by BClark09** [comment]
Hi @nickde9999, no problem! 

You will need a slightly different syntax to keep the same logging configuration, but hopefully it should be straight forward to re-apply. If you need an example then I find [this community topic](https://community.openhab.org/t/log4j2-sample-config/33284?u=benjy) very helpful!
