### ISSUE TITLE
Bonjour/MDS Service keeps waiting

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-distro#552]
I have been seeing Bonjour/MDS stuck in 'Waiting' state forever and throughout many OH snapshots versions.
Not even sure what it's good for (Homekit?), and I don't see any direct impact, so it ain't urgent in any way, albeit a couple of observed quirks might be related.
Either way, shouldn't that dependency get resolved properly?

```
openhab> bundle:list|grep -i discover
 97 │ Active   │  80 │ 0.9.0.201710101404     │ Eclipse SmartHome Configuration Discovery
123 │ Waiting  │  80 │ 0.9.0.201710101404     │ Eclipse SmartHome Bonjour/MDS Service Discovery Bundle
openhab> bundle:diag 123
Eclipse SmartHome Bonjour/MDS Service Discovery Bundle (123)
------------------------------------------------------------
Status: Waiting
Declarative Services
org.eclipse.smarthome.io.transport.mdns.discovery (131)
  missing references: MDNSDiscoveryParticipant
```

**Comment by kaikreuzer** [comment]
This is absolutely ok.
mDNS is something like UPnP - it is a way to discover devices on your local network. The MDNSDiscoveryService only needs to become active in the system if there is a binding that wants to use mDNS for discovery of Things for which it registers an MDNSDiscoveryParticipant. As long as no such service is registered, there is no need for the bundle to become active.
