### ISSUE TITLE
Fresh installation of IDE does not work

### ISSUE THREAD

**Issue by ppieczul** [openhab/openhab-distro#556]
Upon installing IDE the target definition has lots of errors and compilation failes with 50K+ errors. Reported by multiple users also at https://github.com/eclipse/smarthome/issues/4418

![image](https://user-images.githubusercontent.com/10254718/31587701-79c0ba16-b1e6-11e7-828c-6b84c3d5cec8.png)

**Comment by kaikreuzer** [comment]
It seems that a recent new Oxygen release on Oct 9 brought in a new version of Equinox which is incompatible with the dependencies we have in openhab-deps-repo. Will have to check how to best bring this back into sync.

**Comment by lsafelix75** [comment]
wondering what is the workaround at the moment? like can we use old equinox version and steps involved to do it?

**Comment by kaikreuzer** [comment]
Should be fixed by #557. Please pull the latest master from openhab-distro.

**Comment by sprehn** [comment]
I can confirm, it is working again for me.
