### ISSUE TITLE
Distro should not require JDK - JRE should be enough

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#56]
See https://community.openhab.org/t/oh2-karaf/5992/4?u=kai

**Comment by kaikreuzer** [comment]
Hi @dvanherbergen, As you are back on the project right now, maybe I can ask you for another favor? :-) Do you happen to remember the details on why Karaf required a full JDK instead of the JRE? Is there any way to address this (e.g. by requesting some fix on the Karaf side)?

**Comment by dvanherbergen** [comment]
It doesn't look like this is still is an issue on Windows.  
 
On Windows 10, with the 64-bit versions of JRE 7 and 8, openHAB starts without issues. 
 
With the 32-bit versions of JRE 7 & 8, I had to manually set JAVA_HOME. After that, openHAB starts correctly, but does display a warning. The warning was introduced as the result of this issue https://issues.apache.org/jira/browse/KARAF-1695, but can be safely ignored.
 
```
Launching the openHAB runtime... 
WARNING: Running Karaf on a Java HotSpot Client VM because server-mode is not available. 
Install Java Developer Kit to fix this. 
For more details see http://java.sun.com/products/hotspot/whitepaper.html#client 
 
                          __  _____    ____ 
  ____  ____  ___  ____  / / / /   |  / __ ) 
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  | 
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ / 
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/ 
    /_/                        2.0.0-SNAPSHOT 
                               Build #500 
```

**Comment by kaikreuzer** [comment]
Hm, ok, interesting. I will have to test this again on a Raspberry Pi as well, but it appears it was only a problem on WIndows indeed. After a successful test on ARM, we can hence close this issue.

**Comment by thopiekar** [comment]
Don't know whether it is relevant or not, but openHAB2 is working here on my QNAP NAS with JRE for a long time without any problems.
If OH2 wasn't working for sure in the past, then the  AppCenter of my NAS is lying that only JRE (without JDK) is in their package.

**Comment by kaikreuzer** [comment]
ok, thanks. Seems as if we can safely close this issue.
