### ISSUE TITLE
Switch items are mistaken for colorpickers in PaperUI

### ISSUE THREAD

**Issue by tommy2d** [openhab/openhab-distro#560]
I added a Thing for a sylvania/Osram rgbw light bulb and attach a Switch item to this color channel, the item turns into a colorpicker in PaperUI. Even if I attach multiple items (Switch, Dimmer, Colorpicker) all of them will yield a colorpicker in PaperUI. I already tried a clean install and both stable 2.1 and nightly 2.2. The problems is the same everywhere.

Things.json:
`
  "osramlightify:rgbw:84-18-26-00-00-CA-DC-18": {
    "class": "org.eclipse.smarthome.core.thing.internal.ThingImpl",
    "value": {
      "label": "Woonkamerlamp",
      "bridgeUID": {
        "segments": [
          "osramlightify",
          "gateway",
          "017ae8f0"
        ]
      },
      "channels": [
        {
          "acceptedItemType": "Color",
          "kind": "STATE",
          "uid": {
            "segments": [
              "osramlightify",
              "rgbw",
              "84-18-26-00-00-CA-DC-18",
              "color"
            ]
          },
          "channelTypeUID": {
            "segments": [
              "osramlightify",
              "color"
            ]
          },
          "label": "Color",
          "description": "Controls the color and brightness of the light. Can also be used to switch the light on and off.",
          "configuration": {
            "properties": {}
          },
          "properties": {},
          "defaultTags": []
        }
`

Item.json:
`
"Woonkamerlamp_OnOff": {
    "class": "org.eclipse.smarthome.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [],
      "itemType": "Switch",
      "tags": [],
      "label": "On/Off"
    }
  }
`

ItemChannelLink.json:

`
  "Woonkamerlamp_OnOff -\u003e osramlightify:rgbw:84-18-26-00-00-CA-DC-18:color": {
    "class": "org.eclipse.smarthome.core.thing.link.ItemChannelLink",
    "value": {
      "channelUID": {
        "segments": [
          "osramlightify",
          "rgbw",
          "84-18-26-00-00-CA-DC-18",
          "color"
        ]
      },
      "itemName": "Woonkamerlamp_OnOff"
    }
  }
`

**Comment by kaikreuzer** [comment]
The Paper UI is mainly meant for testing the linked channels of a thing, so it only checks whether it is linked and then renders the best matching widget for the channel (which is the colorpicker in that case).

If you feel that it should take the item (but which, if there are multiple?) into account, please file an issue at https://github.com/eclipse/smarthome/issues (this is where the Paper UI is maintained). Thanks!
