### ISSUE TITLE
Backend EventSource always failing/offline in PaperUI

### ISSUE THREAD

**Issue by hotzen** [openhab/openhab-distro#561]
when doing `log:tail` the following error is reported when reloading PaperUI:
`21:09:31.057 [ERROR] [e.internal.WriterInterceptorExecutor] - MessageBodyWriter not found for media type=text/event-stream, type=class org.glassfish.jersey.media.sse.OutboundEvent, genericType=class org.glassfish.jersey.media.sse.OutboundEvent.`

this means the browser is not able to use the event-stream rest-api to get updated into PaperUI and is always re-subscribing which works for the first few events, then fails again, continously.

using 
`  2.1.0   - release build -`

**Comment by kaikreuzer** [comment]
Could you try to reproduce on the latest snapshot build? I have never seen such a message, I doubt that it is a general issue.
If you can reproduce it, please enter an issue at github.com/eclipse/smarthome/issues with details on your setup (OS, version of browser and similar helpful info). Thanks!
