### ISSUE TITLE
Windows .bat files stroed in Unix format in ...\openhab-2.1.0\runtime\bin

### ISSUE THREAD

**Issue by WaldGrisBang** [openhab/openhab-distro#562]
The following *.bat are stored in unix format (LF only instead of CR/LF). Makes it a bit difficult to track down startup problems on a windows box.

C:\openHAB2\openhab-2.1.0\runtime\bin\setenv.bat
C:\openHAB2\openhab-2.1.0\runtime\bin\status.bat
C:\openHAB2\openhab-2.1.0\runtime\bin\stop.bat

**Comment by bdleedy** [comment]
I'll see if I can get this fixed tonight.

**Comment by kaikreuzer** [comment]
I briefly looked into it - most files are not from our repo, but created by the karaf packaging.

So what is needed is an adaption of the Maven assembly descriptor - just like we already [do it for the start.bat](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/descriptors/archive.xml#L80).

**Comment by kaikreuzer** [comment]
#607 might solve this, but I am not sure, though (see my comment on it).

**Comment by kaikreuzer** [comment]
Closing it as outdated and assuming it was fixed by #607.
