### ISSUE TITLE
Build #1080 Eclipse SmartHome Core Thing stays in state "Waitng"

### ISSUE THREAD

**Issue by gdgeist** [openhab/openhab-distro#565]
Build #1080 Eclipse SmartHome Core Thing stays in state "Waitng"

`Eclipse SmartHome Core Thing (104)
----------------------------------
Status: Waiting
Declarative Services
org.eclipse.smarthome.core.thing.internal.profiles.ProfileTypeRegistryImpl (108)
  missing references: ProfileTypeProvider
org.eclipse.smarthome.core.thing.internal.link.ItemChannelLinkConfigDescriptionProvider (107)
  missing references: ProfileTypeRegistry
`
Cosmetic error as this has no apparent impact on function - yet.
Posting here but should this be in the ESH Git?
Raspbian Jessie Snapshot upgrade.

**Comment by kaikreuzer** [comment]
Thanks for the report! Yes the ESH repo would have been the correct place, but I have fixed it nonetheless ;-)

**Comment by kaikreuzer** [comment]
Fixed in latest build 1081!
