### ISSUE TITLE
Upgrade to Jetty 9.3.22

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#567]
Due to https://github.com/eclipse/smarthome/pull/4569 (which fixes https://github.com/eclipse/smarthome/issues/4531), we need to immediately update the Jetty HTTP client to at least version 9.3.15.

Unfortunately, the latest pax-web 6.0.7 release still uses Jetty 9.3.14, so there is no simple way to get a more recent version.

[Updating Karaf](https://github.com/openhab/openhab-distro/issues/566) might help in a way that it defines a "jetty" feature which comes with version 9.3.15 - but this would mean that we have to drop the usage of Pax-Web. I cannot yet fully assess how we can get there and what it exactly means for existing setups.

**Comment by kaikreuzer** [comment]
@lolodomo FYI, this is required for the Sonos fix.

**Comment by lolodomo** [comment]
@kaikreuzer : just for a clear understanding and a correct communication, that means the Sonos problem is not yet fixed (even if the issue in ESH is now closed) and still present in the last OH distribution ?
I cannot test the fix even in Eclipse ?

**Comment by kaikreuzer** [comment]
As summarized [here](https://github.com/eclipse/smarthome/issues/4531#issuecomment-344953401), the fix is to update the Jetty HTTP library and this is what this issue here is about.

**Comment by lolodomo** [comment]
I understand that we recently moved to Jetty 9.3.14 and JUPnP 2.3 which introduced a problem in the Sonos binding due to a bug in Jetty 9.3.14.
Can you please explain if this bug in Jetty 9.3.14 should impact only bindings using JUPnP or can it impact other bindings too and in this case which kind of bindings ?

**Comment by kaikreuzer** [comment]
@lolodomo I didn't see any other bindings being hit by the Jetty bug. It seemed to only occur in the massive parallel operation that is done when querying remote UPnP devices for all their services.

**Comment by kaikreuzer** [comment]
Updating to Jetty 9.3.15 isn't a good choice when using Pax-Web (as done in Karaf), see https://issues.apache.org/jira/plugins/servlet/mobile#issue/KARAF-4990.

I therefore decided to go for the latest patch level 9.3.22 instead, which seems to work well.
Note that I had to force Pax-Web and Karaf to use this version (see #570) as both are still using older versions in their official builds.
