### ISSUE TITLE
No Project Import for the ESH core bundles

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#57]
Just went through the whole IDE setup process and noticed that in the scripted setup (Perform Setup tasks) there is no entry to install the ESH core bundles (there are cloned from git so that is fine)

**Comment by dvanherbergen** [comment]
Which bundle(s) are you referring to? I did the full install and all the ESH bundles (e.g. org.eclipse.smarthome.core.*, org.eclipse.smarthome.io.*) are installed under the Runtime working set.

**Comment by kgoderis** [comment]
Err... indeed, o.e.s.c.* 

I enabled the Working Sets menus in eclipse (this is not configured by the Set-up tasks, btw?), then tried to change working sets, and only 4 of them are present( Infrastructure, OH1, OH2 and ESH Extensions). 

Looked at the Setup Tasks, and there is no entry listed to import the core bundles

**Comment by kaikreuzer** [comment]
> this is not configured by the Set-up tasks, btw?

It is!

> there is no entry listed to import the core bundles 

You need to add this already when installing the IDE:

<img width="248" alt="bildschirmfoto 2016-01-11 um 17 19 51" src="https://cloud.githubusercontent.com/assets/3244965/12239146/a10a58fc-b887-11e5-986b-b44eaa991285.png">

**Comment by kgoderis** [comment]
? Strange enough I did select all of them so /me not get ? Will give it another try

How to explain that the git clone dos happen then....

K

**Comment by kaikreuzer** [comment]
> How to explain that the git clone dos happen then....

The ESH Extensions obviously checks out the same repo.

**Comment by dvanherbergen** [comment]
My install of all the projects did take a long time to complete. A good chunk of it completed in the background. All working sets only become visible at the very end of the setup. Did you wait until it was completely finished with nothing running in the background anymore?

**Comment by kgoderis** [comment]
Solved. I must have double clicked one time too much I guess. pffff...
