### ISSUE TITLE
Selection with mappings doesn't show [%d %%] since oh2

### ISSUE THREAD

**Issue by zwierbel** [openhab/openhab-distro#572]
In oh1 I have item

`Rollershutter Rollo_DG_Arbeit "Rollo DG Arbeit [%d %%]" <rollershutter> (Rollo,Rollo_Seite) { knx="5.001:3/2/9+<3/5/1" }`

And in sitemap
`Selection item=Rollo_DG_Arbeit label="Rollo DG Arbeit [%d %%]" mappings=[0="OFFEN", 25="25%", 40="40%", 50="50%", 75="75%", 100="ZU"]`

with oh1 I have a x% in front of my selection.
![oh1-rollo](https://user-images.githubusercontent.com/33811979/32994269-1de27622-cd65-11e7-9290-d29b9ddeba16.png)

In oh2 I don't get one. Is it a bug or do I have to use an "other" way?
![oh2-rollo](https://user-images.githubusercontent.com/33811979/32994273-23242f2c-cd65-11e7-8b38-0b31819f1e38.png)

It's version 2.1.0 (running under debian/stretch).

Thanks in advanced!

**Comment by kaikreuzer** [comment]
I doubt that this has every been a supported feature - you either let the UI render the state OR you provide labels with mappings, but not both.

If you want to start a discussion whether this should be supported, this must happen at https://github.com/eclipse/smarthome/issues.

**Comment by zwierbel** [comment]
Also this is not the answer I like to read: Thanks for your answer.

I think I'm going to use a selection and switch for each shutter :-(
