### ISSUE TITLE
Items loosing partial config after restart

### ISSUE THREAD

**Issue by jaghatei** [openhab/openhab-distro#575]
A strange behaviour after some OH restarts. (OH version openhab-syno-spk-2.1.0.008-DSM6)
I have some items where things had been created in non simple mode (i.e. by homematic and max bindings).
Some of these items I assigned to groups (i.e. for overall low battery check) via paper ui.
These groups are defined in a group.items file.
The corresponding things, links and items are created by the bindings / via paper ui and are only in jsondb.
The group assignment is also stored in the jsondb files.
This worked for several days in which I did many further testing of other bindings and rules.

But then after some restarts the group assigment of the items are out of a sudden no longer visible in i.e. paperui. If I try to set the group assignment again paperui does not give any error, but the item then still does not have a group assigned. In the jsondb (backups and actual version) the assigment between items and group is still present. But due to missing assigment in the running OH instance the group status is undef.
This situation survived several further restarts.

Only solution I found is setting simple mode in settings for item linking and performing another restart.

In the restart procedures after which the group assigments where gone I saw warnings like these in openhab.log:
[WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'HMTCITWMWEUOEQ0144520_2_SetTemperature' already exists! Failed to add a second with the same UID!

I assume that this might be an issue for the startup order between reading jsondb during startup and starting the item / thing discovery from the bindings, but I have no clue why simple mode on/off is changing anything here.

**Comment by kaikreuzer** [comment]
This has been fixed with https://github.com/eclipse/smarthome/pull/4580.
