### ISSUE TITLE
String in quotes in cfg files cause addon management to fail

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#576]
We are experiencing cfg files that have string values put in quotes since recently, see [here](https://community.openhab.org/t/jetty-update-karaf-4-1-3-upgrade-and-full-lsp-support/36354/44?u=kai).

We need to figure out whether this is valid and if so, why the quotes are not stripped again from the string when it is passed to configurable services.

**Comment by kaikreuzer** [comment]
I haven't heard any similar reports since the 2.2 release anymore.
Is anybody still suffering under this issue? Otherwise, I'd tend to close it.

**Comment by DanielMalmgren** [comment]
I'm one of those that had this problem, completely broke things here when upgrading to 2.2-pre-something. Haven't had any problems with it since though, so I guess it's magically gone 👍

**Comment by kaikreuzer** [comment]
Ok, thanks for your feedback - glad to hear that it didn't come back anymore!
