### ISSUE TITLE
Update Thing Configuration Parameters yields ERROR: 500 - Internal Server Error on PaperUI

### ISSUE THREAD

**Issue by hdonk** [openhab/openhab-distro#595]
Updating Z Wave thing properties in Paper UI generates a 500 error.

**Comment by martinvw** [comment]
Please provide information from your logs, what version you are using and other relevant information.

**Comment by hdonk** [comment]
Last night's snapshot
Trying to swap the TZ36 switch orientation
20:14:45.059 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 3: Polling...
20:14:45.061 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 3: Polling zwave:device:c9d76e3c:node3:scene_number
20:14:45.062 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 3: Polling zwave:device:c9d76e3c:node3:battery-leve
20:14:45.063 [DEBUG] [ernal.converter.ZWaveBatteryConverter
 - NODE 3: Generating poll message for BATTERY endpoint 0
20:14:45.064 [DEBUG] [commandclass.ZWaveBatteryCommandClass
 - NODE 3: Creating new message for application command BAT
ERY_GET
20:14:45.064 [DEBUG] [.commandclass.ZWaveWakeUpCommandClass
 - NODE 3: Message already on the wake-up queue. Removing o
iginal.
20:14:45.065 [DEBUG] [.commandclass.ZWaveWakeUpCommandClass
 - NODE 3: Putting message SendData in wakeup queue.
20:14:55.998 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update received
20:14:56.005 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update group_4 to [node_1_0]
20:14:56.006 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: Creating new message for application command ASS
CIATIONCMD_GET group 4
20:14:56.006 [DEBUG] [tocol.ZWaveController$ZWaveSendThread
 - Took message from queue for sending. Queue length = 0
20:14:56.006 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 1. Queue={}
20:14:56.007 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 0A 00 13 02 03 85 02 04 25
3C 7D
20:14:56.007 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update action_failed to false
20:14:56.007 [DEBUG] [ding.zwave.handler.ZWaveSerialHandler
 - NODE 2: Sending REQUEST Message = 01 0A 00 13 02 03 85 0
 04 25 3C 7D
20:14:56.007 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update powerlevel_level to 0
20:14:56.008 [DEBUG] [mandclass.ZWavePowerLevelCommandClass
 - NODE 2: Creating new message for application command POW
RLEVEL_SET, level=0, timeout=0
20:14:56.008 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 1. Queue={}
20:14:56.008 [DEBUG] [mandclass.ZWavePowerLevelCommandClass
 - NODE 2: Creating new message for application command POW
RLEVEL_GET
20:14:56.009 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 2. Queue={}
20:14:56.009 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update group_1 to [node_1_0]
20:14:56.010 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: Creating new message for application command ASS
CIATIONCMD_GET group 1
20:14:56.010 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 3. Queue={}
20:14:56.010 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update action_remove to false
20:14:56.011 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update group_3 to [node_1_0]
20:14:56.011 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: Creating new message for application command ASS
CIATIONCMD_GET group 3
20:14:56.011 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 4. Queue={}
20:14:56.012 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update binding_pollperiod to 1800
20:14:56.012 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Polling intialised at 1800 seconds - start in 18
0000 milliseconds.
20:14:56.012 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update group_2 to [node_1_0]
20:14:56.013 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: Creating new message for application command ASS
CIATIONCMD_GET group 2
20:14:56.013 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 5. Queue={}
20:14:56.014 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update action_heal to false
20:14:56.014 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update config_1_1 to 1
20:14:56.015 [DEBUG] [dclass.ZWaveConfigurationCommandClass
 - NODE 2: Creating new message for application command CON
IGURATIONCMD_SET
20:14:56.015 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 04 01 13 01 E8
20:14:56.015 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 6. Queue={}
20:14:56.015 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:14:56.015 [DEBUG] [dclass.ZWaveConfigurationCommandClass
 - NODE 2: Creating new message for application command CON
IGURATIONCMD_GET
20:14:56.016 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 04 01 13 01 E8
20:14:56.016 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 7. Queue={}
20:14:56.016 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 04 01 13 01 E8
20:14:56.016 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update switchall_mode to 255
20:14:56.017 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=SendData[0x13], type=Response[0x01], prio
ity=High, dest=255, callback=0, payload=01
20:14:56.017 [DEBUG] [mmandclass.ZWaveSwitchAllCommandClass
 - NODE 2: Switch All report, device included in All On and
All Off group.
20:14:56.017 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: Sent Data successfully placed on stack.
20:14:56.017 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 8. Queue={}
20:14:56.017 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update config_2_1 to 1
20:14:56.018 [DEBUG] [dclass.ZWaveConfigurationCommandClass
 - NODE 2: Creating new message for application command CON
IGURATIONCMD_SET
20:14:56.018 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 9. Queue={}
20:14:56.018 [DEBUG] [dclass.ZWaveConfigurationCommandClass
 - NODE 2: Creating new message for application command CON
IGURATIONCMD_GET
20:14:56.019 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 10. Queue={}
20:14:56.019 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update action_reinit to false
20:14:56.019 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Configuration update powerlevel_timeout to 0
20:14:56.020 [ERROR] [est.core.internal.thing.ThingResource
 - Exception during HTTP PUT request for update config at '
hings/zwave:device:c9d76e3c:node2/config' for thing 'zwave:
evice:c9d76e3c:node2': java.math.BigDecimal cannot be cast
o java.lang.Integer
20:14:56.031 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 07 00 13 3C 00 00 02 D5
20:14:56.031 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:14:56.032 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 09 00 13 3C 00 00 02 00 00
DB
20:14:56.032 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 09 00 13 3C 00 00 02 00 00 DB
20:14:56.032 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=SendData[0x13], type=Request[0x00], prior
ty=High, dest=255, callback=0, payload=3C 00 00 02
20:14:56.032 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: SendData Request. CallBack ID = 60, Status = Tra
smission complete and ACK received(0)
20:14:56.032 [DEBUG] [ialization.ZWaveNodeInitStageAdvancer
 - NODE 2: Starting initialisation from DONE
20:14:56.033 [DEBUG] [ave.internal.protocol.ZWaveController
 - Event Listener org.openhab.binding.zwave.internal.protoc
l.initialization.ZWaveNodeInitStageAdvancer@16c5cf2c alread
 registered
20:14:56.033 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Sent Message: class=SendD
ta[0x13], type=Request[0x00], priority=Config, dest=2, call
ack=60, payload=02 03 85 02 04
20:14:56.033 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Recv Message: class=SendD
ta[0x13], type=Request[0x00], priority=High, dest=255, call
ack=0, payload=3C 00 00 02
20:14:56.033 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: class=SendData, callback
d=60, expected=ApplicationCommandHandler, cancelled=false
   MISMATCH
20:14:56.043 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 0C 00 04 00 02 06 85 03 04 05 00 01
75
20:14:56.043 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:14:56.043 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 0C 00 04 00 02 06 85 03 04
05 00 01 75
20:14:56.044 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 0C 00 04 00 02 06 85 03 04 05 00 01
75
20:14:56.044 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=ApplicationCommandHandler[0x04], type=Req
est[0x00], priority=High, dest=255, callback=0, payload=00
2 06 85 03 04 05 00 01
20:14:56.044 [DEBUG] [essage.ApplicationCommandMessageClass
 - NODE 2: Application Command Request (ALIVE:DONE)
20:14:56.044 [DEBUG] [ialization.ZWaveNodeInitStageAdvancer
 - NODE 2: Starting initialisation from DONE
20:14:56.045 [DEBUG] [ave.internal.protocol.ZWaveController
 - Event Listener org.openhab.binding.zwave.internal.protoc
l.initialization.ZWaveNodeInitStageAdvancer@16c5cf2c alread
 registered
20:14:56.045 [DEBUG] [essage.ApplicationCommandMessageClass
 - NODE 2: Incoming command class ASSOCIATION
20:14:56.045 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: Received ASSOCIATION command V2
20:14:56.045 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: association group 4 has max associations 5
20:14:56.045 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - NODE 2: association group 4 includes the following nodes
20:14:56.046 [DEBUG] [andclass.ZWaveAssociationCommandClass
 - Node 1
20:14:56.046 [DEBUG] [ave.internal.protocol.ZWaveController
 - Notifying event listeners: ZWaveAssociationEvent
20:14:56.046 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Got an event from Z-Wave network: ZWaveAssociati
nEvent
20:14:56.046 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Got a value event from Z-Wave network, endpoint
 0, command class = ASSOCIATION, value = 0
20:14:56.046 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Update ASSOCIATION group_4
20:14:56.047 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Update ASSOCIATION group_4: Adding node_1_0
20:14:56.047 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Update ASSOCIATION group_4: 1 members
20:14:56.047 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Config updated
20:14:56.048 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Sent Message: class=SendD
ta[0x13], type=Request[0x00], priority=Config, dest=2, call
ack=60, payload=02 03 85 02 04
20:14:56.049 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Recv Message: class=Appli
ationCommandHandler[0x04], type=Request[0x00], priority=Hig
, dest=255, callback=0, payload=00 02 06 85 03 04 05 00 01
20:14:56.049 [INFO ] [smarthome.event.ThingUpdatedEvent
 - Thing 'zwave:device:c9d76e3c:node2' has been updated.
20:14:56.049 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: class=ApplicationCommandH
ndler, callback id=60, expected=ApplicationCommandHandler,
ancelled=false        transaction complete!
20:14:56.049 [DEBUG] [ave.internal.protocol.ZWaveController
 - Notifying event listeners: ZWaveTransactionCompletedEven
20:14:56.049 [INFO ] [smarthome.event.ConfigStatusInfoEvent
 - ConfigStatusInfo [configStatusMessages=[ConfigStatusMess
ge [parameterName=config_1_1, type=PENDING, messageKey=null
 arguments=null, message=null, statusCode=null], ConfigStat
sMessage [parameterName=switchall_mode, type=PENDING, messa
eKey=null, arguments=null, message=null, statusCode=null],
onfigStatusMessage [parameterName=config_2_1, type=PENDING,
messageKey=null, arguments=null, message=null, statusCode=n
ll], ConfigStatusMessage [parameterName=powerlevel_level, t
pe=PENDING, messageKey=null, arguments=null, message=null,
tatusCode=null], ConfigStatusMessage [parameterName=group_1
 type=PENDING, messageKey=null, arguments=null, message=nul
, statusCode=null], ConfigStatusMessage [parameterName=grou
_3, type=PENDING, messageKey=null, arguments=null, message=
ull, statusCode=null], ConfigStatusMessage [parameterName=g
oup_2, type=PENDING, messageKey=null, arguments=null, messa
e=null, statusCode=null]]]
20:14:56.049 [DEBUG] [nding.zwave.handler.ZWaveThingHandler
 - NODE 2: Got an event from Z-Wave network: ZWaveTransacti
nCompletedEvent
20:14:56.050 [DEBUG] [tocol.ZWaveController$ZWaveSendThread
 - NODE 2: Response processed after 43ms/4108ms.
20:14:56.050 [DEBUG] [tocol.ZWaveController$ZWaveSendThread
 - Took message from queue for sending. Queue length = 9
20:14:56.050 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 0B 00 13 02 04 73 01 00 00
25 3D 8B
20:14:56.050 [DEBUG] [ding.zwave.handler.ZWaveSerialHandler
 - NODE 2: Sending REQUEST Message = 01 0B 00 13 02 04 73 0
 00 00 25 3D 8B
20:14:56.058 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 04 01 13 01 E8
20:14:56.059 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:14:56.059 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 04 01 13 01 E8
20:14:56.059 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 04 01 13 01 E8
20:14:56.059 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=SendData[0x13], type=Response[0x01], prio
ity=High, dest=255, callback=0, payload=01
20:14:56.060 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: Sent Data successfully placed on stack.
20:14:56.074 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 07 00 13 3D 00 00 02 D4
20:14:56.075 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:14:56.075 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 09 00 13 3D 00 00 02 00 00
DA
20:14:56.075 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 09 00 13 3D 00 00 02 00 00 DA
20:14:56.076 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=SendData[0x13], type=Request[0x00], prior
ty=High, dest=255, callback=0, payload=3D 00 00 02
20:14:56.076 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: SendData Request. CallBack ID = 61, Status = Tra
smission complete and ACK received(0)
20:14:56.076 [DEBUG] [ialization.ZWaveNodeInitStageAdvancer
 - NODE 2: Starting initialisation from DONE
20:14:56.076 [DEBUG] [ave.internal.protocol.ZWaveController
 - Event Listener org.openhab.binding.zwave.internal.protoc
l.initialization.ZWaveNodeInitStageAdvancer@16c5cf2c alread
 registered
20:14:56.076 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Sent Message: class=SendD
ta[0x13], type=Request[0x00], priority=Set, dest=2, callbac
=61, payload=02 04 73 01 00 00
20:14:56.077 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Recv Message: class=SendD
ta[0x13], type=Request[0x00], priority=High, dest=255, call
ack=0, payload=3D 00 00 02
20:14:56.077 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: class=SendData, callback
d=61, expected=ApplicationCommandHandler, cancelled=false
   MISMATCH
20:15:01.051 [DEBUG] [tocol.ZWaveController$ZWaveSendThread
 - NODE 2: Timeout while sending message. Requeueing - 2 at
empts left!
20:15:01.052 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: Got an error while sending data. Resending messa
e.
20:15:01.053 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message queued. Queue length = 10. Queue={}
20:15:01.053 [DEBUG] [tocol.ZWaveController$ZWaveSendThread
 - Took message from queue for sending. Queue length = 9
20:15:01.054 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 0B 00 13 02 04 73 01 00 00
25 47 F1
20:15:01.054 [DEBUG] [ding.zwave.handler.ZWaveSerialHandler
 - NODE 2: Sending REQUEST Message = 01 0B 00 13 02 04 73 0
 00 00 25 47 F1
20:15:01.063 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 04 01 13 01 E8
20:15:01.064 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:15:01.065 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 04 01 13 01 E8
20:15:01.065 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 04 01 13 01 E8
20:15:01.066 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=SendData[0x13], type=Response[0x01], prio
ity=High, dest=255, callback=0, payload=01
20:15:01.067 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: Sent Data successfully placed on stack.
20:15:01.079 [DEBUG] [ZWaveSerialHandler$ZWaveReceiveThread
 - Receive Message = 01 07 00 13 47 00 00 02 AE
20:15:01.080 [DEBUG] [ave.internal.protocol.ZWaveController
 - Receive queue TAKE: Length=0
20:15:01.081 [DEBUG] [zwave.internal.protocol.SerialMessage
 - Assembled message buffer = 01 09 00 13 47 00 00 02 00 00
A0
20:15:01.081 [DEBUG] [ave.internal.protocol.ZWaveController
 - Process Message = 01 09 00 13 47 00 00 02 00 00 A0
20:15:01.082 [DEBUG] [ave.internal.protocol.ZWaveController
 - Message: class=SendData[0x13], type=Request[0x00], prior
ty=High, dest=255, callback=0, payload=47 00 00 02
20:15:01.083 [DEBUG] [ol.serialmessage.SendDataMessageClass
 - NODE 2: SendData Request. CallBack ID = 71, Status = Tra
smission complete and ACK received(0)
20:15:01.083 [DEBUG] [ialization.ZWaveNodeInitStageAdvancer
 - NODE 2: Starting initialisation from DONE
20:15:01.084 [DEBUG] [ave.internal.protocol.ZWaveController
 - Event Listener org.openhab.binding.zwave.internal.protoc
l.initialization.ZWaveNodeInitStageAdvancer@16c5cf2c alread
 registered
20:15:01.085 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Sent Message: class=SendD
ta[0x13], type=Request[0x00], priority=Set, dest=2, callbac
=71, payload=02 04 73 01 00 00
20:15:01.085 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: Recv Message: class=SendD
ta[0x13], type=Request[0x00], priority=High, dest=255, call
ack=0, payload=47 00 00 02
20:15:01.085 [DEBUG] [l.serialmessage.ZWaveCommandProcessor
 - Checking transaction complete: class=SendData, callback
d=71, expected=ApplicationCommandHandler, cancelled=false
   MISMATCH

**Comment by kaikreuzer** [comment]
If there is some problem in the Z-Wave binding, you might be better off to first discuss it in the forum https://community.openhab.org/ or report it as a bug for the binding at https://github.com/openhab/org.openhab.binding.zwave/issues (but please make sure that you put your log in code fences and that it contains an exception that shows the error)

**Comment by chris400** [comment]
Bug only occurs in PaperUI, Habmin is just fine.
Discussion: https://community.openhab.org/t/bug-update-thing-configuration-parameters-yields-error-500-internal-server-error-on-paperui/28370

**Comment by kaikreuzer** [comment]
FTR, issue at ESH is https://github.com/eclipse/smarthome/issues/4795.
