### ISSUE TITLE
rfxcom switch to Z Wave switch doesn't work

### ISSUE THREAD

**Issue by hdonk** [openhab/openhab-distro#596]
Attach a Z Wave light switch and an rfxcom remote switch to openhab. Link them to a switch item. Controlling the switch from the UI works, but issuing the command from the rfxcom remote updates the ui, but the command is not sent to the z wave switch.

**Comment by martinvw** [comment]
This is indeed not how it works, maybe you can present your question in the community forum (https://community.openhab.org) you are more likely to receive help there.
