### ISSUE TITLE
Cannot refer to the non-final variable <someVar> inside a lambda expression

### ISSUE THREAD

**Issue by jewesta** [openhab/openhab-distro#604]
Hi.

I believe many people using lambdas in openHab will stumble across this eventually. There are a few forum discussions concerning this compiler error message, e.g. [this one](https://community.openhab.org/t/cannot-refer-to-the-non-final-variable-i-inside-a-lambda-expression/27506).

There are two workarounds. The first one is to ignore the error because the code clearly works and I do not see why it shouldn't. It's in the nature of lambdas that they can access the enclosing scope. The second one is to make the var global. Solution 1 is annoying, solution 2 forces users to adopt an inelegant coding style.

Initially I thought that this was a limitation of Designer (as suggested by the forum discussion I mentioned). But now that Designer is (de facto) deprecated and the combination VS Code + LSP shows the same symptoms I thought I'd create this issue.

Here's a simple example just for the purpose of reproducing the bug.

```php
import java.util.List
import java.util.Arrays

rule "test"
when
	System started
then
	var int index = 0
	val List<String> strings = Arrays.asList("a", "b", "c")
	strings.forEach[entry |
		// Cannot refer to the non-final variable index inside a lambda expression
		index++
		logInfo("test", "Entry #" + index + " = " + entry)
	]
end
```

The output:

```
2017-12-10 10:38:16.932 [INFO ] [.eclipse.smarthome.model.script.test] - Entry #1 = a
2017-12-10 10:38:16.938 [INFO ] [.eclipse.smarthome.model.script.test] - Entry #2 = b
2017-12-10 10:38:16.943 [INFO ] [.eclipse.smarthome.model.script.test] - Entry #3 = c
```

Thanks for considering! :-)

**Comment by kaikreuzer** [comment]
Please note that the rule engine is a part of Eclipse SmartHome, so please report your request at https://github.com/eclipse/smarthome/issues. Thanks!
