### ISSUE TITLE
$OPENHAB_LOGDIR vs $KARAF_DATA/log

### ISSUE THREAD

**Issue by jernst** [openhab/openhab-distro#613]
It seems `$KARAF_DATA` by default is the same as `$OPENHAB_USERDATA`, so `$OPENHAB_LOGDIR` and `$KARAF_DATA/log` both point to `$OPENHAB_USERDATA/log`. Now if I set `$OPENHAB_LOGDIR` to something else (like `/var/log/openhab`) -- something that I am probably supposed to be able to do -- Karaf logging still ends up inside the data dir.

It would be nice to be able to cleanly redirect logging into `/var/log/openhab`, or, even better, to the systemd journal.

I'm filing this issue because it seems this could use a little bit of cleanup :-)

**Comment by kaikreuzer** [comment]
Hi @jernst, nice to see you here :-)
May I ask which version you are using? Afair, the current 2.2.0-SNAPSHOT has this cleaned up already and all logs end up in $OPENHAB_LOGDIR. Note that the APT setups already log into `/var/log/openhab2`, so I would claim that this works.

**Comment by kaikreuzer** [comment]
See https://github.com/openhab/openhab-linuxpkg/blob/master/resources/systemd/openhab2.service#L13

**Comment by jernst** [comment]
Hi @kaikreuzer, long time no see :-) I'm finally trying to make this work on UBOS ... work in progress at https://github.com/uboslinux/ubos-openhab/ .

Right, I have been using 2.1.0 but will happily try 2.2.0-SNAPSHOT if, as it seems, that's your recommendation.

**Comment by kaikreuzer** [comment]
I assume this is solved in 2.2.0. If not, feel free to re-open the issue.
