### ISSUE TITLE
http server returns garbage before actual response

### ISSUE THREAD

**Issue by discordianfish** [openhab/openhab-distro#623]
I'm debugging why the http site isn't loading on my iphone and I suspect it's because the server returns a few bytes garbage before the actual response:

$ curl -s http://192.168.1.107:8000/start/index|hexdump -C|head
00000000  ef bf bd ef bf bd ef bf  bd 3c 21 44 4f 43 54 59  |.........<!DOCTY|
00000010  50 45 20 68 74 6d 6c 3e  0a 3c 68 74 6d 6c 20 6c  |PE html>.<html l|
00000020  61 6e 67 3d 22 65 6e 22  3e 0a 3c 68 65 61 64 3e  |ang="en">.<head>|
00000030  0a 0a 3c 6d 65 74 61 20  63 68 61 72 73 65 74 3d  |..<meta charset=|
00000040  22 75 74 66 2d 38 22 20  2f 3e 0a 3c 6d 65 74 61  |"utf-8" />.<meta|
00000050  20 68 74 74 70 2d 65 71  75 69 76 3d 22 72 65 66  | http-equiv="ref|
00000060  72 65 73 68 22 20 63 6f  6e 74 65 6e 74 3d 22 31  |resh" content="1|
00000070  30 22 3e 0a 3c 6d 65 74  61 20 6e 61 6d 65 3d 22  |0">.<meta name="|
00000080  76 69 65 77 70 6f 72 74  22 0a 09 63 6f 6e 74 65  |viewport"..conte|
00000090  6e 74 3d 22 77 69 64 74  68 3d 64 65 76 69 63 65  |nt="width=device|
Looks like something with the utf-8 encoding is broken? But not very familiar with the java world.

Running 2.2.0-1 on debian/rpi from http://dl.bintray.com/openhab/apt-repo2

**Comment by kaikreuzer** [comment]
I've just tested it with our demo server and I get:
```
kai$ curl -s http://demo.openhab.org:8080/start/index|hexdump -C|head
00000000  ef bb bf 3c 21 44 4f 43  54 59 50 45 20 68 74 6d  |...<!DOCTYPE htm|
00000010  6c 3e 0a 3c 68 74 6d 6c  20 6c 61 6e 67 3d 22 65  |l>.<html lang="e|
00000020  6e 22 3e 0a 3c 68 65 61  64 3e 0a 0a 3c 6d 65 74  |n">.<head>..<met|
00000030  61 20 63 68 61 72 73 65  74 3d 22 75 74 66 2d 38  |a charset="utf-8|
00000040  22 20 2f 3e 0a 3c 6d 65  74 61 20 68 74 74 70 2d  |" />.<meta http-|
00000050  65 71 75 69 76 3d 22 72  65 66 72 65 73 68 22 20  |equiv="refresh" |
00000060  63 6f 6e 74 65 6e 74 3d  22 31 30 22 3e 0a 3c 6d  |content="10">.<m|
00000070  65 74 61 20 6e 61 6d 65  3d 22 76 69 65 77 70 6f  |eta name="viewpo|
00000080  72 74 22 0a 09 63 6f 6e  74 65 6e 74 3d 22 77 69  |rt"..content="wi|
00000090  64 74 68 3d 64 65 76 69  63 65 2d 77 69 64 74 68  |dth=device-width|
```
`ef bb bf` is the UTF-8 BOM, so this response seems to be fully correct.

Regarding your bytes, I found [this (german) post](https://seeseekey.net/archive/118203), which seems to hint that there is somewhere an incorrect processing of UTF-8 files involved.
As the Jetty of openHAB seems to return the correct response, I wonder what is different on your installation? Do you use a reverse proxy or is port 8000 directly the Jetty of openHAB?

**Comment by discordianfish** [comment]
No reverse proxy, pretty much a default install from the debian packages. "Java" is listening on port 8000, so yes I suppose it's jetty

**Comment by discordianfish** [comment]
Oh maybe it's my java version. I'm using zulu-embedded-8 which I found was somewhere recommended for openhab on raspberry pi. Probably different from the demo server.

**Comment by kaikreuzer** [comment]
Zulu embedded should be fine.

**Comment by Flole998** [comment]
Using 

openjdk version "1.8.0_144"
OpenJDK Runtime Environment (Zulu Embedded 8.23.0.70-linux-aarch64) (build 1.8.0_144-b70)
OpenJDK 64-Bit Server VM (Zulu Embedded 8.23.0.70-linux-aarch64) (build 25.144-b70, mixed mode, Evaluation)

everything is fine aswell. Response is just like on the demo server.

**Comment by wborn** [comment]
Do you still have this issue @discordianfish?
I also retested this with 2.2.0 and couldn't reproduce it.

If you still have this maybe you can add the `-v` option to also print request/reply headers:

**Comment by discordianfish** [comment]
This has been fixed by something, it's not an issue anymore. Not sure though how I've fixed it, probably just worked in some later version. Either way, I think this can be closed.

**Comment by wborn** [comment]
Great! Thanks for the update. :+1:
