### ISSUE TITLE
Persist changes in org.apache.karaf.shell.cfg

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-distro#627]
When updating openhab via apt-get the 
`/var/lib/openhab2/etc/org.apache.karaf.shell.cfg` file gets overwritten.
This prevents ao the access to the shell console from predefined network segments.

Would be better if this file is not automatically overwritten

**Comment by kaikreuzer** [comment]
Afaik, apt actually asks you whether you want to replace it or not.
But in any case, if you think something should be changed in the apt packaging, the right place to discuss this is https://github.com/openhab/openhab-linuxpkg/.
