### ISSUE TITLE
(new feature) Implement a button in PaperUI to export running config to items and things files

### ISSUE THREAD

**Issue by stefaanbolle** [openhab/openhab-distro#631]
We've discussed this already in the forums, therefor I'd like to add a feature request to implement a button/feature to export the running config to the equivalent things and item config files.

I know this should not be the goal, but since I am using some 1.0 bindings (no 2.0 does exist for them), I am obliged to continue to work with the old config files. Now I have a mix of items files and jsondb things with duplicate items,... as a consequence).
For my rather complex setup I'd like to have everything in text files only config, but migrating my whole setup manually would be quite a (n error prone) job. Therefor this feature request.

**Comment by kaikreuzer** [comment]
This would have to be implemented in ESH, I have created https://github.com/eclipse/smarthome/issues/4817 for it (and note that it is not really relevant for the Paper UI).
Note that although many people already asked for that, there wasn't yet anyone coming forward to actually implement it - maybe it helps to put a bounty on it.

**Comment by kubawolanin** [comment]
@stefaanbolle see https://github.com/eclipse/smarthome/issues/4817#issuecomment-354161855  - you might find it useful.
