### ISSUE TITLE
Change format of logging config from properties-file to xml

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-distro#639]
In the forum there are countless questions about the logging configuration.
This is mainly because there is no proper official documentation for the properties-file.
In the [official documentation](http://logging.apache.org/log4j/2.x/manual/appenders.html) are countless examples with .xml files.
Please revert the file format the the xml-file so users can search in the docs and use the shown examples.
I also suggest adding a link to the official doc commented in the distributed file.

**Comment by kaikreuzer** [comment]
We are using Apache Karaf as the container management framework and they had decided [to use the property format](https://github.com/apache/karaf/blob/2aedd8d9cc4a5b2d000c599ea93ade2a722ddab8/itests/src/test/resources/etc/org.ops4j.pax.logging.cfg).
I agree that it is unfortunate that there isn't much documentation available for that - but please note that this file is currently anyhow not really meant to be changed by the user.

It seems as for https://github.com/openhab/openhab-distro/issues/516, the best option will be to switch to XML format anyhow, so I'd suggest to close this here as a duplicate.
