### ISSUE TITLE
Feature request: prevent rules to run before startup is complete

### ISSUE THREAD

**Issue by staehler** [openhab/openhab-distro#640]
Hi all,
I'm not sure if my feature request is placed in the right git repository:
Is it possible to prevent rules from running before openhab has completly started/initialized. I found already some threads discussing about it, as many seem to have the same issue. Rules run during startup time, when not all items are initialized. This leads at least to many errors in the log, but also to malfunctioning rules and misbehaviour.
Wouldn't it be better to find a general solution, than to have some workarounds - which work more or less?
 
What is your opinion? I'm no developer, so sorry for my question, might be also an unsolvable or quite complicated problem.

Regards,
Michael

**Comment by maggu2810** [comment]
Let me point you to eclipse/smarthome#1896

**Comment by kaikreuzer** [comment]
Right, eclipse/smarthome#1896 is probably the only chance to solve this, so please allow me to close this as a duplicate.
