### ISSUE TITLE
Rest API not working for Group Items

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-distro#641]
Over at Project Rotini we discovered, that the /rest/events API doesn't send any state changes for Group items. When Igor did further investigation, he found out that not even on the official UIs (Basic UI) the Updates are detected properly. Is this intended or is this indeed a bug?

**Comment by lolodomo** [comment]
Group state changes are handled in Basic UI through SSE and at my knowledge it is working well.
Can you say what is not working in the demo sitemap or provide a concrete example ?

**Comment by Flole998** [comment]
Not an issue
