### ISSUE TITLE
Items not displayed if using Group-displaying

### ISSUE THREAD

**Issue by DahlitzFlorian** [openhab/openhab-distro#643]
If you are using a hierarchical group structure with more than 20 groups including more than 240 items and you try to display the items in the sitemap by the group-structure, some items won't be shown in the sitemap although they receive updates and the REAST API tells you, that they exist.

See my [community post](https://community.openhab.org/t/items-not-displayed-but-receiving-updates/39986/12) more code examples.

**Comment by kaikreuzer** [comment]
Could you check whether this is a problem of the Basic UI or of the sitemap construction in general? If the latter, the Classic UI should show the same issue.

In any case, please report it at https://github.com/eclipse/smarthome/issues as this is where the REST API as well as the Basic/Classic UIs are located.

Please include an example setup (items+sitemap file) with which the issue can easily be reproduced.
