### ISSUE TITLE
event.log not compromises all ItemStateChangedEvent's

### ISSUE THREAD

**Issue by Pirx99** [openhab/openhab-distro#645]
I just detected it using MQTT binding 1.11 + OH 2.2.  No idea whether it is a general issue or related to the binding!?
All messages from MQTT are executed correctly in OH 2.2., but only part of them are logged in _event.log_. To say it in another way: I see messages within _mosquitto.log_ which lead to Item updates in OH, but they are not getting logged in OH. 

Any idea?

**Comment by kaikreuzer** [comment]
Only changes are logged, no updates. Does this explain your issue?

**Comment by Pirx99** [comment]
No, but it seams that I overlooked something and need to explore it further. So sorry for bothering. I'm closing the issue for now.
