### ISSUE TITLE
Karaf console ssh connection interrupted

### ISSUE THREAD

**Issue by Josar** [openhab/openhab-distro#652]
When running Karaf to log by sshing as the user and then execute the openhab-cli the ssh connection often stops after a while.

```
[WARN ] [sshd.server.session.ServerSessionImpl] - exceptionCaught(ServerSessionImpl[openhab@/127.0.0.1:33876])[state=Opened] InterruptedByTimeoutException: null
```

Is this because of my bad wlan connection or can anyone reproduce this?

Setup: 
PC Windows (WLAN) 
VSCode with connection to RPI:
for code correction errors etc, 
SFTP for file acces, 
and SSH in terminal to usr@host openhab-cli. 

RPI OpenHAB (WLAN)

It does not matter how the ssh connection is done, openssh, mobaxterm, putty

**Comment by openhab-5iver** [comment]
Is this just when you are inactive? There is an sshIdleTimeout setting in /userdata/etc/org.apache.karaf.shell.cfg. The default timeout is 30 minutes.

**Comment by Josar** [comment]
What does inactive mean? I do not interact with the tailing log as the log just shows state changes and erros etc. so there is no need to interact with the ssh session.

The time out could explain it, But i would ask why is there such a short timeout as default?

When we think the logging console will be opened once and closed when not used anymore.
I for example never edit files withotu an opened log to get fast response of errors, i this case its very annoying to open the log every 30 minutes. IMHO.

But i found a way to include the log into VSCode which works for me.
https://community.openhab.org/t/vs-code-openhab-extension/30205/215

**Comment by ScheissSchiesser** [comment]
I believe this is related to the recent Karaf fix. 

https://github.com/apache/karaf/pull/440/files

I am not sure what version of openhab will contain this fix. If someone knows, please post the info here for others.

**Comment by kaikreuzer** [comment]
The Karaf fix is available in 4.2.0 and 4.1.5 - we will update to [one of those versions](https://github.com/openhab/openhab-distro/pull/625#issuecomment-364836320) next.

**Comment by ScheissSchiesser** [comment]
Thanks @kaikreuzer , good to know.

FYI, I seem to have fixed this on the client side by adding a keepalive to my `ssh` client:
`ssh -o ServerAliveInterval=60 openhab@localhost -p 8101`

**Comment by yveshanoulle** [comment]
I'm afraid it's not fixed yet. I upgraded today to 1257 and I used ssh -o ServerAliveInterval=60 openhab@localhost -p 8101

When I relaunch it, I don't see anything in the log that could have made this happen. (And almost no time between the the last log item before closing and the first one after re-opening...

14:24:49.415 [INFO ] [smarthome.event.ItemStateChangedEvent] - anel31_Temperature changed from 28.0 to 27.9
Connection to localhost closed by remote host.
Connection to localhost closed.
openhab@openhab:~$ ssh -o ServerAliveInterval=60 openhab@localhost -p 8101
Password authentication
Password: 

                          __  _____    ____      
  ____  ____  ___  ____  / / / /   |  / __ )     
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  | 
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /      
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/     
    /_/                        2.3.0-SNAPSHOT
                               Build #1257   

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

openhab> log:tail
14:24:49.363 [INFO ] [smarthome.event.ItemStateChangedEvent] - anel48_Temperature changed from 25.6 to 25.7

**Comment by ScheissSchiesser** [comment]
I am noticing the same thing. My workaround _seemed_ to work, but alas, on the latest snapshot build, I am still seeing the same exception and connection closing by remote host.

It seems to happen when using `log:tail` in karaf. I am running a test now without `log:tail` to see if I get kicked.

**Comment by ScheissSchiesser** [comment]
> It seems to happen when using log:tail in karaf. I am running a test now without log:tail to see if I get kicked.

I SSH'd into Karaf and left it open (in tmux) for hours. I was not booted off. No errors.

Trying `log:tail` now. I will report back.

P.S. Is there any way to check what version of Karaf is running?

P.P.S This is build 1251 of OpenHAB (2.3.0-SNAPSHOT)

**Comment by ScheissSchiesser** [comment]
> Trying log:tail now. I will report back.

`log:tail` caused me to get booted out.
