### ISSUE TITLE
MVN Clean Install build for openhab-distro fails at openHAB Feature Verification

### ISSUE THREAD

**Issue by ncpe20012003** [openhab/openhab-distro#654]
[INFO] openHAB Distribution ............................... SUCCESS [  8.935 s]
[INFO] openHAB Feature Verification ....................... FAILURE [  0.388 s]
[INFO] openHAB Online Repository 2.3.0-SNAPSHOT ........... SKIPPED

[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.3:verify (verify) on project openhab-verify: Feature resolution failed for [openhab-package-demo/2.3.0.SNAPSHOT]
[ERROR] Message: Error:
[ERROR] 	Resource mvn:org.apache.karaf.shell/org.apache.karaf.shell.core/4.1.3 does not contain a manifest
[ERROR] 	Resource mvn:org.jline/jline/3.5.0 does not contain a manifest
[ERROR] Repositories: {
[ERROR] 	mvn:org.apache.karaf.features/framework/4.1.3/xml/features
[ERROR] 	mvn:org.apache.karaf.features/standard/4.1.3/xml/features
[ERROR] 	mvn:org.openhab.distro/addons/2.3.0-SNAPSHOT/xml/features
[ERROR] 	mvn:org.openhab.distro/distro/2.3.0-SNAPSHOT/xml/features
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-features/6.0.7/xml/features
[ERROR] }
[ERROR] Resources: {
[ERROR] 	mvn:org.apache.felix/org.apache.felix.configadmin/1.8.16
[ERROR] 	mvn:org.apache.felix/org.apache.felix.fileinstall/3.5.8
[ERROR] 	mvn:org.apache.karaf.features/org.apache.karaf.features.core/4.1.3
[ERROR] 	mvn:org.apache.karaf.features/org.apache.karaf.features.extension/4.1.3
[ERROR] 	mvn:org.apache.karaf.shell/org.apache.karaf.shell.commands/4.1.3
[ERROR] 	mvn:org.apache.karaf.shell/org.apache.karaf.shell.core/4.1.3
[ERROR] 	mvn:org.apache.karaf.wrapper/org.apache.karaf.wrapper.core/4.1.3
[ERROR] 	mvn:org.fusesource.jansi/jansi/1.16
[ERROR] 	mvn:org.jline/jline/3.5.0
[ERROR] 	mvn:org.ops4j.pax.logging/pax-logging-api/1.10.1
[ERROR] 	mvn:org.ops4j.pax.logging/pax-logging-log4j2/1.10.1
[ERROR] 	mvn:org.ops4j.pax.url/pax-url-aether/2.5.3
[ERROR] }

**Comment by kaikreuzer** [comment]
The build is working (see https://openhab.ci.cloudbees.com/job/openHAB-Distribution) and meanwhile on Karaf 4.1.5.
