### ISSUE TITLE
openHAB server locks resources

### ISSUE THREAD

**Issue by jsassner** [openhab/openhab-distro#661]
OpenHab 2.2 on windows.

Use 'Image url="http://192.168.0.12:8081/static/grapher/WindirectionLast7Days.png"' to display static images generated using outside graphrenderer, but when trying to update those pictures they are locked. Found https://github.com/openhab/openhab1-addons/issues/1546 , but that is ~4 years old and trying to follow those instructions doesn't make sense.
Tried to update "useFileMappedBuffer" in the file webdefault.xml in jetty-webapp-9.3.22.v20171030.jar to no avail.

openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://dl.bintray.com/openhab/mvn/online-repo/2.2

Repository        Version
----------------------------------------
openhab-distro  : 2.2.0
smarthome       : 0.10.0.b1
openhab-core    : 2.2.0
openhab1-addons : 1.11.0
openhab2-addons : 2.2.0
karaf           : 4.1.3

**Comment by jsassner** [comment]
I still have this issue. Anyone that can help me? Running on Windows 10.




openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://dl.bintray.com/openhab/mvn/online-repo/2.3

Repository        Version
----------------------------------------
openhab-distro  : 2.3.0
smarthome       : 0.10.0.oh230
openhab-core    : 2.3.0
openhab1-addons : 1.12.0
openhab2-addons : 2.3.0
karaf           : 4.1.5

**Comment by wborn** [comment]
Is this still an issue?

**Comment by jsassner** [comment]
Close it
