### ISSUE TITLE
Auto-generated release notes

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#668]
With the past releases, we manually compiled the release notes (partially with the help of a script that @BClark09 put together).

In the light of https://github.com/openhab/openhab-distro/pull/662#issuecomment-375442417, we should come to a more automated process that should be based on the information in the update.xyz  file as well as on labels on merged PRs from Github, where we should formalize the labels across the different repos and the style of the PR text, so that they are useful when ending up in the release notes.

**Comment by yveshanoulle** [comment]
I assume this is only major releases? Or is there a way to know about minor releases? 

Aka I have now openHAB 2.4.0 Build #1308 installed. is there a way to know what has changed since a previous installed version?

**Comment by wborn** [comment]
> formalize the labels across the different repos and the style of the PR text

I think the way how issues and PRs are labeled in ESH would be a good starting point for this. Such labels would allow for grouping most PRs as is currently done in the current release notes.

> I have now openHAB 2.4.0 Build #1308 installed. is there a way to know what has changed since a previous installed version?

Currently that's not easy. An easy (but not totally correct) approach could be to determine when `#1308` was build (e.g. based on the timestamps of the OH files) and then see what commits in the repositories were made since that timestamp.

**Comment by kaikreuzer** [comment]
@BClark09 As we are approaching a 2.4.0.M1 build, would it be worth to move the current version of your script to this repo here and maybe even have a Jenkins plan that executes it? This could help to see how well we are doing with the PR labelling and once we are satisfied with the result, we could copy it over to the release descriptions, wdyt?

**Comment by yveshanoulle** [comment]
> Currently that's not easy. An easy (but not totally correct) approach could be to determine when `#1308` was build (e.g. based on the timestamps of the OH files) and then see what commits in the repositories were made since that timestamp.

It would be nice if 
 - the openhab webpage would also add the date of the build (next to the build number)
- somewhere on openhab website we have a list of all builds with their date
==> this way we don't have to go to the openhab server to check timestamps.

**Comment by kaikreuzer** [comment]
This is now in place with https://ci.openhab.org/view/Utility/job/openhab-build-changelog/ - at least as a semi-automated process (that usually still takes some manual steps for the final result).
