### ISSUE TITLE
Rollershutter problem with Snapshot 1244

### ISSUE THREAD

**Issue by s-simma** [openhab/openhab-distro#672]
Hi,
I updated my system from v2.1 to 2.3 Snapshot 1244 (fresh installation).
I used my old item, rules, things configuration.
I recompiled my sienna powerline binding and put it into the addon-folder.

**1. Problem with Rollershutter and Basic-UI**
Pressing UP, DOWN, STOP button sends the command to the item.
08:29:45.957 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'JalousieEZT' received command UP
But with the new version the "handleCommand" function in my binding is no longer triggered.

@Override
public void handleCommand(ChannelUID channelUID, Command command) {
...
...
}
This worked perfect in v2.1, and it even works if i use the new compiled binding in v2.1

**2. Sending commands from habPanel to Rollershutter item**
In v2.1 it was possible to send a command directly from habPanel to the rollershutter item
ng-click="sendCmd(config.blind_item, 'STOP')"

with the new version this creates the following warning:
08:28:27.617 [WARN ] [.rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/gSienna' with an invalid status value 'STOP'.

**Comment by kaikreuzer** [comment]
Is this issue still open or did you meanwhile find any reason/solution for it?

**Comment by wborn** [comment]
Let's close this issue since there hasn't been any reply.
