### ISSUE TITLE
UPnP stream port needs to be changed if Jetty port is changed

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#68]
The port for upnp callbacks is defined in https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/runtime/etc/services.cfg#L23
and jUPnP registers a servlet on Jetty to process those incoming requests.
If the user changed the Jetty port to something different than 8080, this will break.
We need to find a way to feed in the current jetty port to jupnp. Maybe this requires a PR for jUPnP itself.

**Comment by kaikreuzer** [comment]
Addressed by https://github.com/jupnp/jupnp/pull/46

**Comment by kaikreuzer** [comment]
Once a new jUPnP version is available, we should remove the line mentioned above from services.cfg.

**Comment by dvanherbergen** [comment]
Closed via #110
