### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by yveshanoulle** [openhab/openhab-distro#680]
The file addons.cfg contains some documentation that is confusing.

>'# A comma-separated list of bindings to install (e.g. "sonos,knx,zwave")
This is confusing, because it's not clear if the " are part of the list. 

A for me less confusing comment would be:

>'# A comma-separated list of bindings to install (e.g. "binding =  sonos,knx,zwave") 

(And similar for all lists in this file.) 

I don't know yet how to create PR for your project. I think we need an issue first.

**Comment by martinvw** [comment]
I think that the good news is that it also works with quotes:

my addons.cfg

```xtend
ui = "classic,basic,paper,habpanel,habmin"
```

**Comment by yveshanoulle** [comment]
Unfortunately that is not true.

When I write ui = "classic,basic,paper,habpanel,habmin"
both classic and habmin are not installed.

**Comment by martinvw** [comment]
That is weird I copied it from my local file 🤔 

Somebody else some idea? I’m one the newest snapshot on which version are you?

**Comment by yveshanoulle** [comment]
I just changed my addons.cfg from
ui = classic,basic,habmin,paper,habpanel
to 
ui = "classic,basic,habmin,paper,habpanel

And in log:tail I see this happening. 

13:33:25.400 [INFO ] [lassic.internal.servlet.WebAppServlet] - Stopped Classic UI
13:33:25.746 [INFO ] [.core.karaf.internal.FeatureInstaller] - Uninstalled 'openhab-ui-classic'
13:33:25.787 [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'ui-classic' has been uninstalled.
13:33:46.703 [INFO ] [bpanel.internal.HABPanelDashboardTile] - Stopped HABPanel
13:33:46.876 [INFO ] [.core.karaf.internal.FeatureInstaller] - Uninstalled 'openhab-ui-habpanel'
13:33:46.917 [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'ui-habpanel' has been uninstalled.

**I did this on OpenHab 2.3.0 Build 1256**

**Comment by yveshanoulle** [comment]
I have package = expert also on in this file. (From what I understand this is needed to use the  settings from the cfg file.

**Comment by yveshanoulle** [comment]
I just saw that there is already a 1257. I retried and I have the same behavior

**Comment by kaikreuzer** [comment]
> I think that the good news is that it also works with quotes:

I'd actually think it currently shouldn't work.
So wrt this issue, I'd suggest to
1. update the docs in the way @yveshanoulle suggests
2. improve the config processing so that such quotes are stripped off, in case they are there.

Wdyt?

**Comment by martinvw** [comment]
So my config is broken, good you joined in 👍

**Comment by martinvw** [comment]
I'll prepare PR :-)

**Comment by martinvw** [comment]
@yveshanoulle thanks for your suggestion and testing:

https://github.com/openhab/openhab-distro/pull/682

**Comment by martinvw** [comment]
No its fine, somehow something seems wrong in my config, but I never change those files 😄 

I use either the paperUI for installing addons or drop them in the addons folder

**Comment by yveshanoulle** [comment]
I finally had time to install the new version.
The addons.cfg installs correctly. It asks nicely if It can overwrite the file. When it overwrites the file, it also makes a copy of the old file. which is great to see. It might be a good idea to mention that during the setup that when you select overwrite that there will be a copy. (I guess that is not in openhabs control.)

y
