### ISSUE TITLE
Air Quality Binding Error

### ISSUE THREAD

**Issue by rkrisi** [openhab/openhab-distro#681]
It seems that this binding doesn't work / work unrealiably on the latest version.
Reported by multiple users on the community forum.

Issue:
[airquality.handler.AirQualityHandler] - Error in aqicn.org (Air Quality) response: missing data sub-object

**Comment by kaikreuzer** [comment]
Thanks - could you please report this at https://github.com/openhab/openhab2-addons/issues as this is where the binding is maintained?
