### ISSUE TITLE
support multiline in openhabcloud.cfg

### ISSUE THREAD

**Issue by yveshanoulle** [openhab/openhab-distro#689]
Inside openhabcloud.cfg I want to add a rather large list to expose.
When that list is on one line, it's rather hard to find things back.
I would like to use something like 

expose =  a1
,b2
,c3
,d4

At this moment this does not work. What I have to use is 

expose =  a1, b2, c3, d4

Technically that works, yet that is harder to find things back in a large list.

This is probably the same in all cfg files, yet it's only inside the expose part of openhabcloud.org that I really want to add a large list. (To expose a lot of events.)

**Comment by wborn** [comment]
Closing this since we now have https://github.com/eclipse/smarthome/issues/5745 for this. This covers the same request in the appropriate issue tracker. :-)
