### ISSUE TITLE
Update to Karaf 4.1.x broke smarthome:> console command

### ISSUE THREAD

**Issue by pyjamasam** [openhab/openhab-distro#695]
In Karaf 4.1.x there has been support added for redirecting the output of a command (similar to how a bash shell does it) on the console.

It uses the > character to do this. (https://github.com/apache/karaf/blob/karaf-4.1.x/shell/core/src/main/java/org/apache/felix/gogo/runtime/Parser.java#L319)

The new parser is picking up the > character and attempting to redirect instead of letting the ScriptEngineConsoleCommandExtension handle it (https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/extension/ScriptEngineConsoleCommandExtension.java#L38)

This is only in the 4.1.x branch of Karaf. It seams somewhere around July of 2017 there was a pull request in openhab to use Karaf 4.1.x (https://github.com/openhab/openhab-distro/pull/484).

My suspicion is that this bug has existed since then but only rolled out when 2.2 was released. And there doesn’t look like a way to work around it to execute a script from the console.

An easy fix would be to change the > character used by the ScriptEngineConsoleCommandExtension to something else, but I’ll leave that up to the devs to decide.

**Comment by kaikreuzer** [comment]
Thanks a lot for this information, this indeed went unnoticed so far.
I have just created https://github.com/eclipse/smarthome/pull/5606, so that the 2.3 release should be fixed!

**Comment by lolodomo** [comment]
To be closed ?

**Comment by wborn** [comment]
I've tested this on 2.3.0 and it is indeed fixed! :+1:
