### ISSUE TITLE
excessive swapfile growth

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-distro#701]
I installed openhab2 stable on an existing raspi3b+ stretch installation with piViccu, garana and mosquitto. Upon startup of the system, openhab seems to start up.

HTOP shows multiple (>40) java process being started. Four at a time, each second.  Eventually the system crashes. 

![image](https://user-images.githubusercontent.com/33855380/39750586-e0304576-52b5-11e8-986d-137e519d121c.png)

edit: "logout" from the openhab-cli reliably kills all spawned processes.

**Comment by maggu2810** [comment]
You mix threads and processes.

**Comment by s0170071** [comment]
And the webpage says there are no user interfaces installed.

**Comment by wborn** [comment]
If your swapfile keeps growing there is most likely a memory leak. 

Do you also see OutOfMemoryErrors in the openHAB log files? There is a [community thread](https://community.openhab.org/t/how-to-find-the-cause-of-a-outofmemoryerror-in-oh2/24874?u=wborn) on how to troubleshoot these.

You could also upgrade to openHAB 2.3.0 which was released this week to see if this has been fixed.

**Comment by s0170071** [comment]
Maybe rpi3+ related. Moved to rpi3- issue is gone.

**Comment by wborn** [comment]
Thanks for the update!
