### ISSUE TITLE
Openhab 2.3 install fails when no internet connection available

### ISSUE THREAD

**Issue by B0ycee** [openhab/openhab-distro#704]
After clicking “Standard” on the UI selection screen, the page sits refreshing endlessly. In openhab.log:

> [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing ‘openhab-ui-homebuilder, openhab-ui-basic, openhab-ui-habpanel, openhab-ui-paper’: Error:
> Error downloading mvn:org.openhab.ui/org.openhab.ui.habpanel/2.3.0-SNAPSHOT

openhab-addons-2.3.0-SNAPSHOT.kar is available in the addons directory.

Install completes with version 2.2 release + addons .kar in same environment.

Platform information:
OS: Windows 8.1
Java Runtime Environment: Oracle 8 Update 172
openHAB version: 2.3.0 Snapshot Build #1273

**Comment by kaikreuzer** [comment]
Thanks for the report! I was able to reproduce it and identified the problem: We moved the location of the extracted KARs recently and I missed to change the configuration of a specific file - https://github.com/openhab/openhab-distro/pull/705 should fix it!
