### ISSUE TITLE
Scale transformation not working for Sitemap:Selection OH2.3~snapshots

### ISSUE THREAD

**Issue by mitch-geht-ab** [openhab/openhab-distro#707]
* Platform information:
  * Hardware: Intel 64bit, 2GB RAM, 17G free disk
  * OS: Debian GNU/Linux 9.4 
  * Java Runtime Environment: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
  * openHAB version: openhab2 2.3.0~20180417031559-1
  
* Issue of the topic: 
I use "selections" on my sitemap for my rollershutters (mappings=[0="OFFEN", 20="25%", 40="50%", 60="75%", 90="SCHLITZE", 100="ZU"]).
So that the user always has a state for the selection. I used a scale transformation to translate the ranges to my mappings. Example
0-19=0, 20-39=20 and so on (see transformation below).
That mean's, shuttertest.state=22, transformation to 20, selection "25%" selected.
With oh2.0 everything was working fine, with 2.3.0~20180417031559-1 it seems that there is a bug? Or is it works as designed?
When I switch in my sitemap from type:selection to type:slider, there is the correct value shown in front of the slider (see screenshots).

* Please post configurations (if applicable):
  * Items configuration related to the issue
```
Rollershutter shuttertest
```
  * Sitemap configuration related to the issue 
```
Selection item=shuttertest label="test [SCALE(rollladen.scale):%s]" mappings=[0="OFFEN", 20="25%", 40="50%", 60="75%", 90="SCHLITZE", 100="ZU"]
Slider item=shuttertest label="test [SCALE(rollladen.scale):%s]"
```
  * Transformation
```
cat transform/rollladen.scale
[..19]=0
[20..39]=20
[40..59]=40
[60..89]=60
[90..97]=90
[98..]=100
```
* Karaf output
```
openhab> smarthome:items list |grep shuttertest
shuttertest (Type=RollershutterItem, State=22, Label=null, Category=null)
```
![28eef2779250c39d4cf40a71461ff77041e9a09b](https://user-images.githubusercontent.com/8008251/40066471-71f7d61e-5864-11e8-9258-15318ad34fcb.JPG)

![ca41471e9ffbfff138cd05418a3eea3ea4fe4a50](https://user-images.githubusercontent.com/8008251/40066472-72260f20-5864-11e8-8ecd-fcc78262b737.JPG)

**Comment by wborn** [comment]
Does https://github.com/eclipse/smarthome/pull/5719 also fix this issue @lolodomo?

**Comment by lolodomo** [comment]
No, I don't think.
What is requested is to have a mapping based on the result of the transformation (scale) of the item state while the mapping is in fact based on the item state itself.
Maybe it was possible before I fixed the bug to do cuch strange thing but it was clearly a bug to use the transformed state as input rather than the item state.

**Comment by lolodomo** [comment]
To implement what @mitch-geht-ab wants to do, I think he needs to define a second item and have a rule that sets its value by applying the scale transformation. Then he can link the selection widget to this new item. Of course, he needs to have another rule to handle the value changed when one of the button is pressed.
To be clear:
* one additional item
* 2 additional rules

**Comment by wborn** [comment]
Thanks for your thoughts on this @lolodomo!

> I fixed the bug to do cuch strange thing

Do you have a link to the issue/PR that fixed this bug?

**Comment by lolodomo** [comment]
I think my sentence was not clear. With ponctuation, it could be better: Maybe it was possible, before I fixed the bug, to do such strange thing.
The fixed bug is https://github.com/eclipse/smarthome/issues/5718
And for me, the current bug is just not a bug.

**Comment by mitch-geht-ab** [comment]
>

**Comment by mitch-geht-ab** [comment]
> What is requested is to have a mapping based on the result of the transformation (scale) of the item state while the mapping is in fact based on the item state itself.
Maybe it was possible before I fixed the bug to do cuch strange thing but it was clearly a bug to use the transformed state as input rather than the item state.

But transformed states are used for the label or for a switch item with mapping, as in your bug [eclipse/smarthome#5718](https://github.com/eclipse/smarthome/issues/5718)
So why not for selections?

**Comment by lolodomo** [comment]
Yes that is exactly the point, the transformation is only used to change the value in the label. Everyelse is considering the item state.

**Comment by mitch-geht-ab** [comment]
Hm, okay. 
Have documented my workaround here https://community.openhab.org/t/solved-scale-transformation-not-working-for-sitemap-selection/44794
