### ISSUE TITLE
New Update.ps1 found. Using that... double -SNAPSHOT appended

### ISSUE THREAD

**Issue by eusblh** [openhab/openhab-distro#716]
I'm running windows. openhab-2.2.0 stable
I wanted to update to openhab-2.3.0-SNAPSHOT using update.ps1

Update-openHAB -OHVersion 2.3.0 -Snapshot $true
(excerpts from logfile included) 
Downloading the openHAB 2.3.0-SNAPSHOT distribution...
Downloaded 63603K of 63603K
Finished Download
New Update.ps1 found. Using that...

Here's where the trouble starts. It appears that on the second run of update.ps1, it tries to download the snapshot again, but it duplicates/appends the -SNAPSHOT onto the end again:
Downloading the openHAB 2.3.0-SNAPSHOT-SNAPSHOT distribution...
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

also interesting, there seems to be no error catching. It thinks everything went well, although I now don't even have a runtime folder:

openHAB updated to version 2.3.0-SNAPSHOT-SNAPSHOT!

as a workaround, this worked:
Update-openHAB -OHVersion 2.3.0 -Snapshot $true -SkipNew $true
 2.3.0-SNAPSHOT Build #1285

**Comment by wborn** [comment]
Was this issue also fixed in #809 @tmrobert8?

**Comment by wborn** [comment]
I see it had it's own fix in https://github.com/openhab/openhab-distro/pull/736 :wink:
