### ISSUE TITLE
Cant connect via SSH on 8101 to openhab.local

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-distro#719]
kris@OpenHAB:/$ netstat -atn |grep 8101
tcp6       0      0 127.0.0.1:8101          :::*                    LISTEN

But I cant connect.

Any thoughts? Connection refused

**Comment by maggu2810** [comment]
Have you seen a message in the log?
Have you tried to remove the `host.key`, so a new one will be generated?
