### ISSUE TITLE
Creating new items when linking to a thing does not work

### ISSUE THREAD

**Issue by claell** [openhab/openhab-distro#723]
When opening a thing and clicking on the button on a channel to link an item one can select an option to create a new item. This opens a new dialogue to create an item.
At the bottom of the dialogue is the button "Link" to finish the creation of the item and link it to the channel. Unfortunately this does nothing for me. I can click it and nothing happens.

**Comment by wborn** [comment]
There was an issue in the 2.3.0-SNAPSHOT and the RC releases but it was fixed just before the final release of 2.3.0 was made (see [release candidate community thread](https://community.openhab.org/t/openhab-2-3-release-candidate-available/45318/17?u=wborn)). I just retested this with the final 2.3.0 release and it worked just fine.

So can you test if this is still an issue with the final 2.3.0 release?

When this is still an issue, please create an issue for this in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues). That's the issue tracker for the repository that contains the Paper UI source code.

Please also report your OS, openHAB and browser version when creating issues. Adding relevant openHAB and browser logging also helps a lot.

**Comment by claell** [comment]
Sorry, did not have much time, so I did not mention my setup details.
I am running the latest 2.4.0 snapshot version on a Raspberry Pi with latest Raspbian. Maybe this got fixed in between for the final 2.3.0 release but got introduced again or the snapshot uses an older version?
I will create an issue on the Eclipse Smart Home tracker.

**Comment by kaikreuzer** [comment]
I've just checked: The 2.4 snapshot includes an ESH build from `0.10.0.201805241348` - which is older than the openHAB 2.3 release - seems I have to trigger another ESH stable build!

The 2.4 snapshot should be up to date by tonight, so please upgrade then. No need to enter an issue at ESH.

**Comment by claell** [comment]
Alright, thanks!

**Comment by kaikreuzer** [comment]
Latest build 1297 should be fine!

**Comment by claell** [comment]
Yes, can confirm it works now, thanks!

**Comment by kaikreuzer** [comment]
Valid question with a simple answer: As release builds should be reproducible, we cannot include ESH snapshot versions in it. We therefore use our own ESH fork for release builds from which we do "inofficial" ESH releases, [such as 0.10.0.oh230](https://github.com/openhab/smarthome/releases/tag/0.10.0.oh230).
