### ISSUE TITLE
Alphabetical order for bindings in inbox search

### ISSUE THREAD

**Issue by claell** [openhab/openhab-distro#724]
When clicking the "Search for Things" button on the bottom of the inbox a list of the bindings appears. Unfortunately the order of the list seems rather random and also changes every now and then. I suggest to order the bindings alphabetical to make spotting the right one easier.

**Comment by wborn** [comment]
This would be a good and easy improvement! Can you create an issue for this in the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues)? That's the issue tracker for the repository that contains the Paper UI source code.

**Comment by claell** [comment]
Done, thanks for the link.

**Comment by wborn** [comment]
Thank you for creating the issue. It was also one of my own annoyances. :slightly_smiling_face:
