### ISSUE TITLE
[Meta] Use tool for CLA signing

### ISSUE THREAD

**Issue by claell** [openhab/openhab-distro#725]
When one wants to contribute to this project, one has to add the "[Signed-off-by:](https://www.openhab.org/docs/developer/contributing/contributing.html#sign-your-work)" statement to every commit to state that one agrees to the CLA of this project. This is a bit annoying.

Recently I contributed to a different project which used https://cla-assistant.io/ for that and it felt much easier.

Could such a tool be used for this project as well?

**Comment by kaikreuzer** [comment]
Note that we do not have a CLA (which is a formal contract).
Instead, we use the DCO, which is the standard mechanism introduced by Linux.
See https://opensource.com/article/18/3/cla-vs-dco-whats-difference.

You can configure your git client to automatically sign all your commits, so this is no burden.
I think it is much cleaner to have the data available in the repo than relying on some external party, which might not exist in a few years from now.
Note that ESH actually requires an ECA (kind of CLA) AND the sign-off on the commits.

**Comment by claell** [comment]
Thanks for clarification.

The only problem remaining is that I did not find any easy way to configure my git client to automatically sign my commits. There seems to be no config setting for this currently (https://stackoverflow.com/questions/50353511/is-there-a-git-config-setting-to-auto-signed-off-by-my-commits). However it seems to be possible with a template. How did you set it up?

**Comment by martinvw** [comment]
What about https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

**Comment by claell** [comment]
Yes, that is about the command used to do this. Problem is that I normally do not commit from commandline but from Eclipse, Atom or VS Code. So I was wondering whether there is an option to change the git config to always append the Signed-off part. Otherwise I will probably just go with committing from commandline or adding the Signed-off part manually.

**Comment by kaikreuzer** [comment]
I think the way to enable it depends on your git client. In Eclipse it is easy to auto sign commits, SourceTree also supports it and I am sure that there is a similar feature for Atom and VS Code.

**Comment by claell** [comment]
Ok, misunderstood what you meant with git client. Thought you meant the actual git application. Then I will use Eclipse for signing, as Atom does not seem to support it currently: https://github.com/atom/github/issues/914
