### ISSUE TITLE
Debian packages lack dependency on java

### ISSUE THREAD

**Issue by banholzer** [openhab/openhab-distro#728]
Debian packages are missing a required dependency on java. Following installation steps on a blank debian minimal works but daemon is unable to start because java is missing.

I think a "Depends: java8-runtime-headless" should be added.

**Comment by kaikreuzer** [comment]
Thanks - please be so kind and create this issue at https://github.com/openhab/openhab-linuxpkg/issues as this is where the linux packages are constructed.
