### ISSUE TITLE
Offline Archive (addons.kar) installs all Add-Ons

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-distro#729]
## Expected Behavior
When using the openHAB 2.3.0 Stable Add-Ons archive for offline use, Add-Ons should NOT be installed unless the user explicitly installs them using PaperUI (or another method).
When installing an Add-On, the offline archive should be used (not sure if PaperUI->Configuration->System->Add-on Management ->Access Remote Repository should be OFF for this)

## Current Behavior
All Add-ons are being installed when the archive (kar) file is placed in the addons folder.
Multiple errors are being logged (that's normal since there are several problems with empty configs)
Some Add-Ons enter in a install-uninstall loop.

## Steps to Reproduce
1) Download openHAB 2.3.0 Stable Runtime
2) Start it up, select expert mode
3) Shut down the service
4) Donwload openHAB 2.3.0 Stable Add-ons archive
5) Place it in addons folder
6) Start up OH 2.3
7) Laugh at log file :)

## Your Environment
Win10 x64
Oracle JDK x64 1.8.0_171
OH 2.3.0 Stable

Community Thread: https://community.openhab.org/t/cannot-get-fresh-oh-2-3-to-run-all-bindings-were-installed-automatically/46765

**Comment by illnesse** [comment]
I experienced the same.

**Comment by ghostreader86** [comment]
Experienced the same, deleting [userdata]/tmp and [userdata]/cache, restarting the service and patience helped

**Comment by LKuech** [comment]
Yep. Same here.

**Comment by lolodomo** [comment]
Personnally, I always install the offline distribution from scratch (that means not by overwritting an already installed version) and I put the kar file in the addons directory before the first start. And I have not your problem.

**Comment by kaikreuzer** [comment]
I am using the official update script of the distro and have the kar file in my addons folder - and I do not experience this problem either.
Might be only happening if the installation had been started without the KAR before. This would need to be analysed in detail (not sure if/when I find the time myself).

Could anyone maybe enable debug logging on `org.openhab.core.karaf` and post the log of the startup?

**Comment by LKuech** [comment]
I try to find the time on Monday.
Maybe this is just an issue related to a Windows system? My productive
system is running on a Raspi and is using the online mode. But from time to
time I start my configuration for some test on a Windows system behind a
proxy and on this system I experienced this issue.

Kai Kreuzer <notifications@github.com> schrieb am Sa., 30. Juni 2018, 12:16:

**Comment by hisstone** [comment]
I experienced the same in ubuntu 16.04.

**Comment by AngelosF** [comment]
> Could anyone maybe enable debug logging on `org.openhab.core.karaf` and post the log of the startup?

Deploying the Choco method on a fully functional Windows system (which runs the manual installation of OH2 without problems)...

First startup log (this is what a new user will experience): [openhab.log](https://github.com/openhab/openhab-distro/files/2568128/openhab.log)

Enable DEBUG on  `org.openhab.core.karaf`, stop OH2, clear logs, start it up again: 
[openhab.log](https://github.com/openhab/openhab-distro/files/2568131/openhab.log)

It's a mess :)

**Comment by AngelosF** [comment]
This is strange since within openhab-addons-2.3.0.kar the MANIFEST.MF has the correct setting:
```
Karaf-Feature-Start: false
```

I am going to try to replicate this on Linux also but something tells me that it won't happen...

So far, I have seen it happen on Windows only (both using manual and Choco installation methods)

**Comment by AngelosF** [comment]
I think I found it: https://issues.apache.org/jira/browse/KARAF-5197

seems it was not actually fixed ???

**Comment by AngelosF** [comment]
ok... I found something related?

http://karaf.922171.n3.nabble.com/Kar-installation-error-tp4052693p4052717.html



>the MANIFEST header is deprecated. The Kar service uses the install attribute on the feature. 
>
> The Kar service will install a feature only if the install flag is null (not specified) or auto (default). As you set to "false", the feature  should not be installed. Can you try with "manual" instead of "false" (even if it should be OK). 
>

If this is the case, then the issue should appear on Linux also... testing now
More news soon

**Comment by AngelosF** [comment]
damn...  Actually I can replicate this on Linux...

It started installing all Addons...

massive errors in the log

testing with noAutoStartBundles=true in /etc/org.apache.karaf.kar.cfg now to see if things improve

**Comment by kaikreuzer** [comment]
I am not aware of any changes that could have fixed it... Nonetheless, it is good news that you don't see it anymore :-)

**Comment by AngelosF** [comment]
I just tried 2.4.0 M6 with 2.3.0 Stable Addons.kar and I can replicate it

checking the diff on pom.xml and features.xml now

more news soon

**Comment by AngelosF** [comment]
I think I found something...

openhab-addons-2.3.0.kar includes openhab-addons-2.3.0-features.xml which has for every feature 2 settings:

```
<feature prerequisite="false" dependency="false">
```

For example: The `bluetooth` which is being "auto-magically" installed has:
```
    <feature name="esh-binding-bluetooth" version="0.10.0.oh230">
        <feature prerequisite="false" dependency="false">esh-base</feature>
        <bundle>mvn:org.eclipse.smarthome.binding/org.eclipse.smarthome.binding.bluetooth/0.10.0.oh230</bundle>
    </feature>
```

This does NOT appear on openhab-addons-2.4.0-SNAPSHOT-features.xml

```
    <feature name="esh-binding-bluetooth" version="0.10.0.SNAPSHOT">
        <feature>esh-base</feature>
        <bundle>mvn:org.eclipse.smarthome.binding/org.eclipse.smarthome.binding.bluetooth/0.10.0-SNAPSHOT</bundle>
    </feature>
```

I found on the interweb the following statement also: 
```
Current usage of the resolver
Karaf 4 features already use the resolver to avoid installing duplicate versions of bundles like specs. It works by setting dependency=true on some bundles. All bundles with dependency=false or true form the repository to choose from. The top level requirements are the bundles with dependency=false (which is the default). The bundles with dependency=true will then only be installed if the resolver decides they are needed. So this forms a kind of poor man OBR repository.
```

So, if I am right, the resolver decides that these features are needed

Conclusion: openhab-addons-2.3.0.kar has a broken openhab-addons-2.3.0-features.xml

Someone else has to test my theory also.  Who can do this @kaikreuzer  ?

**Comment by AngelosF** [comment]
It doesn't work.. it tries to reach the online repo :(

Ok... test results for the offline kar:

OH 2.4.0M6 using openhab-addons-2.4.0-SNAPSHOT.kar from the latest Snapshot Build (#1433) in my $userdata/addons folder

Step 1) Deploy a clean 2.4.0M6 on Windows
Step 2) Start it up, select Expert package
Step 3) PaperUI -> Configuration -> System -> Add-on Management ->disable Access Remote Repository
Step 4) Enable DEBUG on org.openhab.core.karaf
Step 5) Stop OH2 and copy to the addons folder the offline kar
Step 6) Disable network connectivity on the host
Step 7) Start OH2, try to install KNXv2 binding from PaperUI:

Result:  [openhab.log](https://github.com/openhab/openhab-distro/files/2599533/openhab.log)

**Comment by AngelosF** [comment]
It works fine also in offline mode (I tried with network disabled on the host).  It installs the binding without any problem.

the addons.kar is in my $userdata/addons and it gets unpacked into tmp/kar

log: 
[openhab.log](https://github.com/openhab/openhab-distro/files/2599579/openhab.log)

**Comment by AngelosF** [comment]
I couldn't find the root cause
I cannot reproduce this one anymore with the latest Snapshots and Milestones (M6, M7), so I am going to close it.
