### ISSUE TITLE
Libraries for JSR223 Scripting do not work with Jython 2.7.1

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-distro#746]
Libraries do not work using JSR223 Scripting and Jython 2.7.1.
Every script is loaded using a fresh jython interpreter,
thus it is not possible to use libraries and and share data between scripts.
Correctly every script should be loaded with the same jython interpreter.

Steps to reproduce:
- Download Openhab2.3 from https://www.openhab.org/
- Copy [Jython Standalone](https://search.maven.org/search?q=g:org.python%20AND%20a:jython-standalone&core=gav) to Openhab2\runtime\lib\boot\
  Use 2.7.1 to reproduce problem, use 2.7.0 to see it work
- unzip attached file [automation.zip](https://github.com/openhab/openhab-distro/files/2289293/automation.zip) into Folder Openhab2\conf\
- Edit Openhab2\runtime\bin\setenv.bat Line 118:
  Insert:
    -Dpython.path=%OPENHAB_CONF%/automation/lib ^
  to add library path to JAVA_OPTS
- Start openhab (start.bat)
- See https://www.openhab.org/docs/tutorial/1sttimesetup.html and select Expert
- Activate JSR223 scripting (Next-Gen Rule Engine)
  https://www.openhab.org/docs/configuration/rules-ng.html#installation
- Stop Openhab and restart and watch output in console window
  Scripts are located in automation/jsr223
  Library is located in automation/lib

The Library sets a property and prints the status:
```python
   print( 'TESTPROP: {}'.format(hasattr(testModule, 'TESTPROP')))
   testModule.TESTPROP = 'TEST'
   print( 'TESTPROP: {}'.format(hasattr(testModule, 'TESTPROP')))
```

Correct Output (reproducible with jython 2.7.0 which was behaving not correct with imports and multiple interpreters):
```
   TESTPROP: 0
   TESTPROP: 1
```

Incorrect Output (jython 2.7.1 which behaves now correct):
```
   TESTPROP: 0
   TESTPROP: 1
   
   TESTPROP: 0
   TESTPROP: 1
```

Analysis from Jython-Team:
http://bugs.jython.org/issue2700

**Comment by kaikreuzer** [comment]
If I understand the analysis correctly, some change needs to be done in the jsr233 scripting support - hence please enter the issue at https://github.com/eclipse/smarthome/issues as this is where the code lives.
