### ISSUE TITLE
IDE fails to run, validation errors detected

### ISSUE THREAD

**Issue by bigbasec** [openhab/openhab-distro#75]
Followed the docs, as well as the video.  Windows 10 64 bit.  

2 Problems are detected : 
org.eclipse.jetty.server and org.eclipse.jetty.servlet

Both are "Missing constraint: Import-Package: org.eclipse.jetty.continuation; version="[8.1.0,9.0.0]"

**Comment by kaikreuzer** [comment]
Sounds as if you have done changes to the launch configuration. The one from the repo has only Jetty 9.2.12 bundles selected and they for sure do not have a dependency on <9.0 bundles of Jetty.

<img width="578" alt="screen shot 2016-01-15 at 22 10 01" src="https://cloud.githubusercontent.com/assets/3244965/12365384/c2cfbc0c-bbd4-11e5-8c88-dd0a1edb4dac.png">

**Comment by bigbasec** [comment]
I have done nothing short of following the directions and the the video.  It's a fresh install on a VM with no other workspaces or anything.  It was simple running the Eclipse Installer, and following the steps.  If I build the git directory that is created during that it builds, but doesn't create the nice zip files that OH1 used to.  So I'd like to just run it from the Eclipse GUI, but that fails with the above.  

I'll check the config and see if I can get it to run.  Thank you,

**Comment by bigbasec** [comment]
Nope, doesn't work.   Just literally built a new VM, installed everything from scratch (java, mvn, etc), and ran through the steps.  Same exact failure.

**Comment by dvanherbergen** [comment]
Which bundles have the validation failure?

**Comment by kaikreuzer** [comment]
@bigbasec Simply select the jetty bundles 9.2.12 as shown in my screenshot above and you definitely won't see these validation error. 

The [launch config](https://github.com/openhab/openhab-distro/blob/master/launch/openHAB_Runtime.launch) specifically contains bundles in version 9.2.12:
```
org.eclipse.jetty.server*9.2.12.v20150709@default:default,org.eclipse.jetty.servlet*9.2.12.v20150709@default:default
```
so there is no bug.
If you need further support, please visit our forum at http://community.openhab.org/.

**Comment by bigbasec** [comment]
Yea, I wasn't specifically calling out a bug, but possibly a documentation issue.  As all 5 of the environments that I have tried this on have all failed the same way.  For some reason the default is selected as the 9.x, but the 8.x versions are also selected.  May need to be added to the wiki docs to check that.

**Comment by kaikreuzer** [comment]
> As all 5 of the environments that I have tried this

Were all of them on Windows 10? It definitely does not occur on Mac OS X, but I would really wonder that it should behave differently on other platforms...

**Comment by bigbasec** [comment]
I tried on 2 windows 10 builds, 2 windows XP, finally got it to work correctly on a windows 7 VM.  So I'm off to the races for the most part.

**Comment by bartcerneels** [comment]
Just reproduced this on ubuntu 14.04 LTS 64-bit. Just following https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/ide.md
