### ISSUE TITLE
Update script should support milestones and RCs

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#754]
The update scripts currently do not allow to e.g. do
```
sudo ./runtime/bin/update 2.4.0.M3
```
It only supports releases and snapshots so far.

**Comment by BClark09** [comment]
Ah, I think the script would need to catch a `.RC` or `.M` in the version string, and redirect to the jfrog URL. At the moment it's looking for the version in Bintray. I should be able to send a PR if no one else can by next week.

**Comment by kaikreuzer** [comment]
Maybe it could also simply check for a `x.y.z.<something>` version and refer to the jfrog milestone url in that case.

**Comment by kaikreuzer** [comment]
@BClark09 Next milestone is out, but we still cannot update - your promised PR is highly anticipated!

**Comment by BClark09** [comment]
Sorry Kai, completely forgot about this issue. 🤦‍♂️  Here's a PR!

**Comment by schrej-zz** [comment]
Hi,
is this also valid for the Windows update script?

**Comment by BClark09** [comment]
Unfortunately not. I need to find time to learn powershell to be able to update the Windows scripts.
