### ISSUE TITLE
InfluxDB+Grafana installation error

### ISSUE THREAD

**Issue by lidderdj** [openhab/openhab-distro#769]
Hi,

I’m trying to install InfluxDB+Grafana from udo openhabian-config

It looks like it works (downloads, extracts etc) but when it goes back into the console I get the following error:

Operation Failed! ├───────────────────┐
│ │
│ Sadly there was a problem setting up the selected │
│ option. Please report this problem in the openHAB │
│ community forum or as a openHABian GitHub issue.

So, as suggested, raising it here (have also raised in the community forum)

Thanks in advance for your help.

**Comment by lidderdj** [comment]
The full log:


pi@raspberrypi:~ $ sudo openhabian-config
2018-09-18_19:31:07_AEST [openHABian] Checking for root privileges... OK
2018-09-18_19:31:07_AEST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
grep: /etc/cron.d/firemotd: No such file or directory
/opt/openhabian/functions/openhabian.sh: line 122: firemotd: command not found
2018-09-18_19:31:09_AEST [openHABian] openHABian configuration tool version: [master]v1.4.1-413(7799e0d)
2018-09-18_19:31:09_AEST [openHABian] Checking for changes in origin... OK
2018-09-18_19:31:22_AEST [openHABian] Setting up InfluxDB and Grafana...

$ apt -y install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.4.8).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

InfluxDB...
--2018-09-18 19:31:48--  https://repos.influxdata.com/influxdb.key
Resolving repos.influxdata.com (repos.influxdata.com)... 54.230.245.184, 54.230.245.113, 54.230.245.20, ...
Connecting to repos.influxdata.com (repos.influxdata.com)|54.230.245.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3108 (3.0K) [application/pgp-keys]
Saving to: ‘STDOUT’

-                   100%[===================>]   3.04K  --.-KB/s    in 0s

2018-09-18 19:31:48 (62.1 MB/s) - written to stdout [3108/3108]

OK

$ apt update
Get:1 https://repos.influxdata.com/debian stretch InRelease [4,732 B]
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Get:4 https://repos.influxdata.com/debian stretch/stable armhf Packages [917 B]
Ign:5 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:6 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:6 https://dl.bintray.com/openhab/apt-repo2 stable Release
Get:7 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.5 kB]
Get:8 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages [11.7 MB]
Hit:10 https://repo.mosquitto.org/debian jessie InRelease
Hit:11 https://repo.mosquitto.org/debian stretch InRelease
Err:7 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
Reading package lists... Done
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: GPG error: http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ apt -y install influxdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  influxdb
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 23.5 MB of archives.
After this operation, 71.9 MB of additional disk space will be used.
Get:1 https://repos.influxdata.com/debian stretch/stable armhf influxdb armhf 1.6.2-1 [23.5 MB]
Fetched 23.5 MB in 17s (1,320 kB/s)
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
Selecting previously unselected package influxdb.
(Reading database ... 121231 files and directories currently installed.)
Preparing to unpack .../influxdb_1.6.2-1_armhf.deb ...
Unpacking influxdb (1.6.2-1) ...
Setting up influxdb (1.6.2-1) ...
Created symlink /etc/systemd/system/influxd.service → /lib/systemd/system/influxdb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/influxdb.service → /lib/systemd/system/influxdb.service.
Processing triggers for man-db (2.7.6.1-2) ...
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

$ systemctl daemon-reload

$ systemctl enable influxdb.service

$ systemctl start influxdb.service
FAILED
Grafana...

$ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.SXTaugxbXF/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.SXTaugxbXF/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

$ apt update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:4 https://repos.influxdata.com/debian stretch InRelease
Get:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.5 kB]
Hit:5 https://repo.mosquitto.org/debian jessie InRelease
Ign:6 https://dl.bintray.com/fg2it/deb stretch InRelease
Hit:7 https://repo.mosquitto.org/debian stretch InRelease
Ign:8 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Err:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
Get:9 https://dl.bintray.com/fg2it/deb stretch Release [5,300 B]
Get:10 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:10 https://dl.bintray.com/openhab/apt-repo2 stable Release
Get:12 https://dl.bintray.com/fg2it/deb stretch Release.gpg [821 B]
Ign:12 https://dl.bintray.com/fg2it/deb stretch Release.gpg
Reading package lists... Done
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: GPG error: http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.bintray.com/fg2it/deb stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://dl.bintray.com/fg2it/deb stretch Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ apt -y install grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fonts-font-awesome golang-1.7-go golang-1.7-src golang-go golang-src
  grafana-data libjs-angularjs libjs-jquery-metadata libjs-jquery-tablesorter
  libjs-twitter-bootstrap libqt5qml5 libqt5quick5 libqt5webkit5 phantomjs
Suggested packages:
  bzr mercurial libjs-bootstrap qt5-qmltooling-plugins
The following NEW packages will be installed:
  fonts-font-awesome golang-1.7-go golang-1.7-src golang-go golang-src grafana
  grafana-data libjs-angularjs libjs-jquery-metadata libjs-jquery-tablesorter
  libjs-twitter-bootstrap libqt5qml5 libqt5quick5 libqt5webkit5 phantomjs
0 upgraded, 15 newly installed, 0 to remove and 3 not upgraded.
Need to get 40.4 MB of archives.
After this operation, 208 MB of additional disk space will be used.
Get:1 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf libqt5qml5 armhf 5.7.1-2+rpi1 [970 kB]
Get:2 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf libqt5quick5 armhf 5.7.1-2+rpi1 [896 kB]
Get:3 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf libqt5webkit5 armhf 5.7.1+dfsg-1+rpi1 [7,683 kB]
Get:4 http://mirror.solnode.io/raspbian stretch/main armhf fonts-font-awesome all 4.7.0~dfsg-1 [514 kB]
Get:7 http://mirror.solnode.io/raspbian stretch/main armhf golang-src armhf 2:1.7~5 [3,560 B]
Get:8 http://mirror.solnode.io/raspbian stretch/main armhf golang-go armhf 2:1.7~5 [22.7 kB]
Get:9 http://mirror.solnode.io/raspbian stretch/main armhf libjs-angularjs all 1.5.10-1 [700 kB]
Get:10 http://mirror.solnode.io/raspbian stretch/main armhf libjs-jquery-metadata all 11-3 [7,188 B]
Get:11 http://mirror.solnode.io/raspbian stretch/main armhf libjs-jquery-tablesorter all 11-3 [43.9 kB]
Get:5 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf golang-1.7-src armhf 1.7.4-2+rpi1 [7,677 kB]
Get:6 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf golang-1.7-go armhf 1.7.4-2+rpi1 [17.4 MB]
Get:12 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf libjs-twitter-bootstrap all 2.0.2+dfsg-10 [98.8 kB]
Get:13 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf grafana-data all 2.6.0+dfsg-3 [1,162 kB]
Get:14 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf grafana armhf 2.6.0+dfsg-3+b1 [2,959 kB]
Get:15 http://raspbian.melbourneitmirror.net/raspbian stretch/main armhf phantomjs armhf 2.1.1+dfsg-2 [277 kB]
Fetched 40.4 MB in 32s (1,260 kB/s)
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
Selecting previously unselected package libqt5qml5:armhf.
(Reading database ... 121257 files and directories currently installed.)
Preparing to unpack .../00-libqt5qml5_5.7.1-2+rpi1_armhf.deb ...
Unpacking libqt5qml5:armhf (5.7.1-2+rpi1) ...
Selecting previously unselected package libqt5quick5:armhf.
Preparing to unpack .../01-libqt5quick5_5.7.1-2+rpi1_armhf.deb ...
Unpacking libqt5quick5:armhf (5.7.1-2+rpi1) ...
Selecting previously unselected package libqt5webkit5:armhf.
Preparing to unpack .../02-libqt5webkit5_5.7.1+dfsg-1+rpi1_armhf.deb ...
Unpacking libqt5webkit5:armhf (5.7.1+dfsg-1+rpi1) ...
Selecting previously unselected package fonts-font-awesome.
Preparing to unpack .../03-fonts-font-awesome_4.7.0~dfsg-1_all.deb ...
Unpacking fonts-font-awesome (4.7.0~dfsg-1) ...
Selecting previously unselected package golang-1.7-src.
Preparing to unpack .../04-golang-1.7-src_1.7.4-2+rpi1_armhf.deb ...
Unpacking golang-1.7-src (1.7.4-2+rpi1) ...
Selecting previously unselected package golang-1.7-go.
Preparing to unpack .../05-golang-1.7-go_1.7.4-2+rpi1_armhf.deb ...
Unpacking golang-1.7-go (1.7.4-2+rpi1) ...
Selecting previously unselected package golang-src.
Preparing to unpack .../06-golang-src_2%3a1.7~5_armhf.deb ...
Unpacking golang-src (2:1.7~5) ...
Selecting previously unselected package golang-go.
Preparing to unpack .../07-golang-go_2%3a1.7~5_armhf.deb ...
Unpacking golang-go (2:1.7~5) ...
Selecting previously unselected package libjs-angularjs.
Preparing to unpack .../08-libjs-angularjs_1.5.10-1_all.deb ...
Unpacking libjs-angularjs (1.5.10-1) ...
Selecting previously unselected package libjs-jquery-metadata.
Preparing to unpack .../09-libjs-jquery-metadata_11-3_all.deb ...
Unpacking libjs-jquery-metadata (11-3) ...
Selecting previously unselected package libjs-jquery-tablesorter.
Preparing to unpack .../10-libjs-jquery-tablesorter_11-3_all.deb ...
Unpacking libjs-jquery-tablesorter (11-3) ...
Selecting previously unselected package libjs-twitter-bootstrap.
Preparing to unpack .../11-libjs-twitter-bootstrap_2.0.2+dfsg-10_all.deb ...
Unpacking libjs-twitter-bootstrap (2.0.2+dfsg-10) ...
Selecting previously unselected package grafana-data.
Preparing to unpack .../12-grafana-data_2.6.0+dfsg-3_all.deb ...
Unpacking grafana-data (2.6.0+dfsg-3) ...
Selecting previously unselected package grafana.
Preparing to unpack .../13-grafana_2.6.0+dfsg-3+b1_armhf.deb ...
Unpacking grafana (2.6.0+dfsg-3+b1) ...
Selecting previously unselected package phantomjs.
Preparing to unpack .../14-phantomjs_2.1.1+dfsg-2_armhf.deb ...
Unpacking phantomjs (2.1.1+dfsg-2) ...
Setting up libqt5qml5:armhf (5.7.1-2+rpi1) ...
Setting up libqt5quick5:armhf (5.7.1-2+rpi1) ...
Setting up libqt5webkit5:armhf (5.7.1+dfsg-1+rpi1) ...
Setting up phantomjs (2.1.1+dfsg-2) ...
Setting up fonts-font-awesome (4.7.0~dfsg-1) ...
Setting up libjs-angularjs (1.5.10-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u4) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up golang-1.7-src (1.7.4-2+rpi1) ...
Setting up libjs-jquery-metadata (11-3) ...
Processing triggers for fontconfig (2.11.0-6.7) ...
Setting up libjs-jquery-tablesorter (11-3) ...
Setting up libjs-twitter-bootstrap (2.0.2+dfsg-10) ...
Setting up golang-src (2:1.7~5) ...
Setting up grafana-data (2.6.0+dfsg-3) ...
Setting up golang-1.7-go (1.7.4-2+rpi1) ...
Setting up golang-go (2:1.7~5) ...
Setting up grafana (2.6.0+dfsg-3+b1) ...
Created symlink /etc/systemd/system/grafana-server.service → /lib/systemd/system/grafana.service.
Created symlink /etc/systemd/system/multi-user.target.wants/grafana.service → /lib/systemd/system/grafana.service.
Processing triggers for systemd (232-25+deb9u4) ...
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

$ systemctl daemon-reload

$ systemctl enable grafana-server.service
Failed to enable unit: Refusing to operate on linked unit file grafana-server.service

$ systemctl start grafana-server.service
FAILED
Connecting (TODO)...
Adding openHAB dashboard tile...
2018-09-18_19:36:08_AEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... OK
2018-09-18_19:44:08_AEST [openHABian] Setting up InfluxDB and Grafana...

$ apt -y install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.4.8).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

InfluxDB...
--2018-09-18 19:44:15--  https://repos.influxdata.com/influxdb.key
Resolving repos.influxdata.com (repos.influxdata.com)... 13.32.126.116, 13.32.126.5, 13.32.126.95, ...
Connecting to repos.influxdata.com (repos.influxdata.com)|13.32.126.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3108 (3.0K) [application/pgp-keys]
Saving to: ‘STDOUT’

-                   100%[===================>]   3.04K  --.-KB/s    in 0s

2018-09-18 19:44:15 (94.5 MB/s) - written to stdout [3108/3108]

OK

$ apt update
Hit:1 https://repos.influxdata.com/debian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:4 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Get:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.5 kB]
Ign:5 https://dl.bintray.com/fg2it/deb stretch InRelease
Ign:6 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:7 https://dl.bintray.com/fg2it/deb stretch Release [5,300 B]
Hit:8 https://repo.mosquitto.org/debian jessie InRelease
Err:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
Get:9 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:9 https://dl.bintray.com/openhab/apt-repo2 stable Release
Hit:10 https://repo.mosquitto.org/debian stretch InRelease
Get:12 https://dl.bintray.com/fg2it/deb stretch Release.gpg [821 B]
Ign:12 https://dl.bintray.com/fg2it/deb stretch Release.gpg
Reading package lists... Done
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: GPG error: http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.bintray.com/fg2it/deb stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://dl.bintray.com/fg2it/deb stretch Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ apt -y install influxdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
influxdb is already the newest version (1.6.2-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

$ systemctl daemon-reload

$ systemctl enable influxdb.service

$ systemctl start influxdb.service
FAILED
Grafana...

$ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.t2wDObmY0i/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.t2wDObmY0i/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

$ apt update
Hit:1 https://repos.influxdata.com/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease
Get:4 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.5 kB]
Ign:5 https://dl.bintray.com/fg2it/deb stretch InRelease
Ign:6 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Hit:7 https://repo.mosquitto.org/debian jessie InRelease
Err:4 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
Get:8 https://dl.bintray.com/fg2it/deb stretch Release [5,300 B]
Hit:9 https://repo.mosquitto.org/debian stretch InRelease
Get:10 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:10 https://dl.bintray.com/openhab/apt-repo2 stable Release
Get:12 https://dl.bintray.com/fg2it/deb stretch Release.gpg [821 B]
Ign:12 https://dl.bintray.com/fg2it/deb stretch Release.gpg
Reading package lists... Done
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: GPG error: http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.bintray.com/fg2it/deb stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://dl.bintray.com/fg2it/deb stretch Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ apt -y install grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
grafana is already the newest version (2.6.0+dfsg-3+b1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

$ systemctl daemon-reload

$ systemctl enable grafana-server.service
Failed to enable unit: Refusing to operate on linked unit file grafana-server.service

$ systemctl start grafana-server.service
FAILED
Connecting (TODO)...
Adding openHAB dashboard tile...
2018-09-18_19:44:44_AEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... Replacing... OK
2018-09-18_19:45:07_AEST [openHABian] Checking for default openHABian username:password combination... OK
2018-09-18_19:45:08_AEST [openHABian] We hope you got what you came for! See you again soon ;)

**Comment by kaikreuzer** [comment]
Doesn't look to be related to the openhab distro itself, so please report it at https://github.com/openhab/openhabian/issues instead. Thanks!
