### ISSUE TITLE
package ordering

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-distro#773]
Hi,
absolute unsure which repo to raise this against or if it is at all possible to do this inside here.
I noticed a possible dependency of packages on each other to not be fulfilled at times.

When I apt-get (dist-)upgrade on my openHABian (or any debian), it'll offer me the packages to upgrade in a particular order, openhab2 being first and openhab2-addons(-legacy) after.
Now that resulted in openhab2 being (re)started without that the next package was installed (apt-get was still busy downloading that).
So that results in the updated OH2 version running against old addons, and a "restart" of that addons part of the code whenever the remaining packages installed successfully.
Not sure about the full impact but one for sure thing is that it'll delay startup (and given the large number of users to run on RPi that's not to be underestimated as a problem/improvement).

Shouldn't we sort of rework-reorder-whatever this to force addons to get installed BEFORE main OH2?
Not sure if we can simply change the order of packages the repo offers, or how to accomplish that at all.

**Comment by kaikreuzer** [comment]
Assuming you are talking about Linux packages here, this issue should really go to https://github.com/openhab/openhab-linuxpkg as I wouldn't know what should be done in the distro itself about it.
