### ISSUE TITLE
Does openHAB work with zigbee2mqtt sniffers

### ISSUE THREAD

**Issue by ghasemikasra39** [openhab/openhab-distro#776]
I want to know whether or not, openHAB works with [zigbe2mqtt](https://github.com/Koenkk/zigbee2mqtt) [sniffers](https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-sniffer-devices). (Is it possible to connect these devices to openHAB? So that the traffic can be captured in openHAB)

**Comment by kaikreuzer** [comment]
Please use our community forum at https://community.openhab.org/ for such questions.
