### ISSUE TITLE
Snapshot 1388: HTTP ERROR 404 when opening UIs

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#788]
HTTP ERROR 404 error when opening Paper UI, Classic UI or Basic UI.
Opening REST API is OK.

Reading the last PR merged, I was expecting that it could be have been fixed in this snapshot.

Return to an old snapshot.

**Comment by kaikreuzer** [comment]
I've created https://github.com/eclipse/smarthome/pull/6351 that should fix it.

**Comment by kaikreuzer** [comment]
Fixed in snapshot 1389.

**Comment by lolodomo** [comment]
Thank you.
I will check the nww anapshot this evening.
