### ISSUE TITLE
Push messages

### ISSUE THREAD

**Issue by fastLion** [openhab/openhab-distro#789]
Hi together, 
I may have come across a bug. Since about 2 weeks I get every day push messages on my phone (Android) about open doors, windows garage doors an so on. Some of them in English, other s are coming in German.
The point is that I do not have any instance of openhab running and as well have delete the previous instance from my cloud account.
When I tap on the push message the application will be started with a blank screen.
I'm not sure this here is the right place to post it I thought I have to mention this as it seems that the isolation to other accounts is somehow not perfect. 
If I can help with providing more information your guys and girls need, let me know. But be aware I'm not family with coding. 
By the way, native language for me is German but English is not a problem at all. 

Look forward to hear from you
Jens :-)

**Comment by digitaldan** [comment]
Hi Jens, apologies for the inconvenience. We have a known issues where push notification tokens get duplicated resulting in messages being sent to the wrong device.  I have cleared out the offending entry for your account, which will stop the errant messages.
