### ISSUE TITLE
rules using item names starting with numbers fail

### ISSUE THREAD

**Issue by angergely** [openhab/openhab-distro#796]
See details: https://community.openhab.org/t/rule-with-item-that-starts-with-a-number-not-running/41608
But in short it seems that the rule interpreter has an issue with item names starting with numbers, eg.:

sample.rules:
rule "sample"
    when
        Item 04bed064_0031_46ad_9cbe_7f48cd03c127 received update
    then
...
end

log:
2018-10-17 13:34:50.089 [WARNING] [org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl addOrRefreshModel] - Configuration model 'sample.rules' has errors, therefore ignoring it: [9,14]: mismatched character 'e' expecting set null

This is a problem if the item names are generated (eg UUIDs).

**Comment by kaikreuzer** [comment]
> an issue with item names starting with numbers

This is not valid. See https://www.openhab.org/docs/configuration/items.html#item-definition-and-syntax:

_The only characters permitted in an Item name are letters, numbers and the underscore character. Names must not begin with numbers._
