### ISSUE TITLE
Backup script: Make openHAB (ESH) sync all memory content to files first

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-distro#799]
The current backup script only copies user files, but does not inform a possible running instance
to sync memory content to files first.

If the user has configured a high in-memory cache time to protect his SD card for example,
the backup will not reflect the current state.

I see two possible solutions:

1. Add an OSGI console command or a REST endpoint to sync memory to files. The call could block until the sync has finished and the script can continue from there on.
2. Initiate the backup (copying of files) from within the ESH framework. A console command or REST endpoint would initiate the procedure. The backup script would only be a wrapper around a wget/curl call to that REST endpoint.

**Comment by kaikreuzer** [comment]
I think both options would involve changes in ESH itself as its code would have to deal with such a request, so imho it would make sense to open the issue there and not here.
