### ISSUE TITLE
Uninstalling a binding does not suppress its cfg file

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#80]
When I install from Paper UI the weather binding (1.8), a file named "weather.cfg" is automatically created in conf/services sub-directory.
When I uninstall the binding, weather.cfg is not removed.
Is it expected ?

**Comment by kaikreuzer** [comment]
Expected, since the conf folder is considered read-only (with the exception that files are created if they don't exist. But there is never anything deleted or modified, since these files belong to the user.
