### ISSUE TITLE
request: Implicit variable in rules with rule details

### ISSUE THREAD

**Issue by CrispinP** [openhab/openhab-distro#802]
It would be handy if a rule could have an implicit variable which has the rule details such as name, execution time and triggering item. This would be useful for logging and debugging.

`
`rule "my rule name"
`when Item xyz changed to ON
`then
`
`logWarn(ruleVar.name, "rule called: " + ruleVar.toString)
`
`
`end 
`
`

Any or all options would be welcome and used.

**Comment by kaikreuzer** [comment]
I'd claim that all of it is already available:
- Rule name: Well, it is a static string, so it isn't too hard to simply copy the name into the rule itself. There isn't a real need for having it as a variable as it isn't variable.
- Execution time: Just to a `new Date()` and you have the current execution time
- Triggering Item: Well, as long as there is only one, you do not need it. If you have a group and want to find the item, you can use the "Member of" trigger for rules: https://www.openhab.org/docs/configuration/rules-dsl.html#member-of-triggers.
