### ISSUE TITLE
Snapshot location 

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-distro#808]
Was testing my new windows update script and noticed that the snapshot urls point to cloudbees - I'm assuming they need to point to ci.openhab.org instead?  The linux version will need to be changed as well.

**Comment by kaikreuzer** [comment]
All update scripts (WIndows & Linux) had been updated with https://github.com/openhab/openhab-distro/pull/797/files. What is missing from your pov?

**Comment by tmrobert8** [comment]
Argh - that was my fault.  Didn't realize I was looking at my 2.3 stable directory.
