### ISSUE TITLE
Start/Stop Scripts/Environment Variables

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-distro#815]
Looks like almost all the windows scripts totally ignore any environment variables defined that describe where directories are located.

Example:  start.bat has ""%DIRNAME%runtime" (where DIRNAME is the location of the start script) hardcoded in it rather than looking for an OPENHAB_RUNTIME variable (and using DIRNAME if not defined).  

Looks like start.sh is the same way

Once it get's to the karaf.bat/sh - the environment variables are set (and may or may not be used at that point).

**Comment by BClark09** [comment]
This is only true for the zip file's root `start[_debug] script right? If you were to run the karaf.bat script straight away, it sources the location from `setenv.bat` (which then calls `oh_dir_layout`.bat), which then uses the environment variables if set.

**Comment by tmrobert8** [comment]
Haven't tried it yet but I'm betting you are correct...

**Comment by tmrobert8** [comment]
fyi - just submitted pr on this

**Comment by BClark09** [comment]
Awesome, thanks!

**Comment by wborn** [comment]
This was fixed by https://github.com/openhab/openhab-distro/issues/815.
