### ISSUE TITLE
Add-on "MQTT Action" hangs after update SNAPSHOT 

### ISSUE THREAD

**Issue by stritti** [openhab/openhab-distro#818]
I use add-on "MQTT Action" version `action-mqtt - 1.13.0.SNAPSHOT` on my Raspberry Pi installation of 
openHAB 2.4.0 ( currently Build #1447).

I found, that on some updates using `sudo apt-get upgrade` the add-on "MQTT Action" in not working any more. 

After a longer time of investigation I found following workaround: 
* uninstall "MQTT Action" in Paper UI
* reinstall "MQTT Action"

After that, sending MQTT-actions is working fine again. 

In the log files I found no hints for this issue.

**Comment by kaikreuzer** [comment]
This is a known issue and tracked as https://github.com/openhab/openhab1-addons/issues/5038.
