### ISSUE TITLE
MQTT 2.4 reload config

### ISSUE THREAD

**Issue by sasbibic** [openhab/openhab-distro#828]
Version 2.4 MQTT: When things config file updates I get this message into my log:
2018-12-19 09:31:34.520 [hingStatusInfoChangedEvent] - 'mqtt:topic:mymqtt' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): java.lang.Exception: No MQTT client

MQTT stops working, restarting bundle in console:
231 │ Active │ 80 │ 0.10.0.oh240 │ Eclipse SmartHome MQTT Transport Bundle
resolves problem.

**Comment by wborn** [comment]
Please use the Eclipse SmartHome [issue tracker](https://github.com/eclipse/smarthome/issues) for reporting MQTT Binding related issues. That's the repository where the MQTT Binding source code is maintained.
