### ISSUE TITLE
Mappings issue

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-distro#83]
Both  Classic UI or Basic UI does not support mappings which contains '.' (dot) character. Samsung TV contains web browser, which can be controlled via Samsung TV binding. Currently it's impossible to launch URL which contains dot characters.

```
Selection item=TV_Web_Browser_Url mappings=["www.google.com"=Google, "www.openhab.org"=openHAB]
```

**Comment by kaikreuzer** [comment]
Could you please create one issue per UI at https://github.com/eclipse/smarthome/issues? Thanks!
