### ISSUE TITLE
MQTT 2.4 and Homie: Device with dashes won't work correct

### ISSUE THREAD

**Issue by manswiss** [openhab/openhab-distro#836]
When I add a Homie MQTT device with dashes '-' in the id and this thing has a switch item, it not receives updates or send commands. When I add the same device without dashes in the id, it work correct.

https://community.openhab.org/t/mqtt-homie-switch-wont-work/62104

**Comment by kaikreuzer** [comment]
Please enter the issue at https://github.com/eclipse/smarthome/issues as this is where the MQTT binding lives.
