### ISSUE TITLE
openHAB causing a lot of disc IOs for Java PerfLogs

### ISSUE THREAD

**Issue by drs-project** [openhab/openhab-distro#847]
On my machine (Ubuntu 18.04, Openhab testing, Open JDK 1.8) openhab is permanently writing PerfLogs to /tmp. This keeps the disc from entering standby mode, even if nothing is happening.

Could we add the following option to the default Java parameters to disable PerfLogs for the simple user?
`-XX:-UsePerfData`

**Comment by davidgraeff** [comment]
I think this is rather critical, isn't it? @kaikreuzer

**Comment by kaikreuzer** [comment]
I don't know, as nobody came up with this for years, I don't have the impression that it should be considered critical...?

It seems that this setting is off by default on the embedded JVMs we use on ARM devices. So it is probably only an issue for x86 systems.

But I am not opposed to explicitly setting it to disabled in our launch scripts. Anybody wants to do a PR?
