### ISSUE TITLE
[openHAB.Runtime.launch] Launch script doesn't run successfully!

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab-distro#851]
Dear Community,

I installed the Eclipse IDE with all of its openhab2 projects and the eclipe smart home runtime. Then after running all setup tasks I was expecting to fire up  the launch of the system and see the result in the browser by calling http://localhost:8080. Unfortunately I got this stacktrace (see below). I am running a Windows 10 System, my jdk is 1.8.201. Thanks in advance for any help. 

By the way: why are there so many errors and warnings in the openhab2 code? 

> !SESSION SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 2019-01-21 13:10:58.704 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_201
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
> Framework arguments:  -application org.eclipse.ui.ide.workbench
> Command-line arguments:  -application org.eclipse.ui.ide.workbench -data C:\Users\jobauer\joba\workspaceopenhab\openhab2-master\ws/../runtime-org.openhab.runtime.product.product -dev file:C:/Users/jobauer/joba/workspaceopenhab/openhab2-master/ws/.metadata/.plugins/org.eclipse.pde.core/openHAB_Runtime/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -console
> 
> !ENTRY org.eclipse.jetty.osgi.boot 4 0 2019-01-21 13:11:00.142
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.osgi.boot [54]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.annotations; version="[9.3.0,10.0.0)"; resolution:="optional"
>   Unresolved requirement: Import-Package: org.eclipse.jetty.deploy; version="[9.3.0,10.0.0)"
>     -> Export-Package: org.eclipse.jetty.deploy; bundle-symbolic-name="org.eclipse.jetty.deploy"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.deploy.graph,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component"
>        org.eclipse.jetty.deploy [50]
>          Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.3.15,9.3.16)"; resolution:="optional"
>          Unresolved requirement: Import-Package: org.eclipse.jetty.server; version="[9.3.15,9.3.16)"
>   Unresolved requirement: Import-Package: org.eclipse.jetty.deploy.bindings; version="[9.3.0,10.0.0)"
>     -> Export-Package: org.eclipse.jetty.deploy.bindings; bundle-symbolic-name="org.eclipse.jetty.deploy"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.deploy,org.eclipse.jetty.deploy.graph,org.eclipse.jetty.server"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> osgi> 
> !ENTRY org.eclipse.jetty.client 4 0 2019-01-21 13:11:00.314
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.client [49]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.deploy 4 0 2019-01-21 13:11:00.315
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.deploy [50]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.3.15,9.3.16)"; resolution:="optional"
>   Unresolved requirement: Import-Package: org.eclipse.jetty.server; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.osgi.httpservice 4 0 2019-01-21 13:11:00.317
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.osgi.httpservice [55]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.servlet; version="[9.1.0,10.0.0)"
>     -> Export-Package: org.eclipse.jetty.servlet; bundle-symbolic-name="org.eclipse.jetty.servlet"; bundle-version="9.4.5.v20170502"; version="9.4.5"; uses:="javax.servlet,javax.servlet.descriptor,javax.servlet.http,org.eclipse.jetty.http.pathmap,org.eclipse.jetty.security,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.server.handler.gzip,org.eclipse.jetty.server.session,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.resource"
>        org.eclipse.jetty.servlet [59]
>          Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.4.5,9.4.6)"; resolution:="optional"
>          Unresolved requirement: Import-Package: org.eclipse.jetty.security; version="[9.4.5,9.4.6)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.proxy 4 0 2019-01-21 13:11:00.319
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.proxy [56]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.client; version="[9.3.15,9.3.16)"
>     -> Export-Package: org.eclipse.jetty.client; bundle-symbolic-name="org.eclipse.jetty.client"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.client.api,org.eclipse.jetty.client.util,org.eclipse.jetty.http,org.eclipse.jetty.io,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.ssl,org.eclipse.jetty.util.thread"
>        org.eclipse.jetty.client [49]
>          Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.15,9.3.16)"
>   Unresolved requirement: Import-Package: org.eclipse.jetty.client.api; version="[9.3.15,9.3.16)"
>     -> Export-Package: org.eclipse.jetty.client.api; bundle-symbolic-name="org.eclipse.jetty.client"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.http,org.eclipse.jetty.util"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.security 4 0 2019-01-21 13:11:00.320
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.security [57]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.servlet 4 0 2019-01-21 13:11:00.322
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.servlet [59]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.4.5,9.4.6)"; resolution:="optional"
>   Unresolved requirement: Import-Package: org.eclipse.jetty.security; version="[9.4.5,9.4.6)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.webapp 4 0 2019-01-21 13:11:00.323
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.webapp [61]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.websocket.client 4 0 2019-01-21 13:11:00.324
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.websocket.client [63]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.io; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.websocket.common 4 0 2019-01-21 13:11:00.326
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.websocket.common [64]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.io; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.jetty.xml 4 0 2019-01-21 13:11:00.327
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.xml [65]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.util; version="[9.3.15,9.3.16)"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.jupnp 4 0 2019-01-21 13:11:00.366
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: org.jupnp [76]
>   Unresolved requirement: Import-Package: org.eclipse.jetty.client; version="[9.3.14,10.0.0)"
>     -> Export-Package: org.eclipse.jetty.client; bundle-symbolic-name="org.eclipse.jetty.client"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.client.api,org.eclipse.jetty.client.util,org.eclipse.jetty.http,org.eclipse.jetty.io,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.ssl,org.eclipse.jetty.util.thread"
>        org.eclipse.jetty.client [49]
>          Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.15,9.3.16)"
>   Unresolved requirement: Import-Package: org.eclipse.jetty.client.api; version="[9.3.14,10.0.0)"
>     -> Export-Package: org.eclipse.jetty.client.api; bundle-symbolic-name="org.eclipse.jetty.client"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.http,org.eclipse.jetty.util"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.368
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.client_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.369
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.deploy_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.370
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.osgi.boot_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.371
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.osgi.httpservice_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.372
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.proxy_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.373
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.security_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.374
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.security_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.375
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.servlet_9.4.5.v20170502.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.376
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.servlet_9.4.5.v20170502.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.376
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.webapp_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.377
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.websocket.client_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.378
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.websocket.common_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.379
> !MESSAGE Bundle initial@reference:file:plugins/org.eclipse.jetty.xml_9.3.15.v20161220.jar was not resolved.
> 
> !ENTRY org.eclipse.osgi 4 0 2019-01-21 13:11:00.380
> !MESSAGE Bundle initial@reference:file:plugins/org.jupnp_2.5.1.jar was not resolved.

**Comment by kelsaka** [comment]
same issue here

**Comment by vitp77** [comment]
Same issue here

**Comment by openhab-5iver** [comment]
Everything has been updated after the ESH migration. [The instructions have changed](https://www.openhab.org/docs/developer/development/ide.html), so read those and give it another try.

**Comment by vitp77** [comment]
Thanks for the advice! But it doesn't. When you start the application (or debug) appears here is a window (I'm new).

Добрый день.

Best regards, VitP

**Comment by openhab-5iver** [comment]
@vitp77, you will need to provide more details, as I am not seeing the above errors. I believe @Jochen1980 now has a functioning IDE and this issue can be closed. If you are having trouble setting up the IDE, it would be best to bring it up in the forum.

**Comment by vitp77** [comment]
Yeah, sure, close it. I never once failed to go to https://community.openhab.org website is not responding.

**Comment by Jochen1980** [comment]
I got a working launch script now, thanks! (Windows 10, only openHAB-Addon-Development-Project was created and all launches smoothly!
