### ISSUE TITLE
Sitemap Slider min/max ignored

### ISSUE THREAD

**Issue by CrazyIvan359** [openhab/openhab-distro#870]
So I am trying to switch to using Sliders with a minValue and maxValue for some devices I have that dim lights using a byte (0-255), instead of dimmers. Prior to 2.5, I was using dimmers and transformations on the mqtt sub and pub, but pub transformations are not possible with the new mqtt binding

From the documentation for sliders:
_`minValue` (defaults to 0) and `maxValue` (defaults to 100) limit the possible range of the value (both included in the range)._
However, these settings seem to be ignored by sliders. They are only displaying and sending commands 0-100, despite being attached to a number item and having `maxValue=255`

OH version: 2.5.0~S1521

**Comment by sirea07** [comment]
Although you can set `minValue` and `maxValue`, I guess the maximum range is from 0 to100, i.e. you should be able to set 80 but not 120 for `maxValue`. At least that is what I understand from reading the following part in the documentation: *"This type presents a value as a user-adjustable control which slides from **left (0) to right (100)**"*

I am using the [MQTT Generic Thing Binding](https://www.openhab.org/addons/bindings/mqtt.generic/) and with that I was able to use the transformation (see `transformationPattern` and `transformationPatternOut`). However the outgoing transformation only works with the latest Snapshot. In the current release version 2.4 you can only use `transformationPattern`.

**Comment by CrazyIvan359** [comment]
@sirea07 I did not see that the `transformationPatternOut` had been merged, but I would still like to move away from that in preference of using 0-255 in openHAB.

I did try setting the `maxValue` to 50 to see if what worked, but the slider still sends commands between 0-100

**Comment by sirea07** [comment]
Ok that sounds odd, but since it is a widely used component, I would have expected a lot of issues being reported if it would be a general problem in 2.4. Therefore I guess that it's a problem with your configuration. Please add more details about your item and sitemap config.

**Comment by CrazyIvan359** [comment]
@sirea07 sorry, I am running 2.5 snapshot not 2.4, I have edited my post. I will provide example configs when I get back home tonight

**Comment by CrazyIvan359** [comment]
Please disregard this issue.

I was not running 1521 as I thought when I tried the `maxValue` for the sliders. I am running 1512 now and it is working perfectly
