### ISSUE TITLE
[Demo] Button Switch in Demo does not work

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab-distro#875]
Dear Developers,

The demo at http://demo.openhab.org:8080/basicui/app?w=0202&sitemap=demo does not work properly. See Widget Overview and hit the button switch. This button does not change its status.

Best regards,
Jochen

**Comment by Jochen1980** [comment]
Thanks for the feedback. I was not able to see that this is meant to be a feature - for me it was just a button which is not working properly.

**Comment by ColinShorts** [comment]
Perhaps it would be worthwhile to use the expire binding for this button?

**Comment by wborn** [comment]
Let's then close this since it seems to work as expected.
