### ISSUE TITLE
Build is not properly cleaned before building

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-distro#878]
I just noted that the systeminfo binding is broken on my snapshot, I checked the distributable from jfrog:

https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.systeminfo/2.5.0-SNAPSHOT/

![image](https://user-images.githubusercontent.com/2625279/53120264-be217e80-3551-11e9-9f4c-8dceff82201d.png)

It seems that the build is not properly cleaned.

@kaikreuzer / @pfink would it make sense to add / enable this:

![image](https://user-images.githubusercontent.com/2625279/53120648-9a126d00-3552-11e9-8145-7c84ec3db4a1.png)

I did not yet add it, but could if you agree?

**Comment by cweitkamp** [comment]
We had a similar [issue](https://github.com/openhab/openhab2-addons/issues/4468) some time ago where a package was moved into a different folder.

**Comment by kaikreuzer** [comment]
> I did not yet add it, but could if you agree?

I do agree!

**Comment by martinvw** [comment]
The build is now failing for other reasons:

@wborn is this related to what you were working on?

```
11:09:28 [ERROR] Cannot resolve project dependencies:
11:09:28 [ERROR]   Software being installed: org.openhab.io.rest.docs 2.5.0.qualifier
11:09:28 [ERROR]   Missing requirement: org.openhab.io.rest.docs 2.5.0.qualifier requires 'java.package; org.openhab.ui.dashboard 0.0.0' but it could not be found
11:09:28 [ERROR] 
11:09:29 [ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
11:09:29 [ERROR] Cannot resolve dependencies of MavenProject: org.openhab.io:org.openhab.io.rest.docs:2.5.0-SNAPSHOT @ /var/jenkins_home/workspace/openHAB2-Bundles/openhab2-addons/addons/io/org.openhab.io.rest.docs/pom.xml: See log for details -> [Help 1]
11:09:29 [ERROR] 
11:09:29 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
11:09:29 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
11:09:29 [ERROR] 
11:09:29 [ERROR] For more information about the errors and possible solutions, please read the following articles:
11:09:29 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by wborn** [comment]
I've created some PRs for that @martinvw see: 
* https://github.com/openhab/openhab-webui/pull/10
* https://github.com/openhab/openhab2-addons/pull/4954

**Comment by martinvw** [comment]
Build is green and https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/binding/org.openhab.binding.systeminfo/2.5.0-SNAPSHOT/ looks fine!

Thanks all!
