### ISSUE TITLE
launch config: Equinox bundle duplicates

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-distro#884]
I have installed openHAB Addons development (only) on the Eclipse IDE 2019-03.

The "openHAB_Runtime" launch configuration contains some Equinox bundles selected in two versions:

* org.eclipse.equinox.region
  * 1.4.0.v20170117-1425
  * 1.4.100.v20171221-2204
* org.eclipse.equinox.transform.hook
  * 1.2.0.v20170105-1446
  * 1.2.100.v20171221-2204
* org.eclipse.equinox.util
  * 1.0.500.v20130404-1337
  * 1.1.0.v20180419-0833
* org.eclipse.equinox.weaving.hook
  * 1.2.0.v20160929-1449
  * 1.2.100.v20171221-2204

The validation problem notification will disappear if you select e.g. the most recent version only of the bundles.

**Comment by maggu2810** [comment]
This causes the problem that has been already reported by @lucacalcaterra here:
 https://github.com/openhab/openhab-distro/issues/879#issuecomment-465995445

**Comment by wborn** [comment]
If anyone still runs into it, running the setup tasks in Eclipse should fix it. See also #885.
