### ISSUE TITLE
Repository is down

### ISSUE THREAD

**Issue by Aydan** [openhab/openhab-distro#893]
I tried updating openhab the weekend before last, but it failed with:
“E: The repository ‘https://dl.bintray.com/openhab/apt-repo2 stable Release’ does no longer have a Release file.”

So I thought maybe the repo is being updated.
I tried again last weekend and just now and still get the same error.
When I browse to the URL I only see empty folders. browsing https://dl.bintray.com/openhab/apt-repo  will show the proper repository structure.
There seems to be a problem with the repository synchronisation.

**Comment by wborn** [comment]
Is this still an issue? There have been some outages of Bintray recently. See their [status page](https://status.bintray.com/).

**Comment by Aydan** [comment]
Browsing to https://dl.bintray.com/openhab/apt-repo2/ and opening dists still shows "The requested path was not found.", so the repo is still unusable.

**Comment by J-N-K** [comment]
Works for me

**Comment by wborn** [comment]
Works for me too:

![repo](https://user-images.githubusercontent.com/12213581/54865296-b2e58c80-4d63-11e9-9152-a7ff4bd7c897.png)

**Comment by openhab-5iver** [comment]
From the US, everything is taking a very long time, but eventually got through.

**Comment by Aydan** [comment]
Look at the paths you get from curl, they are prepended with a colon. For me it only works in the browser when I enable java script.
Apt update still throws an error:
```
Err:12 https://dl.bintray.com/openhab/apt-repo2 stable Release
  Received HTTP code 502 from proxy after CONNECT
```
and
```
E: The repository 'https://dl.bintray.com/openhab/apt-repo2 stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

If apt tries to resolve paths from an answer like curl gets, then it won't find any files.

**Comment by wborn** [comment]
I don't use the APT repo myself often. Does your APT sources list contain the right repo since it shows "stable Release"? It should contain:

```
deb https://dl.bintray.com/openhab/apt-repo2 stable main
```

See: https://www.openhab.org/docs/installation/linux.html

**Comment by Aydan** [comment]
~$ cat /etc/apt/sources.list.d/openhab.list 
deb https://dl.bintray.com/openhab/apt-repo2 stable main

**Comment by wborn** [comment]
I don't use it myself. I think it's time now to call @BClark09 to the rescue. :-)

**Comment by BClark09** [comment]
Hi @Aydan,

I'm not sure if I can help, Bintray has recently been unstable but the issues you're having seem like a problem with your particular connection. Your settings file is correct.  Are you able to see the distributions of other package repositories inside Bintray?

e.g. Try https://dl.bintray.com/amurzeau/debian/ (The first one I found on google) 

Does this issue also happen for our artifactory repository? e.g. Try:

```
deb https://openhab.jfrog.io/openhab/openhab-linuxpkg stable main
```

**Comment by wborn** [comment]
I just successfully installed openhab stable on a Debian 9 VM:

```
root@debian:/home/wouter# apt update
Ign:1 http://ftp.nl.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Get:3 http://ftp.nl.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:4 http://ftp.nl.debian.org/debian stretch Release
Ign:5 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:6 https://dl.bintray.com/openhab/apt-repo2 stable Release [6051 B]
Get:8 https://dl.bintray.com/openhab/apt-repo2 stable Release.gpg [821 B]
Get:9 https://dl.bintray.com/openhab/apt-repo2 stable/main amd64 Packages [1812 B]
Fetched 99.7 kB in 0s (307 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@debian:/home/wouter# apt install openhab2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  zulu-8 | zulu-embedded-8 | oracle-java8-installer | openjdk-8-jdk-headless
The following NEW packages will be installed:
  openhab2
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 73.7 MB of archives.
After this operation, 83.5 MB of additional disk space will be used.
Get:1 https://dl.bintray.com/openhab/apt-repo2 stable/main amd64 openhab2 all 2.4.0-1 [73.7 MB]
Fetched 73.7 MB in 6s (12.2 MB/s)                                                                                                                                                              
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!...................................................................................................................] 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "nl_NL.UTF-8",
	LC_MONETARY = "nl_NL.UTF-8",
	LC_ADDRESS = "nl_NL.UTF-8",
	LC_TELEPHONE = "nl_NL.UTF-8",
	LC_NAME = "nl_NL.UTF-8",
	LC_MEASUREMENT = "nl_NL.UTF-8",
	LC_IDENTIFICATION = "nl_NL.UTF-8",
	LC_NUMERIC = "nl_NL.UTF-8",
	LC_PAPER = "nl_NL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package openhab2.
(Reading database ... 26455 files and directories currently installed.)
Preparing to unpack .../openhab2_2.4.0-1_all.deb ...
Unpacking openhab2 (2.4.0-1) ...
Setting up openhab2 (2.4.0-1) ...
### NOT starting on installation, please execute the following statements to configure openHAB to start automatically using systemd
 sudo /bin/systemctl daemon-reload
 sudo /bin/systemctl enable openhab2.service
### You can start openhab2 by executing
 sudo /bin/systemctl start openhab2.service
Processing triggers for systemd (232-25+deb9u9) ...
root@debian:/home/wouter# 
```

**Comment by Aydan** [comment]
Somthing strange is going on here
when I curl https://dl.bintray.com/openhab/apt-repo2
I get this:
```
<html><body>Moved to <a href="http://dl.bintray.com:80/v1/content/openhab/apt-repo2/">http://dl.bintray.com:80/v1/content/openhab/apt-repo2/</a></body></html>
```
when I change my sources.list to use the given link, then it works.
I don't think this is supposed to happen though.
Why is it referring to an non https location?

**Comment by wborn** [comment]
They use a CDN with Bintray so it could be you're using some malfunctioning CDN node. 
Maybe it helps if you flush your DNS caches?

**Comment by wborn** [comment]
Do you still have this issue @Aydan?

**Comment by Aydan** [comment]
Nope, seems to have resolved itself.
