### ISSUE TITLE
Update Jenkins pipeline for UI repository changes

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-distro#898]
https://github.com/openhab/openhab-distro/blob/d8a07a2a364e06f4177992536e0c783ddb012004/launch/Jenkinsfile#L53

The webui repo is missing and ui's are assumed to be in separate repos.

**Comment by wborn** [comment]
Hopefully this will be fixed when https://github.com/openhab/openhab-distro/issues/866 is resolved.

**Comment by wborn** [comment]
Fixed by https://github.com/openhab/openhab-distro/pull/923
