### ISSUE TITLE
Remove Eclipse launch file

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-distro#899]
* It's of no use for development anymore.
* It's ugly in terms of not git diff friendly.

**Comment by lolodomo** [comment]
We, binding developers, are still using them for binding development and testing in Eclipse.
To be suppressed only when there is a clear, simple and working alternative.

**Comment by davidgraeff** [comment]
But you can only develop on not migrated bundles? And we are very close to a full migrated repository with the old pde parts completely shut down and removed.

**Comment by lolodomo** [comment]
Before shutting down anything, please be sure to provide first a new working and documented development environment.
Until that, I (we) continue working with the old one as the new one is not yet ready.

**Comment by kaikreuzer** [comment]
This has been removed with https://github.com/openhab/openhab-distro/pull/905 now.
