### ISSUE TITLE
Windows update doc

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-distro#917]
The windows 'update' documentation (https://github.com/openhab/openhab-distro/releases/tag/2.1.0#manual-installations) is out of date and should be updated.  I'll submit a PR for that eventually..

**Comment by wborn** [comment]
It's not possible to update those release texts using a PR.

Can you create a PR for updating the Windows installation/update (script) documentation instead @tmrobert8?

Maybe we can then edit the release texts so they link to the updated openHAB Windows documentation.

There are already several documentation issues about this:
* https://github.com/openhab/openhab-docs/issues/365
* https://github.com/openhab/openhab-docs/issues/996
* https://github.com/openhab/openhab-docs/issues/1021

**Comment by Confectrician** [comment]
-> solved

**Comment by wborn** [comment]
Thanks for updating the documentation @Confectrician! :+1:
