### ISSUE TITLE
[windows] EXTRA_JAVA_OPTS is overwritten

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-distro#920]
In [setenv](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/setenv#L107), the current value of EXTRA_JAVA_OPTS is appended to the new value that is being generated. In [setenv.bat](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/setenv.bat#L121), the previous value is not considered. This means that a user running Windows cannot set EXTRA_JAVA_OPTS in start.bat or as an environment variable and must modify setenv.bat. I propose to modify setenv.bat to behave the same as setenv. I need to setup a new Windows environment to test this, but plan to submit a PR for this.

Is the current behavior intentional?

**Comment by wborn** [comment]
I think you've found a bug and Linux users on arm may have had the same bug until `setenv` was updated in   https://github.com/openhab/openhab-distro/pull/69. The content of these scripts are all openHAB additions and not part of the Karaf [setenv](https://github.com/apache/karaf/blob/master/assemblies/features/base/src/main/filtered-resources/resources/bin/setenv) and [setenv.bat](https://github.com/apache/karaf/blob/master/assemblies/features/base/src/main/filtered-resources/resources/bin/setenv.bat) scripts. So would be nice if you can create a PR to fix it. :+1:
