### ISSUE TITLE
pax-web-patch-1.0.0.pom missing for Sandbox-openhab2-release

### ISSUE THREAD

**Issue by bjoernbrings** [openhab/openhab-distro#940]
pax-web-patch-1.0.0.pom is expected to be located in https://repo.maven.apache.org/maven2/org/openhab/util/pax-web-patch/1.0.0/pax-web-patch-1.0.0.pom for [Sandbox-openhab2-release](https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/)

Because of the missing file the build breaks.

Honestly I'm not quite sure whether the expected path is incorrect or the file is missing.

[Analysis by shutterfreak [here](https://community.openhab.org/t/preparation-for-2-5m2/75738/68)]

**Comment by kaikreuzer** [comment]
The file is at the same location as it has been for the last years: https://dl.bintray.com/openhab/mvn/org/openhab/util/pax-web-patch/1.0.0/ and it has always been found there by the build.

So the question is rather, why the build suddenly does not find it anymore.
My assumption is that it is related to the new Super Pom. It seems to [not include bintray for the plugin dependencies](https://github.com/openhab/infrastructure/blob/master/pom.xml#L91-L102).
After adding the Super Pom, the repos had been [removed from the distro pom](https://github.com/openhab/openhab-distro/commit/8dddc30bbff5689d378e00fc6e33c2487d71201b#diff-600376dffeb79835ede4a0b285078036). It might be easiest to add the repo there again.

This happened end of May already, so I am wondering, why the build didn't break at this moment already. 
@pfink Do you have clue here as you are the master of the Super Pom as well as the sandbox build?

**Comment by kaikreuzer** [comment]
> It might be easiest to add the repo there again.

I've created https://github.com/openhab/openhab-distro/pull/941 for it.
