### ISSUE TITLE
openHAB nrjavaserial POM is missing

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-distro#947]
I am pretty sure I reported this already somewhere, but I don't find it anymore...
So, please excuse to report it again...

I see a lot of warnings:

```
The POM for org.openhab:nrjavaserial:jar:3.15.0.OH2 is missing, no dependency information available
```

As you can see in the repository https://openhab.jfrog.io/openhab/libs-release/org/openhab/nrjavaserial/3.15.0.OH2/ the POM is not available.

Can you please add the POM to get rid of this warnings.

**Comment by maggu2810** [comment]
@wborn IIRC you build that patched version and already replied "something" to the other place I comment this... Correct?

**Comment by wborn** [comment]
Yes I build the patched version and saw your comment in the other place (https://github.com/wborn/nrjavaserial-builder/issues/1#issuecomment-504373746). I've now added POMs to those [releases](https://github.com/wborn/nrjavaserial-builder/releases/). The warnings are gone when I open the Demo App after adding the 3.15.0.OH2 POM to my local Maven repository. So maybe @kaikreuzer can upload the latest POM to the OH repo?

**Comment by maggu2810** [comment]
@wborn Thanks for adding the POM file (no I remember the place I comment before, too :wink: ).

> So maybe @kaikreuzer can upload the latest POM to the OH repo?

That would be great!

**Comment by kaikreuzer** [comment]
Done, see https://openhab.jfrog.io/openhab/libs-release/org/openhab/nrjavaserial/3.15.0.OH2/
