### ISSUE TITLE
Build failure om master

### ISSUE THREAD

**Issue by zephod77** [openhab/openhab-distro#958]
$ git branch
* master
$ git pull
Already up to date.
$ date
Sat 17 Aug 2019 12:14:55 PM EDT
$ mvn clean install > distro_build.log 2>&1
[distro_build.log](https://github.com/openhab/openhab-distro/files/3512189/distro_build.log)

**Comment by kaikreuzer** [comment]
The reference is Jenkins, which is totally happy: https://ci.openhab.org/job/openHAB-Distribution/

Issue must be with your local machine. Maybe an old Maven version? broken .m2 repo? Proxy setting?

**Comment by zephod77** [comment]
On Sat, 17 Aug 2019 12:06:30 -0700
Kai Kreuzer <notifications@github.com> wrote:

> The reference is Jenkins, which is totally happy:
> https://ci.openhab.org/job/openHAB-Distribution/
> 
> Issue must be with your local machine. Maybe an old Maven version?
> broken .m2 repo? Proxy setting?
> 
No proxy,
$ mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation,
runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre Default locale: en_US,
platform encoding: UTF-8 OS name: "linux", version: "4.19.0-4-amd64",
arch: "amd64", family: "unix"

and deleted .m2 repo and rebuilt.
Same problem.

Any other possibilities?

Thanks,
Steve

**Comment by kaikreuzer** [comment]
Could you try a `mvn -X clean install` and see if that provides any further details?

**Comment by zephod77** [comment]
On Sun, 18 Aug 2019 03:08:32 -0700
Kai Kreuzer <notifications@github.com> wrote:

> Could you try a `mvn -X clean install` and see if that provides any
> further details?
> 

The output is in the attachement. It looks like mvn doesn't know what a
kar or a feature is.

**Comment by zephod77** [comment]
On Sun, 18 Aug 2019 03:08:32 -0700
Kai Kreuzer <notifications@github.com> wrote:

> Could you try a `mvn -X clean install` and see if that provides any
> further details?
> 
 It looks like mvn doesn't know what a
kar or a feature is.

OK. I removed the whole repo and re-cloned. That fixed it.

Steve

**Comment by kaikreuzer** [comment]
Excellent, glad to hear that!
