### ISSUE TITLE
openHAB 2.5.0 Build #1713

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-distro#978]
Hello,

Not sure why first binding is ignored in addons.cfg

if I put in addons.cfg line binding
binding = ntp,modbus
I see only modbus installed. but when I add
binding = ntp,ntp,modbus
then I see ntp & modbus installed.

the same issue with ui, transformations

I am doing something wrong? using latest unstable snapshoot.

Log:
Failed installing ‘openhab-transformation-= javascript, openhab-ui-= basic, openhab-binding-= ntp’

Ed

**Comment by Bl00d-B0b** [comment]
Failed to install artifact: /var/lib/openhab2/etc/org.openhab.ephemeris.cfg

org.openhab.ephemeris.cfg:
dayset-weekend=[SATURDAY,SUNDAY]
dayset-school=[MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY]

Error Log message:
Oct 08 12:31:09 sm0-srv karaf[19420]: 12:31:09.316 [Start Level: Equinox Container: 7a17acb5-3d00-47e2-a133-61de8317200e] ERROR org.apache.felix.
fileinstall - Failed to install artifact: /var/lib/openhab2/etc/org.openhab.ephemeris.cfg
Oct 08 12:31:09 sm0-srv karaf[19420]: java.lang.NullPointerException: null
Oct 08 12:31:09 sm0-srv karaf[19420]: at java.util.Hashtable.put(Hashtable.java:460) ~[?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.ConfigInstaller.setConfig(ConfigInstaller.java:277) ~[10:org.apach
e.felix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.ConfigInstaller.install(ConfigInstaller.java:99) ~[10:org.apache.f
elix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:950) [10:org.apache
.felix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:884) [10:org.apache
.felix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:489) [10:org.apac
he.felix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache
.felix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.DirectoryWatcher.start(DirectoryWatcher.java:247) [10:org.apache.f
elix.fileinstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.FileInstall.updated(FileInstall.java:254) [10:org.apache.felix.fil
einstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.apache.felix.fileinstall.internal.FileInstall.start(FileInstall.java:138) [10:org.apache.felix.filei
nstall:3.6.4]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) [?:?
]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.container.Module.doStart(Module.java:581) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.container.Module.start(Module.java:449) [?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
[?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614)
[?:?]
Oct 08 12:31:09 sm0-srv karaf[19420]: at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.jav
a:1585) [?:?]

**Comment by openhab-5iver** [comment]
Thank you for reporting, but this issue should be in openhab-core. There has been recent work on ephemeris that is likely related... https://github.com/openhab/openhab-core/pull/919. @cweitkamp.

**Comment by cweitkamp** [comment]
Thank you for reporting. Please have a look here: https://github.com/openhab/openhab-core/issues/903#issuecomment-539364949.

**Comment by Bl00d-B0b** [comment]
Hello,

just install openHAB 2.5.0 Build #1714_1.

and i found:
binding=ntp,modbus   - works as expected
binding= ntp,modbus   - steel an error.

seems it's an space problem in string.

Ed
