### ISSUE TITLE
Extend demo sitemap with complete icon preview

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhab-distro#98]
### Problem:
I have a hard time finding available icons for `basic-ui` and what they are called.

### Solution:
Create a new subgroup / frame for the demo like the widget section for icons.
In this section just display all icons (A-Z) as buttons with with the `config name` as name.

This will then be part of all shipped artefacts and its easy to copy paste as we configure new devices.

**Comment by EliasGabrielsson** [comment]
Ping @reitermarkus

**Comment by kaikreuzer** [comment]
Note that there can be different icon sets in place. I prefer to simply add it to the documentation of the according iconset like already started here: https://github.com/eclipse/smarthome/blob/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.md (note that it is still on the to-do list to migrate @reitermarkus' icons from OH2 to ESH).
