### ISSUE TITLE
Update `MOVE` command did not work

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-distro#987]
> During upgrade of openHAB I got a notice from apt package manager that there was a change in the runtime.cfg file - which was nice.
> 
> But the MOVE command was not applied. The config file is still in its old location.

_Originally posted by @cweitkamp in https://github.com/openhab/openhab-distro/pull/979#issuecomment-541566468_

> When updating on my Mac, the `MOVE` didn't work either. I found this as an output:
> ```
> Performing post-update tasks for version 2.5.0:
>   Replacing: String org.eclipse.smarthome.automation.dto.RuleDTO to org.openhab.core.automation.dto.RuleDTO in file /Applications/openHAB/userdata/jsondb/automation_rules.json
> sed: 1: "/Applications/openHAB/u ...": invalid command code o
>   Moving:   From /Applications/openHAB/userdata/config/org/eclipse/smarthome/core/i18nprovider.config to /Applications/openHAB/userdata/config/org/eclipse/smarthome/i18n.config
>   Replacing: String org.eclipse.smarthome.core.i18nprovider to org.eclipse.smarthome.i18n in file /Applications/openHAB/userdata/config/org/eclipse/smarthome/i18n.config
> sed: 1: "/Applications/openHAB/u ...": invalid command code o
> ```

_Originally posted by @kaikreuzer in https://github.com/openhab/openhab-distro/pull/979#issuecomment-541599719_

**Comment by kaikreuzer** [comment]
@BClark09 Could you maybe help on this issue?

**Comment by BClark09** [comment]
It looks like we have run into: https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

Perhaps we should provide a .bak extention to make the command `sed -i.bak` (which could be deleted after) so that the command is compatible across systems?

**Comment by kaikreuzer** [comment]
That should solve it for macOS, yes.

FTR: @cweitkamp problem with MOVE on apt should be solved by https://github.com/openhab/openhab-linuxpkg/pull/152.

**Comment by cweitkamp** [comment]
Great. Thank you.

A backup file sounds reasonable. It would even be fine to keep it.

**Comment by kaikreuzer** [comment]
@BClark09 Can we hope for a PR from you for it? 😄

**Comment by BClark09** [comment]
Looks like the Mac had trouble with `REPLACE`, instead of `MOVE`. I've made the PR!
