### ISSUE TITLE
Upgrade to Karaf 4.2.7

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#995]
If there are no blocking issues, it would be good to upgrade openHAB to the latest Karaf 4.2.7.

**Comment by kaikreuzer** [comment]
@wborn As you are a usual suspect: Did you already do any tests in this regard? If not, would you be willing to do some? 😎

**Comment by wborn** [comment]
Sure I'll give it a try again! Karaf 4.2.8 won't be ready for OH 2.5 anyways and upgrading now should give us plenty of time to evaluate the upgrade.

**Comment by wborn** [comment]
As you can see I've created some PRs to update to Karaf 4.2.7 @kaikreuzer.

I've given it some testing with the Demo which worked and fixed some new Jetty warnings that showed.

**Comment by kaikreuzer** [comment]
Sounds excellent - so let's merge and see if anybody finds any regressions :-)
