### ISSUE TITLE
Warnings with cipher at startup of snapshot 1751

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#999]
```
11:45:35.408 [WARN ] [org.apache.karaf.shell.ssh.SshUtils  ] - Configured cipher 'aes256-ctr' not available
11:45:35.508 [WARN ] [org.apache.karaf.shell.ssh.SshUtils  ] - Configured cipher 'aes192-ctr' not available
```

**Comment by kaikreuzer** [comment]
Those ciphers were defined by @wborn in https://github.com/openhab/openhab-distro/pull/996/files#diff-70c5ca4bdc40b3229f09eae7275b584eR116.

Is it possible that those ciphers are only available if JCE is installed?

**Comment by wborn** [comment]
The lines I've updated are all commented values that reflect the new defaults that were updated in https://github.com/apache/karaf/commit/2409edc5f760b3d134575b3e4ad9c2b39c1025e7. So it seems that by default Karaf 4.2.7 now uses more secure ciphers.

What JVM do you use @lolodomo (vendor/version/update level)?
Do you have have the Java Cryptography Extension (JCE) installed for enabling unlimited cipher strength?

**Comment by lolodomo** [comment]
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)

I have no idea if JCE is installed but I have not done any specific action for that.

Yes, I can connect to the console as earlier without any warning.

**Comment by lolodomo** [comment]
I found this command to check if JCE is enabled:
`jrunscript -e 'exit (println(javax.crypto.Cipher.getMaxAllowedKeyLength("AES") >= 256));'`
It returns false in my case.

**Comment by wborn** [comment]
So looks like the warnings are indeed due to the missing JCE.

Since the default is `aes256-ctr,aes192-ctr,aes128-ctr`, it looks like it will try to use the strongest cipher available and fallsback to `aes128-ctr` in case the JCE isn't installed.

I don't like suppressing warnings but it may be the best option in this case. That way it won't needlessly alert users but will still use the stronger ciphers when the JCE is installed. WDYT @kaikreuzer?

**Comment by kaikreuzer** [comment]
I'd agree - the warnings will alarm users, which isn't helpful here, but for people with JCE, the stronger ciphers should be used. So suppressing the warnings sounds good to me.
